### ISSUE TITLE
Adding in a feature vector to describe manual vs auto segmentation

### ISSUE THREAD

**Issue by pburnham50** [MouseLand/cellpose#10]
Hi, what an awesome tool for segmentation!

I've been applying it to some nuclei segmentation data I have, performing the segmentation and then cleaning up where needed (would say it calls ~98% of nuclei with <1% of calls being partial nuclei).

In the exported .npy file, could you include a feature that defines if the segmentation was performed manually or in the automated step? This could help correct for effects downstream. Thank!

**Comment by carsen-stringer** [comment]
Good idea, this has been implemented, has not been put in the pip yet but is in the github version
