### ISSUE TITLE
Cannot launch Cellpose GUI

### ISSUE THREAD

**Issue by adna-siana** [MouseLand/cellpose#100]
Hi, 

I did a fresh install of Anaconda and Python 3.7 and then installed Cellpose using pip install cellpose[gui] in my base environment. I didn't get any errors in the installation. But when I try to open it I get the following error message below. 

Any change you can help me figure out what the problem is so that I can run the Cellpose GUI? 

`(base) ICM-WYART-MP003:~ adna.dumitrescu$ python -m cellpose
objc[90902]: Class QMacAutoReleasePoolTracker is implemented in both /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/cv2/.dylibs/QtCore (0x1a24a0f700) and /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x1a2e6b70f8). One of the two will be used. Which one is undefined.
objc[90902]: Class QT_ROOT_LEVEL_POOL__THESE_OBJECTS_WILL_BE_RELEASED_WHEN_QAPP_GOES_OUT_OF_SCOPE is implemented in both /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/cv2/.dylibs/QtCore (0x1a24a0f778) and /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x1a2e6b7170). One of the two will be used. Which one is undefined.
objc[90902]: Class KeyValueObserver is implemented in both /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/cv2/.dylibs/QtCore (0x1a24a0f7a0) and /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x1a2e6b7198). One of the two will be used. Which one is undefined.
objc[90902]: Class RunLoopModeTracker is implemented in both /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/cv2/.dylibs/QtCore (0x1a24a0f7f0) and /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x1a2e6b71e8). One of the two will be used. Which one is undefined.
objc[90902]: Class QCocoaPageLayoutDelegate is implemented in both /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/PyQt5/Qt/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x1a314bc540) and /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/cv2/.dylibs/QtPrintSupport (0x1a35be1468). One of the two will be used. Which one is undefined.
objc[90902]: Class QCocoaPrintPanelDelegate is implemented in both /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/PyQt5/Qt/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x1a314bc5b8) and /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/cv2/.dylibs/QtPrintSupport (0x1a35be14e0). One of the two will be used. Which one is undefined.
QObject::moveToThread: Current thread (0x7fd6b17c77c0) is not the object's thread (0x7fd6b1c29990).
Cannot move to target thread (0x7fd6b17c77c0)

You might be loading two sets of Qt binaries into the same process. Check that all plugins are compiled against the right Qt binaries. Export DYLD_PRINT_LIBRARIES=1 and check that only one set of binaries are being loaded.
qt.qpa.plugin: Could not load the Qt platform plugin "cocoa" in "/Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: cocoa, minimal, offscreen, webgl.

Abort trap: 6
`

**Comment by marius10p** [comment]
Does this help:

MAC OS ISSUE: You may have an issue on Mac with the latest opencv-python library (package name cv2). Downgrade it with the command

pip install opencv-python==3.4.5.20

**Comment by adna-siana** [comment]
This did the trick as the GUI opens now. BUT, I think that something else is off because the segmentation won't start and there are some display issues (i.e. I can't see the segmentation bar loading). 

Here's the terminal output: 
`(base) ICM-WYART-MP003:~ adna.dumitrescu$ python -m cellpose
objc[5700]: Class QCocoaPageLayoutDelegate is implemented in both /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/cv2/.dylibs/QtGui (0x1a2a139260) and /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/PyQt5/Qt/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x1a36711540). One of the two will be used. Which one is undefined.
objc[5700]: Class QCocoaPrintPanelDelegate is implemented in both /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/cv2/.dylibs/QtGui (0x1a2a1392d8) and /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/PyQt5/Qt/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x1a367115b8). One of the two will be used. Which one is undefined.
objc[5700]: Class QCocoaApplicationDelegate is implemented in both /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/cv2/.dylibs/QtGui (0x1a2a138fe0) and /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib (0x1a3a80e030). One of the two will be used. Which one is undefined.
objc[5700]: Class QNSApplication is implemented in both /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/cv2/.dylibs/QtGui (0x1a2a138f90) and /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib (0x1a3a80e080). One of the two will be used. Which one is undefined.
objc[5700]: Class QCocoaMenuLoader is implemented in both /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/cv2/.dylibs/QtGui (0x1a2a138f40) and /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib (0x1a3a80e1c0). One of the two will be used. Which one is undefined.
objc[5700]: Class QNSOpenSavePanelDelegate is implemented in both /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/cv2/.dylibs/QtGui (0x1a2a139120) and /Users/adna.dumitrescu/opt/anaconda3/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib (0x1a3a80e350). One of the two will be used. Which one is undefined.
/Users/adna.dumitrescu/Desktop/hindbrain_small.tif
1 (447, 512, 3)
removed all cells
`

And I've also attached a screenshot of how the GUI looks on my end. 
<img width="1196" alt="Cellpose_GUI" src="https://user-images.githubusercontent.com/46405156/86150373-3bb9af00-baf5-11ea-8a5e-b3a914da249b.png">

**Comment by adna-siana** [comment]
Update: I manually downgraded both Pyqt and PygtEngine to version 5.12.0 and now the GUI works. This also fixed my Spyder installation which always got broken when I installed Cellpose before. 

Thanks for your help!
