### ISSUE TITLE
[FEATURE] Request for Feature: Visualize Training Curves for Human-in-the-Loop Models

### ISSUE THREAD

**Issue by piliamei** [MouseLand/cellpose#1005]
Hi there,

I’m currently working with Cellpose GUI to train a model using the human-in-the-loop method. I have successfully obtained a model that works well for my images. However, I would like to visualize the training curves to better understand the training progress and performance.

I am not able to find all the data needed to generate these curves after training in the GUI, I only have the loss value and LR. Could someone provide guidance or suggest a way to integrate this feature?

Any help or advice would be greatly appreciated!

Thank you in advance!

**Comment by carsen-stringer** [comment]
the train losses are now saved in an npy file in the model path + _train_losses.npy
