### ISSUE TITLE
[BUG] TypeError for channels=None in model.eval for multichannel image stacks

### ISSUE THREAD

**Issue by macromeer** [MouseLand/cellpose#1007]
Hi there,

I am trying to denoise multichannel z-stacks. The latest documentation [reads](https://cellpose.readthedocs.io/en/latest/restore.html#denoisemodel) 

> leave channels=None to apply the model to all channels

but I cannot find this option in the [eval function](https://github.com/MouseLand/cellpose/blob/dc3848da80c671772fa5b6593867bbed784f95ac/cellpose/models.py#L142).

When I execute `model.eval(img, channels=None, z_axis=0,channel_axis=3)` on an image with dim order ZYXC, I get 

```
  File "/opt/miniforge3/envs/tmidas-env/lib/python3.8/site-packages/cellpose/denoise.py", line 759, in eval
    if np.ptp(x[..., -1]) < 1e-3 or channels[-1] == 0:
TypeError: 'NoneType' object is not subscriptable
```

I was thus wondering if the option to "apply the model to all channels" is a deprecated feature or a bug?

I've tried both models:
```
model = denoise.DenoiseModel(model_type="denoise_cyto3", gpu=True)
model = denoise.CellposeDenoiseModel(gpu=True, restore_type="denoise_cyto3")
```
They give the same TypeError, even though in [line 495 of denoise.py](https://github.com/MouseLand/cellpose/blob/dc3848da80c671772fa5b6593867bbed784f95ac/cellpose/denoise.py#L555) it still says that channels default to None.

**Comment by macromeer** [comment]
This is a most ugly workaround:
```
denoised_channels = model.eval([img,img,img,img], channels=[[0,0],[1,0],[2,0],[3,0]], z_axis=0,channel_axis=3)
# afterwards: squeeze and merge channels
```

**Comment by carsen-stringer** [comment]
in your example, all of your channels are cellular channels? when you use the standard channel input we run the nuclear denoising model on the second channel with a slightly smaller diameter. and then for segmentation, do you want to segment each cellular channel separately too? in that case I think you want to use the z_axis option instead

**Comment by carsen-stringer** [comment]
I see you have a z-stack in that case you could make a list across channel dimensions to segment and denoise each channel separately -- for channels e.g. with nuclei or other organelles you likely want to change the diameter

**Comment by macromeer** [comment]
Yes, this is what I am doing now. Thank you.
