### ISSUE TITLE
[FEATURE]Segmentation using transcripts density

### ISSUE THREAD

**Issue by marsdenl** [MouseLand/cellpose#1009]
Hey there, 

Thank you so much for providing us with this amazing tool! I have a MERSCOPE brain dataset I'd like to segment and the default off-the-shelf segmentation from vizgen failed (I assume since poly/cellbound stainings don't really work on brain samples). I'm therefore left with DAPI and transcripts density to segment (image below).

I was hoping to tailor the cellpose2 model to my dataset by training it on dapi/transcript.png images and later on applying that model to segment my DAPI.TIFF files. Is there a way to do this? Apologies if I missed this in the documentation. 

Thanks for your help. 

Luc

![sample](https://github.com/user-attachments/assets/bc22ea44-e0c8-41cc-8dbf-6a90afaf2f45)

**Comment by carsen-stringer** [comment]
if you'd like cellpose to use both channels for segmentation, you can put all the transcripts into one channel (e.g. average/sum across the transcript channels), and then use DAPI as your second channel. From there you can train your own model. Alternatively, you can use the DAPI channel and dilate your masks a small amount, we have a fork of vizgen-postprocessing that does this: https://github.com/carsen-stringer/vizgen-postprocessing

**Comment by marsdenl** [comment]
Lovely thanks for your help.
