### ISSUE TITLE
ImageJ ROI Converter

### ISSUE THREAD

**Issue by computation29** [MouseLand/cellpose#101]
I am receiving the below error when I run the ROI converter for ImageJ in JupyterLab.

**AttributeError: module 'cellpose.io' has no attribute 'outlines_to_text'**

Code:
from cellpose import io, plot

# image_name is file name of image
# masks is numpy array of masks for image
base = os.path.splitext('img03.png')[0]    # My image file name
outlines = plot.outlines_list('img03_seg.npy') # Numpy array for this image
io.outlines_to_text(base, outlines)

**Comment by carsen-stringer** [comment]
apologies this was in the github version (and at some point I think I removed it -.-). it's now in the pip package, please
```
pip install cellpose --upgrade
```
