### ISSUE TITLE
[BUG]Cellpose QuPath extension give error upon channel color change

### ISSUE THREAD

**Issue by TechnoBear1000** [MouseLand/cellpose#1014]
**Describe the bug**

**To Reproduce**
1. Go to Brightness & contrast in QuPath 0.5.0
2. Click on the color of the DAPI channel
3. Change the color and click OK
4. Save and run script for Cellpose training.

**Run log**
WARN: Unable to write image
ERROR: Unable to write F:\QuPath projects\TRAINING\cellpose-training\train\DK43LN AF_region_1.tif!  No compatible writer found.
ERROR: Troubleshooting:
 - Check that the channel names are correct in the builder.
``` 
This can be corrected by naming the channel "DAPI" again despite that it is already named DAPI.

**Comment by carsen-stringer** [comment]
@TechnoBear1000 please open this issue in qupath, I don't know how qupath calls cellpose
