### ISSUE TITLE
[BUG] demo_images Website out of service

### ISSUE THREAD

**Issue by jkjkiiiii** [MouseLand/cellpose#1021]
**Describe the bug**
The webpage cannot retrieve data.

**To Reproduce**
1. Go to '[step-by-step-demo](https://github.com/MouseLand/cellpose?tab=readme-ov-file#step-by-step-demo)'
2. Click on '[folder](http://cellpose.org/static/images/demo_images.zip)'

**Run log**
Got 404 error.

**Comment by carsen-stringer** [comment]
oops I think because it's missing https://www., updated link: https://www.cellpose.org/static/images/demo_images.zip
