### ISSUE TITLE
[INSTALL]Install cyto3 in TrackMate-Cellpose

### ISSUE THREAD

**Issue by sparkefish** [MouseLand/cellpose#1024]
Hi I'd like to know if I can download cyto3 model and install it into this fiji plugin because this plugin seems not to update this new powerful model. And where to download this model? many thanks in advance!

**Comment by carsen-stringer** [comment]
the URLs are here: https://cellpose.readthedocs.io/en/latest/models.html; it's https://www.cellpose.org/models/cyto3
