### ISSUE TITLE
[BUG] Fail to download "older" models

### ISSUE THREAD

**Issue by romainGuiet** [MouseLand/cellpose#1025]
Dear @carsen-stringer 

**Describe the bug**
Download models using a script works for some but fails for others.
From the [models page](https://cellpose.readthedocs.io/en/latest/models.html#models) on the documentation, I could find this list of model names : 
```
MODEL_LIST = [ 'cyto3' , 'tissuenet_cp3', "livecell_cp3", "yeast_PhC_cp3", "yeast_BF_cp3", "bact_phase_cp3", "bact_fluor_cp3", "deepbacs_cp3", "cyto2_cp3", 'cyto2' , 'cyto', 
"cytotorch_0", "cyto2torch_0", "size_cytotorch_0.npy","size_cytotorch_0", "size_cyto2torch_0.npy","size_cyto2torch_0", "size_cyto3.npy","size_cyto3",  "cyto_0", "nuclei_0", "size_cyto_0.npy", "size_nuclei_0.npy" ,"CP", "CPx", "TN1", "TN2", "TN3", "LC1", "LC2", "LC3", "LC4", "style_choice.npy"
               ]
```

**To Reproduce**
but when running the script below 

```
from cellpose import models

MODEL_LIST = [ 'cyto3' , 'tissuenet_cp3' ,"livecell_cp3","yeast_PhC_cp3","yeast_BF_cp3","bact_phase_cp3","bact_fluor_cp3","deepbacs_cp3","cyto2_cp3",
                'cyto2' , 'cyto', "cytotorch_0", "cyto2torch_0", "size_cytotorch_0.npy","size_cytotorch_0", "size_cyto2torch_0.npy","size_cyto2torch_0", "size_cyto3.npy","size_cyto3",
                "cyto_0", "nuclei_0", "size_cyto_0.npy", "size_nuclei_0.npy" ,"CP", "CPx", "TN1", "TN2", "TN3", "LC1", "LC2", "LC3", "LC4", "style_choice.npy"
               ]

for m in MODEL_LIST:
    print(m)
    models.CellposeModel(model_type=m)
    print("=====")
```
Some are downloaded but the others return `model_type does not exist, using default model `
See screenshot below
![image](https://github.com/user-attachments/assets/80bbb7b3-d34f-4043-b588-84eae7779332)

Thank you for your help

Romain

**Comment by carsen-stringer** [comment]
this URL worked for me: https://www.cellpose.org/models/cytotorch_0

the model is not called "cytotorch_0", it is called "cyto" as the model type, I think that's the issue?

these are the officially supported model_types: https://github.com/MouseLand/cellpose/blob/f4df31328d3c74d8f60c740b5f22e7e709d40766/cellpose/models.py#L28

I can add in the legacy models TN1 etc
