### ISSUE TITLE
Can Cellpose be used to segment cell in the HE-stained images ?

### ISSUE THREAD

**Issue by februaryfang** [MouseLand/cellpose#1027]
Hi Cellpose Team,

    I have a question regarding the use of Cellpose3 for a specific application. Recently, single-cell spatial transcriptomics and single-cell spatial HD technologies (e.g., 10x Genomics Visium) have become very popular. These technologies typically report data in units of spots or bins, which represent the average gene expression of all cells within a specific region.However, I have a requirement to identify individual cells from the corresponding HE-stained tissue images and obtain cell-level results. Specifically, I need to segment and identify each cell in the HE-stained images.Can Cellpose be used to achieve this? If so, are there any specific considerations or best practices for using Cellpose with HE-stained images?
    Thank you for your help!

Best regards, februaryfang

**Comment by carsen-stringer** [comment]
I have not seen the visium data myself, but the merscope data works with cellpose, they have it integrated in their post-processing pipeline, which is open-source: https://github.com/Vizgen/vizgen-postprocessing

I would recommend retraining a model if it looks like cellpose isn't working well out of the box on your data. if you want to provide images + segmentations we can provide advice

**Comment by februaryfang** [comment]
I set the parameters model_type=cyto2, channels=[1,0], flow_threshold=0.8, diameter=10, and min_size=5 to perform cellpose analysis, and obtained the following results. 
![sample1_cyto2_channels_1_0_diameter10](https://github.com/user-attachments/assets/6d9cce3c-08e8-40d1-8826-335f4f9658e8)

These parameters were selected after testing multiple combinations and are considered the optimal ones. Since the input images are H&E images, I believe the results are biased towards nuclear segmentation, and there are still cell masks that do not correspond to actual cells. 

How can I adjust the parameters to optimize the results?

**Comment by carsen-stringer** [comment]
you may get better results with grayscale (channels=[0,0]), but you will have to retrain the network using Cellpose 2. from this image I can't see the cell boundaries but I'm assuming if you zoom in and take crops you can use them to train the network. if that doesn't work I'll reopen the issue
