### ISSUE TITLE
Installation problems on Mac

### ISSUE THREAD

**Issue by helpkate1991** [MouseLand/cellpose#105]
Hi Guys,

I am trying to install Cellpose on my MacOS Catalina Version 10.15.6 and I am having a whole host of problems. 
First, when I try pip install cellpose[gui] it says no matches found.
Next, I tried creating an environment and was able to open up the GUI but the GUI was blank. I checked the python version that I'm using and it is 3.7.6.
Does anyone know a workaround or a solution to installing Cellpose GUI on a Mac? 

Edit: I've figured out how to run Cellpose through an Anaconda notebook but now I am unable to process multistack tiffs, and can only process single frames at a time. 

Any help would be appreciated! Thank you thank you!

**Comment by carsen-stringer** [comment]
can you try the latest version? I've removed some of the dependencies that are tricky on mac. 

Are you trying to process images in 3D? If so, set `do_3D=True` in the `eval` method:
```
model = Cellpose(model_type='cyto')
masks = model.eval(zstack, channels=[2,1], do_3D=True)[0]
```
where `zstack.shape` is `(nplanes, nchan, npix_y, npix_x)`
