### ISSUE TITLE
Segmentation Artifact 

### ISSUE THREAD

**Issue by amovsheva** [MouseLand/cellpose#107]
Hi!
Similar to issue #35 I'm experiencing thin segmentation artifacts when I'm using the cytoplasm model. For me, the artifact is quite common. I'm using a google colab notebook, following the colab notebook linked at https://github.com/MouseLand/cellpose. 

I've attached some pictures where you can see the thin slicing segmentation clearly in the middle of the cell colony.
<img width="1140" alt="Screen Shot 2020-08-06 at 6 04 13 PM" src="https://user-images.githubusercontent.com/33842155/89806879-4f493400-dafd-11ea-9173-36ad6eb17366.png">

I was wondering if it is possible that I have an old version of cellpose. How can I check what version of cellpose I am working with?

**Comment by carsen-stringer** [comment]
You can see the version with 
```
pip show cellpose
```

I'm not sure why that artifact is happening, please try upgrading and see if it's still there. This may be a QC step we want to add. But generally speaking cellpose has not been trained on data that looks like that so I don't think it knows what to do
