### ISSUE TITLE
Installation problems on mac

### ISSUE THREAD

**Issue by Seleit** [MouseLand/cellpose#110]
Hello,

i am running into installation problems on mac...i tried both from the terminal and opening a new envir, same error

pip install 'cellpose[gui]' 
Collecting cellpose[gui]
  Using cached cellpose-0.0.2.8-py3-none-any.whl (92 kB)
Requirement already satisfied: scikit-image in ./opt/anaconda3/lib/python3.8/site-packages (from cellpose[gui]) (0.16.2)
Requirement already satisfied: matplotlib in ./opt/anaconda3/lib/python3.8/site-packages (from cellpose[gui]) (3.2.2)
Collecting Pillow<=7.0.0
  Using cached Pillow-7.0.0-cp38-cp38-macosx_10_9_x86_64.whl (2.1 MB)
ERROR: Could not find a version that satisfies the requirement mxnet-mkl (from cellpose[gui]) (from versions: none)
ERROR: No matching distribution found for mxnet-mkl (from cellpose[gui]

**Comment by carsen-stringer** [comment]
this might be an incompatibility with numpy, I've pinned numpy<=1.16.6 in the environment. you can remove the environment and reinstall with the new environment file with
```
conda env remove -n cellpose
conda env create -f environment.yml
```

**Comment by Seleit** [comment]
Thank you !

so now it runs and i can even open the GUI BUT as soon as i press any button on the GUI it crashes and i get the following error

/Users/aliseleit/Desktop/epithelialcellnuleucbx1GFP-1.tif
1 (733, 887, 3)
removed all cells
removed all cells
cyto
using model cyto
processing 1 image(s)
OMP: Error #15: Initializing libiomp5.dylib, but found libomp.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
zsh: abort      python3 -m cellpose

**Comment by carsen-stringer** [comment]
can you try the latest environment? or try 

`conda install nomkl`

**Comment by carsen-stringer** [comment]
clsing due to inactivity
