### ISSUE TITLE
GUI speedup

### ISSUE THREAD

**Issue by LRpz** [MouseLand/cellpose#111]
Hi, 

Congratulations for Cellpose, this is a fantastic tool! 

I am dealing with large images (6k by 6k pixels) which seem to affect the latency of the GUI, especially when manually drawing cell outlines. 

Would there be any way to speedup the GUI other than down-sampling or splitting the original image? Would using the GPU help for this particular case?

Thank you very much.

**Comment by carsen-stringer** [comment]
Hey @LRpz if you are manually labelling images for training you can want to split them up and label them split up and you won't see any difference (the GPU is being trained with 224x224 patches of the images). Unfortunately speeding up the GUI for this sort of thing would be a lot of work and will not be supported. I'd recommend something like [napari](https://github.com/napari/napari) if you want to load and label the whole image at once (but I'm not sure if they have labelling like cellpose with outline drawing->masks - I know they have painting)
