### ISSUE TITLE
Proposal for two new functions for the GUI in fixing mask mistakes.

### ISSUE THREAD

**Issue by amovsheva** [MouseLand/cellpose#113]
Cellpose has been working very well in segmenting my cell images. Sometimes though there are small mistakes - like a cell is divided into two or two cells are merged into one. Instead of clearing the incorrect masks completely and redrawing the mask by hand, it would be much easier to have a function that can merge two (or more) adjacent masks into one, and a function that will divide a mask into two pieces (by drawing a line through the existing mask).

**Comment by carsen-stringer** [comment]
the github version now has merging -- click on one cell then left click while holding ALT to merge it with the current cell. I don't plan to add splitting because that's more complicated. please comment if it's not working.
