### ISSUE TITLE
Cannot work labels_to_flow properly in some cells

### ISSUE THREAD

**Issue by tamotamo17** [MouseLand/cellpose#115]
Hello, I tried labels_to_flow with the attached label. The top two cells worked fine, but the bottom one cell didn't work properly.
I didn't understand why it happened. Do you have any ideas?

![example](https://user-images.githubusercontent.com/34983217/92065063-decec380-edd9-11ea-8a5e-69b12fdbea73.png)

**Comment by tamotamo17** [comment]
I added a red arrow to the image.
Flow is not calculated at the edge of cell.
![example1](https://user-images.githubusercontent.com/34983217/92124033-40be1600-ee38-11ea-8c32-4c9189405dd4.png)
![example png (blue)](https://user-images.githubusercontent.com/34983217/92124103-54697c80-ee38-11ea-92c1-336783e8f72f.png)

**Comment by carsen-stringer** [comment]
I think @kevinjohncutler's [omnipose](https://github.com/mouseland/cellpose/blob/master/omnipose/README.md) will be helpful in these scenarios! going to close this issue for now, let us know if you have questions
