### ISSUE TITLE
[GUI] Enable cell_probability_threshold for 3D segmentation

### ISSUE THREAD

**Issue by b2jia** [MouseLand/cellpose#116]
Is there a strategy to enable the slider on the GUI to set different cell_probability_thresholds? Manipulating this parameter is easy at the command line/notebook but the subsequent masks are difficult to manipulate without the GUI (ie. adjusting masks, deleting masks). 

Editing line 492 in ```gui.py``` doesn't seem to do the trick:

```self.probslider.setEnabled(True)```

**Comment by carsen-stringer** [comment]
I haven't found that comparing to the ground-truth flows in 3D helps to throw out false cells, instead I usually set a size threshold, which you could do in a notebook. I don't plan to add this functionality, but if you find it useful for your data I can, it will be very slow to interact with though

**Comment by cberri** [comment]
Dear Carsen,

Thank you for the great job with CellPose. It is absolutely a very powerful tool and right now I am running several tests to see if it can be used on some of my users data  (3D most of the time). So far I am using the jupyter notebook however yesterday I gave a try to the CellPose GUI in Windows 10 on CUDA 11.0.

It is great and I think very useful for those users that do not have any coding experience. 

The main limitation in my opinion is what @b2jia posted. I think will be great to include the option to change the *cell_probability_threshold*. The size threshold is great but sometime I have the feeling that playing with both help the final output.

Would you have time to add this feature in the GUI?

Thank you for your help.

Carlo

**Comment by carsen-stringer** [comment]
this is enabled now in the cellpose-napari plugin: https://cellpose-napari.readthedocs.io/en/latest/running.html#d-segmentation

I will not be supporting this in the native cellpose GUI
