### ISSUE TITLE
An unexpected error has occurred. Conda has prepared the above report.

### ISSUE THREAD

**Issue by christianrickert** [MouseLand/cellpose#12]
I've tried to install the Anaconda environment using the `environment.yml` file provided.
However, during the creation of the environment, I got an error report:
`An unexpected error has occurred. Conda has prepared the above report.`

Turns out the `environment.yml` file cotained a lot of `html` tags,
because I right-clicked the link to save the file ... _ups!_

However, Github does provide a way to directly link to files in the repository:

[`environment.yml`](https://github.com/MouseLand/cellpose/blob/master/environment.yml?raw=true)

My suggestion would therefore be to change the link to the `environment.yml` file,
so that you don't have to deal with error reports after "unexpected errors". :sweat_smile:

**Comment by marius10p** [comment]
Thanks for the tip! I have replaced the link as suggested.

**Comment by christianrickert** [comment]
You're very welcome!
