### ISSUE TITLE
Windows/Mac executible links are broken

### ISSUE THREAD

**Issue by kevinjohncutler** [MouseLand/cellpose#123]
The links to https://github.com/MouseLand/cellpose/blob/master/www.cellpose.org/windows and https://github.com/MouseLand/cellpose/blob/master/www.cellpose.org/mac just give a 404 error.
<img width="901" alt="image" src="https://user-images.githubusercontent.com/39454982/93964940-b0c40b80-fd15-11ea-9a13-7acf8455b304.png">

**Comment by carsen-stringer** [comment]
sorry forgot the http://
