### ISSUE TITLE
Any way to import binary masks?

### ISSUE THREAD

**Issue by kevinjohncutler** [MouseLand/cellpose#124]
Cellpose looks incredible. I'm working on bacterial phase contrast images, such as this (cropped) one:
![test](https://user-images.githubusercontent.com/39454982/93965209-62fbd300-fd16-11ea-9683-3c037724a25d.png)
With some image adjustment, cellpose does manage to do quite well:
<img width="2552" alt="Screen Shot 2020-09-22 at 7 06 33 PM" src="https://user-images.githubusercontent.com/39454982/93965275-93dc0800-fd16-11ea-9e58-71105f0fff99.png">
This can certainly be improved with re-training. Before discovering cellpose, I was planning on training mask r-cnn. For ground truth data, I developed a workflow in MATLAB that uses cytosolic fluorescence to generate approximate cell masks and a GUI to loop though cell clusters and correct for errors. I think this will be faster than the cellpose GUI (at least for my datasets with fluorescence) and less prone to human error. I am also able to scrape SuperSegger's database of segmented images (though I am not sure yet if they are of sufficient quality), also resulting in sets of 4-connected binary masks corresponding to phase contrast images. 

I haven't yet installed the cellpose GUI (Mac and Windows executables seem to be missing, but I'll install it on my Linux machine later), but from the documentation it looks like all I need to do is convert my binary masks to label matrices (stored as correspondingly labeled tiffs) to run the training from the CLI. Does that sound right?

As far as using the GUI, however, I am wondering if there is any existing method to load in a directory of images and masks for the propose of correcting them. Would I need to make a `*_seg.npy` file corresponding to the image? It looks like I could use `dynamics.labels_to_flows` to that end, and the rest of the fields would be trivial to generate.

**Comment by carsen-stringer** [comment]
Yes you are correct for training from the CLI it takes tiffs or int16 PNGs where 0 is no mask and 1,2,... are labelled masks.

The GUI also allows you to load masks -- it's in the "File" menu as an option

**Comment by kevinjohncutler** [comment]
Fantastic - thanks!
