### ISSUE TITLE
Issue launching GUI

### ISSUE THREAD

**Issue by kevinjohncutler** [MouseLand/cellpose#125]
I'm on Ubuntu 20.04, and I thought I had configured everything properly with regard to drivers, CUDA version (10.1) etc. (I had successfully been training models though jupyter notebooks), but I get the following error when trying to run cellpose:

```
~$ python -m cellpose
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```
This is in a local install with Python 3.8 (no conda environemnt, nor is Anaconda installed). I've been trying for hours to figure this out but to no avail. Perhaps tomorrow I will try with a fresh installation of the OS...

**Comment by carsen-stringer** [comment]
I think if you install this without Anaconda you will need to install the Qt requirements yourself on Linux. I'd recommend installing the Anaconda version of python and it will take care of installing the Qt dependencies for you.

This forum is suggesting that you need to install (or reinstall) libxcb: https://forum.qt.io/topic/93247/qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found/17 (e.g. `sudo apt-get install libxcb-xinerama0`)

**Comment by kevinjohncutler** [comment]
That did the trick, thanks!
