### ISSUE TITLE
Disparity between masks returned from web tool vs installed program

### ISSUE THREAD

**Issue by jepearce** [MouseLand/cellpose#126]
![120043885_264456144671957_7247961376422020827_n](https://user-images.githubusercontent.com/26277641/93999555-dd1b6e80-fd8d-11ea-933d-ae01255d4bde.png)
![120065635_262523314875332_7001844141915309053_n](https://user-images.githubusercontent.com/26277641/93999576-e1e02280-fd8d-11ea-92a8-ba84ef2b1bc3.png)

I've encountered a difference with image processing whereby the quick web tool appears to return great cell outlines and masks, but no matter the parameters in the cellpose program on my computer I cannot achieve the same result despite using the identical image as input and the same parameters as per the website. Is there any way to identify what the difference is so that I can replicate these cell masks in the cellpose program itself?

**Comment by carsen-stringer** [comment]
Hey @jepearce the difference is that for computational efficiency the website resizes the image to be max 512 pixels on each side -- this in your case happens to resize your images close to the default diameter of 20-30 pixels it looks like.

in the GUI we process the full image and in your case the cells are much bigger than 30 pixels (see the scale disk at the bottom of the gui). Try setting the diameter to something closer to 100 pixels.

**Comment by jepearce** [comment]
Thanks so much, that worked really well! Great tool.
