### ISSUE TITLE
Sending manual training set of packed cells

### ISSUE THREAD

**Issue by AlexBouz** [MouseLand/cellpose#13]
Greetings and thanks a lot for sharing your tool for imaging data single cell segmentation, i have a challenging image of packed cells i tried to segmentate with cellpose, and would like to send a manually labeled dataset to your server, do you need a fully manual labeling? cause my image contains about 2000 nuclei. Any guidance is appreciated!
![packed nuclei of adherent cells](https://user-images.githubusercontent.com/37419030/74208593-3c3ecf80-4c52-11ea-8e03-b2251d27bbae.png)
![Manual segmentation](https://user-images.githubusercontent.com/37419030/74208604-419c1a00-4c52-11ea-9fbc-c0a0bc72ed8d.png)

**Comment by marius10p** [comment]
You should crop the image and segment less of it, but yes, the segmentation has to be "dense". If you leave some nuclei unsegmented, the algorithm will learn to do that too! 

Also, only contribute images with <300 or so segmented objects, because the average in our training set is 100-200.  You can contribute more than one, for this particular style I would recommend 3-4 images with 200-300 nuclei each.  It really shouldn't take that long to do, we don't need super precise outlines.

**Comment by cyf203** [comment]
What I did is to crop the image into very small pieces and count all the possible neurons.

**Comment by AlexBouz** [comment]
Thanks you for the input to both, as suggested i cropped the big image into small islands of nuclei and try to annotate manually as possible, i found the probability map view of the image more intuitive to clearly see the nuclei compared to the greyscale image, i think i sent two cropping areas so far with annotations to the server. One thing i noted is an occuring error when annotating the nuclei, the red circle tends sometimes to disappear and right click to stop the annotation does not seem to work, not sure if it is reproducible though. Any comment on annotation will be helpful regarding training the nuclei model of the algorithm!
![Island of nuclei with manual annotations](https://user-images.githubusercontent.com/37419030/74302010-f0a82680-4d22-11ea-9c80-cbe75c0f0709.png)
![Island of nuclei with manual annotations on probability map](https://user-images.githubusercontent.com/37419030/74302027-fe5dac00-4d22-11ea-92bd-acba3d5c7156.png)
![Island of nuclei](https://user-images.githubusercontent.com/37419030/74302032-03baf680-4d23-11ea-96a6-e03406f7be0c.png)
![Annotation error log](https://user-images.githubusercontent.com/37419030/74302035-061d5080-4d23-11ea-8a7e-a78ed034b63b.png)

**Comment by marius10p** [comment]
That cropped size is good. However, please only do manual annotation based on the original image, and do not use the results of the algorithm for this, otherwise it's circular. We will not be able to include such annotations in the training set, because you are reinforcing the algorithm's errors. In fact, we thought it should not be possible to send annotations after running Cellpose in the GUI. Have you found a workaround that?

**Comment by AlexBouz** [comment]
Hi @marius10p thank you for the instructions, i understand particular challenging images may decrease the performance specs of the generalist segmentation algorithm. Just to describe what i did, i uploaded one cropped tiff, then adjusted the saturation pixel of the raw grayscale image to visualize the nuclei  i could manually annotate. Afterwards i just clicked the server button, and log shows generation of the npy file followed by being uploaded to another npy file. 
![Manual Annotation of nuclei](https://user-images.githubusercontent.com/37419030/74393980-89997900-4dd9-11ea-8c1f-a58a0025f199.png)
![Log sending manual annotation to server](https://user-images.githubusercontent.com/37419030/74393986-8c946980-4dd9-11ea-83fb-86d5761dde73.png)
Afterwards i run the segmentation nuclei model which replaced the manual annotation by the u-net detected nuclei and as expected the results can not be sent out to the server.
![U-net nuclei model](https://user-images.githubusercontent.com/37419030/74394095-e301a800-4dd9-11ea-8a7f-ca00dffeb64b.png) So i deleted by ctrl+0 all the u-net masks and started annotating the probability pixel image, in this case the annotations can be sent back to the server again.
![Manual annotation on the pixel probability map](https://user-images.githubusercontent.com/37419030/74394323-602d1d00-4dda-11ea-9df6-2f96f5aeada4.png) That summarizes the steps i did. Regarding these cells they obviously grow on three dimensions, and the scanned image is two dimensional only with packing of nuclei into islands happen when growing these three dimensional spheroids structures which are difficult to segmentate when scanned on a x-y orthogonal plane.

Just to show the accuracy of your generalist algorithm cytoplasm i was able to make an accurate segmentation of more than 4000 cells at once on a combination of 4 stitched images, only some big cells were not totally masked.
![Cytoplasm model raw stitched images](https://user-images.githubusercontent.com/37419030/74395026-370d8c00-4ddc-11ea-8506-40aaadd3a855.png)
![Cytoplasm model u-net mask](https://user-images.githubusercontent.com/37419030/74395029-3aa11300-4ddc-11ea-88ba-b71a161062f6.png)
![Cytoplasm model raw stitched images](https://user-images.githubusercontent.com/37419030/74395327-0d089980-4ddd-11ea-8615-986e23b9777e.png)

**Comment by dkoove** [comment]
Hi,
many thanks for your work and for sharing it. 
After sending a manually labelled dataset to your server, how much time would I need to wait until the training is complete and I can try to segment again?

Best,

**Comment by cyf203** [comment]
I have another question is for manual segmentation. If I have two channels, green and red. Should I split these two channels before I even load my image for segmentation? Or should I only segment one channel and send it to the server then segment the other channel? I just realized that if I manually segment both channels. The mask will actually stay across channels. So, I am worrying these may affect the training of Cellpose. Could you please give me some advice? @carsen-stringer @marius10p

**Comment by carsen-stringer** [comment]
Good question, is the red channel (nucleus) failing such that you need to upload it? We suspect that most of the training will be needed for cytoplasmic images, so I would segment the cytoplasm. 

In the cytoplasm case you need to tell the GUI which channel is cytoplasm and which channel is nucleus ('chan to seg' and 'chan2' respectively). After you choose the channels you can click CTRL+S to save them to the npy so that the algorithm knows the channels.
![examplechannels](https://user-images.githubusercontent.com/15067541/75685251-4740ba80-5c68-11ea-8ab6-44b6a4df8205.png)

@dkoove We plan on making a new model later this week

**Comment by EdoDImp** [comment]
> That cropped size is good. However, please only do manual annotation based on the original image, and do not use the results of the algorithm for this, otherwise it's circular. We will not be able to include such annotations in the training set, because you are reinforcing the algorithm's errors. In fact, we thought it should not be possible to send annotations after running Cellpose in the GUI. Have you found a workaround to do that?

Hi @marius10p, do I understand correctly that we should **not** submit manually corrected results of cellpose segmentation (removing/fixing wrong masks) but rather the original stack (talking about confocal data) completely annotated by hand from scratch when Cellpose doesn't perform well?

**Comment by carsen-stringer** [comment]
yeah that's what we want. Also segment EVERYTHING. we've gotten several incomplete submissions.

**Comment by carsen-stringer** [comment]
these cells are included in the cyto2 model released in May
