### ISSUE TITLE
CLI error when using my own trained model only

### ISSUE THREAD

**Issue by kevinjohncutler** [MouseLand/cellpose#134]
Running cellpose via CLI with the pretrained cyto model works, but when I pass in the directory for my own model (in which I had been specifying batch size as a parameter, although that never seemed to change anything) then I get the following error:

```
kcutler@kevin-desktop:~$ python -m cellpose --dir ~/DataDrive/cellpose_training/cli_testing --pretrained_model /home/kcutler/DataDrive/cellpose_training/phs/models/cellpose_residual_on_style_on_concatenation_off_phs_2020_10_12_21_19_58.735908 --diameter 27 --save_png --use_gpu
** CUDA version installed and working. **
>>>> using GPU
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kcutler/.local/lib/python3.8/site-packages/cellpose/__main__.py", line 261, in <module>
    main()
  File "/home/kcutler/.local/lib/python3.8/site-packages/cellpose/__main__.py", line 158, in main
    model = models.CellposeModel(device=device, pretrained_model=cpmodel_path,
TypeError: __init__() got an unexpected keyword argument 'batch_size'
```

**Comment by EkilGitHub** [comment]
same problem as I encountered. you can delete 'batch_size' from               
  model = models.CellposeModel(device=device, pretrained_model=cpmodel_path, batch_size=args.batch_size).
--------
' model = models.CellposeModel(device=device, pretrained_model=cpmodel_path) ' can work well.

**Comment by kevinjohncutler** [comment]
Good idea! This is definitely related to the other batch_size issue I've submitted. I went the other route and instead deleted the bit of code that was giving it trouble initializing a model with that parameter.

**Comment by carsen-stringer** [comment]
oops, can you try the latest github version of cellpose please? I think this has been fixed
