### ISSUE TITLE
Multi-cell segmentation training

### ISSUE THREAD

**Issue by EkilGitHub** [MouseLand/cellpose#137]
If there are multiple cells in a picture, do I need to label them at once for training? Or separately label, obtain different masks, and conduct separate training.

**Comment by b2jia** [comment]
I'm not one of the authors of this repo, but if I understand you correctly you are asking about instance segmentation (where each cell receives a separate label) vs semantic segmentation (all pixels classified as cells receive the same value). From how I've interpreted Cellpose, Cellpose does instance segmentation - which means each cell is given a unique label (usually an integer).

**Comment by EkilGitHub** [comment]
> I'm not one of the authors of this repo, but if I understand you correctly you are asking about instance segmentation (where each cell receives a separate label) vs semantic segmentation (all pixels classified as cells receive the same value). From how I've interpreted Cellpose, Cellpose does instance segmentation - which means each cell is given a unique label (usually an integer).

thank you

**Comment by kevinjohncutler** [comment]
Just to add to this - you'll want to make all the unique labels, but _all at once_ in a single label matrix for any given image, making sure that each cell has a label. I personally prefer doing this in Photoshop with pen input followed by some post-processing in MATLAB, but the cellpose GUI is set up specifically to do this as with traditional mouse input. I think you can load in some demo images too to see examples of fully-annotated data.

**Comment by carsen-stringer** [comment]
thanks for the helpful answers @b2jia and @kevinjohncutler , going to close this issue now
