### ISSUE TITLE
Mac OSX GUI closes on calibrate or segmentation

### ISSUE THREAD

**Issue by pearlryder** [MouseLand/cellpose#138]
I'm trying to run the GUI from a conda environment created using your environment.yml file on Mac OS X 10.15.7. 

When I do so, I'm able to launch the GUI and load an image. However, when I try to either calibrate the cell size or run a segmentation, the GUI window closes and the following error message prints to the terminal:

`OMP: Error #15: Initializing libiomp5.dylib, but found libomp.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
zsh: abort      python -m cellpose`

I did some googling on the error message and found a suggestion to install nomkl [https://github.com/dmlc/xgboost/issues/1715](https://github.com/dmlc/xgboost/issues/1715). That does work to stop the GUI window from closing abruptly and I can get segmentation results, but I don't really know why it works or if there's a better solution. Thanks!

computer specs:
<img width="517" alt="Screen Shot 2020-10-23 at 12 44 17 PM" src="https://user-images.githubusercontent.com/28375904/97030946-8be9d080-152d-11eb-98ca-69f6559b76b9.png">

**Comment by carsen-stringer** [comment]
Hmm that `nomkl` package may disable the mkl installed with anaconda so that python uses the preinstalled OMP libraries? I'm not sure if it will be as fast, but hopefully it is. They also recommend as a potential solution on macOS Catalina
```
conda install -c intel mkl
```
You could try this as well and see if it fixes the problem.

**Comment by pearlryder** [comment]
Thanks! The `conda install -c intel mkl` didn't work for me to solve the problem - the gui still closed abruptly on trying to calibrate or segment. 

After using `conda install nomkl` I can segment my images only a few seconds per image, which is fast enough for me. Hopefully others won't have the same error w/ their conda env!

**Comment by carsen-stringer** [comment]
oh actually it is erroring for me on windows too with a fresh install. I changed the environment file so that numpy (and numba) are installed with pip so they don't depend on MKL as the conda build does. I don't think this error always happened, I'm not sure what changed.

**Comment by pearlryder** [comment]
Thanks @carsen-stringer! The new environment.yml file works for me to create an environment that runs the GUI without closing.
