### ISSUE TITLE
error saving seg_npy and tif for 3D images

### ISSUE THREAD

**Issue by ishainer** [MouseLand/cellpose#142]
When I run cellpose through the gui on a 3D image, the saved _seg.npy is fine and can be reopened. When I run the same 3D tiff through python using this code:

import numpy as np
import matplotlib.pyplot as plt
import skimage.io
from cellpose import models, io
model = models.Cellpose(model_type='cyto')
files = ['composite.tif']
imgs = [skimage.io.imread(f) for f in files]
nimg = len(imgs) 
channels = [[2,1]]
masks, flows, styles, diams = model.eval(imgs, diameter=12, channels=channels, cellprob_threshold=0.0, do_3D=True, net_avg=False)
io.masks_flows_to_seg(imgs, masks, flows, diams, files, channels)

The _seg.npy is cannot be opened in the gui, and I get this error:

Traceback (most recent call last):
  File "cellpose/gui.py", line 738, in dropEvent
  File "cellpose/io.py", line 351, in _load_image
  File "cellpose/io.py", line 510, in _load_seg
TypeError: setCurrentIndex(self, int): argument 1 has unexpected type 'list'
[10:05:28]  Error sending click event:

    |==============================>>
    |  Traceback (most recent call last):
    |    File "cli.py", line 4, in <module>
    |    File "cellpose/__main__.py", line 98, in main
    |    File "cellpose/gui.py", line 129, in run
    |    File "pyqtgraph/widgets/GraphicsView.py", line 364, in mouseReleaseEvent
    |    File "pyqtgraph/GraphicsScene/GraphicsScene.py", line 214, in mouseReleaseEvent
    |    File "pyqtgraph/GraphicsScene/GraphicsScene.py", line 361, in sendClickEvent
    |    --- exception caught here ---
    |    File "pyqtgraph/GraphicsScene/GraphicsScene.py", line 359, in sendClickEvent
    |    File "cellpose/guiparts.py", line 403, in mouseClickEvent
    |  IndexError: index 52 is out of bounds for axis 0 with size 1
    |==============================<<

Also tried to save the masks as tif using this command:
io.save_masks(imgs, masks, flows, files, tif=True)

and I get this error:
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-11-5bae9ce98f26> in <module>
----> 1 io.save_masks(imgs, masks, flows, files, tif=True)

~/.local/lib/python3.7/site-packages/cellpose/io.py in save_masks(images, masks, flows, file_names, png, tif)
    166     if isinstance(masks, list):
    167         for image, mask, flow, file_name in zip(images, masks, flows, file_names):
--> 168             save_masks(image, mask, flow, file_name, png=png, tif=tif)
    169         return
    170 

~/.local/lib/python3.7/site-packages/cellpose/io.py in save_masks(images, masks, flows, file_names, png, tif)
    183         warnings.simplefilter("ignore")
    184         for ext in exts:
--> 185             imsave(base + '_cp_masks' + ext, masks.astype(np.uint16))
    186 
    187     if png and MATPLOTLIB and not (images.ndim==3 and min(images.shape)>3):

~/.local/lib/python3.7/site-packages/cellpose/io.py in imsave(filename, arr)
     56         tifffile.imsave(filename, arr)
     57     else:
---> 58         cv2.imwrite(filename, arr)
     59 
     60 def masks_flows_to_seg(images, masks, flows, diams, file_names, channels=None):

error: OpenCV(4.2.0) /Users/travis/build/skvark/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp:668: error: (-215:Assertion failed) image.channels() == 1 || image.channels() == 3 || image.channels() == 4 in function 'imwrite_'

Any ideas on how to solve it?

Thank you!

**Comment by carsen-stringer** [comment]
can you try the latest github version of cellpose please? I think this has been fixed

**Comment by ishainer** [comment]
It's working now for both _seg.npy and tif.
Thank you!
:)
