### ISSUE TITLE
cellpose segmentations are pixelated in newer releases compared to older releases

### ISSUE THREAD

**Issue by adrtsc** [MouseLand/cellpose#143]
Hi, I've lately observed that cellpose generates very pixelated segmentations when I use newer versions of cellpose. In older versions of cellpose, segmentations were usually smooth and more precise. Here are two examples of a 2160x2560 image of nuclei that I tried to segment with the nuclei model in cellpose 0.0.3.1 and cellpose 1.0.1:

Input image:
![input](https://user-images.githubusercontent.com/41194383/98002801-414e3b00-1dee-11eb-8204-7ffbc33d9d43.jpg)

result of nuclei model, cellpose version 0.0.3.1:

![old](https://user-images.githubusercontent.com/41194383/98002745-2da2d480-1dee-11eb-9989-9f77218fa475.jpg)

result of nuclei model, cellpose version 0.1.0.1: 

![new](https://user-images.githubusercontent.com/41194383/98002782-3bf0f080-1dee-11eb-99c1-c0eed973119c.jpg)

In both cases I generated the cellpose segmentations the following way:

```
masks_nucleus, flows, styles, diams = model_nuc.eval(imgs, channels=channels, diameter = 90)

```

Is this an intentional change or has the syntax somehow changed to get the smooth segmentations? 

Thanks

**Comment by carsen-stringer** [comment]
yeah this is to make the algorithm run faster and reduce RAM usage, I've added in the option to run it in the old way -- see the dropdown in the GUI, the --resample flag in the CLI, and use `model.eval(img, resample=True)` to run in the notebook

**Comment by adrtsc** [comment]
Thanks, this seems to work. 

Just a remark: Maybe it would be a better idea to have the resampling on as a default? It's great that there is an option to run cellpose more quickly but I think the results look much better when the resampling is turned on.

**Comment by kevinjohncutler** [comment]
@carsen-stringer does this only affect evaluation of the model, or does it also need to be specified as a parameter for training?
