### ISSUE TITLE
How to handle different diameter of the cell

### ISSUE THREAD

**Issue by cyf203** [MouseLand/cellpose#15]
![image](https://user-images.githubusercontent.com/26474966/74281865-2cc09480-4ced-11ea-8515-d5f909d392a9.png)
As you can see, different cells may have different diameters. When I set up different cell diameter the algorithm will pick up different proportions of the cells. And those cells are intermingled with each other, I think it is not possible to split this image into two easily. I wonder how I should handle this issue. BTW, I've sent the manual segmented version to the server. 
![image](https://user-images.githubusercontent.com/26474966/74282134-a3f62880-4ced-11ea-8e70-2fefc5dddcb7.png)

**Comment by marius10p** [comment]
We don't have anything quite like this in the training set, so I think performance should improve just by retraining the model and it will automatically be scale-invariant. In the future, please try to maximize the image area that contains cells, which will maximize the impact your segmented images make to the training set. For example, in this case I would have taken a crop of the central part of this image (1/3 in each axis).
