### ISSUE TITLE
imagej_roi_converter.py can not run in ImageJ

### ISSUE THREAD

**Issue by davidyuyuan** [MouseLand/cellpose#156]
ImageJ supports Python version up to 2.5.4. Line 17 "with open(file_name, 'r') as textfile:" fails as "with" keyword was introduced in Python 2.6. We need to change the statement to "textfile = open(file_name, 'r')" and fix the indentation.

**Comment by carsen-stringer** [comment]
@vinisalazar fixed this (https://github.com/MouseLand/cellpose/pull/173), you can see the new file in the repo now
