### ISSUE TITLE
Split GPU & CPU tasks to run on different hardware

### ISSUE THREAD

**Issue by olatarkowska** [MouseLand/cellpose#158]
Hello

We have been looking into cellpose eval function to see if is possible to run network on GPU hardware that complete fast and flow+mask computation on different hardware.

I was thinking about moving https://github.com/MouseLand/cellpose/blob/master/cellpose/models.py#L1195 into the different script. What is your suggestion to split it?

```
time spent: running network 96.71s; flow+mask computation 1894.61
estimated masks for 1 image(s) in 1997.15 sec
```

**Comment by loomcode** [comment]
I was able to do this for nucleus segmentation (https://github.com/MouseLand/cellpose/issues/207).  Let me know if you would like any more details, or if I can pass along some code.

**Comment by carsen-stringer** [comment]
closing this issue due to #207
