### ISSUE TITLE
3D image segmentation

### ISSUE THREAD

**Issue by jahdoos** [MouseLand/cellpose#16]
Hi - this tool looks really awesome, and it definitely performs well with our low mag live cells. I also have been doing MERFISH experiments at high magnification where we want to segment some cells in 3D. I've tried stardist with some manually labels, but performance wasn't great.

Does cellpose support 3D nuclei segmentation?

Secondly, I really like the labeling in cellpose (have used napari for this previously), but I wonder if there are plans to support 3D images and facilitate manual labels in 3D. I am able to manually annotate 2d images really well, but there doesn't seem to be a way for me to either:
1. Use the same label ID in different planes of Z to demark the labels being of the same cell.
2. Take a bunch of 2D labels and easily click label IDs across 3D

I would definitely label a bunch of our images and send them to your server if there are plans to support 3D labels please let me know.

Thanks!

**Comment by marius10p** [comment]
Sorry for the slow response. We are testing a version of 3D segmentation that does not require new 2D labels and will release it in a month or two. Let's see how that does, and if it doesn't work so well we can train a model on 3D data, but that would require a lot of 3D data which is hard to segment manually. We do in fact have an extension for the GUI to do 3D segmentation and we'll probably release it with the 3D model.

**Comment by carsen-stringer** [comment]
I've added the manual 3D segmentation to the GUI, see the readme for info on how it works (turn off "single_stroke", use left/right arrow keys to move in Z, and then press enter when done). It doesn't currently have the ability to join 2D segmentations across planes. Hopefully no manual 3D annotation will be necessary though.

**Comment by carsen-stringer** [comment]
3D segmentation has been added. See the [documentation](http://www.cellpose.org/static/docs/inputs.html#d-segmentation) for input formatting. You can drag and drop 4D tiffs (nplanes x nchan x Ly x Lx) into the GUI and run from there.

Update with `pip install cellpose --upgrade`
