### ISSUE TITLE
UnboundLocalError: local variable 'diams' referenced before assignment

### ISSUE THREAD

**Issue by EkilGitHub** [MouseLand/cellpose#162]
___main__.py", line 174, in main
    io.masks_flows_to_seg(image, masks, flows, diams, image_name, channels)
UnboundLocalError: local variable 'diams' referenced before assignment_
when i try to label cells in WINDOWS's terminal by use a pretrained_model. 
it maybe works:
add   _diams = diameter * np.ones(len(image))_  at line 172, in __main__.py.

**Comment by carsen-stringer** [comment]
thanks, fixed this bug
