### ISSUE TITLE
GPU use Installation Instructions

### ISSUE THREAD

**Issue by jbkelley** [MouseLand/cellpose#164]
When installing Cellpose to use on my computer with GPU functionality, I followed your instructions, but they lead to an error when I tried to start Cellpose.  The problem ultimately turned out to be that I had the CUDA toolkit installed in windows, but not in Anaconda.  After installing the CUDA toolkit in anaconda, it appears to be working.  While many users may know this, it may be helpful to note this in the installation instructions.
----------------------------------------------
GPU version (CUDA)

If you plan on running many images, you may want to install a GPU version of mxnet. We recommend using CUDA 10.0 or greater.

ON WINDOWS

Just install the GPU version of mxnet directly in the environment, i.e.:

pip install mxnet-cu101
---------------------------------------------

could benefit from a line instructing the user to install the CUDA toolkit in Anaconda

**Comment by carsen-stringer** [comment]
interesting thanks what command did you use to install the cuda toolkit for windows? I'll add it to the documentation

**Comment by jbkelley** [comment]
I think that I installed it with the Anaconda GUI, but it appears that the command line way to do it is: `conda install -c anaconda cudatoolkit `

**Comment by carsen-stringer** [comment]
thanks!
