### ISSUE TITLE
colab issue

### ISSUE THREAD

**Issue by lacinh** [MouseLand/cellpose#166]
I get the following error from colab. Help is appreciated. 

AttributeError                            Traceback (most recent call last)
<ipython-input-3-88d528d52b3f> in <module>()
     12 from cellpose import utils
     13 
---> 14 use_GPU = utils.use_gpu()
     15 print('GPU activated? %d'%use_GPU)
     16 

AttributeError: module 'cellpose.utils' has no attribute 'use_gpu'

**Comment by KEDIARAHUL135** [comment]
The 'use_gpu' function is shifted from utils.py to core.py in the newer version.

Change your code to:
```
from cellpose import core
use_GPU = core.use_gpu()
print('GPU activated? %d'%use_GPU)
```

**Comment by carsen-stringer** [comment]
thanks, this has been fixed in the notebook
