### ISSUE TITLE
new google colab notebook

### ISSUE THREAD

**Issue by pr4deepr** [MouseLand/cellpose#168]
Hi @carsen-stringer 
   I've modified the existing Colab notebook and generated a notebook somewhat inspired by ZeroCostDl4Mic notebooks. Its only for 2D prediction right now and can be found here:
https://github.com/pr4deepr/cellpose-colab

I can do a similar one for 3D if needed
I've disabled the mxnet option as I just noticed you've moved to PyTorch.

**Comment by lacinh** [comment]
yes, please. 3D will be appreciated a lot.
thanks

**Comment by carsen-stringer** [comment]
this notebook is amazing! please make a pull request with it added to the notebooks folder and we'll add it to the repo and a link in the readme (crediting you)
