### ISSUE TITLE
Define Cell Size in 

### ISSUE THREAD

**Issue by trasse** [MouseLand/cellpose#17]
Dear All,

I am using run_cellpose.ipynb and want to set the cell size.

what does line 39 mean?
"if you want to set the size yourself, set it to 30. / average_cell_diameter"

1) Set the cell size to 30 (as default) or the actual diameter?
2) 30 divided by the average_cell_diameter?

Thanks a lot & Kind regards

Tobias

**Comment by marius10p** [comment]
Sorry, it's ambiguous. It means to set the parameter "rescale" to "30/average_cell_diameter". So if your cells are 15 pixels across, set rescale to 2, which will upsample the image by a factor of 2. The final result will still be at the same size as your original image.

**Comment by trasse** [comment]
Dear Marius,

Thank you very much for the fast answer and for creating and sharing this great tool!

Kind regards

Tobias
