### ISSUE TITLE
What is the best practice to handle very large images?

### ISSUE THREAD

**Issue by qiagu** [MouseLand/cellpose#171]
Our group has incorporate Cellpose as a key component into our pipeline. It works rather well most times. A small pitfall is an issue that Cellpose gives memory error and slowness when dealing with really large images, like in Gigabytes size. Do you have any suggestion for handling those large images? Parameter setting or images preprocessing? Thanks!

**Comment by papalagirauscher** [comment]
tile them or if time is not an issue, create enough vram

**Comment by Michael-shannon** [comment]
@papalagirauscher thanks for your input, I would really like some help on this - how do you make all of that vram available?
