### ISSUE TITLE
training problem,i can't run it well.

### ISSUE THREAD

**Issue by EkilGitHub** [MouseLand/cellpose#176]
when i  run " python -m cellpose --train ...." by use pytorch. it tells me that:
**_RuntimeError: Tensor for argument #2 'weight' is on CPU, but expected it to be on GPU (while checking arguments for cudnn_batch_norm)_**
![image](https://user-images.githubusercontent.com/29229492/103595180-c9a7a400-4f35-11eb-9a5d-4f405ee1b7be.png)
The version I am running is release cellpose_0.6

**Comment by EkilGitHub** [comment]
i can solve this problem by change **core.py **,line 791, in  **_self.net.train()_** to **_self.net.train().cuda()_**.
it works well.

**Comment by carsen-stringer** [comment]
thanks for finding this bug, it is fixed in the github version
