### ISSUE TITLE
when  a pretrained model to use,the code could not work.

### ISSUE THREAD

**Issue by EkilGitHub** [MouseLand/cellpose#177]
![image](https://user-images.githubusercontent.com/29229492/103623151-a7804700-4f72-11eb-8109-55b159a1f1a6.png)
according to **_model.py  class CellposeModel(UnetModel)_**  its return values is 3
![image](https://user-images.githubusercontent.com/29229492/103623633-51f86a00-4f73-11eb-8bc8-296583fff7d3.png)
but  the **___main__.py_** in line 152 wants 4 return values.

**Comment by jboulanger91** [comment]
I have the same problem @carsen-stringer. 
I tried to find a workaround using a notebook but couldn't fix it. 
Thanks a lot for your help and amazing work.

**Comment by jboulanger91** [comment]
Adding the --test_dir xxx\test\  option worked for me (it should be optional so it's very confusing). 
When training using this command: `python -m cellpose --train --dir xxx\training\ --test_dir xxx\test\ --pretrained_model nuclei --diameter 8 --chan 0 --n_epochs 100 --use_gpu. `
I could use the output model later for predictions.

**Comment by jboulanger91** [comment]
I have been able to train using the following command: 
`python -m cellpose --train --dir ~\training\  --pretrained_model cyto --diameter 10 --chan 0 --chan2 0 --n_epochs 5000 --use_gpu `

As you suggest @EkilGitHub I had to change  **core.py **,line 789, in self.net.train() to self.net.train().cuda() to allow GPU training. 

I could predict using the following command: 
`python -m cellpose --dir ~\predictions --pretrained_model ~cellpose ...` 

However the predictions I get are way worse than the pre-trained Cellpose model ... I'd still exploring this issue.

**Comment by jboulanger91** [comment]
When trying to train using the notebook using the following command:
`model.train(train_data, train_labels, train_files=None, test_data=None, test_labels=None, test_files=None,
      channels=None, normalize=True, pretrained_model=None, save_path=save_path, save_every=100, 
      learning_rate=0.2, n_epochs=500, momentum=0.9, weight_decay=1e-05, batch_size=8, rescale=True) `

I get this error: 
`RuntimeError: running_mean should contain 50 elements not 2`

**Comment by EkilGitHub** [comment]
> I have been able to train using the following command:
> `python -m cellpose --train --dir ~\training\ --pretrained_model cyto --diameter 10 --chan 0 --chan2 0 --n_epochs 5000 --use_gpu `
> 
> As you suggest @EkilGitHub I had to change **core.py **,line 789, in self.net.train() to self.net.train().cuda() to allow GPU training.
> 
> I could predict using the following command:
> `python -m cellpose --dir ~\predictions --pretrained_model ~cellpose ...`
> Weirdly sometime I also get the same error as described by @EkilGitHub ... no clue why.
> 
> However the predictions I get are way worse than the pre-trained Cellpose model ... I'd still exploring this issue.


maybe you can not choice --diameter 10. and try again.

**Comment by EkilGitHub** [comment]
> I have been able to train using the following command:
> `python -m cellpose --train --dir ~\training\ --pretrained_model cyto --diameter 10 --chan 0 --chan2 0 --n_epochs 5000 --use_gpu `
> 
> As you suggest @EkilGitHub I had to change **core.py **,line 789, in self.net.train() to self.net.train().cuda() to allow GPU training.
> 
> I could predict using the following command:
> `python -m cellpose --dir ~\predictions --pretrained_model ~cellpose ...`
> Weirdly sometime I also get the same error as described by @EkilGitHub ... no clue why.
> 
> However the predictions I get are way worse than the pre-trained Cellpose model ... I'd still exploring this issue.

maybe you can delete "**_--diameter 10._**" and train again.

**Comment by jboulanger91** [comment]
@EkilGitHub I tried removing the diameter argument but I still have the same problem.

**Comment by carsen-stringer** [comment]
Cellpose has been pretrained with a diameter of 30, so I would recommend keeping the default.

Have you tried retraining from scratch? Unfortunately I haven't had much success training from the pretrained model either, particularly if the images are far out of class from the training set. You can download the full dataset here: http://www.cellpose.org/dataset

**Comment by carsen-stringer** [comment]
> When trying to train using the notebook using the following command:
> `model.train(train_data, train_labels, train_files=None, test_data=None, test_labels=None, test_files=None, channels=None, normalize=True, pretrained_model=None, save_path=save_path, save_every=100, learning_rate=0.2, n_epochs=500, momentum=0.9, weight_decay=1e-05, batch_size=8, rescale=True) `
> 
> I get this error:
> `RuntimeError: running_mean should contain 50 elements not 2`

Can you tell me more about this error? Sorry about these bugs, I've fixed the two other bugs you mentioned

**Comment by jboulanger91** [comment]
Thank you @carsen-stringer. Here is the where I get the error message when using the notebook: 
![cp_noteboook_err1](https://user-images.githubusercontent.com/62715309/105712838-aeb7c680-5f1a-11eb-849b-f4e3569291a2.JPG)

and the full err. message: 
`RuntimeError                              Traceback (most recent call last)
<ipython-input-23-c7acb4dce8b1> in <module>
     27 model.train(train_data, train_labels, train_files=None, test_data=None, test_labels=None, test_files=None,
     28       channels=None, normalize=True, pretrained_model=None, save_path=save_path, save_every=100,
---> 29       learning_rate=0.2, n_epochs=500, momentum=0.9, weight_decay=1e-05, batch_size=8, rescale=True)                             
     30 

~\anaconda3\envs\cellpose\lib\site-packages\cellpose\models.py in train(self, train_data, train_labels, train_files, test_data, test_labels, test_files, channels, normalize, pretrained_model, save_path, save_every, learning_rate, n_epochs, momentum, weight_decay, batch_size, rescale)
    640                                      test_data, test_flows,
    641                                      pretrained_model, save_path, save_every,
--> 642                                      learning_rate, n_epochs, momentum, weight_decay, batch_size, rescale)
    643         self.pretrained_model = model_path
    644         return model_path

~\anaconda3\envs\cellpose\lib\site-packages\cellpose\core.py in _train_net(self, train_data, train_labels, test_data, test_labels, pretrained_model, save_path, save_every, learning_rate, n_epochs, momentum, weight_decay, batch_size, rescale, netstr)
    926                 if self.unet and lbl.shape[1]>1 and rescale:
    927                     lbl[:,1] /= diam_batch[:,np.newaxis,np.newaxis]**2
--> 928                 train_loss = self._train_step(imgi, lbl)
    929                 lavg += train_loss
    930                 nsum += len(imgi)

~\anaconda3\envs\cellpose\lib\site-packages\cellpose\core.py in _train_step(self, x, lbl)
    788             self.optimizer.zero_grad()
    789             self.net.train().cuda()
--> 790             y, style = self.net(X)
    791             loss = self.loss_fn(lbl,y)
    792             loss.backward()

~\anaconda3\envs\cellpose\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~\anaconda3\envs\cellpose\lib\site-packages\cellpose\resnet_torch.py in forward(self, data)
    189         if self.mkldnn:
    190             data = data.to_mkldnn()
--> 191         T0    = self.downsample(data)
    192         if self.mkldnn:
    193             style = self.make_style(T0[-1].to_dense())

~\anaconda3\envs\cellpose\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~\anaconda3\envs\cellpose\lib\site-packages\cellpose\resnet_torch.py in forward(self, x)
     81             else:
     82                 y = x
---> 83             xd.append(self.down[n](y))
     84         return xd
     85 

~\anaconda3\envs\cellpose\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~\anaconda3\envs\cellpose\lib\site-packages\cellpose\resnet_torch.py in forward(self, x)
     44 
     45     def forward(self, x):
---> 46         x = self.proj(x) + self.conv[1](self.conv[0](x))
     47         x = x + self.conv[3](self.conv[2](x))
     48         return x

~\anaconda3\envs\cellpose\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~\anaconda3\envs\cellpose\lib\site-packages\torch\nn\modules\container.py in forward(self, input)
    115     def forward(self, input):
    116         for module in self:
--> 117             input = module(input)
    118         return input
    119 

~\anaconda3\envs\cellpose\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~\anaconda3\envs\cellpose\lib\site-packages\torch\nn\modules\batchnorm.py in forward(self, input)
    134             self.running_mean if not self.training or self.track_running_stats else None,
    135             self.running_var if not self.training or self.track_running_stats else None,
--> 136             self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
    137 
    138 

~\anaconda3\envs\cellpose\lib\site-packages\torch\nn\functional.py in batch_norm(input, running_mean, running_var, weight, bias, training, momentum, eps)
   2056     return torch.batch_norm(
   2057         input, weight, bias, running_mean, running_var,
-> 2058         training, momentum, eps, torch.backends.cudnn.enabled
   2059     )
   2060 

RuntimeError: running_mean should contain 50 elements not 2`

Thanks a lot for your help. 
Jon

**Comment by carsen-stringer** [comment]
oh it seems like Cellpose thinks your images have 50 channels, is that true? what is the shape of `train_data[0]`?

**Comment by its-jd** [comment]
Hey thank you so much for the great work!

I am trying to train on my custom dataset and got the same eror.
I have training images with three channels (shape: (3,820,820)) and .png labels in label format (shape: (820,820))
please have a look at the error traceback and let me know if  you know of any possible reason for this error.

![image](https://user-images.githubusercontent.com/41875270/106741713-5c625e00-661c-11eb-8325-5615caab21b9.png)


Thank you so much!

**Comment by its-jd** [comment]
I converted all training images into grayscale and now I am getting this error. I am not sure, what do 2 elements  mean in the error and from where it's getting that


![image](https://user-images.githubusercontent.com/41875270/106756017-1662c580-662f-11eb-8f8b-d971ec340700.png)


> Hey thank you so much for the great work!
> 
> I am trying to train on my custom dataset and got the same eror.
> I have training images with three channels (shape: (3,820,820)) and .png labels in label format (shape: (820,820))
> please have a look at the error traceback and let me know if you know of any possible reason for this error.
> 
> ![image](https://user-images.githubusercontent.com/41875270/106741713-5c625e00-661c-11eb-8325-5615caab21b9.png)
> 
> Thank you so much!

**Comment by carsen-stringer** [comment]
If your images have different numbers of channels you need to specify `nchan=3` in the `CellposeModel(nchan=3, pretrained_model=None)` call, that will create the model with the right number of image channels. then train with your images.

from the command line interface, add the `--all_channels` flag and cellpose will determine `nchan` and initialize accordingly. <<this was supposed to work correctly but there was a bug I fixed yesterday. please try the latest code.
