### ISSUE TITLE
How to get cytoplasma area without nuclear

### ISSUE THREAD

**Issue by monroelml** [MouseLand/cellpose#179]
Segmentation of cytoplasma and nuclear works well by using Cellpose. My target is the cytoplasma area without nuclear. Now I make cytoplasm segmentation and nuclear segmentation independently and then subtract nuclear mask from cytoplasm mask. I am just wondering if I can get subtracted image at once. 

If you can suggest some solution, I will be very grateful.
Thank you very much.

**Comment by jboulanger91** [comment]
You could try to use the cyto only as training data but I'm not sure Cellpose is designed to predict such objects.

**Comment by carsen-stringer** [comment]
we don't have an integrated solution for this - the cytoplasm and nucleus need to be predicted separately -- the way you're computing it now is the recommended solution

**Comment by monroelml** [comment]
Thank you very much. I have tried to train cyto image to get nuclear. It is not successful as @jboulanger91 pointed out. So I guess I will just do segmentation separately and subtract later.
