### ISSUE TITLE
Extracting (x,y) positions of cell centers

### ISSUE THREAD

**Issue by ostapstephan** [MouseLand/cellpose#18]
Hi, 

I like the work you have done, your model seems to work well for the task I need. I am trying to use your code in a pipeline for cell clustering. Is there a way to get the x,y position of the center of each of the cells. 

Thanks!

**Comment by cyf203** [comment]
Agree! Altought imagepy (a ImageJ-liked python-based package) integrate cellpose and probably can do such things, but I found many issues when I use cellpose as a plugin in imagepy. So, if cellpose can provide a basic function to get the x,y position of the center of each mask/cell. That will be very helpful.

**Comment by marius10p** [comment]
The output of cellpose includes pixel masks for every cell, in the npy file. Therefore to get the centers, all you have to do is average those coordinates (or take the median).

**Comment by ostapstephan** [comment]
Thanks, I ended up using the unique cell  using the method here to find the center. If anyone is interested.
https://www.learnopencv.com/find-center-of-blob-centroid-using-opencv-cpp-python/  

After getting the mask object given by cellpose I did the following.

```
def get_centroid(img):
    img[img>0]=1
    img =np.array(img,dtype=np.uint8)
    gray_image = cv2.cvtColor(cv2.cvtColor(img, cv2.COLOR_GRAY2BGR), cv2.COLOR_BGR2GRAY)   
    # calculate moments of binary image
    M = cv2.moments(gray_image)

    # calculate x,y coordinate of center
    cX = int(M["m10"] / M["m00"])
    cY = int(M["m01"] / M["m00"])

    return (cY,cX)
    

coords =[]
for idx in range(len(masks)):
    maski = masks[idx]

    # get the number of cells we found
    num = np.unique(maski)[-1]
    print(f'num: {num}')

    for i in range(num):
        if i == 0:
            # 0 means nothing there 1 is the first cell
            continue
        m = maski.copy()
        m[m!= i] = 0
        coords.append(get_centroid(m))
```
