### ISSUE TITLE
Cellpose not finding large constructs

### ISSUE THREAD

**Issue by bilbylazer** [MouseLand/cellpose#180]
Cellpose  is unable to find large constructs in my images. Any idea on how to help this or how to train my own model?

![Bright_ORG_cp_output](https://user-images.githubusercontent.com/77159326/104026295-526b4d80-518b-11eb-8007-f02db6c8c6c9.png)

**Comment by EkilGitHub** [comment]
you can read the last paragraph of _**gui.rst**_ ,It is placed in the  **_docs_** folder. 
This may be useful to you

**Comment by carsen-stringer** [comment]
there aren't any examples like this in the cellpose database, if you have some labelled images you can submit them to the cellpose server. alternatively you can train your own model: https://cellpose.readthedocs.io/en/latest/train.html
