### ISSUE TITLE
mx_GPU torch_GPU management

### ISSUE THREAD

**Issue by max-endeavour** [MouseLand/cellpose#182]
Hi,

I'm having issue with the way you handle mx and torch gpu on the software.
Indeed in you code core.py the try except does not assign a default value to the torch_GPU (neither CPU) to the mx_GPU (nor CPU). Thus, line 84 when willing to use it a variable not found is raised.
Here are the involved pieces of code: l12 to 31 in core.py

```try:
    from mxnet import gluon, nd
    import mxnet as mx
    from . import resnet_style
    MXNET_ENABLED = True 
    mx_GPU = mx.gpu()
    mx_CPU = mx.cpu()
except:
    MXNET_ENABLED = False

try:
    import torch
    from torch import optim, nn
    from torch.utils import mkldnn as mkldnn_utils
    from . import resnet_torch
    TORCH_ENABLED = True 
    torch_GPU = torch.device('cuda')
    torch_CPU = torch.device('cpu')
except:
    TORCH_ENABLED = False
```

The error is then raised by the assign device method l80
```
def assign_device(istorch, gpu):
    if gpu and use_gpu(istorch=istorch):
        device = torch_GPU if istorch else mx_GPU
        gpu=True
        print('>>>> using GPU')
    else:
        device = torch_CPU if istorch else mx_CPU
        print('>>>> using CPU')
        gpu=False
    return device, gpu
```

This is a good practice not to let a used variable unset especially in a try except event where the error can thus be hard to spot.

Unfortunately I don't know how to fix this, maybe by assigning default computer CPU when the try fails for both.

Cheers

**Comment by carsen-stringer** [comment]
if both fail then neither mxnet nor pytorch are installed correctly - there's no need to have a gpu installed to set mx.gpu() and torch.device('cuda'). I agree that I should have more error handling here, but how did you get both to fail? :)
