### ISSUE TITLE
TORCH CUDA version not installed/working.

### ISSUE THREAD

**Issue by fanweiya** [MouseLand/cellpose#184]
---
OS:  ubuntu 18.04
GPU: GeForce RTX 3090
Python: 3.7.9
torch: 1.7.1+cu110
-----
```
>>> import torch
>>> print(torch.__version__)
1.7.1+cu110
>>> print(torch.cuda.is_available())
True
```
```
python -m cellpose
TORCH CUDA version not installed/working.
```
I’m sure my torch can be used, but I can’t use it properly with cellpose.

**Comment by carsen-stringer** [comment]
hmm can you try to create an array on the GPU? that's the test that cellpose performs:
```
device = torch.device('cuda:0')
_ = torch.zeros([1, 2, 3]).to(device)
```

**Comment by fanweiya** [comment]
```
(cellpose) alit@alit-PowerEdge-T640:/data/origin_data/instance_seg$ python
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> device = torch.device('cuda:1')
>>> torch.zeros([1, 2, 3]).to(device)
tensor([[[0., 0., 0.],
         [0., 0., 0.]]], device='cuda:1')

```

**Comment by EkilGitHub** [comment]
> ```
> (cellpose) alit@alit-PowerEdge-T640:/data/origin_data/instance_seg$ python
> Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
> [GCC 7.3.0] :: Anaconda, Inc. on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import torch
> >>> device = torch.device('cuda:1')
> >>> torch.zeros([1, 2, 3]).to(device)
> tensor([[[0., 0., 0.],
>          [0., 0., 0.]]], device='cuda:1')
> ```
the problem maybe is in the header file. you can try comment out **_from * import_** .
such as change  **_from * import resnet_torch_**  to  _**import resnet_torch**_.

**Comment by fanweiya** [comment]
> > ```
> > (cellpose) alit@alit-PowerEdge-T640:/data/origin_data/instance_seg$ python
> > Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
> > [GCC 7.3.0] :: Anaconda, Inc. on linux
> > Type "help", "copyright", "credits" or "license" for more information.
> > >>> import torch
> > >>> device = torch.device('cuda:1')
> > >>> torch.zeros([1, 2, 3]).to(device)
> > tensor([[[0., 0., 0.],
> >          [0., 0., 0.]]], device='cuda:1')
> > ```
> 
> the problem maybe is in the header file. you can try comment out **_from * import_** .
> such as change **_from * import resnet_torch_** to _**import resnet_torch**_.

thank you,It worked for me

**Comment by carsen-stringer** [comment]
I don't understand why this worked, I thought it was an issue with me having the default GPU number as `0`. Do you know why changing this from a relative import fixed it?

**Comment by EkilGitHub** [comment]
> I don't understand why this worked, I thought it was an issue with me having the default GPU number as `0`. Do you know why changing this from a relative import fixed it?

Scripts that use relative paths can't be directly import and run. Duing execution,the name of the module will change to  __main__.py but not current module's name.
Note that both explicit and implicit relative imports are based on the name of the current module. Since the name of the main module is always "__main__", modules intended for use as the main module of a Python application should always use absolute imports.
you can do it  by:
python -m module.py

**Comment by carsen-stringer** [comment]
thanks this is useful to know! it's weird that it works for me, I've changed the imports
