### ISSUE TITLE
issues with img/flows in seg_npy file

### ISSUE THREAD

**Issue by bindassylvie** [MouseLand/cellpose#187]
In the seg npy files the model outputs, (1) there is no 'img' field and (2) the size of the flows does not match with the pixel size of the original image - why might this be?

thanks!

**Comment by carsen-stringer** [comment]
in the output from 3D we don't resave the img because it's too big. also in 3D, if the diameter is a different size then the flows will be computed at a different size and not rescaled to the original image size. You can run cv2.resize to rescale the flows to the original image size.

**Comment by carsen-stringer** [comment]
if this is a 2D output please let me know because then this is a bug!

**Comment by carsen-stringer** [comment]
there was a bug here in 2D in terms of resizing, I've made a new release, please `pip install cellpose --upgrade`. the GUI is backward compatible with non-resized 2D processing outputs as well

**Comment by motviybletb** [comment]
> there was a bug here in 2D in terms of resizing, I've made a new release, please `pip install cellpose --upgrade`. the GUI is backward compatible with non-resized 2D processing outputs as well

I already upgraded cellpose, but 'img' is still missing for some reason
But GUI can open npy file correctly
