### ISSUE TITLE
NumPy pinned to <1.17

### ISSUE THREAD

**Issue by jni** [MouseLand/cellpose#19]
Hello! I'll open by saying that the day after cellpose was announced, my colleague and I held our usual image analysis office hours, and cellpose almost perfectly segmented *all* our visitors' cell images. So, thank you, and thank you also for the website "test" that allows us to instantly check if it's going to work for our users, without any installs at all. :tada: 

Anyway, now I was getting ready to play around with it locally, and was dismayed to see it downgrade my NumPy! I tried to scan the git history for the reason but couldn't find anything clear. Can I ask why it's pinned? With some pointers, I'd be super happy to submit a PR to remove this requirement.

Thank you!

**Comment by marius10p** [comment]
That's why we recommend installing in a conda environment. There has been some variability in the MKL implementations for recent version of NumPy, so we pinned to 1.17 until this stabilizes. Without MKL, the CPU version of mxnet is much slower. Maybe it's fixed by now, we'll try again soon.

**Comment by jni** [comment]
Do you have a small benchmark that could be used to create an issue on the NumPy repo? It'd be nice to let the NumPy devs know of a performance regression, rather than waiting to see if it fixes itself...

**Comment by mgheirat** [comment]
Hi. Thank you for developing this great segmentation tool. On the same topic, I am getting the following error during pip install cellpose in a conda environment:

**ERROR: opencv-python 4.2.0.32 has requirement numpy>=1.17.3, but you'll have numpy 1.16.6 which is incompatible.**

Just wondering whether this would cause a problem in running cellpose (from jupyter) or further post processes on the cellpose output using numpy or other image processing packages. 

Thank you. 

p.s. As mentioned by the other user, attempts to update numpy fails (also warns an inconsistent environment: 
The following packages are causing the inconsistency:
- defaults/osx-64::mkl_random==1.1.0=py38h6440ff4_0
- defaults/osx-64::numpy==1.18.1=py38h7241aed_0
- defaults/osx-64::mkl_fft==1.0.15=py38h5e564d8_0

p.p.s. OS: Mac OS (Mojave 10.14.6)

**Comment by carsen-stringer** [comment]
I think numpy 1.18 is working fine so I've unpinned this dependency. but we need to keep python<=3.7 for now (pyqtgraph has errors with 3.8)
