### ISSUE TITLE
imagej outlines to txt creates empty lines, error with imagej_roi_converter.py

### ISSUE THREAD

**Issue by papalagirauscher** [MouseLand/cellpose#191]
Hello!
Sometimes empty lines are written into the imagej roi output txt. This results in the imagej_roi_converter.py script throwing errors. 

I suggest adding a skip empty lines statement to the conververt script. Please find attached a possible solution.

from ij import IJ;
from ij.plugin.frame import RoiManager;
from ij.gui import PolygonRoi;
from ij.gui import Roi;
from java.awt import FileDialog

fd = FileDialog(IJ.getInstance(), "Open", FileDialog.LOAD)
fd.show()
file_name = fd.getDirectory() + fd.getFile()
print(file_name)

RM = RoiManager()
rm = RM.getRoiManager()

imp = IJ.getImage()

with open(file_name, 'r') as textfile:
	for line in textfile:
		**if not line.rstrip():
       			continue**
		xy = map(int, line.rstrip().split(','))
		X = xy[::2]
		Y = xy[1::2]
		imp.setRoi(PolygonRoi(X, Y, Roi.POLYGON));
		#IJ.run(imp, "Convex Hull", "")
		roi = imp.getRoi()
		print roi
		rm.addRoi(roi)

rm.runCommand("Associate", "true")
rm.runCommand("Show All with labels")

Warm regards,
Jan

**Comment by carsen-stringer** [comment]
Thanks Jan, can you open a pull request with this change?

**Comment by papalagirauscher** [comment]
Hello!
I would like to help, but sadly am not familiar with how the GitHub ecosystem works. I will try to create one

**Comment by JKesby** [comment]
Hi, I keep getting the following error when trying to run the imagej_roi_converter.py script:

SyntaxError: ("mismatched input '<' expecting EOF", ('<string>', 7, 0, ''))

I am not sure if this is related to this issue or not, but any idea why this is occurring? I really just want to get the outlines for all segmented cells as an image to feed into Cellprofiler.
Thanks for the excellent program.
Cheers,
James

**Comment by papalagirauscher** [comment]
Hello James, 
Try adding the highlighted lines in the converting script and indent them properly (one indent first line, two indents second line). I don’t remember if the error that I got was the same, but could be and it worked flawless afterwards, even with insanely huge files.

Warm regards,
Jan

**Comment by JKesby** [comment]
Hi Jan,

found another issue on my side but this helped immensely. Thanks!

**Comment by carsen-stringer** [comment]
hey @papalagirauscher  and @JKesby , if you have a fix I'd really appreciate a pull request with correct file if you can.

github will automatically make a fork if you edit the appropriate file:
![image](https://user-images.githubusercontent.com/15067541/116396362-4ca97e80-a7f3-11eb-9360-568d0bc5ff51.png)

then from your fork you click "create pull request" and it should create a pull request on the cellpose repo
