### ISSUE TITLE
Unclear license of pretrained models

### ISSUE THREAD

**Issue by gkossakowski** [MouseLand/cellpose#192]
I've been looking at the license of pretrained models and I can't find it. It's not part of the repo so I'm guessing it's not covered by BSD3?

I also noticed that the raw dataset has custom license: http://www.cellpose.org/dataset

Which of the two covers pretrained models?

**Comment by marius10p** [comment]
Thanks for pointing this out. The license status of pretrained models is a gray zone (look up Imagenet pretrained models).

The additional license we put on the model files is the same Cellpose BSD3 license. However, depending on your interpretation of licensing laws, the models may or may not inherit the non-commercial use license from the images in the training dataset. We will let you know if we learn more about this, but meanwhile it is up to you to make this determination.

**Comment by gkossakowski** [comment]
Thanks for the swift response and the clarification!
I was expecting the license of pretrained model to be a tricky issue. Good point on checking ImageNet models to look for precedents.
