### ISSUE TITLE
Literature implementation mismatch

### ISSUE THREAD

**Issue by eddy6081** [MouseLand/cellpose#193]
According to the paper published in Nature Methods, in each up-pass layer the operation _G_ is performed which reads as follows:
_G(x)[k,i,j] = F(x)[k,i,j] + P(s)[k]_
where the operation _P(s)_ is the projection of the "style" vector and _F_ is the function performing the batch-norm, ReLU, and 2D convolution operations. This suggests that the convolution should first be performed on the input of G, and then the style projection added. 

It seems that in the up-pass the argument of _G(x)_ is first being added to _P(s)_ and then the convolution _F(x)_ is being taken over that result. To be clear, the convolution is being performed **after** the addition. This equation would read as:
_G(x)[k,i,j] = F(x[k,i,j] + P(s)[k])_
https://github.com/MouseLand/cellpose/blob/1a3eea8bc49371f80526462b93c8c06e6f8fec4e/cellpose/resnet_style.py#L112-L114

Am I misinterpreting the equation, or is there a mismatch in the operation being performed?

**Comment by marius10p** [comment]
Yes, I think you're right, sorry about that.

**Comment by eddy6081** [comment]
Thanks Dr. Pachitariu! Just to clarify then, should line 114 and 113 be switched or should it remain as is and the equation is changed?

**Comment by marius10p** [comment]
I think the equation is wrong and the code makes sense. The performance of the model probably wouldn't change much if the lines were swapped.
