### ISSUE TITLE
How to reproduce pretrained models?

### ISSUE THREAD

**Issue by gkossakowski** [MouseLand/cellpose#198]
Hi,

I'd like to reproduce training of pretrained models you provide. I looked at:
https://cellpose.readthedocs.io/en/latest/train.html
and downloaded the data from:
http://cellpose.org/dataset

My understanding is that this lets me train cyto model. For the nuclei model, I need the other dataset you describe in your paper (with 1139 images). Is that right?

Also, what are the exact cmd parameters you use to train 4 model variants for the model ensemble?

**Comment by carsen-stringer** [comment]
Here is the string:
```
python -m cellpose --train --dir /datasets/cellpose/train --test_dir /datasets/cellpose/test --img_filter _img --pretrained_model None --n_epochs 500 --chan 2 --chan2 1 --learning_rate 0.2
```
