### ISSUE TITLE
how do you arrive at these numbers?

### ISSUE THREAD

**Issue by pskeshu** [MouseLand/cellpose#199]
https://github.com/MouseLand/cellpose/blob/ac1a301178180fb4a231010b4dabdd4f8a9bae33/cellpose/models.py#L106

**Comment by pr4deepr** [comment]
You can read in the documentation:
https://cellpose.readthedocs.io/en/latest/settings.html#diameter
My understanding is that this is based on the median diameter of the cells/nuclei within the images used to train cellpose models.
"The cellpose models have been trained on images which were rescaled to all have the same diameter (30 pixels in the case of the cyto model and 17 pixels in the case of the nuclei model)."

Cellpose paper as well: https://www.nature.com/articles/s41592-020-01018-x
