### ISSUE TITLE
Batch processing and quantification per cell

### ISSUE THREAD

**Issue by atreyiChak** [MouseLand/cellpose#20]
Hi, 

Cellpose is the by far the best platform for cell segmentation that I have come across so far - both in terms of accuracy and user-friendliness. 

I am a biologist and would like to segment my cells in cultures and brain slices, and measure pixel intensities within the masked areas across different channels. Is there a way this can be implemented in cellpose or using the individual _seg.npy files in a separate python script?

Also, is there a way in the cellpose GUI to run automatic segmentation on multiple files in a given directory for batch processing?

Thank you for your help!

**Comment by marius10p** [comment]
For batch processing and image analytics, you probably want to set up your own python script, where you can also call cellpose directly and get as output the pixels associated with each cell. See the [Jupyter notebook](https://github.com/MouseLand/cellpose/blob/master/notebooks/run_cellpose.ipynb) example to start from. You don't need much programming experience to set these up. In the future, other image processing frameworks downstream of cellpose could implement more image analytics.

**Comment by carsen-stringer** [comment]
I've also added the option to run cellpose on the command line with a directory as input: https://github.com/MouseLand/cellpose#from-the-command-line

**Comment by vinisalazar** [comment]
Hi,

I'm trying to run Cellpose on the command line like described. However, the image it exports does not contain any masks. I'm using the same settings as in the GUI. Any thoughts on what is happening?

Thank you for any assistance you can provide.

**Comment by peggyscshu** [comment]
Hi there,

Cellpose is indeed a good tool to segment fluorescence images. I am trying to convert text files generated by Cellpose in a batch mode, therefore I did some modifications in the script "imagej_roi_converter.py" and wrote a image j macro to do it. Somehow, image j macro editor interpreted them well. 
Here is the macro to do the batch conversion.
![image](https://user-images.githubusercontent.com/67047201/106082882-7c92a880-6156-11eb-9ec6-a8bee3b7fb55.png)
The following is the py code modified from the original version.
![image](https://user-images.githubusercontent.com/67047201/106082904-89af9780-6156-11eb-958c-4d93a11357f9.png)
And this is the error message shown in log.
![image](https://user-images.githubusercontent.com/67047201/106082981-aba91a00-6156-11eb-90db-a6d40bd45be1.png)

Could anyone here help me to go through it? If you already have the solution for batch conversion, I appreciate ahead for your kindly share.

By the way, the batch process goes well on my hand, but I still have further questions.
1.  Here is the spec of my HP Z840 workstation equipped with Xeon E5-2623 3Ghz dual processors, NVIDA QuadroK2200 and 128GB RAM. CUDA toolkit is updated to the latest version 11.2.  Every 2D image costs 1 min and a 53 slices z stack will cause the system exhausted. Can you recommend a PC spec to run Cellpose efficiently?
2. The parameters "model match threshold" and "cell prob threshold" are missing in the command line document. Are these parameters also adjustable in the batch mode?

Thank you for your help in advance.


All Best,
Peggy

**Comment by Andrianarivelo** [comment]
Hi there, 

Did you solve the problem Peggy ? 
I am experiencing the same issue,

Best wishes, 
Andry

**Comment by aftabnadim** [comment]
> Hi there,
> 
> Cellpose is indeed a good tool to segment fluorescence images. I am trying to convert text files generated by Cellpose in a batch mode, therefore I did some modifications in the script "imagej_roi_converter.py" and wrote a image j macro to do it. Somehow, image j macro editor interpreted them well. Here is the macro to do the batch conversion. ![image](https://user-images.githubusercontent.com/67047201/106082882-7c92a880-6156-11eb-9ec6-a8bee3b7fb55.png) The following is the py code modified from the original version. ![image](https://user-images.githubusercontent.com/67047201/106082904-89af9780-6156-11eb-958c-4d93a11357f9.png) And this is the error message shown in log. ![image](https://user-images.githubusercontent.com/67047201/106082981-aba91a00-6156-11eb-90db-a6d40bd45be1.png)
> 
> Could anyone here help me to go through it? If you already have the solution for batch conversion, I appreciate ahead for your kindly share.
> 
> By the way, the batch process goes well on my hand, but I still have further questions.
> 
> 1. Here is the spec of my HP Z840 workstation equipped with Xeon E5-2623 3Ghz dual processors, NVIDA QuadroK2200 and 128GB RAM. CUDA toolkit is updated to the latest version 11.2.  Every 2D image costs 1 min and a 53 slices z stack will cause the system exhausted. Can you recommend a PC spec to run Cellpose efficiently?
> 2. The parameters "model match threshold" and "cell prob threshold" are missing in the command line document. Are these parameters also adjustable in the batch mode?
> 
> Thank you for your help in advance.
> 
> All Best, Peggy

Hi Peggy,

Could you please share the text file for the Image J macro that you generated for batch processing? 
Another question, is it possible to run this macro if I am using PBIOP plugin for ImageJ to run cellpose?

Best wishes,
Aftab
