### ISSUE TITLE
Wiggly Cell Boundaries

### ISSUE THREAD

**Issue by mayishazn** [MouseLand/cellpose#201]
How can I get cellpose to recognize wiggly cell boundaries instead of recognizing smoothed versions of the boundaries? Is this a problem that a small trained data set can help with? Advice would be appreciated. Thanks! 

By the way, I am super grateful to you for creating cellpose! <3 

![Screenshot (126)](https://user-images.githubusercontent.com/43865608/107594403-da57d380-6bdf-11eb-9ad6-95ce4e0f11b6.png)

**Comment by kevinjohncutler** [comment]
Re-training with a small dataset should help, but I also suspect that turning off rescaling should help capture those smaller boundary features.

**Comment by carsen-stringer** [comment]
hmm yeah I think that the model needs new data to capture this unfortunately
