### ISSUE TITLE
Large delay between *.npy/masks.png outputs to outlines.txt

### ISSUE THREAD

**Issue by JKesby** [MouseLand/cellpose#204]
Hi,

I am running rather large files (20-40k average pixel dimensions and 1-2GB in size), so it takes a while to process the files. This is fine but there is a huge lag between generating the masks and npy files before the outline txt files are generated.
I am actually only after the outline ROIs so I was wondering if there was something I could do to speed up that part of the process.

I am running on GPU (** TORCH CUDA version installed and working. **) but do not see any GPU activity during processing (just roughly 7-10% CPU usage consistently throughout).

An example of file times in some tests I ran with cropped images:

Size of image / total time to generate npy file / lag to outline file generation / outline file size
300 MB / 10 min / 2 h    / 30 MB
530 MB / 30 min / 3.5 h / 51 MB
630 MB / 40 min / 6.5 h / 63 MB
770 MB / 60 min / 10 h  / 80 MB

These are 16-bit files full of nuclei (40x magnification with nuclei size at 50 for cellpose). Any idea how I can speed up the outline file generation (I run using Jupyter notebook)? Seems like an extremely long time to generate the text file given the processing (npy file) has been completed.
If this is expected behaviour then I will just have to live with it.

Thanks for your help.
James

**Comment by JKesby** [comment]
To follow up on this. I have found a way to use the PNG files without the ROIs. Is there a way to produce ONLY the PNG files and rather than wait for the ROI, just move on to the next file?

**Comment by Michael-shannon** [comment]
Hi James. I'm not a part of the cellpose team, and am a user myself. If you run cellpose from the command line interface, you can add the flag --no_npy to prevent saving of the npy file, and --save_tif or --save_png to save either of those after each processed image.

I don't know about the outline/ROI files though. Perhaps you could do that fast using an imagej macro from the mask files?

**Comment by JKesby** [comment]
Hi Michael, thanks for the reply. I have added the --no_npy flag and use --save_png.
What I think I need (now that I can use the png file rather the the ROI.txt) is a flag --no_ROI as the generation of the NPY and png files occurs hours before the ROI.txt is finished. 
Wasted computer processing time if the ROI is not required.

**Comment by carsen-stringer** [comment]
oh wow I had no idea creating the ROI text files could be so slow. I will add a flag for this

**Comment by carsen-stringer** [comment]
there is a new flag `--save_outlines` to create the outlines for ImageJ. If not specified, no outlines will be created

**Comment by JKesby** [comment]
Thanks, this should speed things up.
Great program as well.
