### ISSUE TITLE
Extract all detected cells as independent images

### ISSUE THREAD

**Issue by jeannechaverot** [MouseLand/cellpose#205]
Great project!

The identification of cells works perfectly for my data. Once I have the images, masks and flows how can I get the coordinates of each identified cell? 

I would like to create a new image for each cell found by the algorithm.

![image](https://user-images.githubusercontent.com/10252332/107959236-e77b1680-6f81-11eb-90b8-8945a2f19078.png)

**Comment by apaks** [comment]
Hello,

Thanks for the great tool.  
I am, actually, looking into the same issue. Is there an efficient way of doing this?

At this point, I simply looping over all cells. 



    # load seg npy file
    seg = np.load(fname, allow_pickle =  True).item()
    masks = seg["masks"]
    img_path = seg["filename"]

    img = io.imread(img_path)
    ls_outlines = utils.outlines_list(masks)
  
    for idx, cell in enumerate(ls_outlines[:]):
        # mask outline
        mask = np.zeros(img.shape, dtype=np.uint8)
        channel_count = img.shape[2]  # i.e. 3 or 4 depending on your image
        ignore_mask_color = (255,)*channel_count
        cv2.fillConvexPoly(mask, cell, ignore_mask_color)

        masked_image = cv2.bitwise_and(img, mask)
        
        # crop the cell
        x = cell.flatten()[::2]
        y = cell.flatten()[1::2]

        (topy, topx) = (np.min(y), np.min(x))
        (bottomy, bottomx) = (np.max(y), np.max(x))
        out = masked_image[topy:bottomy+1, topx:bottomx+1,:]
        
        # cv2.imwrite(os.path.join(name, str(idx) + ".png" ), out)
        im = Image.fromarray(out)
        im.save(os.path.join(foldername, os.path.basename(foldername) + str(idx) + ".png" ))

**Comment by carsen-stringer** [comment]
thanks for the code @apaks I would recommend your approach for making a new image for each cell, we won't support this type of output natively.

@jeannechaverot is this the sort of solution you were looking for? if not please comment, I'm going to close the issue for now
