### ISSUE TITLE
ZeroCostDL4Mic Notebook

### ISSUE THREAD

**Issue by guijacquemet** [MouseLand/cellpose#209]
Hi,
Many thanks for developing this fantastic segmentation DL algorithm!
We are now starting to use it quite a bit in my lab.
I just wanted to share that we created a [ZeroCostDL4Mic](https://github.com/HenriquesLab/ZeroCostDL4Mic) notebook for Cellpose 2D, that you can access [here](https://github.com/HenriquesLab/ZeroCostDL4Mic/wiki#under-beta-testing) in case you find it useful.
Cheers
Guillaume

**Comment by carsen-stringer** [comment]
very awesome thanks! I've added a link to the notebook in our readme
