### ISSUE TITLE
Neurons segmentation

### ISSUE THREAD

**Issue by PMLLancao** [MouseLand/cellpose#21]
Hello.
I tried the online version of Cellpose with some hippocampal neurons in culture at 3DIV.
I wanted to see if CEllpose can segment the neurites and axon and if the program can count automatically the number of extension per cell. This feature would be a great advantage compared to other free sources since most of the detection of neurites or axon requires manual tracking.

Cellpose could detect cell body ( I did not have a nuclei stain) relatively well, but not the rest of the cell extension.
Maybe is not the main purpose of CEllpose to detect neurons but it would be a great tool. 
To quantify the number of neurites and length or even fluorescence intensity in those structures.

Thanks for this great tool.
Regards
![EQNL3KNWsAM17EO](https://user-images.githubusercontent.com/24482728/74973282-2a4af280-53f1-11ea-8771-704a4e0eb849.png)
![EQNL3KKWsAE27Qx](https://user-images.githubusercontent.com/24482728/74973284-2a4af280-53f1-11ea-8585-73139642a8c3.png)
![EQNL3KKXUAAciNC](https://user-images.githubusercontent.com/24482728/74973285-2a4af280-53f1-11ea-91d7-6dd90b17c4b1.png)
![EQNL3KNXUAY1niX](https://user-images.githubusercontent.com/24482728/74973286-2a4af280-53f1-11ea-846d-df679324d261.png)

**Comment by marius10p** [comment]
Sorry, the pretrained Cellpose is specifically for cell body segmentation. You could imagine retraining it on a large dataset of neurites, but there is too much crossing between segments and Cellpose doesn't handle overlaps.
