### ISSUE TITLE
optimize the flow 2 label mask method

### ISSUE THREAD

**Issue by yxdragon** [MouseLand/cellpose#212]
I am trying to optimize the flow2mask method, but now I get the 2 channels XY vector from the eval result.
can you show me how to get the model's output (XY flow and cellprob) directly?

**Comment by yxdragon** [comment]
hi! a super fast flow to label algrithsm, 100 times faster than now. [cellpose flow2msk](https://github.com/Image-Py/cellpose2msk)
(with numba, it may becomes 300 times faster. and with cupy, it may becomes 3000 times faster)

supporting 2d/3d, but now I have no 3d test data

**Comment by carsen-stringer** [comment]
wow super fast! thanks, I will try running this on our test data and see how similar the results are.

**Comment by yxdragon** [comment]
yes，it needs more test，and add parameter auto estimate. but I think the method is ok.
now I only use the flow, so how to use the prob?  just prob > threshold?

**Comment by carsen-stringer** [comment]
thanks I'm not getting the kinds of speed ups you are. I'm comparing to the cellpose functions (excluding the quality control step, which your function doesn't have). Here is the code I compared to:
```
dP = flows[1]
cellprob = flows[2]
cellprob_threshold=0
niter= 200
interp=True
tic=time.time()
p = dynamics.follow_flows(-1 * dP * (cellprob > cellprob_threshold) / 5., 
                                                   niter=niter, interp=interp, use_gpu=True)
maski = dynamics.get_masks(p, iscell=(cellprob>cellprob_threshold),
                                                    flows=dP, threshold=0)
print(time.time()-tic)
```
For a 2048x2048 image, this takes the same amount of time as your function and allows interpolated dynamics. Without the GPU it is ~5x slower.

I do like the trick you're doing with the flows though to put them in 1D space, it may be possible to use it to speed up the QC step (which uses the slow function `masks_to_flows`)

**Comment by yxdragon** [comment]
could you show your test image？

mask 2  flow? I think it is distance transform + sobel.

**Comment by carsen-stringer** [comment]
I tiled one of our test images, see attached
![020_img_test](https://user-images.githubusercontent.com/15067541/110794490-cf767a00-8243-11eb-99c6-ea4fa499b243.png)

**Comment by qixinbo** [comment]
Hi, @carsen-stringer, I have tested the image with the algorithm from @yxdragon.
Below is the testing result, and it shows that the acceleration is obvious (22.36s versus 0.65s):
![image](https://user-images.githubusercontent.com/6218739/110909931-a3deb700-834b-11eb-81bd-ae465d90cd0e.png)

**Comment by carsen-stringer** [comment]
hmm I was getting ~1 second for both @yxdragon 's code and my code. I'm confused though are you running the QC step in cellpose as well, with `flow_threshold>0`? that is not within the above script. are you using the torch GPU version of cellpose or the cpu?

**Comment by yxdragon** [comment]
Hi, @carsen-stringer. We publish a repo [cellpose-planer](https://github.com/Image-Py/cellpose-planer) which need neighter torch nor mxnet. (run with only numpy, or accelerate with cupy)

I transfer the cellpose models through onnx. and rewrite some after-processing and render method.
may be you can have a look, or reference some method if needed. here is a demo.

**pip install cellpose-planer**

```python
import cellpose_planer as cellpp
from time import time
from skimage.io import imread
import numpy as np

# ===== if first time =====
# cellpp.search_models()
# cellpp.download()

print('reading a online image...')
img = imread('http://www.cellpose.org/static/images/img10.png')
img = np.tile(np.tile(img[:,:,0], 4).T, 4).T
x = img.astype('float32')/255

# ========== CUP ==========
import numpy as np
from scipy import ndimage as ndimg
# set cpu backend
cellpp.engine(np, ndimg)

net = cellpp.load_model('cyto_0')
# count flow
flow, prob, style = cellpp.tile_flow(net, x, size=768, work=2)
# flow 2 mask
start = time()
msk = cellpp.flow2msk(flow, prob)
print('flow 2 mask cost (cpu):', time()-start)

cellpp.show(img, flow, prob, msk)

# ========== GPU ==========
import cupy as cp
import cupyx.scipy.ndimage as cpimg
cellpp.engine(cp, cpimg)

net = cellpp.load_model('cyto_0')
# count flow
flow, prob, style = cellpp.tile_flow(net, x, size=768)
# flow 2 mask
msk = cellpp.flow2msk(flow, prob) # gpu preheat
start = time()
msk = cellpp.flow2msk(flow, prob)
print('flow 2 mask cost (gpu):', time()-start)


flow, prob, msk = [cellpp.asnumpy(i) for i in (flow, prob, msk)]
cellpp.show(img, flow, prob, msk)
```
on my computer (i7 cpu and 2070 gpu) the result is:
flow 2 mask cost (cpu): 0.475s
flow 2 mask cost (gpu): 0.039s

![image](https://user-images.githubusercontent.com/24822467/111036407-e4821300-83d3-11eb-9dd5-c9b8cc043ed4.png)

eg. We use cellpose's logo, and combine it with planer's logo. here ask your permission, may I use it?

**Comment by marius10p** [comment]
Hi @yxdragon, thanks for trying to make the code faster. Sorry, but you don't have permission to use our logo. We also would like you to use the following disclaimer prominently at the top of the readme: "Cellpose-planer is an unofficial port of Cellpose and is not guaranteed to produce the same results." You should also say somewhere: "If you use Cellpose-planer, please cite Stringer et al, Nature Methods 2021".

Finally, we tried your code and we noticed that the diameter cannot be changed. Results can be really bad if you don't allow that. It also produced worse results than the official implementation at IoUs of 0.75 and 0.9. I am going to add these as issues on your repo now.
