### ISSUE TITLE
Typo in sample notebook

### ISSUE THREAD

**Issue by snownontrace** [MouseLand/cellpose#214]
In "run_cellpose.ipynb" in the notebooks folder, inside the code commented out:

# you can run all in a list e.g.
# >>> imgs = [io.imread(filename) in files]

Missing "for filename" in the list comprehension. Found this out when uncommenting this to run images in a folder.

Thank you so much for making this amazing tool!

**Comment by carsen-stringer** [comment]
thanks for catching this, I think the new version no longer uses this format
