### ISSUE TITLE
module 'cellpose.utils' has no attribute 'use_gpu'

### ISSUE THREAD

**Issue by tbnxyzfz1** [MouseLand/cellpose#217]
I am using Windows 10 and Jupyter notebook to run a code downloaded from Github.
When I run this code
`use_gpu = cp_utils.use_gpu()`
I got this error
`module 'cellpose.utils' has no attribute 'use_gpu'`
My cellpose version is 0.6.1.
What's the problem and how to solve it?

**Comment by carsen-stringer** [comment]
can you point to the code source? the lines should be 
```
from cellpose import models
use_gpu = models.use_gpu()
```

**Comment by tbnxyzfz1** [comment]
> can you point to the code source? the lines should be
> 
> ```
> from cellpose import models
> use_gpu = models.use_gpu()
> ```

I am trying to use the OpSeF-IV-master. I ran the demo notebook cobblestone first, then ran the OpSeF_IV_Run_001.ipynb. The exact error is from line 130 in this file.
https://github.com/trasse/OpSeF-IV/blob/master/Utils_and_Configs/Segmentation_Func_06.py

**Comment by carsen-stringer** [comment]
this is not our repo, please put the issue there
