### ISSUE TITLE
Improving segmentation speed with GPU

### ISSUE THREAD

**Issue by Jsakkos** [MouseLand/cellpose#218]
I'm using the GPU-enabled version of Cellpose for segmenting images of bacteria. The images are single channel, ~2000 x 1500 pixels. The GPU version seems to speed things up considerably, e.g., on one image it reduced the segmentation time from 520 seconds to 96 seconds. However, CPU and GPU utilization are quite low during the process, and a single image takes ~1-2 minutes for segmentation to finish, the vast majority of this time spent on flow + mask computation (~85%) vs running the network (~15%). Can the speed be improved? It seems like this might be a CPU bottleneck.

**Comment by carsen-stringer** [comment]
much of the CPU runtime is the quality control step, you can turn it off with `flow_threshold=0` (without QC a 2048x2048 post-processing takes ~3s on my computer, with QC it takes ~15s). Your run speeds seem a bit slow -- see the table in the readme. I would make sure that numba is working correctly, do you get any warnings about that during running?

I'm definitely open to pull requests for improving the speed of the `masks_to_flows` function that is currently the bottleneck for this step. I will note though that this

**Comment by Jsakkos** [comment]
Thanks, setting `flow_threshold = 0` made the total time ~20s. My images do have ~1-4k cells, and I wonder if that is part of the issue? You can find a sample image [here](https://github.com/Jsakkos/microtools/blob/main/Images/Control-02.czi%20-%20C%3D1.tif).

**Comment by qixinbo** [comment]
Hello, @Jsakkos maybe you can try [this unofficial implementation](https://github.com/Image-Py/cellpose-turbo).
I have tested your image on my laptop, the result is really promising:
![image](https://user-images.githubusercontent.com/6218739/111400366-224ba800-8702-11eb-8656-af9651c092f3.png)

**Comment by kevinjohncutler** [comment]
> Hello, @Jsakkos maybe you can try [this unofficial implementation](https://github.com/Image-Py/cellpose-turbo).
> I have tested your image on my laptop, the result is really promising:
> ![image](https://user-images.githubusercontent.com/6218739/111400366-224ba800-8702-11eb-8656-af9651c092f3.png)

Wow! That's great. What differences are in the `flow2msk` function compared to the original? I would like to speed up my own version of cellpose (which is already heavily modified in the mask reconstruction) but a drop-in `cupy` replacement doesn't seem to make a difference.

**Comment by qixinbo** [comment]
> > Hello, @Jsakkos maybe you can try [this unofficial implementation](https://github.com/Image-Py/cellpose-turbo).
> > I have tested your image on my laptop, the result is really promising:
> > ![image](https://user-images.githubusercontent.com/6218739/111400366-224ba800-8702-11eb-8656-af9651c092f3.png)
> 
> Wow! That's great. What differences are in the `flow2msk` function compared to the original? I would like to speed up my own version of cellpose (which is already heavily modified in the mask reconstruction) but a drop-in `cupy` replacement doesn't seem to make a difference.

The `flow2msk` function implements a hydrological algorithm to simulate the water flow in order to find the water collection points. The detailed algorithm is explained in [this blog post](https://qixinbo.info/2021/03/03/cellpose-3/) (Unfortunately, it is written in Chinese :( Maybe you can translate it using Google Translate). 
Any questions are welcomed~~

**Comment by Jsakkos** [comment]
> 
> 
> > > Hello, @Jsakkos maybe you can try [this unofficial implementation](https://github.com/Image-Py/cellpose-turbo).
> > > I have tested your image on my laptop, the result is really promising:
> > > ![image](https://user-images.githubusercontent.com/6218739/111400366-224ba800-8702-11eb-8656-af9651c092f3.png)
> > 
> > 
> > Wow! That's great. What differences are in the `flow2msk` function compared to the original? I would like to speed up my own version of cellpose (which is already heavily modified in the mask reconstruction) but a drop-in `cupy` replacement doesn't seem to make a difference.
> 
> The `flow2msk` function implements a hydrological algorithm to simulate the water flow in order to find the water collection points. The detailed algorithm is explained in [this blog post](https://qixinbo.info/2021/03/03/cellpose-3/) (Unfortunately, it is written in Chinese :( Maybe you can translate it using Google Translate).
> Any questions are welcomed~~

That's awesome! How can I try your implementation? I don't see a PyPI package with your version.

**Comment by qixinbo** [comment]
> > > > Hello, @Jsakkos maybe you can try [this unofficial implementation](https://github.com/Image-Py/cellpose-turbo).
> > > > I have tested your image on my laptop, the result is really promising:
> > > > ![image](https://user-images.githubusercontent.com/6218739/111400366-224ba800-8702-11eb-8656-af9651c092f3.png)
> > > 
> > > 
> > > Wow! That's great. What differences are in the `flow2msk` function compared to the original? I would like to speed up my own version of cellpose (which is already heavily modified in the mask reconstruction) but a drop-in `cupy` replacement doesn't seem to make a difference.
> > 
> > 
> > The `flow2msk` function implements a hydrological algorithm to simulate the water flow in order to find the water collection points. The detailed algorithm is explained in [this blog post](https://qixinbo.info/2021/03/03/cellpose-3/) (Unfortunately, it is written in Chinese :( Maybe you can translate it using Google Translate).
> > Any questions are welcomed~~
> 
> That's awesome! How can I try your implementation? I don't see a PyPI package with your version.

You can just clone it into your local machine. And enter the directory, run: 
`python -m cellpose`
just like the original cellpose.

**Comment by carsen-stringer** [comment]
As a warning, these functions do not have the same performance as cellpose on our test images (~0.6 average precision vs 0.8)

**Comment by carsen-stringer** [comment]
also masks_to_flows, which is the slower function has been sped up by the GPU now
