### ISSUE TITLE
acessing *_seg.npy file

### ISSUE THREAD

**Issue by haniyyahs** [MouseLand/cellpose#219]
Hello, I installed cellpose using the terminal on my macbook. I was able to run one of my own images and get masks, and it was saved as .npy file in the same folder as the image. However, I am having trouble accessing this file. Is there something specific I can type in the terminal to load it (similar to what's described on the docs: https://cellpose.readthedocs.io/en/latest/outputs.html)?

I'm not using a notebook when I run the GUI, I just launch it from the terminal. I tried typing 'import numpy as np' when I'm in the same folder as the .npy file but get an error that the command is not found. 

I would appreciate any insights into this, thank you!

**Comment by carsen-stringer** [comment]
if you want to load npy files in python you will need to run python first from the terminal by first typing `python`. then you can use `import numpy as np` and load accordingly. going to close the issue but let me know if you still have problems

**Comment by haniyyahs** [comment]
Hello, I'm still getting the error (see below) in my terminal when I try to load the image with the red outlines. Is there a way to get this in the GUI instead? Thank you! 

"Traceback (most recent call last).
  File "<stdin>", line 1, in <module>
AttributeError: module 'cellpose.plot' has no attribute 'outlines_list'"
