### ISSUE TITLE
How can I make traning pair?

### ISSUE THREAD

**Issue by zsef123** [MouseLand/cellpose#22]
Thanks for useful tool!!

I want to train model about my datasets.

But as I understood, Annotated mask must be transform to the flow representation.
I want to find a code related to this.

**Comment by carsen-stringer** [comment]
The training scripts are now working, see new [training](http://www.cellpose.org/static/docs/train.html) doc

The script for converting labels to flows is labels_to_flows in [dynamics.py](cellpose/dynamics.py)

I am going to close this issue for now but please reopen it if you are having issues.

**Comment by glossdrop** [comment]
Hello and thanks for this great work!

I upgraded to the new version (1.25) but I still keep finding problems with the training 
For example, if I run the code: 
`python -m cellpose --train --dir C:\Users\cavalieri\Desktop\CFOS\JULIEN\TdTomato\TRAIN --pretrained_model None  --use_gpu`

I get the error message: 
`Traceback (most recent call last):
  File "C:\Users\cavalieri\Anaconda3\envs\cellpose\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\cavalieri\Anaconda3\envs\cellpose\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\cavalieri\Anaconda3\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 167, in <module>
    label_names = get_label_files(image_names, imf, args.mask_filter)
  File "C:\Users\cavalieri\Anaconda3\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 35, in get_label_files
    raise ValueError('labels not provided with correct --mask_filter')
ValueError: labels not provided with correct --mask_filter`

Why should I need the Mask_filter argument? Is the '_seg.npy' not enough?

**Comment by carsen-stringer** [comment]
I'm sorry the training script currently doesn't use _seg.npy files it uses tiffs or pngs of masks (to be more consistent with other pipelines). To convert your _seg.npy files to png masks quickly, drag an image into the GUI and click CTRL+N, and then use the LEFT/RIGHT arrow keys to go through the directory and click CTRL+N on each one.

I will add support for _seg.npy files in the near future.

**Comment by glossdrop** [comment]
Thank you very much for you feedback!

**Comment by tkr789** [comment]
Hi, thanks so much for this tool!

I am still confused about the usage of --mask_filter during training on your own data. It is necessary but not used in the training scrips listed in the training doc and the description on github states: "end string for masks to run on". What does that mean? 

Also once the model is trained where is it saved and how could one point to it?
