### ISSUE TITLE
add "look one level down" feature to command line

### ISSUE THREAD

**Issue by carsen-stringer** [MouseLand/cellpose#220]
add flag to process all subfolders of input folder

**Comment by carsen-stringer** [comment]
flag added to CLI `--look_one_level_down` which will process all images in folder and subfolder

**Comment by saskra** [comment]
Great enhancement! Unfortunately, the corresponding argument is not passed all the way to the executing function.

https://github.com/MouseLand/cellpose/blob/ff46c5f4ebd3e3c580be62765e38dc8108fcd041/cellpose/io.py#L148
https://github.com/MouseLand/cellpose/blob/ff46c5f4ebd3e3c580be62765e38dc8108fcd041/cellpose/__main__.py#L209

**Comment by carsen-stringer** [comment]
My understanding was that this was needed for model application, not training, but I can see how it could be useful for that too. Happy to take a PR implementing this functionality.

**Comment by saskra** [comment]
Your understanding is not wrong, just that I keep combining training and application in the leave-one-sample-out cross-validation. I will do a PR.
