### ISSUE TITLE
No text files for 3D images

### ISSUE THREAD

**Issue by gabriel5222** [MouseLand/cellpose#223]
Hi

When I try to save text files for 3D images after segmentation I got this error message: error cannot save 3D outlines.

Everything works for the 2D and I still can save PNG image for the 3D. 

How can I solve this issue ?

Thanks a lot.

**Comment by carsen-stringer** [comment]
Yes I don't know how this works in ImageJ, if you want to add this capability I'm happy to accept a pull request. There's this LabelstoROIs ImageJ plugin that may help: https://www.biorxiv.org/content/10.1101/2021.01.20.427432v1
github: https://labelstorois.github.io/
