### ISSUE TITLE
Fiji Cellpose wrapper, default values

### ISSUE THREAD

**Issue by romainGuiet** [MouseLand/cellpose#224]
Hi @carsen-stringer ,

thank you for making your tool available! Following recent [work to use Cellpose within QuPath](https://forum.image.sc/t/using-python-command-line-from-groovy-qupath-cellpose/47684/3), I'm working on a simple [Cellpose wrapper for Fiji](https://github.com/BIOP/ijl-utilities-wrappers/tree/conda-cellpose-wrapper).

Your [documentation](https://cellpose.readthedocs.io/en/latest/command.html#input-settings) mentions the default value for the diameter ``diameter: (float)`average diameter of objects in image, if 0 cellpose will estimate for each image, default is 30`` but I couldn't find (yet) the default values for :
``--flow_threshold FLOW_THRESHOLD , flow error threshold, 0 turns off this optional QC step``
and 
``--cellprob_threshold CELLPROB_THRESHOLD cell probability threshold, centered at 0.0``

So far I guessed it's zero, but I'd be happy to have a confirmation.

Thank you again,

Romain

**Comment by carsen-stringer** [comment]
awesome! you can find the default values here: https://cellpose.readthedocs.io/en/latest/api.html

**Comment by carsen-stringer** [comment]
FYI not sure what level of wrapper you're thinking, but there is this already implemented: github: https://labelstorois.github.io/

**Comment by romainGuiet** [comment]
Hi @carsen-stringer ,

>awesome! you can find the default values here: https://cellpose.readthedocs.io/en/latest/api.html

Thank you for providing the link, that's exactly what I needed! I should have thought to look there -_-' 

>FYI not sure what level of wrapper you're thinking, but there is this already implemented

Currently, the Cellpose wrapper sequentially:
- saves the current Fiji image in a temporary folder
- starts the cellpose-env and runs Cellpose with defined parameters
- opens the created label image in Fiji
- cleans the temporary folder

We also implemented a [Label2Rois ](https://github.com/BIOP/ijp-LaRoMe) a while ago...

Best
