### ISSUE TITLE
Force CellPose to recognize dimensionality?

### ISSUE THREAD

**Issue by bethac07** [MouseLand/cellpose#226]
I have some TIF images that are single channel multi-Z plane; CellPose's GUI seems to think they are single Z plane multichannel.  They open correctly in Fiji as the correct dimensionality; is there any way to force the GUI to treat them correctly and load with a certain configuration (ala Fiji's "Reorder Hyperstack")?  Thanks.

**Comment by bethac07** [comment]
(the same image also fails with the `do_3D flag` headless; if I open it in Fiji, do nothing, and just resave it, it works both in headless with `do_3D` and in the GUI)

**Comment by carsen-stringer** [comment]
Sorry that the cellpose loader isn't recognizing the channels correctly in the GUI. I've specifically added this functionality to the cellpose-napari plugin: the user labels the axis as 'c' and the plugin then knows the channel axis: https://cellpose-napari.readthedocs.io/en/latest/running.html#d-segmentation. I'm not going to implement this functionality in the native cellpose GUI, but I will add a flag to the CLI called `--channel_axis`

**Comment by bethac07** [comment]
Thanks, super appreciate it!

**Comment by carsen-stringer** [comment]
this has been added to the github version, how to:

`channel_axis` and `z_axis` can be used to specify the axis of the image which corresponds to the image channels and to the z axis. For example an image with 2 channels of shape `(1024,1024,2,105,1)` can be specified with `channel_axis=3` and `z_axis=4`. If `channel_axis=None` cellpose will try to automatically determine the channel axis by choosing the dimension with the minimal size after squeezing. If `z_axis=None` cellpose will automatically select the first non-channel axis of the image to be the Z axis.

These parameters can be specified using the command line with `--channel_axis` or `--z_axis` or as inputs to `model.eval` for the `Cellpose` or `CellposeModel` model.
