### ISSUE TITLE
Assigning channel values 

### ISSUE THREAD

**Issue by pushkal777** [MouseLand/cellpose#227]
I have a stack of greyscale images with the first being the cytoplasm and the second being the nucleus. I am not sure what values to put in the command line for the channel 1 and 2 (depicted bold below) as I have tried [0,0] which is what the https://cellpose.readthedocs.io/_/downloads/en/latest/pdf/recommends for the greyscale images and [1,2] which is what the Google CoLab version of 2D segmentation is executing. Unfortunately, they are performing poorer than expected. 

The 2D segmentation Google colab version is working really neat on the same images so not sure if it is problem of parameter optimization or something else.

$ python -m cellpose --dir /lab/jain_imaging/Pushkal_Cellpose/Test  --pretrained_model cyto --**chan 0** --**chan2 0** --save_tif

**Comment by romainGuiet** [comment]
Hi @pushkal777,

>[0,0] which is what the documentaion recommends for the greyscale images

My guess is that even if each channel is a greyscale , "cellpose greyscale image" have only one channel.
So in your image if your cyto is channel 1 and nuclei channel 2 , you can use : 
```$ python -m cellpose --dir /lab/jain_imaging/Pushkal_Cellpose/Test --pretrained_model cyto --chan 1 --chan2 2 --save_tif```

>they are performing poorer than expected.

What I found critical for the results is the diameter parameter, maybe you can try to use different value --diameter, or to enforce a search of an optimal value with the value ```--diameter  0``` .

Best,

Romain

**Comment by pushkal777** [comment]
This works Romain! Thank you much for your help.

**Comment by pushkal777** [comment]
This works Romain! Thank you much for your help.
