### ISSUE TITLE
Windows executable download link broken?

### ISSUE THREAD

**Issue by haesleinhuepf** [MouseLand/cellpose#229]
Hi @carsen-stringer, hi all,

I was just trying to download the Window Executable and the [link](http://www.cellpose.org/windows) from the readme appears broken. Did it change or can you fix it? :-)

Thanks!

Best,
Robert

**Comment by haesleinhuepf** [comment]
Addendum: It works in the Microsoft Edge browser, but not in Google Chrome on Windows. Is it possible that Google blocks downloads of executable files when the URL does not have .exe by the end?

**Comment by haesleinhuepf** [comment]
Edge also says this: 
![image](https://user-images.githubusercontent.com/12660498/112597219-22882980-8e0d-11eb-9b2a-b57aaef0cc89.png)

**Comment by haesleinhuepf** [comment]
And Windows asks this
![image](https://user-images.githubusercontent.com/12660498/112597345-4c415080-8e0d-11eb-9a81-9d85f3073497.png)

Is it possible that all this is releated to a missing certificate?

**Comment by carsen-stringer** [comment]
weird, I've changed the links to https instead of http, hopefully that does the trick

**Comment by haesleinhuepf** [comment]
It does help @carsen-stringer Works now. Thanks! :-)
