### ISSUE TITLE
GPL or BSD-3 ?

### ISSUE THREAD

**Issue by guiwitz** [MouseLand/cellpose#23]
Hello! First, thanks a lot for this great tool that you developed. I think it will make the life of a lot of people much simpler!

I forked your repo to make some adjustments to the package requirements in the setup file. While doing that I noticed that the license in the setup.py file is GPL while the license of the repository is BSD-3. Is that intended ? The two licenses have very different from each other, so it might be good to clarify this. Thanks!

**Comment by carsen-stringer** [comment]
this has been set to BSD everywhere, thanks for point this out
