### ISSUE TITLE
error when plot.show_segmentation is called for 3D image 

### ISSUE THREAD

**Issue by sunyi000** [MouseLand/cellpose#230]
Hi,
the show_segmentaion for 3d image does not seem to work..
I have a 3D image in the correct shape requried by cellpose, if plot.show_segmentation is called, an error occurs from line 46 of the plot.py .. it seems that matplotlib requires an different shape. Thanks for any pointers and helps..

**Comment by carsen-stringer** [comment]
Unfortunately you cannot plot the 3D segmentation with that function. You could call it with slices of your masks and do a loop over the function if you want to visualize slices of the segmentation.

To do proper 3D mask visualization I've used ImageJ with labels saved as a tiff, there is probably a way to do this in napari as well
