### ISSUE TITLE
Speed up "labels_to_flows"?

### ISSUE THREAD

**Issue by saskra** [MouseLand/cellpose#231]
First of all, thank you for the great software, applying your pre-trained neural network to my images works pretty well already. However, I wanted to test if it gets even better when I re-train myself - unfortunately I can't wait 2,000 hours for pre-processing, see below. I have three Tesla V100 graphics cards with 32GB each, 40 CPUs and 377GB RAM available. The image size is ~5,000 x 5,000 pixels, but I also have a dataset with ~15,000 x 15,000. Am I doing something wrong, or is there another way to speed this up?

```bash
(cellpose) saskra@a:~/PycharmProjects/cellpose$ python -m cellpose --train --dir /home/saskra/PycharmProjects/b/ --pretrained_model cyto --train_size --use_gpu --diameter 300. --img_filter "_img"
** TORCH CUDA version installed and working. **
>>>> using GPU
>>>> pretrained model /home/saskra/.cellpose/models/cytotorch_0 is being used
>>>> during training rescaling images to fixed diameter of 30.0 pixels
Running test snippet to check if MKL-DNN working
see https://pytorch.org/docs/stable/backends.html?highlight=mkl
** MKL version working - CPU version is sped up. **
NOTE: test data not provided OR labels incorrect OR not same number of channels as train data
NOTE: computing flows for labels (could be done before to save time)
  1%|█| 5/714 [15:37:52<1991:42:15, 10113.03s/it]
```

**Comment by marius10p** [comment]
The image size is too large. How many pixels across for a single cell? Downsize to ~30 pixel ROIs please, at least for training.

**Comment by saskra** [comment]
Thanks, that helped.
