### ISSUE TITLE
 dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by aczirok** [MouseLand/cellpose#233]
After conda installation cellpose fails to start:
```
    mamba env create -f environment.yml
    conda activate cellpose
    pip install cellpose
```
... Successfully installed cellpose-0.6.1
```
    python -m cellpose
```
...  Downloading: "https://www.cellpose.org/models/size_nucleitorch_0.npy" to ...
ERROR: dlopen: cannot load any more object with static TLS

**Comment by aczirok** [comment]
probably related to this issue: https://github.com/pytorch/pytorch/issues/2575
works under debian 10.9

**Comment by carsen-stringer** [comment]
weird, they mention sklearn and matplotlib conflicts but neither of those should be in the cellpose environment. what OS were you using originally?

**Comment by carsen-stringer** [comment]
this may be fixed in newer pytorch versions, have you managed to get it to work?

closing for now due to inactivity but let us know if you still need help
