### ISSUE TITLE
using cellpose in 3 dimensions

### ISSUE THREAD

**Issue by h1408** [MouseLand/cellpose#235]
Hello, I am interested in seeing if I can use cellpose to segment the overlap of two cytoplasm channels. For example, I have an image with merged red and green channels and I want to segment out the overlap of these, so only the yellow cells. Would this be possible?

Thanks so much!

**Comment by carsen-stringer** [comment]
You could segment each channel separately and then check which ones are labelled in both sets of masks. but this would require a separate function in python or an export and import into imageJ.
