### ISSUE TITLE
Incorrect output from transforms.reshape_and_normalize_data

### ISSUE THREAD

**Issue by alandegenhart** [MouseLand/cellpose#236]
I was attempting to train a new model from scratch and ran into an issue when providing a list of 2D images as input and using the default 'channels' value (`channels=None`).

The issue appears to be around line 353-354 of `transforms.py`.  If the number of dimensions in the input image is 2, but channels is set to `None`, a new third dimension for the channels is created, but this dimension is not moved to axis 0 nor is the second "empty" image channel added (as is done in line 352).

This only appears to be an issue if `channels=None`.  If `channels=[0, 0]`, the function returns the expected output.

**Comment by carsen-stringer** [comment]
oops this is fixed now. note you'll also need to set `nchan=1` in the model, I've added this as an option for `CellposeModel`. Or you can use the CLI with the `--all_channels` option which won't make the data 2 channel if it's only 1 channel like `[0,0]` will (`[0,0]` is the default in the CLI).
