### ISSUE TITLE
use own model - command line - documentation suggestion

### ISSUE THREAD

**Issue by romainGuiet** [MouseLand/cellpose#237]
Dear @carsen-stringer ,

From the documentation I wasn't sure if it's possible to use the [command line](https://cellpose.readthedocs.io/en/latest/command.html) with a newly trained cellpose model.

In other words, it was not clear to me if PRETRAINED_MODEL can only be nuclei or cyto ? or if it can be something else , eg the path to another model file.

I used [ZeroCostDL4Mic notebook](https://github.com/HenriquesLab/ZeroCostDL4Mic) to train a model and I wanted to test it locally. After a couple of test I realized that it is possible, one just has to make sure that it is the right kind of network (here I have to enforce --mxnet) 

Thank you again for the great tool and for your efforts!

Best,

Romain

**Comment by carsen-stringer** [comment]
thanks for pointing this out, you can use a path too! I've added that to the docs
