### ISSUE TITLE
`model_dir` creation complicating container creation

### ISSUE THREAD

**Issue by mellertd** [MouseLand/cellpose#24]
This looks great! I am interested in getting this running on our shared HPC cluster, and for many reasons I think the best option will be to set up a cellpose singularity container.

First question: have you all tried making a singularity container for cellpose? I see some Docker containers out there, but the ones that I have tried fail in singularity for the same reason my attempt at a singularity container fails, e.g.,:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/cellpose/__main__.py", line 12, in <module>
    gui.run()
  File "/usr/local/lib/python3.7/site-packages/cellpose/gui.py", line 70, in run
    models.download_model_weights()
  File "/usr/local/lib/python3.7/site-packages/cellpose/models.py", line 72, in download_model_weights
    os.mkdir(model_dir)
OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.7/site-packages/cellpose/models/'`

It looks like the app needs to write to the cellpose package directory at runtime (I guess caching model weights), which is a no-no in Singularity.

I have a couple of workarounds I am going to try to make this work, but I wonder if you might consider an option to change the model path, so users could, e.g., set that to something in their home directory.

Thanks!

**Comment by mellertd** [comment]
fwiw, an option is to bind a writable directory to the `.../cellpose/models/` directory when launching the container. I'll handle that with a shell script that I can bundle with the container for now. Thanks again!

**Comment by carsen-stringer** [comment]
would a solution where the model_dir is in a `~/.cellpose` type directory work with singularity?

**Comment by mellertd** [comment]
That would work...home directory should always be writable.

**Comment by carsen-stringer** [comment]
I have changed the model path to `$HOME/.cellpose`. Please `pip install cellpose --upgrade`. I am going to close this issue for now, but please reopen it if this is still an issue.
