### ISSUE TITLE
Valueerror while generating masks

### ISSUE THREAD

**Issue by serrob23** [MouseLand/cellpose#242]
Hello,

I'm working with some large image stacks 300x2048x2048, dtype = np.uint16.

 I've got a 3D segmentation pipeline setup that generally works well, however occasionally I will run into an error after computing the dynamics while the masks are being generated. Below is a screenshot I get of the error message. 

It looks like its generated during the call to dynamics.get_masks() step, however I'm not sure what the underlying cause of the issue is.

Any tips would be greatly appreciated!
<img width="954" alt="Screen Shot 2021-04-07 at 7 12 48 AM" src="https://user-images.githubusercontent.com/26012921/113886295-6b2cd480-9775-11eb-84c1-08d9a2e6afb8.png">

**Comment by kevinjohncutler** [comment]
I'm not sure either, but do the datasets that fail do so repeatedly? And do they have any similarities, such as being particularly dense?

**Comment by carsen-stringer** [comment]
Yeah I'm not sure how to get np.histogramdd to throw this error without hitting the other error statements? Are you chunking your data and some of your chunks are accidentally of size zero?

**Comment by carsen-stringer** [comment]
going to close this issue due to inactivity but please let us know if you're still having issues
