### ISSUE TITLE
Reg. Split for Training and testing of Specialist and Generalist Algorithms

### ISSUE THREAD

**Issue by programmer-770** [MouseLand/cellpose#243]
Thank you for releasing Cellpose. 
I was looking to reproduce the Evaluation as mentioned in FIg.4 of the paper. Can you please share the split for images in the Cellpose dataset (540 Train + 68 Test) in terms of the sources of the cells (i.e. Cell Image Library, Fluorescent, Non-Fluorescent, Membranes, Other microscopy, Non-microscopy).
A corresponding split of which image number correspond to the above 6 categories will be helpful.

**Comment by carsen-stringer** [comment]
I do not have all the train splits as we did not use those labels in the benchmarking, but here are the labels for the test images: https://github.com/MouseLand/cellpose/blob/5cc03de9c2aa342d4b4469ff476ca04541b63414/paper/performance_figs.py#L521. The train split we did use was first 89 images (specialized) vs all train images.
