### ISSUE TITLE
do_3D with output of imagej compatible ROIs

### ISSUE THREAD

**Issue by jnkoberstein** [MouseLand/cellpose#245]
I have found cellpose to be spectacularly good at segmentation, thanks for the great work! I would really like to use it to generate ROIs for time series data in order to quantify the mean intensity for each cell over time while accounting for slight movement and shape changes that occur with cultured cells. I can run cellpose from the command line on a .tif stack with the do_3D flag, however, this does not output ImageJ importable ROI text file like it does when performed on 2D data. Also, the masks saved in the .tif output do not seem to capture the cells very well. Is there any way to create ROIs for each frame of time-series besides simply running cellpose on each frame individually?

**Comment by kevinjohncutler** [comment]
Currently running it on a per-frame basis is the only way to do time lapses, as the 3D option was trained on (simulated?) z-stacks, not t-stacks. That's something I'm currently working on, first for bacteria and maybe later for eukaryotes via the DeepCell datasets. If your time lapses are in a TIFF stack by default, then I would recommend loading that into Jupyter, splitting it into separate images, running cellpose on it, and then saving the labels as a stack (perhaps after running a cell-linking/tacking/tracing algorithm on them - I still do this in Matlab via SuperSegger, but I want to explore DeepCell or another python implementation). What's nice is that the cellpose GUI will load these TIFF stacks very nicely as well as the label TIFF stack as masks. I have not tried ImageJ for opening the label stack yet, but it would be worth a try!

**Comment by romainGuiet** [comment]
Hi @jnkoberstein ,
it doesn't really solve your problem but we recently released a [Cellpose wrapper for Fiji](https://github.com/BIOP/ijl-utilities-wrappers). 
Each frames of the time-lapse are exported as an individual image, processed, then open as a Label image in Fiji.
Here is an example workflow described on the [forum.image.sc](https://forum.image.sc/t/pipeline-for-cell-tracking-using-cellpose-for-segmentation-and-trackmate-for-tracking/51615/2)
So far, I tested 2D+t or 3D
Best

**Comment by carsen-stringer** [comment]
@kevinjohncutler is correct, the 3D mode is for 3D images, not 2D + time. It was not trained on 3D data but is actually the 2D algorithm run on XY, YZ, and XZ slices then combined to run the dynamics in 3D.

for simple time stitching, you can use the `stitch_threshold` parameter to combine masks across frames with a certain IoU. I have an example of doing this now in the napari plugin for cellpose, but it's not going to be as good as using a custom built algorithm: https://cellpose-napari.readthedocs.io/en/latest/running.html#time-segmentation

@romainGuiet , is there a function in your library we could import to do mask to text file conversion?

**Comment by romainGuiet** [comment]
Hi @carsen-stringer ,

just to be sure , when you wrote :
> is there a function in your library we could import to do mask to text file conversion?

Do you mean a way to convert Labels image to a Text file , which will be later imported as ROIs in the ROImanager (like [here](https://cellpose.readthedocs.io/en/latest/outputs.html?highlight=imagej#roi-manager-compatible-output-for-imagej) ) but in 3D ?

Our Cellpose wrapper for Fiji](https://github.com/BIOP/ijl-utilities-wrappers), is just saving the current image in Fiji as 2D or 3D (z-stack and into series of images in case of time-lapse), then starting cellpose (conda or venv cli) , before retrieving the output_labels_image(s) and finally opening it/them in Fiji.

Except the dedicated plugin](https://imagejdocu.tudor.lu/plugin/stacks/3d_roi_manager/start) , there is no 3D-ROIs in ImageJ/Fiji.

**Comment by carsen-stringer** [comment]
okay thanks so the labels you retrieve are the tiffs of the masks and you open them as an image?

**Comment by romainGuiet** [comment]
yes exactly!

**Comment by carsen-stringer** [comment]
closing this for now because it seems like there is not a default supported format

**Comment by SomayehZ** [comment]
Hello! @carsen-stringer

I'm currently using human-in-the-loop training, it looks nice. My problem is that as I started to use GPU, after training the first image, it doesn't go to the next image and stuck there! wonder how I can solve it!? Many thanks for any help.
