### ISSUE TITLE
IndexError when using GUI

### ISSUE THREAD

**Issue by SylvyG** [MouseLand/cellpose#246]
Hi,
I am really new to this cellpose tool, and python. I can upload the image into the GUI but after that I cannot do calibration or segmentation, with the same indexerror appeared: tensors used as indices must be long, byte or bool tensors. 
Is there any solutions for this?
Thanks!!

**Comment by kevinjohncutler** [comment]
That does sound weird... to debug, I suggest using the Jupyter Notebook template. That way you can read in your images and try running cellpose through the notebook. If you still see errors, then you can probe the image properties a lot better and maybe convert the images to a form that cellpose can process.

**Comment by SylvyG** [comment]
> That does sound weird... to debug, I suggest using the Jupyter Notebook template. That way you can read in your images and try running cellpose through the notebook. If you still see errors, then you can probe the image properties a lot better and maybe convert the images to a form that cellpose can process.

Thanks for reply! It seems the other person also encountered the same problem as mine (#247). My image type is tiff, which I think should be readable because I can see my uploaded image in GUI, but I cannot do anything to it. I will try with CPU but it seems this problem is not unique to me...

**Comment by carsen-stringer** [comment]
Can you please try the latest version? I'm going to close this for now but please reopen and comment if it's still a problem
