### ISSUE TITLE
Ability to use mask as seed for suite2p?

### ISSUE THREAD

**Issue by Cumol** [MouseLand/cellpose#25]
I just found out about this amazing tool of yours! Initially, I started using suite2p because many of the cell segmentation algorithms were doing a very bad job to segment my calcium imaging experiments as well as finding a way to deal with contamination.

Suite2p is doing a very good job in finding (mainly active) cells. However, I am spending most of my time cleaning up the results from things that are not cells, or adding cells that were missed because they responded only to one stimulus in my experiment.

I just quickly tried cell pose on the first image from a calcium imaging dataset and it did a *very* good job!

![Screenshot 2020-02-29 at 21 46 51](https://user-images.githubusercontent.com/4943380/75614844-1dd74000-5b3d-11ea-94a0-b9d047b09d4c.png)

Now I am wondering if it is possible to use cellpose on the mean of the first images of a calcium imaging dataset and use the generated mask as a seed for suite2p?

**Comment by carsen-stringer** [comment]
This is the plan! Can you post this on the suite2p issues and I can give you code there to use these masks if you need to do that ASAP?
