### ISSUE TITLE
image segmentation problem

### ISSUE THREAD

**Issue by iyasasse** [MouseLand/cellpose#258]
I have confocal microscope images. I run this segmentation code "python -m cellpose --dir ~ --pretrained_model cyto --chan 2 --diameter 50 --save_png --no_npy --cellprob_threshold 0.0 --fast_mode". 
I do not get good segmentation of my cells, some are missed while some are wrongly identified. please is there some thing I can do to get better segmentation? I have tried to varry the diameter but segmentation is not still good. I have upload an example with its mask/output
![22042021 lif - M105_PV_GFP_S1_cp_masks](https://user-images.githubusercontent.com/83674820/117076048-b4008a80-ad2d-11eb-8d1e-72f0408ffb98.png)

![22042021 lif - M105_PV_GFP_S1_cp_output](https://user-images.githubusercontent.com/83674820/117075999-a1865100-ad2d-11eb-8102-19afe6a30097.png)
![22042021 lif - M105_PV_GFP_S1](https://user-images.githubusercontent.com/83674820/117076021-ab0fb900-ad2d-11eb-8234-514256572470.png)

**Comment by carsen-stringer** [comment]
can you try turning off `flow_threshold` (set `flow_threshold=0`), also you can try turning off fast mode to improve the segmentation

**Comment by iyasasse** [comment]
Dear Carsen,

Thank you for your reply and suggestion. It was good but we still are not
able to get good segmentation for our images. So we wish to do
3D-segmentation now.

We have tried to run 3D using the cyto model, it runs for a very long time
and return no masks. We cannot figure out what the problem can be.

Our images are of size 2352x2352.

I had wished to send you a copy but it's too large to send because it can
not attach.

Please we would be glad to receive suggestions from you on how to proceed.
I can also attach a file to my former issue if you wish.

Best regards,

Iya Sasse Ruth Nyaba

**Comment by iyasasse** [comment]
Dear Carsen,

Thank you for your help on the segmentation of our problem last time.

We also wish to do 3D segmentation but we encountered the following issues.
Firstly, the segmentation runs for very long times and secondly we get a
message that 'there is insufficient space to save the results'

Our images are generated using confocal microscope and of size '2352x2352'
pixels.

Can help us again with any further tips or maybe we need to use different
parameters. For the parameters, we used cell diameter of  45,
cellprobability threshold of 0.2 and flowthreshold of 0.

Best regards,

Iya

**Comment by iyasasse** [comment]
Dear Carsen,

sorry to send this in a different mail.

Find below a link to a sample of our Tif image.

https://drive.google.com/file/d/12ESyyzmUMRGFnc1prIQ2poVWuuaH4oMy/view?usp=sharing

I hope to hear from you soon,

Iya

**Comment by carsen-stringer** [comment]
if you are having issues with 3D segmentations, I recommend trying the `stitch_threshold` parameter: https://cellpose.readthedocs.io/en/latest/settings.html#d-settings. going forward, we recommend usage questions, not bugs, to be asked here: https://forum.image.sc/tag/cellpose

going to close this issue for now, let us know if you have any questions
