### ISSUE TITLE
no outlines txt created, mask png only black

### ISSUE THREAD

**Issue by papalagirauscher** [MouseLand/cellpose#259]
Hello!
I created a new cellpose environment in conda, using the provided environment.yml and forcing pytorch from the pytorch channel (pytorch::pytorch).

It works, which makes me happy, but sadly does not save the outlines in a txt like before (--save_png flag). Also the mask pngs are all black.

Did somebody run into the same issue?

-----
edit: I was able to save the outlines by adding --save_outlines, the masks remain black/empty. Is there a way to solve this issue?

Thank you!

**Comment by carsen-stringer** [comment]
have you tried opening the png in imageJ or in the cellpose GUI? it's an int16 so it will be black in a standard image viewer. are you using the same parameters as before? can you install an older version and confirm that there is a difference?

**Comment by papalagirauscher** [comment]
![image](https://user-images.githubusercontent.com/74896770/117465783-0acdb600-af20-11eb-8dda-b6621e77025f.jpg)

**Comment by carsen-stringer** [comment]
sorry for the delay in getting back to you, are things working for you now, is that what you mean? Going to close this issue for now, but please let us know if you're still having problems
