### ISSUE TITLE
Plotting masks and outlines

### ISSUE THREAD

**Issue by h1408** [MouseLand/cellpose#262]
Hello,

I am trying to visualize the masks on a set of images that I ran in one of the colab notebooks. I added the suggested code to the notebook but am getting the following error when trying to load in one of the files. Would you happen to know why this is or how I could get around it? 

Also, is there an efficient way to visualize and plot all outlines on a whole folder of images? 

Thank you very much! 
![Screen Shot 2021-05-10 at 11 43 49 AM](https://user-images.githubusercontent.com/80368001/117709334-a744c200-b185-11eb-9ecf-de24badc64ff.png)

**Comment by carsen-stringer** [comment]
the colors are only saved from the GUI, please run that function with `colors=None`

to output all the images with outlines, use the CLI and make sure you have `pip install matplotlib` and use the option `--save_png`
