### ISSUE TITLE
Retrain model using pretrained cyto2

### ISSUE THREAD

**Issue by BohengZhao** [MouseLand/cellpose#265]
I'm trying to retrain the model using `--pretrained_model cyto2  `. My training image is grey scaled .tif file with one channel, which only contains cyto and no nucleus. I generated the masks using the GUI provided. 

Using the generated model, I tested on some images. The model cannot generate masks. 
`2021-05-12 15:29:37,855 [INFO] >>>> running cellpose on 5 images using chan_to_seg GRAY and chan (opt) NONE

2021-05-12 15:29:37,855 [INFO] parsing model string cellpose_residual_on_style_on_concatenation_off_Cropped_may11_2021_05_12_15_02_51.302017 to get cellpose options

2021-05-12 15:29:37,988 [INFO] 0%|          | 0/5 [00:00<?, ?it/s]
2021-05-12 15:29:43,766 [WARNING] WARNING: no mask pixels found
`

**Comment by petratom** [comment]
Hi, 
I'm having the same issue with empty predictions on retrained model with 16-bit .tif grayscale images. 
Did you manage to solve this problem?

**Comment by carsen-stringer** [comment]
I think this training bug for single channel images is fixed now thanks to @kevinjohncutler , going to close this issue but let us know if it's not working
