### ISSUE TITLE
after installing matplotlib for the jupyter notebook in the cellpose environment, the cellpose GUI no longer opens

### ISSUE THREAD

**Issue by SandraBL** [MouseLand/cellpose#266]
Hi, 
I'm trying to use cellpose either in the GUI or in the Jupyter Notebook run_cellpose.ipynb. The notebook uses matplotlib so I installed it in the cellpose conda evironment. However, after I do that, starting cellpose using the GUI no longer works. 

Here's a step-by-step of what I did:
1. create cellpose environment: conda env create -f environment.yml
2. activate environment: conda activate cellpose
3. upgrade cellpose: pip install cellpose --upgrade
4. open cellpose GUI: python -m cellpose (works fine)

To use the Jupyter notebook:
5. install jupyter notebook inside the cellpose environment: conda install -c conda-forge notebook
6. install matplotlib: conda install matplotlib
7. open jupyter notebook: jupyter notebook
8. run notebook (works fine)
9. close jupyter notebook

To now use the GUI again:
10. python -m cellpose
It does not open complaining about a wrong version of qt: "pyqtgraph requires Qt version >= 5.12  (your version is 5.9.6)"

How can I use the jupyter notebook without breaking the GUI version?

The full error message is:
(cellpose) PS C:\Users\cbe-cmn\Documents\Sandra\Software\Python\Cellpose> python -m cellpose
2021-05-13 19:51:20,196 [INFO] WRITING LOG OUTPUT TO C:\Users\cbe-cmn\.cellpose\run.log
[5, 9]
Traceback (most recent call last):
  File "C:\Users\cbe-cmn\.conda\envs\cellpose\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\cbe-cmn\.conda\envs\cellpose\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\cbe-cmn\.conda\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 11, in <module>
    from cellpose.gui import gui
  File "C:\Users\cbe-cmn\.conda\envs\cellpose\lib\site-packages\cellpose\gui\gui.py", line 7, in <module>
    import pyqtgraph as pg
  File "C:\Users\cbe-cmn\.conda\envs\cellpose\lib\site-packages\pyqtgraph\__init__.py", line 13, in <module>
    from .Qt import QtGui, mkQApp
  File "C:\Users\cbe-cmn\.conda\envs\cellpose\lib\site-packages\pyqtgraph\Qt.py", line 391, in <module>
    raise Exception('pyqtgraph requires Qt version >= %d.%d  (your version is %s)' % (versionReq[0], versionReq[1], QtVersion))
Exception: pyqtgraph requires Qt version >= 5.12  (your version is 5.9.6)

**Comment by emmanuel-contreras** [comment]
I ran into the same problem ended up installing matplotlib-base which does not depend on qt. Tried to fix the above issue by installing qt 5.12 afterwards introduced a different error so I just recreated the cellpose env

```conda install -c conda-forge matplotlib-base```

https://stackoverflow.com/questions/45817358/how-can-i-install-matplotlib-without-installing-qt-using-conda-on-windows

**Comment by carsen-stringer** [comment]
was this resolved? thanks @emmanuel-contreras , I can add your suggestion to the documentation

**Comment by carsen-stringer** [comment]
also you can `pip install matplotlib` instead?

**Comment by emmanuel-contreras** [comment]
I just got a chance to try this today and I can confirm that using pip to install matplotlib in the cellpose conda environment does not break cellpose, so it could be because we were installing matplotlib through conda
