### ISSUE TITLE
bug when running codes

### ISSUE THREAD

**Issue by Angelelily** [MouseLand/cellpose#267]
When I ran codes, it occurs error for cellpose/models.py Line 567
flows=dP, threshold=flow_threshold*(not do_3D))

TypeError: unsupported operand type(s) for *: 'NoneType' and 'bool'

**Comment by carsen-stringer** [comment]
can you give us more details on what you ran? going to close this issue until we get more information, please also try the latest cellpose `pip install git+https://github.com/MouseLand/cellpose.git`
