### ISSUE TITLE
Code problem

### ISSUE THREAD

**Issue by jtyytim** [MouseLand/cellpose#268]
Hello,

I tried the code to train a cellpose model on colab. But I had this problem for image tiff I think. And I can't load any other formats either. How can I fix this problem ?
![image](https://user-images.githubusercontent.com/35915517/118649502-dbeaf600-b7e3-11eb-971b-b2413ed2ed98.png)

Looking forward for the reply, thanks!
Thiem

**Comment by carsen-stringer** [comment]
looks like you need to install imagecodecs? try `!pip install imagecodecs` in a cell.

if this doesn't work let us know, going to close this issue for now
