### ISSUE TITLE
Automating nucleus detection

### ISSUE THREAD

**Issue by pburnham50** [MouseLand/cellpose#27]
I have found that cellpose works very well for nucleus detection in my imaging data. I was hoping to automate this process with a python scrypt, but have had trouble even to get my images process in the jupyter notebook.

For reference, I am trying to detect nuclei in single stack TIFF image (grayscale 16 bit) - there are only ~100 nuclei in the test image. The only channel I am using is DAPI (nothing for cytoplasm), so i am only trying to detect in one channel.

When I run the jupyter notebook, the main errors I get are:
"axes don't match array" or "int object is not subsettable". 

I think this may be due to the fact that I am only uploading a single channel image? But was hoping you could suggest a way to get around this issue.

Thanks!

**Comment by pburnham50** [comment]
Also, tried reinstalling and reformatting my images as PNG. Then ran your notebook (trying both cyto and nuclei model). Same error as before - "axes don't match array".

**Comment by carsen-stringer** [comment]
sorry this has been fixed now (`pip install cellpose --upgrade`), it was an issue with single channel tiffs I believe as you suggest, let me know if it's working now and close the issue if it is
