### ISSUE TITLE
how to turn off compute_masks

### ISSUE THREAD

**Issue by lidanwu** [MouseLand/cellpose#270]
Hello, 
I'm trying to do get flow output of cellpose without generating the masks as this would save me a lot of time. 
However, the code below does not work. This is running in Jupyter notebook with 2-channel tiff files. 
```
model_2D = 'cyto'
use_GPU = 0
channels_2D = [0, 1]
flow_threshold = 0.4
cellprob_threshold = 0
cellpose_model = models.CellposeModel(gpu= use_GPU, model_type= model_2D)
masks, flows, styles, diams = cellpose_model.eval(data_2D, diameter=None, channels=channels_2D, 
                                                 flow_threshold = flow_threshold, cellprob_threshold = cellprob_threshold,
                                                 compute_masks=False)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-3ae82c94b1dc> in <module>
      9 masks, flows, styles, diams = cellpose_model.eval(data_2D, diameter=None, channels=channels_2D, 
     10                                                  flow_threshold = flow_threshold, cellprob_threshold = cellprob_threshold,
---> 11                                                  compute_masks=False)

TypeError: eval() got an unexpected keyword argument 'compute_masks'

```

I can see that under [class Cellpose(), eval()](https://github.com/MouseLand/cellpose/blob/master/cellpose/models.py#L130-L134) does not have input argument for compute_masks. But under[ class CellposeModel(UnetModel), eval()](https://github.com/MouseLand/cellpose/blob/master/cellpose/models.py#L362-L367), there is input argument of compute_masks. How could I specify my model to be class CellposeModel(UnetModel)? 
Any idea what I should do to get flow output without computing the masks? 

Thanks,

**Comment by lidanwu** [comment]
When I included` pretrained_model` as input argument for `cellpose_model`. The script got stuck in 0% processing for more than 20min. What I did wrong?
```
import pathlib
model_dir = pathlib.Path.home().joinpath('.cellpose', 'models')
model_type= model_2D
torch_str = ['','torch'][False]
pretrained_model = [os.fspath(model_dir.joinpath('%s%s_%d'%(model_type,torch_str,j))) for j in range(4)]
pretrained_size = os.fspath(model_dir.joinpath('size_%s%s_0.npy'%(model_type,torch_str)))
print(pretrained_model)
cellpose_model = models.CellposeModel(gpu= use_GPU, model_type= model_2D, pretrained_model=pretrained_model)
masks, flows, styles, diams = cellpose_model.eval(data_2D, diameter=None, channels=channels_2D, 
                                                 flow_threshold = flow_threshold, cellprob_threshold = cellprob_threshold,
                                                 compute_masks=False)

---------------------------------------------------------------------------
['C:\\Users\\lwu\\.cellpose\\models\\cyto_0', 'C:\\Users\\lwu\\.cellpose\\models\\cyto_1', 'C:\\Users\\lwu\\.cellpose\\models\\cyto_2', 'C:\\Users\\lwu\\.cellpose\\models\\cyto_3']
2021-05-25 18:13:22,900 [INFO] >>cyto<< model set to be used
2021-05-25 18:13:22,904 [INFO] >>>> using CPU
2021-05-25 18:13:23,215 [INFO] 0%|          | 0/3 [00:00<?, ?it/s]
```

**Comment by pushkal777** [comment]
Hi! Not help but was curious about how do you plan to use the flow output for image processing: I am also struck with long processing times and was wondering what's a good way to make it faster
.

**Comment by lidanwu** [comment]
I plan to do standard image processing (color thresholding, watershed, etc) to convert flow into mask. This might not be as accurate as the gradient flow tracking method but is definitely faster.

**Comment by qixinbo** [comment]
> 
> 
> I plan to do standard image processing (color thresholding, watershed, etc) to convert flow into mask. This might not be as accurate as the gradient flow tracking method but is definitely faster.

@pushkal777 @lidanwu You may refer to this repo to realize the function of converting cellpose flow to mask:
[https://github.com/qixinbo/cellpose2msk](https://github.com/qixinbo/cellpose2msk)
or the cellpose-planer repo:
[https://github.com/Image-Py/cellpose-planer/blob/b4879cd6f1ddde4562cd25dd47960af8cb7fdffc/cellpose_planer/cellpose.py#L94](https://github.com/Image-Py/cellpose-planer/blob/b4879cd6f1ddde4562cd25dd47960af8cb7fdffc/cellpose_planer/cellpose.py#L94)

**Comment by lidanwu** [comment]
Thanks for the suggestion! But what I’m looking for is how to turn off the mask computation when running cellpose. 
The suboptimal approach I found right now is to specify pretrained_model and set compute_mask = False. But this approach would also turn off the size estimation model. I’m wondering whether there’s a way to use normal cellpose (which does automatic size estimation and model selection) with compute_masks = False...

**Comment by qixinbo** [comment]
@lidanwu Then you may try this repo:
[https://github.com/qixinbo/cellpose-turbo](https://github.com/qixinbo/cellpose-turbo)
It replaces the mask computation module with the above code, meanwhile doesn't change other functions.

**Comment by carsen-stringer** [comment]
the automatic size estimation always uses the compute_masks unfortunately, so there is no point in using the `Cellpose` model rather than the `CellposeModel` if you are turning off mask computation. going to close this issue for now, let us know if you have any other questions
