### ISSUE TITLE
Cellpose GUI not running after installing GPU version (CUDA) on Windows

### ISSUE THREAD

**Issue by brendavasquez** [MouseLand/cellpose#271]
I want to use the GPU-enabled version of Cellpose for segmenting stacks of neurons to speed up segmentation time. It is currently taking almost 4.5 hours to segment one stack that is single channel, 512 x 512 pixels, and 81 planes. 

After installing cellpose, I run: 
pip uninstall torch
then
conda install pytorch cudatoolkit=10.2 -c pytorch

Then I try to run cellpose but the GUI does not open. No errors are shown. It only shows the path of the generated log. 
What can be causing this?

**Comment by carsen-stringer** [comment]
unfortunately I haven't seen this issue before, can you run cellpose on the command line okay instead of the GUI?

**Comment by arkansertan** [comment]
I have the same problem.  When I use GPU , cellpose does not give any result ! on the other hand, when I choose not use GPU, the cellpose make segmentation and produce  result in GUI

**Comment by carsen-stringer** [comment]
I think the workaround is now documented here: https://cellpose.readthedocs.io/en/latest/installation.html#common-issues. closing issue but let us know if it's not working.
