### ISSUE TITLE
masks_flows_to_seg documentation issue

### ISSUE THREAD

**Issue by cornhundred** [MouseLand/cellpose#272]
Hi, in the documentation the example using [`io.masks_flows_to_seg`](https://cellpose.readthedocs.io/en/latest/outputs.html?highlight=save#seg-npy-output) is says to run 

```
io.masks_flows_to_seg(images, masks, flows, diams, channels, file_name)
```

but this gives me an error 

```
TypeError: expected str, bytes or os.PathLike object, not int
```

at 

```
base = os.path.splitext(file_names)[0]
```

If you reorder the arguments, it works for me

```
io.masks_flows_to_seg(images, masks, flows, diams, file_name, channels)
```

**Comment by carsen-stringer** [comment]
thanks!
