### ISSUE TITLE
download cellpose_gui.png fail

### ISSUE THREAD

**Issue by Jacketlove** [MouseLand/cellpose#278]
I think it is a bug.
cellpose/cellpose/gui/gui.py    line 127
download_url_to_file('https://github.com/MouseLand/cellpose/raw/master/docs/_static/cellpose_gui.png', guip_path, progress=True)
need modify to
download_url_to_file('https://github.com/MouseLand/cellpose/tree/master/docs/_static/cellpose_gui.png', guip_path, progress=True)

**Comment by carsen-stringer** [comment]
I don't get an error from this, can you please print the error message? I'm going to close for now but let me know if you're still having issues
