### ISSUE TITLE
Cellpose GPU Issue

### ISSUE THREAD

**Issue by borovij** [MouseLand/cellpose#279]
Hello,

I am trying to install the GPU version (CUDA) on Windows. I am using Anaconda to access cellpose and have used the commands under the "GPU version (CUDA) on Windows or Linux" to try and install this. My computer is running NVIDIA Quadro K4000 and it seems to be working properly. I have also successfully installed Pytorch and  CUDA 10.2 on my computer. However, I am having trouble making the GPU compatible with cellpose. I keep getting an error saying that "TORCH CUDA version not installed/working".
Please let me know if any other information is needed and I will try my best to provide it. 
I appreciate all of your help!

**Comment by cwood1967** [comment]
Hi,

I have had similar issues, and I have found that installing CUDA 10.0 fixes the problem.

Chris

**Comment by borovij** [comment]
Hello,

Thank you @cwood1967 for your prompt reply. 
I have installed CUDA 10.0 on my computer using this link: 

https://developer.nvidia.com/cuda-10.0-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal.

However, when I try to use this command for Anaconda Prompt (Anaconda3): 

conda install pytorch cudatoolkit=10.0 -c pytorch

I receive a "failed with initial frozen solve" and it says it has found "conflicts". How would I go about solving this problem?
Thanks again!

**Comment by JKesby** [comment]
Hi,

After upgrading our GPU (RTX 3090) I could only get it working by installing v11.1 
From memory I had 10.2 installed and tried 10.0 as well.

conda install pytorch cudatoolkit=11.1 -c pytorch -c=conda-forge

Could try that.
Cheers.

**Comment by carsen-stringer** [comment]
thanks for all the help everyone, I'm going to close this issue for now, @borovij please let us know if you're still having issues
