### ISSUE TITLE
making a version of cellpose without graphical dependencies

### ISSUE THREAD

**Issue by carsen-stringer** [MouseLand/cellpose#28]
"that functionality could be obtained via downstream software" agree it! (so is there any way to pip install cellpose without pyqt? it is large, but not useful for imagepy)
Any features needed such as roi can pop an issue [https://github.com/Image-Py/cellpose-plgs](https://github.com/Image-Py/cellpose-plgs).

_Originally posted by @yxdragon in https://github.com/MouseLand/cellpose/issues/2#issuecomment-585287088_

**Comment by carsen-stringer** [comment]
@yxdragon do you know how to make a pip without certain dependencies? I know for instance I could have
~~~
pip install cellpose[gui]
~~~
with more dependencies, but I'd prefer that the `pip install cellpose` has the pyqt dependencies, and then a command like `pip install cellpose[nogui]` does not have those.

Thanks.

**Comment by sofroniewn** [comment]
@carsen-stringer we've had some similar discussions within napari around our `PySide2` / `PyQt5` dependencies - see this comment here for some conclusions https://github.com/napari/napari/issues/704#issuecomment-572902289

One option in the context of this issue might be to make a `cellpose-base` that could be pip installed without your GUI by both your main cellpose repo (you still have `pip install cellpose` pull down your full GUI + `cellpose-base`) and things like `ImagePy-cellpose` or a `napari-cellpose` plugins that could just pull down `cellpose-base`.

You then keep things simple for your main users, but allow your core code to be reused in plugins.

**Comment by carsen-stringer** [comment]
thanks so much for the advice! I'll think about this option

**Comment by AlexEMG** [comment]
Nice project @carsen-stringer ! 

For DeepLabCut, we have an environment variable system, that works quite well. A user can import DLC while suppressing the GUIs: https://github.com/AlexEMG/DeepLabCut/blob/37d4f6fe62776e06bada851ebbdff88ffff24f9d/docs/UseOverviewGuide.md#option-3-using-the-program-terminal-start-ipython

That said, going forward we are most likely splitting code in deeplabcut-core/base and everything...

**Comment by carsen-stringer** [comment]
Thanks everyone for the advice. I've decided to use the `extras_require` tag, so that the GUI dependencies install if the user says `pip install cellpose[gui]`. I think most users will choose this route, and then if used as a plug-in, cellpose can be installed with `pip install cellpose`.
