### ISSUE TITLE
Importing 3D Labels into ImageJ

### ISSUE THREAD

**Issue by vineet-kureel** [MouseLand/cellpose#286]
Hi All,
Thank you for developing such a useful program to help non-programmers like me to get tasks done easily.
I have generated a label map and want to import it in FIJI, but am facing failures in that.
I tried to follow the steps mentioned in the cellpose Documentation. but it works only for 2D images.
It will be a great help to me if you can provide me with a solution or direction toward solving the problem.

Thank you again !
Looking forward to hearing from you soon.
![noramlize_cell_segment_cp_masks](https://user-images.githubusercontent.com/67627842/124732263-b9d83f00-df1b-11eb-8f39-76c9bdf8a5e8.jpg)

Attached below is one of my label map images.

**Comment by carsen-stringer** [comment]
From my understanding there is no way to import 3D labels, see info in this issue: https://github.com/MouseLand/cellpose/issues/245

The workaround is to import the masks tiff into imageJ, I think from there you can use the plugin they mentioned? I have not done this myself so please comment in that issue #245 if you need help
