### ISSUE TITLE
what is the function of rescale

### ISSUE THREAD

**Issue by Reardonlab** [MouseLand/cellpose#29]
I may have missed it but can you describe what "rescale" is in the jupyter notebook? It says "if you want to set `rescale` yourself (recommended), set it to 30. / average_cell_diameter" is this 30 divide by the average cell diameter in pixels?

**Comment by carsen-stringer** [comment]
yes that is how "rescale" works. I've now changed it so that the user can use the diameter in pixels instead of rescale (https://github.com/MouseLand/cellpose/blob/master/notebooks/run_cellpose.ipynb)

please let me know if you are having issues I will close for now
