### ISSUE TITLE
Problem chosing the cells diameter in Python

### ISSUE THREAD

**Issue by koopa31** [MouseLand/cellpose#291]
Hi,
I faced a problem trying to chose the cell diameter in python. Indeed, I wrote:
model.eval(imgs, diameter=70)
and realized that the diameter I wanted had not been taken into account. Then, I figured out that the default parameter is 30., so I tried to add the dot in order to convert my 70 from integer to float and it finally worked!
I think that could be great for the user to enter an integer without having to specify the type, because it is not very intuitive.
The GUI is very nice btw!
Best regards

**Comment by carsen-stringer** [comment]
This is in a notebook? And is model `CellposeModel` or `Cellpose`? I cannot reproduce this issue

**Comment by carsen-stringer** [comment]
also please tell me operating system, especially if you're running in the GUI, I'm testing on windows

**Comment by carsen-stringer** [comment]
sorry closing due to inactivty, I'm glad you got it working
