### ISSUE TITLE
cuda runtime requirement vs recommendation

### ISSUE THREAD

**Issue by chrisroat** [MouseLand/cellpose#292]
The [README](https://github.com/MouseLand/cellpose/blob/35c16c94e285a4ec2fa17f148f06bbd414deb5b8/README.md#gpu-version-cuda-on-windows-or-linux) indicates the recommended CUDA runtime is 10.2, though I have seen in  https://github.com/MouseLand/cellpose/issues/247 and https://github.com/MouseLand/cellpose/issues/20 there seems to be success with 11.x.  How strong is the recommendation -- are there known problems/incompatibilities with newer runtimes?

**Comment by JKesby** [comment]
Hi,
My experience suggests it depends on your GPU. 
I initially was using 10.2 but on an RTX 3090 I couldn't get it to work. I upgraded to 11.1 and it works like a dream. I think the newer GPU tech requires the updated CUDA runtime.

Cheers.

**Comment by carsen-stringer** [comment]
perhaps we should remove the recommendation now that pytorch has good support for new cuda versions. as long as the pytorch version is >1.6, things should work well
