### ISSUE TITLE
simplified GPU installation instructions

### ISSUE THREAD

**Issue by chrisroat** [MouseLand/cellpose#293]
The instructions for installing locally and for installing the GPU version on linux have several steps, and most might not be needed.  I found the entire process needed was:

```bash
conda create -n cellpose python=3.7 
conda activate cellpose
pip install cellpose  # add [gui] for GUI stuff
```

Specifically, the GPU seemed to be detected ("** TORCH CUDA version installed and working. **"), without uninstalling torch and installing pytorch.  

Would you accept a PR to rework the instructions, or is there a potential gotcha in using the instructions above?  (I would write a version for anaconda, as well.)

**Comment by carsen-stringer** [comment]
I would be very happy to accept a pull request with this! I think python=3.8 should be supported now too
