### ISSUE TITLE
UserWarning about align_corners change

### ISSUE THREAD

**Issue by chrisroat** [MouseLand/cellpose#294]
There is a UserWarning being generated, and it concerned me (and other others: #232 #263).  Users should pay attention to warnings, and shouldn't be trained to ignore them.

In this case, one is worried that cellpose intended to use the old pytorch behavior and may give incorrect results now that the behavior has changed.

To rid the warning and ensure correct operation, the cellpose library should explicitly set `align_corners` where it is parameter.   If you would accept a PR, what is your intended behavior -- `align_corners=True` or `align_corners=False`?

**Comment by carsen-stringer** [comment]
good point, I wrote this with a newer torch version, so always using `align_corners=False`, this is now in the function call
