### ISSUE TITLE
turn off logging configuration

### ISSUE THREAD

**Issue by chrisroat** [MouseLand/cellpose#295]
Upon import, cellpose takes over the logging apparatus, changing the logging format, logging streams, and logging level.  This is non-standard practice, and could cause problems for users (say, they environment has no disk or has precious disk space... or the cellpose logging level is way too verbose in other parts of the system).

Would it be acceptable to move this configuration to the main of the cellpose scripts, and leave the main logging config untouched when cellpose is imported as a library?

**Comment by carsen-stringer** [comment]
Hmm, I was doing this to make sure the logging from cellpose got routed to suite2p logging and napari logging, in both of these cases cellpose is imported as a library. What is standard practice here? This is my first time using the logging library actually :)

**Comment by chrisroat** [comment]
Logging should automatically be available to any code that imports cellpose modules.  Nothing extra should be necessary!   Just create the loggers for each module, as you have done, and there is usually not a need to do anything else.  

The calling code should usually take responsibility for setting the logging levels it wants and where the output should go.    This includes any cellpose scripts -- the scripts can setup the logging the way they want (e.g. inside their main).

Let me know if you have a counter-example, or are having problems getting it to work.

**Comment by pskeshu** [comment]
I have been wondering how to best turn this off, without have to install cellpose from a local repo.

**Comment by chrisroat** [comment]
Yeah, we just work off our own branch.  Here's the commit I used, which you can cherry pick or just copy:

https://github.com/deisseroth-lab/cellpose/commit/34258c92d1db819cb522ed296a86f9dace64b02d

@carsen-stringer I recommend not setting up logging within the cellpose init file, and only doing it within the apps themselves.

Libraries generally don't set up logging configuration.  A module typically imports the logging module, uses the root logger or creates a custom logger, and then makes calls to the logger.  

The calling code (e.g. the gui or another app) would then configure the logging how it wants.  It can say "cellpose should log DEBUG and higher to file x/y/z.txt".  Here's an example of that:

```sh
$ cat app.py 
import logging
import cellpose

def setup_logging():
    logger = logging.getLogger('cellpose')
    fh = logging.FileHandler('/tmp/cellpose.log')
    logger.addHandler(fh)
    logger.setLevel(logging.DEBUG)

if __name__ == "__main__":
    setup_logging()
    cellpose.run()

$ cat cellpose.py
import logging

logger = logging.getLogger(__name__)

def run():
    logger.debug('debug')
    logger.info('info')
    logger.warning('warning')

$ python app.py

$ cat /tmp/cellpose.log
debug
info
warning
```
