### ISSUE TITLE
cellpose installation results in AttributeError: module 'PyQt5.QtGui' has no attribute 'QPushButton' error

### ISSUE THREAD

**Issue by jdecarre** [MouseLand/cellpose#298]
after following instructions to create the cellpose environment I run python -m cellpose and recieve the AttributeError: module 'PyQt5.QtGui' has no attribute 'QPushButton' error message. I tried to reinstall or upgrade the pyqt5 module but neither works. Any suggestions for getting this to work?

**Comment by timblosser** [comment]
I get the same error, also following the instructions:
AttributeError: module 'PyQt5.QtGui' has no attribute 'QPushButton'
...cellpose\gui\guiparts.py", line 19

I did the following and now the gui is opening:
pip install cellpose[gui]
python -m cellpose

**Comment by bvandenbroek** [comment]
Same here. I've installed cellpose on various computers without issues (well, at least not this one). On another computer, after setting up a brand new cellpose environment I now get this error.
- I created the environment from PyCharm/Anaconda3, using `environment.yml`. I also installed Pytorch GPU for CUDA toolkit 10.2, according to the readme.
- Uninstalling and reinstalling PyQt5-tools does not solve the issue.

Here's the full error:
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Git_repositories\cellpose\cellpose\__main__.py", line 11, in <module>
    from cellpose.gui import gui
  File "D:\Git_repositories\cellpose\cellpose\gui\gui.py", line 14, in <module>
    from . import guiparts, menus, io
  File "D:\Git_repositories\cellpose\cellpose\gui\guiparts.py", line 19, in <module>
    class QuadButton(QtGui.QPushButton):
AttributeError: module 'PyQt5.QtGui' has no attribute 'QPushButton'
```

Here's the full error:

**Comment by carsen-stringer** [comment]
Please try installing these specific package versions: https://github.com/MouseLand/suite2p/issues/691#issuecomment-876728260

I need to update cellpose's imports to the new formatting

**Comment by bvandenbroek** [comment]
Ok, I didn't read @timblosser 's comment. Running `pip install cellpose[gui]` fixes the issue!
This is not only true for the gui, but also for running cellpose from the command line, without the gui.

Thanks for this magnificent tool, by the way!
Bram

**Comment by carsen-stringer** [comment]
thanks :) good to hear! I am still worried about that import error, but at least it's working for you now

**Comment by jdecarre** [comment]
Thanks everyone for the help on this. I will try installing the packages you linked as the pip install cellpose[gui] didn’t immediately solve the issue. Hopefully I can get this running tomorrow and begin the fun part.

Justin Decarreau

**Comment by bvandenbroek** [comment]
Thanks @carsen-stringer!
Not sure if this is useful information for you. I got cellpose running on that machine, but in the end it turned out that the graphics card (NVIDIA TITAN Black) is not supported by PyTorch any more. :-(
So no GPU for us there. But anyway, CPU works well now.

Thanks,
Bram

**Comment by DarioMoed** [comment]
It does seem like Cellpose needs some GUI parts to be rewritten to follow PyQt5's latest changes.
Installing the specific package version in suite2p's #691 [issue](https://github.com/MouseLand/suite2p/issues/691#issuecomment-876728260) did not do the trick for me, so I went down and looked a bit at what the problem was.

From a fresh install, in /cellpose/cellpose/gui, I had to change the following code to succesfully launch Cellpose:
Change QtGui to QtWidgets in the following lines from guiparts.py, gui.py, menus.py:
guiparts = [10,  19,  29, 107, 123, 234, 256, 265, 556, 557, 564, 575]
menus = [ 10,  15,  21,  31,  37,  43,  49,  54,  65,  71,  77,  83,  93,
        97, 102]
gui = [ 35,  38,  39, 118, 151, 190, 191, 258, 263, 268, 277, 295, 302,
       309, 320, 328, 338, 348, 357, 369, 376, 381, 391, 401, 411, 419,
       427, 435, 444, 444, 452, 467, 474, 481, 488, 496, 507, 514, 530,
       537, 548, 555, 559, 567]

Also, it seems that QtCore.Signal was replaced by QtCore.pyqtSignal. I had to change that in gui.py, line 362, to get Cellpose started.

It seems like there is much more code to change though, as these were just the errors I encountered while simply launching Cellpose with `python -m cellpose`.

Hope you can fix it without too much trouble

**Comment by cecilomar6** [comment]
I had the same problem. After installing the package versions suggested and running `pip install cellpose[gui]`, I have a different error when running `python -m cellpose`

```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
```
I have tried to reinstall the application, but it didn't help. What should I try next?

Thanks! 
Ceci

**Comment by carsen-stringer** [comment]
hey @cecilomar6 it looks like you may need to install an ubuntu package, see details here: https://discuss.pixls.us/t/solved-could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found/17677

the import errors are now fixed on the github version of cellpose, will make a new pip soon
