### ISSUE TITLE
Loading saved weights when training from scratch

### ISSUE THREAD

**Issue by atob1** [MouseLand/cellpose#299]
Hi, I trained the cellpose model from scratch and was trying to benchmark the model by loading the saved weights into the cellpose model and then using that model to predict. When trying to load the weights getting this error: basically that an ordereddict has no attribute eval. How do you recommend benchmarking the model?
<img width="634" alt="Screen Shot 2021-07-16 at 12 37 54 AM" src="https://user-images.githubusercontent.com/57077728/125892573-7c205447-cfa1-4502-8aef-3596bc64cc34.png">

**Comment by carsen-stringer** [comment]
here is the api for the CellposeModel: https://cellpose.readthedocs.io/en/latest/api.html#cellpose.models.CellposeModel. Did you set `pretrained_model='/path/to/model'`? I think that may be the problem, if not let me know and I'll reopen the issue
