### ISSUE TITLE
size_cyto_0.npy not found

### ISSUE THREAD

**Issue by cyf203** [MouseLand/cellpose#3]
Hi, I tried your GUI and works fine. 

When I run the script, I found an Error: [Errno 2] No such file or directory: 'D:\\JanakLabTest\\David\\Anaconda\\envs\\cellpose-yifeng\\lib\\site-packages\\cellpose\\models\\size_cyto_0.npy'

Do you have any possible thoughts?
Thank you so much,

**Comment by carsen-stringer** [comment]
Did you run the script before or after you ran the GUI? the GUI should automatically download the models for you, and then after that you can run it in a script. I will fix the code now so that the download will happen the first time you import the cellpose model as well.

**Comment by carsen-stringer** [comment]
this should now be fixed

**Comment by cyf203** [comment]
Thank you very much! It has been fixed!
