### ISSUE TITLE
Handling of single-channel grayscale image in run_cellpose notebook

### ISSUE THREAD

**Issue by LauLauThom** [MouseLand/cellpose#30]
Hi,
thanks for the tool and the documentation.
I just noticed that when using single-channel grayscale images in the demo notebook to run cell pose, with `channels=[0,0]`, I had an error `ValueError: axes don't match array`.

Converting the grayscale to RGB (ie duplicating the gray channel) seems to work. I think in the GUI version it was done automatically.
Here the command if that can help someone
`imgs = [cv2.cvtColor(img, cv2.COLOR_GRAY2RGB) for img in imgs] # convert grayscale to RGB`

The `imread` function from OpenCV automatically returns a BGR (not RGB but simple resorting would yield RGB) if the argument  `cv2.IMREAD_COLOR` is set. That could be an even better alternative ?

**Comment by carsen-stringer** [comment]
thanks for pointing this out, I've fixed this so the user doesn't have to worry if the tiff/image is 2 dimensional
