### ISSUE TITLE
Issues installing the GUI, pip install cellpose[gui]

### ISSUE THREAD

**Issue by sdand318** [MouseLand/cellpose#302]
I am trying to get the GUI to open up for cellpose, but every time I try to open cellpose itself, no other terminal/window opens for me to drag-and-drop pictures. It states I need to install the cellpose[gui], but am not sure how. When I type "pip install cellpose[GUI]" it shoots out zsh: no matches found: cellpose[gui]. If someone could please help me figure out if I have cellpose downloaded correctly, and if so how to get the window to open so that I can view and edit pictures like on their website! Thank you so much for the help, I appreciate it a lot!

**Comment by n-amb** [comment]
Hi sdand318, 

I experienced a similar installation issue. Try putting cellpose[gui] in single quotes. So in terminal you would enter the following: 
> pip install 'cellpose[gui]'

Hope this helps!
