### ISSUE TITLE
Out of memory error (Pytorch)

### ISSUE THREAD

**Issue by Prehani** [MouseLand/cellpose#303]
I suspect this may be a combination of factors, however we are getting the following error: 
 `NET ERROR: CUDA out of memory. Tried to allocate 308.00 MiB (GPU 0; 8.00 GiB total capacity; 6.17 GiB already allocated; 0 bytes free; 6.48 GiB reserved in total by PyTorch)` 
When we try to run with a larger single TIFF stack (~200MB, representing a time course). 
Not sure why Pytorch is hogging 6.5GB of memory, but I suspect that this can be parallelized. We have 4 Nvidia Quadro P4000's and only 1 is being slammed right away at the moment with the entire memory load. I am not sure if the combination of all 4 would be enough, but my guess would be that it would help. I'd also guess that Pytorch's Data Parallel function would help a lot with this well (maybe an easy fix?). 
We can segment with the CPU, but that is obviously not ideal given the time hit we'll take on every single dataset we'd hope to segment. The alternative is just scripting everything and doing it frame by frame; however, we were hoping to use the GUI for those in the lab who aren't as technically savvy. 
If I missed anything, please let me know! Happy to provide more information as needed as well.

**Comment by Prehani** [comment]
As a temporary workaround, in case anybody else runs into this issue, the best way to segment time course images (in 2D at least) appears to be by treating the dataset as a list of 2D numpy image arrays rather than as a single 3D numpy array. This gets around the issue of GPU memory utilization. 

Might be nice to include an optional parameter in the model eval to set 3D arrays as either time course or Z-stacks.

**Comment by carsen-stringer** [comment]
hmm, I think the napari plugin for cellpose will run your stacks correctly without utilizing too much memory, check it out here: https://github.com/MouseLand/cellpose-napari. I am not really supporting time series data in the cellpose native GUI, but I am supporting it (hopefully :)) in the napari plugin.

Other options are to reduce the batch_size but that would also involve scripting.

**Comment by Prehani** [comment]
Gotcha, that makes a lot of sense! Do you have any specific plans for support to prefer one/the other? We've found Cellpose to be super useful in many of the projects we're working on, and having an easy to use interface has been awesome! Thanks for all of your work on this.
