### ISSUE TITLE
Running cellpose on colab - segmentation, finding masks on an image, and displaying results

### ISSUE THREAD

**Issue by sdand318** [MouseLand/cellpose#305]
So I'm using colab through google and trying to run cellpose. I've successfully been able to import my image, but it doesn't show up and I get an error message about my codes and no masks show up if I change the diameter and flow threshold to something like -1 or 10 it shows nothing and says 0 secs. 

This is the code I'm using for the error message: 

!nvcc --version
!nvidia-smi
!pip install cellpose
import numpy as np
import time, os, sys
from urllib.parse import urlparse
import skimage.io
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline
mpl.rcParams['figure.dpi'] = 300

from urllib.parse import urlparse
from cellpose import models

use_GPU = models.use_gpu()
print('>>> GPU activated? %d'%use_GPU)

from IPython.display import Image
Image('WellA01_ChannelBrightfield_Seq0000.png')
files = ['WellA01_ChannelBrightfield_Seq0000.png']
import skimage.io 
imgs = [skimage.io.imread('WellA01_ChannelBrightfield_Seq0000.png')]
nimg = len(imgs)

plt.figure(figsize=(8,4))
for k,img in enumerate(imgs[:-1]):
  plt.subplot(1,3,k+1)
  plt.imshow(img)

imgs_2D = imgs[:-1]

from cellpose import models
model = models.Cellpose(gpu=True, model_type='cyto')

# define CHANNELS to run segementation on
#grayscale=0, R=1, G=2, B=3
channels = ['cytoplasm', 'nucleus']
#if NUCLEUS channel does not exist, set the second channel to 0
channels = [0,0]
# IF ALL YOUR IMAGES ARE THE SAME TYPE, you can give a list with 2 elements
channels = [0,0] 

masks, flows, styles, diams = model.eval(imgs_2D, diameter=None, flow_threshold=None, channels=channels)

from cellpose import plot

nimg = len(imgs_2D)
for idx in range(nimg):
    maski = masks[idx]
    flowi = flows[idx][0]

    fig = plt.figure(figsize=(12,5))
    plot.show_segmentation(fig, imgs[idx], maski, flowi, channels=channels[idx])
    plt.tight_layout()
    plt.show()

but when it gets to: 

masks, flows, styles, diams = model.eval(imgs_2D, diameter=None, flow_threshold=None, channels=channels)

it says: 

IndexError                                Traceback (most recent call last)
<ipython-input-3-e6e0ede3cce9> in <module>()
     42 channels = [0,0]
     43 
---> 44 masks, flows, styles, diams = model.eval(imgs_2D, diameter=None, flow_threshold=None, channels=channels)
     45 
     46 from cellpose import plot

/usr/local/lib/python3.7/dist-packages/cellpose/models.py in eval(self, x, batch_size, channels, channel_axis, z_axis, invert, normalize, diameter, do_3D, anisotropy, net_avg, augment, tile, tile_overlap, resample, interp, flow_threshold, cellprob_threshold, min_size, stitch_threshold, rescale, progress)
    229 
    230         estimate_size = True if (diameter is None or diameter==0) else False
--> 231         if estimate_size and self.pretrained_size is not None and not do_3D and x[0].ndim < 4:
    232             tic = time.time()
    233             models_logger.info('~~~ ESTIMATING CELL DIAMETER(S) ~~~')

IndexError: list index out of range
<Figure size 2400x1200 with 0 Axes>

if I change the diameter to -1 like so: 
masks, flows, styles, diams = model.eval(imgs_2D, diameter=-1, flow_threshold=-1, channels=channels)

 I get this: 
2021-07-28 00:42:25,313 [INFO] ** TORCH CUDA version installed and working. **
2021-07-28 00:42:25,314 [INFO] >>>> using GPU
2021-07-28 00:42:25,434 [INFO] ~~~ FINDING MASKS ~~~
2021-07-28 00:42:25,436 [INFO] >>>> TOTAL TIME 0.00 sec
<Figure size 2400x1200 with 0 Axes>

I'm not sure how to fix it to show the image and results of the masks it finds? I don't know the diameter of the cells so they said use none if you don't know it, but that gets me this error message... I would appreciate any help, thank you so much in advance!

**Comment by carsen-stringer** [comment]
these variables should not be negative numbers
