### ISSUE TITLE
How to define flow_threshold and diameter in Python 

### ISSUE THREAD

**Issue by sdand318** [MouseLand/cellpose#306]
**The error I get is:** 

NameError                                 Traceback (most recent call last)
<ipython-input-13-7abfe64f85a5> in <module>()
     47 
     48 diameter = 15
---> 49 masks, flows, styles, diams = model.eval(imgs_2D, diameter==0, flow_threshold==0, channels=channels)
     50 
     51 from cellpose import plot

NameError: name 'flow_threshold' is not defined OR that diameter is not defined. 

**the code it is flagging is the following:** 
masks, flows, styles, diams = model.eval(imgs_2D, diameter==0, flow_threshold==0, channels=channels)

**The whole code is the following:** 

!nvcc --version
!nvidia-smi
!pip install cellpose
import numpy as np
import time, os, sys
from urllib.parse import urlparse
import skimage.io
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline
mpl.rcParams['figure.dpi'] = 300

from urllib.parse import urlparse
from cellpose import models

use_GPU = models.use_gpu()
print('>>> GPU activated? %d'%use_GPU)

from IPython.display import Image
Image('WellA01_ChannelBrightfield_Seq0000.png')
files = ['WellA01_ChannelBrightfield_Seq0000.png']
import skimage.io 
imgs = [skimage.io.imread('WellA01_ChannelBrightfield_Seq0000.png')]
nimg = len(imgs)

plt.figure(figsize=(8,4))
for k,img in enumerate(imgs[:-1]):
  plt.subplot(1,3,k+1)
  plt.imshow(img)

imgs_2D = imgs[:-1]

from cellpose import models
model = models.Cellpose(gpu=True, model_type='cyto')

# define CHANNELS to run segementation on
#grayscale=0, R=1, G=2, B=3
channels = ['cytoplasm', 'nucleus']
#if NUCLEUS channel does not exist, set the second channel to 0
channels = [0,0]
# IF ALL YOUR IMAGES ARE THE SAME TYPE, you can give a list with 2 elements
channels = [0,0] 

# if diameter is set to None, the size of the cells is estimated on a per image basis
# you can set the average cell `diameter` in pixels yourself (recommended) 
# diameter can be a list or a single number for all images and flow_threshold can too

masks, flows, styles, diams = model.eval(imgs_2D, diameter==0, flow_threshold==0, channels=channels)

**Any and all help would be greatly appreciated, thank you so much in advanced!**

**Comment by carsen-stringer** [comment]
see info here, diameter should be set to a value you think it is, not zero. https://cellpose.readthedocs.io/en/latest/settings.html#diameter. Same with flow_threshold, also not sure if you have the `==` in the code or not, that will produce an error
