### ISSUE TITLE
How to fix: List index is out of range? 

### ISSUE THREAD

**Issue by sdand318** [MouseLand/cellpose#307]
**This is the error I'm getting:** 
IndexError                                Traceback (most recent call last)
<ipython-input-16-38f6f6645cc3> in <module>()
     46 # diameter can be a list or a single number for all images and flow_threshold can too
     47 
---> 48 masks, flows, styles, diams = model.eval(imgs_2D, diameter=None, flow_threshold=None, channels=channels)
     49 
     50 from cellpose import plot

/usr/local/lib/python3.7/dist-packages/cellpose/models.py in eval(self, x, batch_size, channels, channel_axis, z_axis, invert, normalize, diameter, do_3D, anisotropy, net_avg, augment, tile, tile_overlap, resample, interp, flow_threshold, cellprob_threshold, min_size, stitch_threshold, rescale, progress)
    229 
    230         estimate_size = True if (diameter is None or diameter==0) else False
--> 231         if estimate_size and self.pretrained_size is not None and not do_3D and x[0].ndim < 4:
    232             tic = time.time()
    233             models_logger.info('~~~ ESTIMATING CELL DIAMETER(S) ~~~')

IndexError: list index out of range

**This is the code it is flagging:** 

--> 48 masks, flows, styles, diams = model.eval(imgs_2D, diameter=None, flow_threshold=None, channels=channels)

**This is my entire code for this section:** 
!nvcc --version
!nvidia-smi
!pip install cellpose
import numpy as np
import time, os, sys
from urllib.parse import urlparse
import skimage.io
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline
mpl.rcParams['figure.dpi'] = 300

from urllib.parse import urlparse
from cellpose import models

use_GPU = models.use_gpu()
print('>>> GPU activated? %d'%use_GPU)

from IPython.display import Image
Image('WellA01_ChannelBrightfield_Seq0000.png')
files = ['WellA01_ChannelBrightfield_Seq0000.png']
import skimage.io 
imgs = [skimage.io.imread('WellA01_ChannelBrightfield_Seq0000.png')]
nimg = len(imgs)

plt.figure(figsize=(8,4))
for k,img in enumerate(imgs[:-1]):
  plt.subplot(1,3,k+1)
  plt.imshow(img)

imgs_2D = imgs[:-1]

from cellpose import models
model = models.Cellpose(gpu=True, model_type='cyto')

# define CHANNELS to run segementation on
#grayscale=0, R=1, G=2, B=3
channels = ['cytoplasm', 'nucleus']
#if NUCLEUS channel does not exist, set the second channel to 0
channels = [0,0]
# IF ALL YOUR IMAGES ARE THE SAME TYPE, you can give a list with 2 elements
channels = [0,0] 

# if diameter is set to None, the size of the cells is estimated on a per image basis
# you can set the average cell `diameter` in pixels yourself (recommended) 
# diameter can be a list or a single number for all images and flow_threshold can too

masks, flows, styles, diams = model.eval(imgs_2D, diameter=None, flow_threshold=None, channels=channels)

from cellpose import plot

nimg = len(imgs_2D)
for idx in range(nimg):
    maski = masks[idx]
    flowi = flows[idx][0]

    fig = plt.figure(figsize=(12,5))
    plot.show_segmentation(fig, imgs[idx], maski, flowi, channels=channels[idx])
    plt.tight_layout()
    plt.show()

**If someone could please help me figure out how to fix the diameter so it is no longer out of range that would be greatly appreciated! Thank you so much in advance for all your help :D !**

**Comment by carsen-stringer** [comment]
going to close due to inactivity, let us know if you're still having issues
