### ISSUE TITLE
How to Fix: TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by sdand318** [MouseLand/cellpose#308]
In cellpose my figure is showing up blank and not doing any masks or segmentations, it returns this TypeError: 'int' object is not subscriptable flagging the following code: 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-fc16b5d93e8f> in <module>()
----> 1 plot.show_segmentation (fig, imgs[idx], maski, flowi, channels=channels[idx])

1 frames
/usr/local/lib/python3.7/dist-packages/cellpose/plot.py in image_to_rgb(img0, channels)
    169     if img.shape[0]<5:
    170         img = np.transpose(img, (1,2,0))
--> 171     if channels[0]==0:
    172         img = img.mean(axis=-1)[:,:,np.newaxis]
    173     for i in range(img.shape[-1]):

I'm wondering if anyone can please help me figure out how to make it so the program recognizes the function and will display the image? Thank you so much for any and all help, I appreciate it a lot! 

Warm Wishes and Many Thanks!

**Comment by carsen-stringer** [comment]
hey @sdand318 it looks like you are giving channels as an integer instead of a list, see the documentation here: https://cellpose.readthedocs.io/en/latest/settings.html#channels

closing issue but let me know if it doesn't work
