### ISSUE TITLE
segmentation of 3D data

### ISSUE THREAD

**Issue by tischi** [MouseLand/cellpose#31]
Hello, 

I was wondering whether cellPose also works on 3D data?
Specifically, we have 3D stacks with cells as shown below:

![image](https://user-images.githubusercontent.com/2157566/76225301-98c6e780-621c-11ea-9175-94fb4c8eda11.png)

**Comment by tischi** [comment]
Wow. It works really well in 2D!
But 3D?

![image](https://user-images.githubusercontent.com/2157566/76225529-e8a5ae80-621c-11ea-84cc-39bb4059dfde.png)

**Comment by VolkerH** [comment]
@tischi, have a look at #16

**Comment by carsen-stringer** [comment]
You can now drag-and-drop this 3D tiff into cellpose and the 3D version will run in the GUI, using the model you choose and the channels you set (Note: you will have to set the diameter manually)

See info on 3D format [here](http://www.cellpose.org/static/docs/inputs.html#d-segmentation)

**Comment by tischi** [comment]
Great! I tried to upload [this file](https://oc.embl.de/index.php/s/iWrM7HHSTxbSgYe) onto the website but nothing happened. Could you please try as well?

**Comment by marius10p** [comment]
The website is only for 2D data. You need to install Cellpose on your computer for the 3D version.

**Comment by tischi** [comment]
Thank you!
