### ISSUE TITLE
Error acessing _seg.ny

### ISSUE THREAD

**Issue by SamarAhmedAbbass** [MouseLand/cellpose#311]
Hi,
We have a problem in accessing _seg.npy or finding its location and keep seeing this error. Any help?
![Segnpy](https://user-images.githubusercontent.com/38736335/129203443-8ac83544-ae20-43ad-82e5-7d92bbbe2657.jpeg)

**Comment by carsen-stringer** [comment]
you need to look in the files that have been created in the file viewer in google colab on the left, it should be a file that ends with _seg.npy but the full path depends on the file name
