### ISSUE TITLE
OpenCV image size error

### ISSUE THREAD

**Issue by jnmark** [MouseLand/cellpose#312]
I am trying to use the GUI version of cellpose, but it seems like there is an error with handling the input files. My files are quite large .tiff images, so I have tried a downsampled version and also exported it as .jpg which reduces the size, but neither seems to work. Here is the error:

ERROR: could not read file, OpenCV(4.4.0) /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-req-build-v0h6zy15/opencv/modules/imgcodecs/src/loadsave.cpp:77: error: (-215:Assertion failed) pixels <= CV_IO_MAX_IMAGE_PIXELS in function 'validateInputImageSize'

Could you please help me resolve this? Thanks!

**Comment by prete** [comment]
Don't know if it's the right fix, but a workaround could be setting the environment variable manually with a really high number before launching cellpose, like
```bash
export CV_IO_MAX_IMAGE_PIXELS=1099511627776
python -m cellpose
```

**Comment by jnmark** [comment]
Thanks so much for the suggestion! I actually already tried that based on
some online workarounds in the OpenCV forum, and I did actually set it to a
super high number, but I still get the same error. :/

**Comment by prete** [comment]
Can you open **_any_** other image using the Cellpose GUI?

I may be worng but if your image is super large (>30M pixles) that would trigger your issue. The environment var `CV_IO_MAX_IMAGE_PIXELS` should be **set to a value higher than the number of pixels in your image but not larger than the max integer your OS supports.** 

If you're on a 32bit system you'll get an error going above ~2147483646 and on a 64bit system the limit should be something like ~9223372036854775806. Exceeding those limits will overflow the var when it's read by OpenCV and get you something that won't work. Additionally, your OS needs to be able to supoprt allocating that much memory to a process.

For further troubleshooting, try triggering the error from OpenCV without using cellpose:
```python
import cv2 
cv2.imread(path_to_your_image)
```
Do you get the same error?

**Comment by carsen-stringer** [comment]
thanks for the help here @prete, going to close this issue for now, but let us know if you're still having issues
