### ISSUE TITLE
cellpose plugin ignores the input layer’s scale metadata of napari

### ISSUE THREAD

**Issue by matfallet** [MouseLand/cellpose#319]
dear all,

When I crop my image on napari (with layers) and launch cellpose plugin, the crop image are not well recognized and finally I have bad dimension :
for layer in viewer.layers:
    layer.data = layer.data[..., 0:500,0:500]  # crop XY

![f9f591579d5a69715c01302cb1b899e12714d094](https://user-images.githubusercontent.com/41480459/130453849-bfb529c9-094e-4181-9382-66c6d8d9da8f.png)

**Comment by carsen-stringer** [comment]
hmm you may want to try to reselect the cropped layer if it's not being found correctly by cellpose? e.g. it seems to be running on something much larger. if you're still having problems can you please open an issue on the cellpose-napari github?
