### ISSUE TITLE
Save as .png from GUI?

### ISSUE THREAD

**Issue by PhilippFW** [MouseLand/cellpose#32]
Hi,

first off: great tool. For someone without knowledge in coding cellpose seems magic. 

Would it be possible to add some save/export options to the GUI? e.g. as PNG? I have struggled with opening the .npy files. I have tried opening xxx_seg.npy in ImagePy and it gives me an error: "ValueError: not enough values to unpack (expected 2, got 0)"

My end goal is to use the cellpose masks for creating ROIs in imagej/fiji

Best,
Philipp

**Comment by carsen-stringer** [comment]
Glad you like the tool! I've added this option to the GUI (see in the File menu). Please `pip install cellpose --upgrade`. I am going to close this issue for now, but please reopen it if this is still an issue.
