### ISSUE TITLE
size problems with segmentation of very different and large cells

### ISSUE THREAD

**Issue by SepidehRezaei** [MouseLand/cellpose#320]
Hello everyone,
I am trying to segment cells from bright field images which are very difficult and unclear. first I tested some cropped tiles of whole images on your cyto2 model, which with some modifications looked quite satisfying:

![image](https://user-images.githubusercontent.com/86788839/130763968-2c86b9b4-def0-4554-8701-ff35b0856156.png)

but while the whole images contain different cellswith different size and orientations the model is not able to segment the whole images:

![image](https://user-images.githubusercontent.com/86788839/130764395-d7b0290b-f260-42d6-ab9f-a28618394ce3.png)
so i tried to train the networks with different approaches, with pretrained parameters of your general model, from scratch and also with your data and my own data together from scratch, but during training from scratch even when I set the cell diameter to 0 while they have different sizes, after starting the training it is written that the diameter is set to 30.0:
![image](https://user-images.githubusercontent.com/86788839/130765154-272f8787-4d35-4b2d-a58a-71759c8f5568.png)
and consequently the prediction results of Q.C process are always showing cells with 30 px diameter:

![image](https://user-images.githubusercontent.com/86788839/130765621-51712824-4d77-4b48-a4bb-0e4e86f686b5.png)
how can I set the parameters to segment the cells with their actual sizes?
BTW, I have tried the flags --diameter 0, --sizeModel, and turnning off --fastMode.

**Comment by SepidehRezaei** [comment]
I have still the problem, anybody any idea?

**Comment by carsen-stringer** [comment]
sorry that was a bug in the writing from the logger, the images were not rescaled. I've fixed the logger message. please let us know if you're still having issues @SepidehRezaei , going to close for now, but I agree with @kevinjohncutler you like want to try the new omnipose algorithm: https://github.com/MouseLand/cellpose/tree/master/omnipose
