### ISSUE TITLE
Save only the outline image

### ISSUE THREAD

**Issue by Erwan67** [MouseLand/cellpose#324]
hi,

I would like to know if is it possible to save only teh ouline image ?

thank you

**Comment by kevinjohncutler** [comment]
Yes, we recently added a --save_outlines flag you can use via CLI, or save_outlines=1 in a Jupyter notebook using the save_masks function.

**Comment by ywtsay** [comment]
> Yes, we recently added a --save_outlines flag you can use via CLI, or save_outlines=1 in a Jupyter notebook using the save_masks function.

hi there:

I'm trying to save predicted outlines image only in Jupiter notebook

io.save_masks(img, masks, flows, '123', save_outlines=1)

and got the follwoing  message

TypeError: save_masks() got an unexpected keyword argument 'save_outlines'


thanks for your help

**Comment by kevinjohncutler** [comment]
> > Yes, we recently added a --save_outlines flag you can use via CLI, or save_outlines=1 in a Jupyter notebook using the save_masks function.
> 
> hi there:
> 
> I'm trying to save predicted outlines image only in Jupiter notebook
> 
> io.save_masks(img, masks, flows, '123', save_outlines=1)
> 
> and got the follwoing message
> 
> TypeError: save_masks() got an unexpected keyword argument 'save_outlines'
> 
> thanks for your help

Do you have the latest version? You'll need to download and install from GitHub directly. We will be releasing a new version that you can install through pip soon.
