### ISSUE TITLE
Trouble installing GUI dependencies with Zsh [SOLVED]

### ISSUE THREAD

**Issue by beowulfey** [MouseLand/cellpose#325]
Hi, I ran into a small problem with install this morning and wanted to mention it in case it helps others. I didn't know this, but [zsh uses square brackets for pattern matching](https://stackoverflow.com/questions/30539798/zsh-no-matches-found-requestssecurity), so installing the gui dependencies with pip doesn't work. It will work if you put the search in quotes though: 
`pip install 'cellpose[gui]'`

The error that zsh throws is vague... it says no matches found, and I didn't immediately realize it was zsh complaining instead of pip. It may be worth throwing the quotes around the command in the Readme, since it should work even when not using zsh. It's really on me though, I guess I need to learn the full power of my own shell...

**Comment by kevinjohncutler** [comment]
Thanks for posting this! We need to add it to the documentation.

**Comment by carsen-stringer** [comment]
thanks! added these instructions to the readme
