### ISSUE TITLE
ConnectionRefusedError when trying to start cellpose_mac from China

### ISSUE THREAD

**Issue by ShingoYasu** [MouseLand/cellpose#327]
Dear Sir,

First of all, thank you for providing such a wonderful program.  

I'm a researcher working in the U.S., and have been successfully using Cellpose during the last few weeks.  Now, since I love your program so much, I have been recommending it to all my previous post-docs, some of who are already back in their home countries.  Some had successfully installed the program and were able to run it, some didn't.  More specifically, the guy in Japan was successfully, but those in China seem to be having trouble in the initial setup.

Here is what they've got.  Somehow, in China, the government bans Chinese people to access the website abroad, and so, they use VPN.  Sure, they can download python, anaconda, and cellpose, and run chmod 777 command without any problem.  But when they try to run cellpose from the command line, it starts to have connection errors, like, 'ConnectionRefusedError [Errno 60]'.  When they tried to do the same without a VPN, it did not change the errors.

More specifically, it is showing Tracebacks (most recent call last):
File "urllib/request.py" in line 1350, in do_open
File "http/client.py", in line 1277, in request
File "http/client.py", in line 1323, in _send_request
File "http/client.py", in line 1272, in endheaders
File "http/client.py", in line 1032, in _send_output
File "http/client.py", in line 1439, in connect
File "http/client.py", in line 944, in connect
File "socket.py" in line 728, in create_connection
File "socket.py" in line 716, in create_connection
ConnectionRefusedError: [Errno 60] Connection refused

and so on and on.
I am guessing these connections are necessary for downloading the "http://www.cellpose.org/models/cyto_0", etc, as I assume from the successful setting-up by the post-docs in the U.S. and in Japan.  It seems that this is an issue with people in China, only.

I was wondering if it is also the case with other people in China, and if so, how we can circumvent this issue.
Thank you very much for your advice.

Shingo.

**Comment by qixinbo** [comment]
They can try to set the VPN to be "global proxy" mode or just make the terminal also in proxy mode manually and explicitly.
If any questions, contact me via "qixinbo at gmail.com".

**Comment by carsen-stringer** [comment]
thanks @qixinbo ! is there a file sharing client that can be accessed without VPN? I could put the models for example in a dropbox folder

**Comment by qixinbo** [comment]
Hello, @carsen-stringer , the dropbox is also banned. Our most frequent used service for file sharing is [Baidu Cloud](https://pan.baidu.com/) (https://pan.baidu.com/). Maybe the question is to give an instruction to tell user how to put the weight files in the right directory after downloading them.

**Comment by carsen-stringer** [comment]
okay good point, I'm going to make a google drive folder and share the instructions so people can VPN just to access them and save them, since I cannot make a baidu account I just realized since I'm not in China

**Comment by carsen-stringer** [comment]
added to the readme these alternate instructions: https://github.com/MouseLand/cellpose#download-of-pretrained-models

**Comment by qixinbo** [comment]
Good README instruction! I have downloaded the google drive file, and re-uploaded it to baidu cloud:
Link：[https://pan.baidu.com/s/1CARpRGCBHIYaz7KeyoX-fg](https://pan.baidu.com/s/1CARpRGCBHIYaz7KeyoX-fg)
Fetch code：pose 
Feel free to distribute this sharing link, and hope it is helpful for the people without VPN.

**Comment by carsen-stringer** [comment]
thanks so much @qixinbo !
