### ISSUE TITLE
cellpose doesn't see gpu

### ISSUE THREAD

**Issue by OmerRonen** [MouseLand/cellpose#328]
Hi, 
I'm trying to use cellpose with my GPU, but for some reason the behavior is buggy:
<img width="553" alt="Screen Shot 2021-09-15 at 13 26 07" src="https://user-images.githubusercontent.com/34376340/133504652-5b7b4488-bb1b-4519-83cd-5576a6552f35.png">

Can you let me know what needs to be done for cellpose to use my pytorch?

Thanks!

**Comment by carsen-stringer** [comment]
can you try setting the GPU with `gpu=True` in the model call?

also are you sure you can create memory on the GPU? e.g. run `x = torch.zeros(100, device=torch.device('cuda'))`
