### ISSUE TITLE
Single dark pixel in some masks

### ISSUE THREAD

**Issue by trasse** [MouseLand/cellpose#33]
Dear All,

for some reason i have sometimes in the mask in some objects single pixel with the value 0.
Did anyone else observe this?

Thanks a lot & Kind regards

Tobias

**Comment by carsen-stringer** [comment]
I've fixed this issue with scipy's binary_fill_holes. Please `pip install cellpose --upgrade`. I am going to close this issue for now, but please reopen it if this is still an issue.
