### ISSUE TITLE
Pre-downloading models and specifying model directory doesn't work (?)

### ISSUE THREAD

**Issue by Prehani** [MouseLand/cellpose#334]
Hi Cellpose team! Thanks again for your continued work supporting Cellpose. 

I am running into some issues trying to run Cellpose on a distributed computing system (HTCondor).

I ran into an issue while attempting to set the local model directory environment variable. Specifically, after setting, it does seem to register and instead tries to and download write to a non-existent home directory (1-disregarding the specific directory set through the environment variable and 2-creating issues for me with SSL security). 

Here's the example: 
If I am on /home/peter, and I run the following commands: 
```
from cellpose import models   
use_GPU = models.use_gpu() 
print('>>> GPU activated? %d'%use_GPU)
```
everything works as expected. Upon checking my .cellpose/models folder, it has not updated since I first ran the script on a fresh conda environment. However, if I attempt to submit this to a distributed computing system, it tries to download to a non existent directory. 

Here's the output from the bash script I'm running with some check points: 

1. Here's my output right when I begin with all details: 
![image](https://user-images.githubusercontent.com/20289373/134416216-e6160a54-5778-4a69-befc-bd1efa934f19.png)
2. Then, after I untar the cellpose models into the .cellpose folder I have this (note cellpose testing is a tarred miniconda environment with only the GPU version of Cellpose installed and then packaged up w/ all relevant dependencies):
![image](https://user-images.githubusercontent.com/20289373/134416453-b466c225-0f39-4f5e-82d1-afdabe693d59.png)
3. So far so good. Then, I run the following small script just to ensure that everything is setting up correctly: 
```
from cellpose import models   
use_GPU = models.use_gpu() 
print('>>> GPU activated? %d'%use_GPU)
```
and I get the following output: 
![image](https://user-images.githubusercontent.com/20289373/134417015-03f72fb0-9b0c-4f9c-8049-44e23d2a1039.png)
which is exactly what I'd expect; however, this only comes after I run the model import script on the submit server prior to actually packing the miniconda environment. Trying to run the script for the first time with just the freshly created environment and without running that sample script causes every instance of cellpose to have to download the models again.
Without running the model first, I get the following: 
![image](https://user-images.githubusercontent.com/20289373/134539189-e2abcbb6-6e7f-47af-9422-3d21139c6060.png)
...and after enabling the unverified context for ssl: 
![image](https://user-images.githubusercontent.com/20289373/134539764-a5d46e1c-7cca-4103-bce7-374114042890.png)
4.Finally, I check the directories one more time: 
![image](https://user-images.githubusercontent.com/20289373/134417157-4fb36408-df84-4446-8865-45403944ed61.png)
5.   However, the log output is being written to a non existent home directory as seen above in the output from 3. I am writing this on 09/22, and all of the models are downloaded into the cellpose directory on 09/21

Cellpose attempts to redownload models to my home directory. I specifically check for what the environment variable is set as, unset it, set it again, and check again. Due to the nature of how this system works, the environment variables don't stay after the job is complete. So, the initial reading is blank for the model location, then I set it and it appears correctly. I also get an SSL error because of a lack of certificate when it attempts to download. I'm able to get around that with the following: 
```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context 
```
however, this is far from optimal. 

The main question that now arises is how do I change where cellpose works from? I'd like to have cellpose logs as well as prevent it from downloading arbitrary models to a non-existent directory. I've extracted the same .cellpose directory to the root where the Cellpose script is and set the model path to that directory, neither of which worked. This issue grows with the scale that we are hoping to apply this at, as presently for every instance of cellpose that we'd want to start up, it would download a copy of the models pointlessly every time instead of using the locally cached version. The download also requires that I generate the unverified ssl certificate context as mentioned above as well. 

Am I missing something? 

Thanks again for all you've done, and I'm happy to keep trying some different options to get this working properly. Please let me know if you need anything from me.

**Comment by chrisroat** [comment]
The SSL problem is likely a totally separate issue, unrelated to cellpose and perhaps related to your condor environment.

FWIW, when I've run a container on a cluster, I packaged the models onto my container.  This avoided every machine in my cluster downloading the models simultaneously, which caused the cellpose server to crash.   But this has nothing to do with the ability to customize the directory -- it was true when the directory was hard-coded as well.

One thing to note is that the CELLPOSE_LOCAL_MODELS_PATH  environmental variable is read only at initial import time.  So if you change the environmental variable after you've imported cellpose, you won't be actually changing where cellpose is looking.  Could that be your problem?

**Comment by Prehani** [comment]
I believe the issue was in how I set the directory for the environment variable: https://stackoverflow.com/questions/4774054/reliable-way-for-a-bash-script-to-get-the-full-path-to-itself 
This was super useful in getting that all configured correctly. 
It would be great if there were another environment variable/parameter to change where the logs are stored, would probably be a super similar implementation to how the model environment variable was set up.

**Comment by chrisroat** [comment]
There is an issue for that:
https://github.com/MouseLand/cellpose/issues/295

Typically, logging should be configured by whomever is calling the library, not the library itself.  Python has great logging support, and cellpose should not be setting up logging levels, output locations, etc.

Please close this out if you have solved your issue.

**Comment by Prehani** [comment]
Yup, makes sense. Thanks for your help on this, closing out.
