### ISSUE TITLE
How to fuse the results of 2D models trained on 2D slices of 3D dataset?

### ISSUE THREAD

**Issue by memphizz** [MouseLand/cellpose#336]
Hi,
I have single channel 3D datasets. My understanding is that you can't train cellpose on 3D data. I can train 3 models separately on XY, YZ, XZ slices, but not sure how to fuse the predictions from the three models.

Are there any documentation for this last step?

Thanks!

**Comment by carsen-stringer** [comment]
You want to call this function with your flow predictions and cell probability predictions: https://github.com/MouseLand/cellpose/blob/f28395219168552f7239cc742b12eec36227fe71/cellpose/dynamics.py#L850

They are computed from the XY, YZ, and XZ slice estimates on the following lines in models :(https://github.com/MouseLand/cellpose/blob/f28395219168552f7239cc742b12eec36227fe71/cellpose/models.py#L591)

`dist` is the combination of the predicted cell probabilities, and `dP` is the combination of the flows.

if you write some code to do this we can link to it in the readme/docs for others to use
