### ISSUE TITLE
Incorrect time-lapse segmentation in cellpose (napari bundled version) 

### ISSUE THREAD

**Issue by Hanqi-Lin** [MouseLand/cellpose#338]
Hi!

I’m currently learning on how to use cellpose for time-lapse segmentation. The cellpose I use is the plugin installed on the Napari bundled app.

Cellpose seems to work well on single image of our dataset. However, when I tried it on our time-lapse video, cellpose cannot return a correct mask.

For example, our video has dimension of 20 * 800 * 1280 (z * y * x). Following the cellpose demo video and instruction, when I tried to estimate the cell dimension from the image, error message “tuple index out of range” will pop up. Moreover, when I run the time-lapse segmentation by unchecking “process as 3D” and set the stitching threshold as 0.5, the mask size will be 20 * 800 (y * x) instead of 20 * 800 * 1280 (z * y * x).

I guess this issue is caused by the incorrect dimension mapping but I have no clue how to solve it at the moment.

**Comment by kevinjohncutler** [comment]
Time lapses (for now) are meant to be segmented frame-by-frame, for example by having each time slice as a separate 2D image in a directory. I'm going to be training models to segment volumetric time stacks in the next year, but those will not be out for a while, and likely limited to bacterial microscopy at first (but will allow others to train on their own movies).

**Comment by Hanqi-Lin** [comment]
> Time lapses (for now) are meant to be segmented frame-by-frame, for example by having each time slice as a separate 2D image in a directory. I'm going to be training models to segment volumetric time stacks in the next year, but those will not be out for a while, and likely limited to bacterial microscopy at first (but will allow others to train on their own movies).

Thanks for your reply Kevin! Do you mean I can't directly load the video into Napari for segmentation? But the demo video on youtube suggest that at least it works with multi-channel video. I tried separating the video into image sequence and store them in one directory, but the result was the same. 

Ideally Cellpose should allow me to perform time lapse segmentation (based on IoU stitching), but for singel channel video, the segmentation was done in an instant and return a mask with incorrect dimension (as I mentioned in my previous post)

**Comment by carsen-stringer** [comment]
can you put this issue on the napari github? Yes, with `stitch_threshold` you can use a time-lapse image. You can also run cellpose in a jupyter-notebook with the stitching on
