### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by nmroueh** [MouseLand/cellpose#344]
Hi, 

I am having trouble obtaining an output from Cellpose. After segmenting my images, I am unable to save the masks as PNG or ROI to load in ImageJ. I open my image in Cellpose, segment then type in the Anaconda Prompt the command lines (--save_png) and  (imagej_roi_converter.py) as per https://cellpose.readthedocs.io/en/latest/outputs.html but then nothing happens and I cannot proceed. I know nothing about Python and coding languages, so I would like to know what seems to be the problem? Any help? Please and thank you.

**Comment by giocard** [comment]
The proper platform for questions on how to use the software is the forum at [https://forum.image.sc/tag/cellpose](https://forum.image.sc/tag/cellpose)

**Comment by nmroueh** [comment]
Okay, thank you.
