### ISSUE TITLE
Modifying the Heat-Source

### ISSUE THREAD

**Issue by mrseekdeep** [MouseLand/cellpose#345]
Hi there,
According to CellPose, the cells are initially represented [by](https://youtu.be/4ZZjr6SFBV8?t=1127) a Point which is a "heat-source in the middle" then diffusion is applied.
Can a Line be used as the heat-source instead of a Point? In cases where the object that i want to segment looks like
![image](https://user-images.githubusercontent.com/92168032/136584248-d95a2b74-2324-4119-aaf6-aa3f87b6924f.png)

![image](https://user-images.githubusercontent.com/92168032/136583410-5edd26ff-9765-4bec-9906-bb28b9834a6c.png)

**Comment by kevinjohncutler** [comment]
I've actually been working on essentially that for the last year, and Carsen and I have been incorporating my changes into Cellpose under the '--skel' flag in the last few weeks. We'll post the paper describing the method once it gets up on biorxiv. For now, there is no built-in model using it, but you can train it on your own data. I'd love to see some examples of your data if you want to post them here!

**Comment by mrseekdeep** [comment]
awaiting eagerly for the release, and wishing you good luck
