### ISSUE TITLE
Segmentation artifacts using cytoplasm model

### ISSUE THREAD

**Issue by adrtsc** [MouseLand/cellpose#35]
Hi,
I am using Cellpose to segment the cytoplasm and nuclei of cells. I noticed rare segmentation artifacts that occur when using the cytoplasm model. These artifacts are much smaller than the average cell diameter that I specify and consist of multiple labels. The artifacts look as follows:

![grafik](https://user-images.githubusercontent.com/41194383/77338910-4e209180-6d2b-11ea-9637-acf41aed3e74.png)

![grafik](https://user-images.githubusercontent.com/41194383/77336162-6bebf780-6d27-11ea-9cdd-a1c183e8362b.png)

As far as I can tell they do not occur when using the nuclei model. I am currently circumventig these artifacts by applying a size filter on the output masks of cellpose and then relabeling them.

Edit: After some more testing I also found the same types of artifacts when using the nuclear model

**Comment by carsen-stringer** [comment]
I've removed these artifacts. Please `pip install cellpose --upgrade`. I am going to close this issue for now, but please reopen it if this is still an issue.
