### ISSUE TITLE
Different outcome with CPU or GPU based segmentation

### ISSUE THREAD

**Issue by abhamacher** [MouseLand/cellpose#351]
Hi,

first of all, cellpose is great! Thanks for providing this fantastic algorithm! :-)

And coming to my topic --  I finally managed to get cellpose run with GPU support, but I realized that for some reason the segmentation outcome is different if I use CPU or GPU:

![cellpose-CPU-GPU](https://user-images.githubusercontent.com/61734239/138076977-dd92d83f-84f5-4dcf-b409-46cb8905e2ac.PNG)

Of course any other settings were not changed, only the tick set on or off for "use GPU". That is somehow surprising for me. Does this work as intended? Is there any easy explanation for this?

Thanks a lot,
Anna

**Comment by carsen-stringer** [comment]
we now have two implementations of the flows -> masks computations, one implemented in pytorch for GPU and one implemented in numba for CPU that could be creating the differences. it is unlikely that the output of the network is different itself. thanks for pointing this out, I'm going to label it with the bug tag. we could use the same interp method for both but it would make the CPU version slower

**Comment by kevinjohncutler** [comment]
I think I caught this bug myself in my testing and fixed it.

**Comment by carsen-stringer** [comment]
oh hurray! Anna please try the latest version of cellpose (`pip install git+https://github.com/mouseland/cellpose.git`)

**Comment by abhamacher** [comment]
Thanks for the update. I've tried to test it, but the install of the git version breaks my installation. Starting cellpose moans about:

`ModuleNotFoundError: No module named 'omnipose'`

**Comment by SepidehRezaei** [comment]
Hi,
@kevinjohncutler  Thanks for the upgrade of omnipose, but I also have the same issue, after trying to install the latest cellpose version, with code: pip install git+https://github.com/mouseland/cellpose.git
i when trying the code below to run the omnipose:
 python -m cellpose --dir ~/Test/ --omni --pretrained_model cyto2 --chan 2 --chan2 3 --save_png

it always gives the error of not finding omnipose:

  File "C:\Users\sepideh.rezaei\Anaconda3\envs\cellpose\lib\site-packages\cellpose\transforms.py", line 12, in <module>
    from omnipose import omnipose
ModuleNotFoundError: No module named 'omnipose'

**Comment by SepidehRezaei** [comment]
even trying to run the usuall cellpose in cellpose environment via (python -m cellpose) is now impossible :(

**Comment by yixiizziechen** [comment]
I have the exact same issue with version 1.0.0 (python -m pip install cellpose). I can see the CPU and GPU generated slightly different masks, where some of the data points at the edge of a cell are 0 in CPU and non 0 in GPU version, or the other way around. I suppose this caused the difference in downstream cell count.
@kevinjohncutler Is the bug fixed only in the git version of cellpose? 
Many thanks
Yixi

**Comment by MichaelDoron** [comment]
We observe the same behavior in the latest version, both installed from pip and directly from git. Is there anything we can do to solve this?

**Comment by carsen-stringer** [comment]
the flows for the QC step are computed differently for CPU and GPU for speed, they will always be slightly different
