### ISSUE TITLE
Diameter value used for training cyto2 model

### ISSUE THREAD

**Issue by abailoni** [MouseLand/cellpose#352]
Hello,

Was the `cyto2` model trained with cells resized to an average diameter of 30 (similarly to the `cyto` model)?

In that case, then this [line 287](https://github.com/MouseLand/cellpose/blob/e85a78585bd180e98229a1f692b864d37764d5a0/cellpose/__main__.py#L287) should be updated, because now `smean=17` is set when finetuning a `cyto2` model.

Best,
Alberto

**Comment by carsen-stringer** [comment]
thanks for catching this! this is now fixed
