### ISSUE TITLE
New parameters

### ISSUE THREAD

**Issue by AmeliaCulpP1819** [MouseLand/cellpose#353]
Hi there! I noticed recently that some of the cellpose modules were reconfigured with different parameters than the original flow threshold and cell probability threshold. It sounds like cell threshold and boundary threshold have replaced cell probability threshold--is this correct? I noticed that in core.py (285, 286) the defaults set to 2.0 for cell threshold and 0.5 for boundary threshold, but I'm wondering what the viable ranges for these parameters are? Also, which aspects of masking are they controlling? And how do they relate to model match and cell prob threshold in the GUI?
Thanks

**Comment by AmeliaCulpP1819** [comment]
Marius said this was the place to open this issue. Please let me know if you can shed some light on this!

**Comment by carsen-stringer** [comment]
we've reverted back to the original formatting sorry for the confusion, please use `flow_threshold` and `cellprob_threshold`. `mask_threshold` is equivalent to `cellprob_threshold` now

**Comment by carsen-stringer** [comment]
in the GUI model match threshold is inversely related to `flow_threshold`, you can see the `flow_threshold` values in the terminal as you move that scroll bar
