### ISSUE TITLE
cell outlines as coordinates (GeoJSON)

### ISSUE THREAD

**Issue by cornhundred** [MouseLand/cellpose#354]
Hi, is it possible to export cell segmentation results as coordinates in Cellpose - I did not see this as an output in the documentation? If not, is there a recommended way of doing this?

**Comment by carsen-stringer** [comment]
The `--save_outlines` option saves the coordinates of the outlines to a txt file, that may be what you're looking for.

going to close this issue for now, let me know if you're having problems

**Comment by cornhundred** [comment]
Thanks!
