### ISSUE TITLE
Segmentation Fault while trying to run from command line

### ISSUE THREAD

**Issue by asanjana** [MouseLand/cellpose#357]
I am trying to install and run cellpose on a community cluster of my university. The cluster has pre-installed anaconda with python 3.8. I have followed the local installation guideline described on the Github page.  The installation process does not encounter any errors. I do not want to run the GUI, rather I want to run cellpose on a directory of .jpg images (each of dimension 1384*1036). So, I tried the following commands:

module load anaconda/2020.11-py38
conda create --name cellpose python=3.8
conda activate cellpose
python -m pip install cellpose

python -m cellpose --dir my_absolute_dir_path --pretrained_model nuclei --chan 1 --chan2 1 --diameter 0. --save_png

The previous command starts running like the following...
2021-10-28 19:25:27,908 [INFO] WRITING LOG OUTPUT TO /home/user1/.cellpose/run.log
2021-10-28 19:25:27,945 [INFO] >>>> using CPU
2021-10-28 19:25:27,950 [INFO] >>>> running cellpose on 32 images using chan_to_seg RED and chan (opt) RED
2021-10-28 19:25:27,951 [INFO] >>>> using CPU
2021-10-28 19:25:28,033 [INFO] >>>> estimating diameter for each image
2021-10-28 19:25:28,035 [INFO] 0%|          | 0/32 [00:00<?, ?it/s]
2021-10-28 19:25:28,069 [INFO] ~~~ ESTIMATING CELL DIAMETER(S) ~~~

Then most cases it terminates with Segmentation Fault.

I got it to run only once, where it showed the following run-time warnings and took a lot of time to compute cell diameter and mask for 1 image... Also --save_png did not save the outlines as text file for ImageJ!!

/home/user1/.conda/envs/cent7/2020.11-py38/cellpose/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3419: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/user1/.conda/envs/cent7/2020.11-py38/cellpose/lib/python3.8/site-packages/numpy/core/_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
2021-10-28 19:33:32,337 [INFO] estimated cell diameter(s) in 484.27 sec
2021-10-28 19:33:32,337 [INFO] >>> diameter(s) = 
2021-10-28 19:33:32,338 [INFO] [ 17.00 ]
2021-10-28 19:33:32,338 [INFO] ~~~ FINDING MASKS ~~~

What could be the possible reason for Segmentation Fault? Why could be the process so slow?

**Comment by carsen-stringer** [comment]
I've seen segmentation faults occur when numpy or numba is installed incorrectly. Can you try using our `environment.yml` in the github repo to create the environment? e.g.

```
conda env create -f environment.yml
conda activate cellpose
```

I would guess these libraries did not install correctly so things ran extra-slow. Things will also be slower if you don't have a GPU. To use a GPU, you can use the google colab notebooks linked.

To save outlines, please use `--save_outlines`

Going to close this issue for now, please let us know if you're still having problems
