### ISSUE TITLE
Issues launching cellpose - "GUI FAILED"

### ISSUE THREAD

**Issue by g1-yi** [MouseLand/cellpose#364]
I've been trying to install/run Cellpose in Windows 10 using Anaconda. Every time i try to launch cellpose, I get the following error: 

  (cellpose) C:\WINDOWS\system32>python -m cellpose
  2021-11-08 14:44:42,086 [INFO] WRITING LOG OUTPUT TO C:\Users\User\.cellpose\run.log
  2021-11-08 14:44:42,255 [CRITICAL] ERROR: No module named 'omnipose'
  2021-11-08 14:44:42,256 [CRITICAL] GUI FAILED: GUI dependencies may not be installed, to install, run
  2021-11-08 14:44:42,257 [CRITICAL]      pip install cellpose[gui]

I'm running on conda 4.10.3 & Python v 3.8.12 & followed instructions for the GPU ver. I've already tried manually installing cellpose[gui] & pip install PyQt5, but I still get this message. 

Does anyone have any advice? Is it possible there are other GUI dependencies that I haven't installed yet (as a novice Python user)?

**Comment by AlineRangolO** [comment]
I'm having the same problem

**Comment by carsen-stringer** [comment]
sorry can you please try updating to the latest version?

**Comment by AlineRangolO** [comment]
I removed the cellpose and installed the new one version. Still getting the same error...

**Comment by AlineRangolO** [comment]
Thanks! It works

**Comment by g1-yi** [comment]
Thank you all!! Beyond excited to get started with CellPose, now that I got it to open! :)
