### ISSUE TITLE
Running Cellpose in Mac 10.11.6: Symbol not found: _clock_gettime

### ISSUE THREAD

**Issue by tamaldas1982** [MouseLand/cellpose#37]
I'm getting the following error while trying to run the Cellpose in my Macbook Pro:
ImportError: dlopen(/opt/anaconda3/lib/python3.7/site-packages/cv2/cv2.cpython-37m-darwin.so, 2): Symbol not found: _clock_gettime
  Referenced from: /opt/anaconda3/lib/python3.7/site-packages/cv2/.dylibs/libavutil.56.31.100.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /opt/anaconda3/lib/python3.7/site-packages/cv2/.dylibs/libavutil.56.31.100.dylib

I have an El Capitan 10.11.6. Is there any way to get rid of this problem?

**Comment by carsen-stringer** [comment]
Maybe try downgrading opencv-python? (the package name for `cv2`)
```
pip install opencv-python==3.4.5.20
```
(recommendation from [here](https://stackoverflow.com/questions/48717726/python3-opencv-install-error-symbol-not-found-clock-gettime))
