### ISSUE TITLE
--save_outlines not working after upgrading cellpose

### ISSUE THREAD

**Issue by asanjana** [MouseLand/cellpose#372]
Previously, --save_outlines flag in the command-line argument used to save a txt file of outlines readable in ImageJ. After upgrading cellpose --save_outlines flag does not work that way, rather saves a png file of the outline. How to get the outlines' txt file?

The upgraded version of cellpose also doesn't run with --cellprob_threshold parameter and --no_npy flag does not suppress the generation of npy file.

**Comment by kevinjohncutler** [comment]
Sorry for changing that on you! Use `--save_txt` to save those ImageJ outlines. We aslo changed `cellprob_threshold` to `mask_threshold`. I need to check out the `--no_npy` though.

**Comment by kevinjohncutler** [comment]
Ah yeah, I might have toggled the default value a long time ago and forgot since I never use the npy files. Fixed now, thanks!
