### ISSUE TITLE
Flow Error Calculation in Post Processing

### ISSUE THREAD

**Issue by jun2tong** [MouseLand/cellpose#377]
Looking through the code, I have a question regarding this one line in `dynamics.py`

https://github.com/MouseLand/cellpose/blob/7d13ddd671b2099fa22a62c5a882175871634ae0/cellpose/dynamics.py#L892

The `remove_bad_flow_masks` function is always called with `omni=False` even with Omni model. Wouldn't this affect the error calculation for Omni model since the flow is defined differently between Omnipose and CellPose model?

Please take a look. @kevinjohncutler 

P.S. This is more of a question or bug report.

**Comment by kevinjohncutler** [comment]
Great catch! I had the flow threshold turned off in all my testing and I forgot to pass that through, even though I put it into the `remove_bad_flow_masks` function haha. I'll push that change shortly. Thanks @jun2tong!
