### ISSUE TITLE
Analysing images in sub-folders

### ISSUE THREAD

**Issue by Dobrokhotov1989** [MouseLand/cellpose#382]
I have my images organized in sub-folders. In the case of running cellpose via command line, is there any way to pass just a parent folder path instead of re-writing command for each sub-folder?

**Comment by kevinjohncutler** [comment]
I don't think we have this functionality built-in, but it would not be very hard to do and I personally see this being useful. Many of the functions we need for it are already implemented in cellpose, just not for CLI.
