### ISSUE TITLE
Retrained models not appearing as model being used? 

### ISSUE THREAD

**Issue by Prehani** [MouseLand/cellpose#383]
I may be doing something incorrectly, but I'm not getting any .npy files when I retrain existing models. I get the weight output, and it states it's trained and saves, but I can't load that in as a model. 

Here is the sample command I use (trained from scratch): 
`C:\Users\peter>python -m cellpose --train --dir C:\Users\peter\Documents\cellpose_training_data\  --img_filter _img --mask_filter _masks --use_gpu`

And for existing models: 
` C:\Users\peter>python -m cellpose --train --dir C:\Users\peter\Documents\cellpose_training_data\  --img_filter _img --mask_filter _masks  --pretrained_model cyto2 --use_gpu`

A models folder is created, but I'm only getting the intermediate weights (no npy files).

**Comment by Prehani** [comment]
Here is the output after training completes: 

`

2021-11-24 20:54:41,142 [INFO] saving network parameters to C:\Users\peter\Documents\cellpose_training_data\models/cellpose_residual_on_style_on_concatenation_off_cellpose_training_data_2021_11_24_19_51_01.134965
2021-11-24 20:54:41,211 [INFO] >>>> model trained and saved to C:\Users\peter\Documents\cellpose_training_data\models/cellpose_residual_on_style_on_concatenation_off_cellpose_training_data_2021_11_24_19_51_01.134965
`

**Comment by Prehani** [comment]
Missed the `--train_size` flag in the documentation. I think the documentation for training might be a bit all over the place--it would be great to have a fully worked example with all relevant flags explained in the context of the command. Happy to submit what I'm referencing as a PR at some point!

**Comment by Prehani** [comment]
After getting a .npy output from the retraining, it doesn't appear to be recognized...
I created a naive model from scratch called `naive` and added it to the Cellpose model directory, then spun up a new model:
`curr_model = models.Cellpose(gpu=True, model_type='naive')`
However, I get this output: 
`2021-11-24 23:11:54,273 [INFO] ** TORCH CUDA version installed and working. **
2021-11-24 23:11:54,274 [INFO] >>>> using GPU
2021-11-24 23:11:54,275 [INFO] >>cyto<< model set to be used
2021-11-24 23:11:54,337 [INFO] ~~~ ESTIMATING CELL DIAMETER(S) ~~~` 
Am I missing something on the model set to be used?

**Comment by mpl24** [comment]
Hi @Prehani did you ever figure out how to run your newly trained model? I saved it as a .npy file and want to use it to segment my cell images now and am having similar issues to you.
