### ISSUE TITLE
No npy files stored

### ISSUE THREAD

**Issue by gabrielpan147** [MouseLand/cellpose#384]
Hello, 

I just updated  and started to use omnipose today. I want to save npy files but I found  it showed "Running without saving any output" and don't save any npy files. I didn't use --no_npys flag. Are there any solutions for this issue?

Thanks in advance!

**Comment by gabrielpan147** [comment]
Ah I just found I need to use --no_npys flag to enable storing npy file... It's a little bit weird but it works

**Comment by gabrielpan147** [comment]
But I think it should be fixed for being easily mosunderstood..

**Comment by kevinjohncutler** [comment]
@gabrielpan147 what version are you using? I believe I fixed this after issue #372 was posted.

**Comment by gabrielpan147** [comment]
@kevinjohncutler Hello, I just upgraded cellpose using pip upgrade command when I posted this issue. It should be the newest version but when I checked the local source code, the parameter is not changed. I should try to upgrade it again. Thank you!

**Comment by sipie800** [comment]
use -no_npys to save npy,that's very weird.
