### ISSUE TITLE
Installation of github version

### ISSUE THREAD

**Issue by AlMenuet** [MouseLand/cellpose#388]
Hello
When installing github version in anaconda with this line : pip install git+https://www.github.com/mouseland/cellpose.git
it says :

ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://www.github.com/mouseland/cellpose.git 'C:\Users\REVOLUTION - K30\AppData\Local\Temp\pip-req-build-0j3ox5i0'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

Do you have any idea where to find it ? thank you

**Comment by SepidehRezaei** [comment]
Hi, it seems that you do not have installed git in your conda environment,
first try the command:

conda install git

then :

pip install git+https://www.github.com/mouseland/cellpose.git
