### ISSUE TITLE
masks_to_flows bottleneck for large images

### ISSUE THREAD

**Issue by eburling** [MouseLand/cellpose#39]
Hello, cellpose devs.

Thank you for your work on this project. I'm always happy to add a new cell segmentation method to the toolbox, since no one method/configuration ever seems to suffice for associated tissues with heterogeneous cell populations.

We'll be covering your pre-print in our lab's journal club this week, so I've been going over the code base and trying out a few things with some of the large format images that we're used to dealing with, i.e. whole slide images of IF-stained biopsy tissue. 

Naturally, I expected the processing of images that are at least 10K x 10K pix in size to take a long time relative to the examples, but I figured I'd take a look around to see which steps are the most demanding in time.

After a bit of print/tqdm exploration, I identified the `masks_to_flows` function as a potential bottleneck for processing large images, since `masks_to_flows` iterates over `nmasks` without parallelization. For a 14K x 9K pix image where cellpose has detected ~10,000 cells/masks, the estimated runtime of the `for k in range(nmask):` loop is around 4 hours. 

I see extensive use of numba/jit in the cellpose codebase, so I'm wondering if there is a roadmap for parallelization in cellpose?

I noticed one impediment to the use of numba with `masks_to_flows` being that the numba implementation of `np.unique` does not support `return_inverse` or `return_counts`, which `masks_to_flows` depends on. As such, I drafted a new numba implementation for `np.unique` which can be used to `@overload` the default definition:
```
@overload(np.unique)
def np_unique(ar, return_inverse=False, return_counts=False):
    def np_unique_impl(ar, return_inverse=False, return_counts=False):
        
        ar = ar.ravel()
        
        if return_inverse:
            perm = ar.argsort(kind='quicksort')
            aux = ar[perm]
        else:
            aux = np.sort(ar)
        
        mask = np.empty(aux.shape, dtype=np.bool_)
        mask[:1] = True
        mask[1:] = aux[1:] != aux[:-1]

        ret = [aux[mask]]

        if return_inverse:
            imask = np.cumsum(mask) - 1
            inv_idx = np.empty(mask.shape, dtype=np.intp)
            inv_idx[perm] = imask
            ret += [inv_idx]
            
        if return_counts:
            idx = np.concatenate(np.nonzero(mask))
            idx = np.append(idx,mask.size)
            ret += [np.diff(idx)]

        return ret
    return np_unique_impl
```
There is also the issue of 2D-slice value assignments, which I don't believe numba (0.46.0) supports, which means that assignments like this:
```
mu_c[y-1,x-1] = np.exp(-d2/s2)
```
must become something like this:
```
tmp = np.exp(-d2/s2)
for i in range(y.shape[0]):
    mu_c[y[i]-1,x[i]-1] = tmp[i]
```

I'm still testing to see whether my numba-ingestable re-factor/implementation of `masks_to_flows` and its dependencies makes any substantial improvements in time. It may not. Like I said, numba is new to me, but if I can get it sorted out, would you be interested in a pull request for this work?

Again, thanks for your effort on cellpose. We're excited to integrate it into our work.

All the best,

Erik

**Comment by carsen-stringer** [comment]
Thanks for your input and pull request suggestion. I think running the network (on the CPU) is the largest bottleneck in the code right now, but we'd be happy to make `masks_to_flows` faster too if you find a way and make a pull request. In the pipeline it's used for quality control to throw out bad masks, so we can also allow the user to turn it off (I will add in this option).

**Comment by carsen-stringer** [comment]
I made this function much faster by acting only on the slices containing each mask
