### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by mrseekdeep** [MouseLand/cellpose#391]
@kevinjohncutler hello

- is there any conference or explanatory video coming for the latest paper
- any updates regarding the omnipose lic, because currently it too strict that it's hard to contribute in developing and improving.

**Comment by kevinjohncutler** [comment]
@mrseekdeep sorry for the late reply. We did make a twitter thread here https://twitter.com/KevinJohnCutler/status/1459714695686864900 with some explanatory figures. The Omnipose license will probably stay as-is, though if there are significant changes to make to it in the near future by non-authors we will probably want to reconsider.
