### ISSUE TITLE
ValueError: labels not provided with correct --mask_filter

### ISSUE THREAD

**Issue by r-matsuzaka** [MouseLand/cellpose#396]
I got the writtn error in the title when I run following.
What could be the problem?

`python -m cellpose --train --dir ./cell/train/ --img_filter _image.tiff --mask_filter _mask.tiff --test_dir ./cell/test --pretrained_model None --n_epochs 500 --chan 2 --chan2 1 --learning_rate 0.2 --use_gpu`

file name is like this;

- brabra_masks.tiff
- brabra_image.tiff

**Comment by r-matsuzaka** [comment]
Maybe I find the reason...

**Comment by LSilvagnoli** [comment]
Hello,

can you let us know how u resolve this ?

Thanks.

**Comment by r-matsuzaka** [comment]
Hello,

In my case, .tiff is the problem.
If you use this extension, try .tif.
Actually both data is same...
That's it.

You can easily find the reason if you read the code.


BTW, I use this repo for ongoing kaggle competition. But I have another issue for inference.
Do you use this for research?

**Comment by LSilvagnoli** [comment]
Yeah understand this aswell after reading the code.

i'm using it for research purpose yes.
