### ISSUE TITLE
Target

### ISSUE THREAD

**Issue by jaideep11061982** [MouseLand/cellpose#398]
Hi @imagejan 
how should we set the target.. what they are like .. i have instance based RLEs, so how should the target look like

**Comment by imagejan** [comment]
@jaideep11061982 I'm not sure why you tagged me here. I didn't contribute to the cellpose source and am not affiliated with the authors. Maybe your question is suitable for the image.sc forum? https://forum.image.sc/tag/cellpose

**Comment by jaideep11061982** [comment]
@carsen-stringer could u help in above..

**Comment by carsen-stringer** [comment]
you can train with all of the channels with the flag `--all_channels`, check out the docs for more details: https://cellpose.readthedocs.io/en/latest/. the masks are all instances of the same class, we do not have support for semantic segmentation
