### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by Mrc010** [MouseLand/cellpose#4]
Hi there,

I have just successfully segmented an image:

```
estimated diameter of cells using cyto model = 58.3 pixels
removed all cells
using model cyto
693 cells found with unet
plane 0 outlines processed
--- 693 ROIs saved chan1 gray, chan2 none
```
But when I try to plot the image with masks overlaid, I get an `IndexError: tuple index out of range`:
![image](https://user-images.githubusercontent.com/40266184/73842831-a3592000-481d-11ea-9d2d-f42825a4026a.png)

**Comment by carsen-stringer** [comment]
Sorry about that, those zero indices shouldn't be there, see the readme for the updated code. Also I've updated the rescaling of those plots, so please
~~~
pip install cellpose --upgrade
~~~

**Comment by Mrc010** [comment]
Thanks! Cellpose helps a lot. Previously, I was using Tissue Analyzer (Fiji Plugin) or Ilastik im combination with extensive manual curation. These times are now fortunately over.

**Comment by Mrc010** [comment]
Hmm, still getting the same error. Will check again tomorrow + run the upgrade again in case I missed your changes.

**Comment by marius10p** [comment]
Is it working now?

**Comment by Mrc010** [comment]
Unfortunately, the problem prevails (cellpose-0.0.1.22). Exact same error message. I tried the same procedure (calibrate, segment, save masks and images) with an image from cellpose.org and obtain the same error when running the cellpose plotting script in a notebook.

**Comment by atreyiChak** [comment]
Hi, I was having the same issue with my images. I wonder whether it is something to do with the way it deals with RGB vs greyscale images. I tried changing the normalisation step in the plot.py masks_overlay function, which finally gave me an output.

![plot_function_edited](https://user-images.githubusercontent.com/45823204/74965116-8707d680-540c-11ea-8bb4-ce8469f15629.PNG)

![corrected_plot_output](https://user-images.githubusercontent.com/45823204/74964832-03e68080-540c-11ea-9069-527becf2e97d.PNG)

**Comment by carsen-stringer** [comment]
I think mask_overlay should work on any image now. Update with `pip install cellpose --upgrade`. 

Here are some examples of plotting ([docs](http://www.cellpose.org/static/docs/outputs.html))
