### ISSUE TITLE
Error displaying results in Jupyter notebook workflow

### ISSUE THREAD

**Issue by PaulineBlz** [MouseLand/cellpose#40]
Hello,

I have tried to run the new script for the notebook but I add an error when displaying the results.
As an input, I put an image 1378*2048 pixels and I set the channel to [0,0].
But I've got an error when I want to plot the results using plot.show_segmentation().
The script part is:
```
from cellpose import plot
print(imgs[1].shape)
nimg = len(imgs)
for idx in range(nimg):
    maski = masks[idx]
    flowi = flows[idx][0]

    fig = plt.figure(figsize=(12,5))
    plot.show_segmentation(fig, imgs[idx], maski, flowi, channels=channels[idx])
    plt.tight_layout()
    plt.show()

```
And the error that pops up is:

> ValueError                                Traceback (most recent call last)
> <ipython-input-70-e73ae139dd79> in <module>
>       9 
>      10     fig = plt.figure(figsize=(12,5))
> ---> 11     plot.show_segmentation(fig, imgs[idx], maski, flowi, channels=channels[idx])
>      12     plt.tight_layout()
>      13     plt.show()
> 
> c:\users\paulinecci\image processing\yuki\cellpose\cellposeenv\lib\site-packages\cellpose\plot.py in show_segmentation(fig, img, maski, flowi, channels, file_name)
>      59     outX, outY = np.nonzero(outlines)
>      60     imgout= img0.copy()
> ---> 61     imgout[outX, outY] = np.array([255,75,75])
>      62     ax.imshow(imgout)
>      63     #for o in outpix:
> 
> ValueError: shape mismatch: value array of shape (3,) could not be broadcast to indexing result of shape (17932,)

I have tried to investigate the issue put did not find a solution yet.
If you have some solution to help me :)

Thank you !

**Comment by carsen-stringer** [comment]
sorry about this! I fixed this now, please `pip install cellpose --upgrade`. I'm closing this issue for now please reopen it if there are still problems

**Comment by PaulineBlz** [comment]
Hello,

It works, thanks you very much for your help !
