### ISSUE TITLE
result type Float can't be cast to the desired output type Long

### ISSUE THREAD

**Issue by LSilvagnoli** [MouseLand/cellpose#401]
Hi,

When i run cellpose with "using GPU" on, i keep get "result type Float can't be cast to the desired output type Long" error message. Correct some lines in dynamics.py doesn't seems to work.

any ideas to correct the issue without generating more errors ?

Thx

**Comment by erjel** [comment]
This looks like a duplicate of #378. A possible workaround can be found [here](https://github.com/MouseLand/cellpose/issues/378#issuecomment-976767543).

**Comment by LSilvagnoli** [comment]
Missed it.

Allowing empty mask during training worked for me

Thx
