### ISSUE TITLE
Omnipose/Cellpose switching requires flows to be deleted (this should be automated)

### ISSUE THREAD

**Issue by trongtuyen99** [MouseLand/cellpose#404]
I want to use cell border as head of model, I used this command to training model:
 ```python -m cellpose --train --dir /content/data_train --test_dir /content/data_train --diameter 20 --nclasses 4 --omni --use_gpu --pretrained_model '' ``` 
and got the error:
```IndexError: index 6 is out of bounds for axis 0 with size 6```
In line 434, file omnipose/core.py
Please help me fix this error. Thanks!

**Comment by kevinjohncutler** [comment]
@trongtuyen99 could you share what dataset you are training on? Even a minimal example of a couple images and masks would help debug.

**Comment by trongtuyen99** [comment]
@kevinjohncutler I used [sartorius cell instance segmentation dataset](https://www.kaggle.com/c/sartorius-cell-instance-segmentation/data?select=train) for training, with gray images (all images and annotations converted to tif in advance). Thanks for your support!

**Comment by kevinjohncutler** [comment]
@trongtuyen99 I see, the images look perfectly fine, though it looks like overlaps need to be handled by manual cropping. Could you provide a couple training annotations that you converted to tifs? I don't happen to have a script to do that from their json format.

**Comment by trongtuyen99** [comment]
@kevinjohncutler You can find annotations from [this link](https://www.kaggle.com/dschettler8845/sartorius-segmentation-train-mask-dataset-npz), I just convert .npz to .tif The annotations is 2D array and has no overlaps (as I know) because each number for one instance only.

**Comment by CozyDoomer** [comment]
@trongtuyen99 this seems to be the same issue as: https://github.com/MouseLand/cellpose/issues/380
fixed in this PR: https://github.com/MouseLand/cellpose/pull/399

I ran into the same Issue and adding the `omni` parameter fixed it.
`use_gpu` and `device` is still missing in the PR and should be added as well

**Comment by kevinjohncutler** [comment]
Ah of course, thanks @CozyDoomer that must be what happened to @trongtuyen99: Cellpose and Omnipose flows are incompatible, and therefore need to be purged if you have already trained Cellpose on the dataset (which I always have done manually when needed). I should put in a check to catch this based on the number of dimensions the flow array has. Alternately, flows could be stored in subfolders such as flows_cellpose and flows_omnipose. @carsen-stringer what do you think?

**Comment by carsen-stringer** [comment]
I think I'd recommend manual deletion, I worry about asking cellpose to delete tiffs
