### ISSUE TITLE
High CPU use and slow execution when importing models on high-core-count server

### ISSUE THREAD

**Issue by alonyan** [MouseLand/cellpose#407]
Hi all and thank you for this fantastic work,

I'm experiencing some very extreme CPU use (see attached) and slow performance (takes 6 seconds, compared to 2 on a standard laptop) when running: 

`from cellpose import models`

This only happens when running on a high-core-count server:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                128
On-line CPU(s) list:   0-127
Thread(s) per core:    1
Core(s) per socket:    64
Socket(s):             2
NUMA node(s):          8
Vendor ID:             AuthenticAMD
CPU family:            25
Model:                 1
Model name:            AMD EPYC 7763 64-Core Processor
Stepping:              1
CPU MHz:               2445.377

When running on standard M1 MacBook air the CPU usage is reasonable and runtime is faster.

<img width="1439" alt="Screen Shot 2021-12-13 at 4 28 31 PM" src="https://user-images.githubusercontent.com/22939455/145892583-e73e6df7-9cef-470d-af21-32e9620f5abb.png">

**Comment by dkurt** [comment]
@alonyan, Hi! If you want, I would like to propose our proposal with Intel OpenVINO backend: https://github.com/MouseLand/cellpose/pull/370. Will be very helpful!

**Comment by alonyan** [comment]
Update: issue caused by loading mxnet model. Solved by removing mxnet-mkl.

**Comment by carsen-stringer** [comment]
thanks for figuring this out and posting the solution @alonyan !
