### ISSUE TITLE
Confusing paragraph in Omnipose README.md 

### ISSUE THREAD

**Issue by CozyDoomer** [MouseLand/cellpose#413]
Pretty sure the following paragraph in the Omnipose readme doesn't make sense: 

`Notably, while we found that Omnipose does not benefit much from more than 500 epochs, Omnipose continues to improve until around 4000 epochs. It outperforms Omnipose at 500, but is significantly better at 4000. You can use --save_every <n> and save_each to store intermediate model traineing states to explore this behavior.`

seems like some of the 'Omnipose' mentions here should be 'Cellpose'.
is: 
`Cellpose does not benefit much from more than 500 epochs, Omnipose continues to improve until around 4000 epochs. It outperforms Cellpose at 500, but is significantly better at 4000`
correct?

**Comment by kevinjohncutler** [comment]
You are right, and there is a typo in there too! Thank you for catching that.
