### ISSUE TITLE
Error using Cellpose Google Colab script

### ISSUE THREAD

**Issue by dkopinke** [MouseLand/cellpose#417]
Happy New Year everyone! We have been using the Cellpose Google Colab script for almost a year now and it works great. However, we now ran into an issue during the install (see below). It would be awesome if someone has any suggestions/tips on how to fix this. Thanks, Daniel

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-8508001bb501> in <module>()
      9 
     10 from urllib.parse import urlparse
---> 11 from cellpose import models, core
     12 
     13 use_GPU = core.use_gpu()

5 frames
/usr/local/lib/python3.7/dist-packages/cv2/__init__.py in <module>()
      7 
      8 from .cv2 import *
----> 9 from .cv2 import _registerMatType
     10 from . import mat_wrapper
     11 from . import gapi

ImportError: cannot import name '_registerMatType' from 'cv2.cv2' (/usr/local/lib/python3.7/dist-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by abhayr5566** [comment]
I've got the same issue

**Comment by dkopinke** [comment]
I think I figured it out. A newer version of open cv got installed, which was incompatible. Just running this command line right before "!pip install Cellpose" will resolve the issue!

!pip install "opencv-python-headless<4.3"

Cheers, Daniel

**Comment by carsen-stringer** [comment]
thanks for catching this and discovering the solution, the main cellpose colab notebook is fixed
