### ISSUE TITLE
ERROR: GUI version is not installed

### ISSUE THREAD

**Issue by Tom-Didom** [MouseLand/cellpose#42]
Hi,

I freshly installed Anaconda with Python 3.7 to use cellpose on Win 10 and followed the instructions.
However, when I try to run cellpose I get:

ERROR: GUI version is not installed, to install, run
     pip install cellpose[gui]

This appears both with the simple installation as well as with the environment file. When I check the packages in cellpose, gui.py seems to be there. I'm not an experienced python user and don't know what to do. It would be great, if I could get some advice.

Best, Tom

**Comment by marius10p** [comment]
Did you run ``pip install cellpose[gui]``?

**Comment by Tom-Didom** [comment]
*Yes. I initally tried that and it didn't work (among some warning for
spyder).*

*Then I tried to do it in the environment:*

(base) C:\Users\tgolde\Cellpose>conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda



Downloading and Extracting Packages
imageio-2.8.0        | 3.0 MB    |
############################################################################
| 100%
certifi-2020.4.5.1   | 156 KB    |
############################################################################
| 100%
mkl_random-1.0.2     | 272 KB    |
############################################################################
| 100%
intel-openmp-2019.4  | 1.4 MB    |
############################################################################
| 100%
setuptools-46.1.3    | 528 KB    |
############################################################################
| 100%
decorator-4.4.2      | 14 KB     |
############################################################################
| 100%
scipy-1.2.1          | 11.0 MB   |
############################################################################
| 100%
mkl-2019.3           | 99.1 MB   |
############################################################################
| 100%
tornado-6.0.4        | 604 KB    |
############################################################################
| 100%
numpy-base-1.16.4    | 3.3 MB    |
############################################################################
| 100%
python-3.7.0         | 16.6 MB   |
############################################################################
| 100%
dask-core-2.14.0     | 571 KB    |
############################################################################
| 100%
numpy-1.16.4         | 48 KB     |
############################################################################
| 100%
mkl_fft-1.0.12       | 118 KB    |
############################################################################
| 100%
openssl-1.1.1f       | 4.8 MB    |
############################################################################
| 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Ran pip subprocess with arguments:
['C:\\Users\\tgolde\\Anaconda3\\envs\\cellpose\\python.exe', '-m', 'pip',
'install', '-U', '-r',
'C:\\Users\\tgolde\\Cellpose\\condaenv.sv43puhv.requirements.txt']
Pip subprocess output:
Collecting mxnet-mkl
  Using cached mxnet_mkl-1.5.0-py2.py3-none-win_amd64.whl (54.8 MB)
Collecting opencv_python
  Using cached opencv_python-4.2.0.34-cp37-cp37m-win_amd64.whl (33.0 MB)
Processing
c:\users\tgolde\appdata\local\pip\cache\wheels\3f\e4\8d\8599d71cbae4524a96a756da5cae31f59db9523a307876c951\pyqtgraph-0.10.0-py3-none-any.whl
Collecting natsort
  Using cached natsort-7.0.1-py3-none-any.whl (33 kB)
Collecting google-cloud-storage
  Using cached google_cloud_storage-1.27.0-py2.py3-none-any.whl (79 kB)
Collecting tqdm
  Downloading tqdm-4.45.0-py2.py3-none-any.whl (60 kB)
Collecting requests<2.19.0,>=2.18.4
  Using cached requests-2.18.4-py2.py3-none-any.whl (88 kB)
Requirement already satisfied, skipping upgrade: numpy<1.17.0,>=1.8.2 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
mxnet-mkl->-r C:\Users\tgolde\Cellpose\condaenv.sv43puhv.requirements.txt
(line 1)) (1.16.4)
Collecting graphviz<0.9.0,>=0.8.1
  Using cached graphviz-0.8.4-py2.py3-none-any.whl (16 kB)
Collecting google-auth<2.0dev,>=1.11.0
  Using cached google_auth-1.13.1-py2.py3-none-any.whl (87 kB)
Collecting google-cloud-core<2.0dev,>=1.2.0
  Using cached google_cloud_core-1.3.0-py2.py3-none-any.whl (26 kB)
Collecting google-resumable-media<0.6dev,>=0.5.0
  Using cached google_resumable_media-0.5.0-py2.py3-none-any.whl (38 kB)
Collecting urllib3<1.23,>=1.21.1
  Using cached urllib3-1.22-py2.py3-none-any.whl (132 kB)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
requests<2.19.0,>=2.18.4->mxnet-mkl->-r
C:\Users\tgolde\Cellpose\condaenv.sv43puhv.requirements.txt (line 1))
(2020.4.5.1)
Collecting idna<2.7,>=2.5
  Using cached idna-2.6-py2.py3-none-any.whl (56 kB)
Collecting chardet<3.1.0,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Requirement already satisfied, skipping upgrade: setuptools>=40.3.0 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
google-auth<2.0dev,>=1.11.0->google-cloud-storage->-r
C:\Users\tgolde\Cellpose\condaenv.sv43puhv.requirements.txt (line 5))
(46.1.3.post20200330)
Collecting rsa<4.1,>=3.1.4
  Using cached rsa-4.0-py2.py3-none-any.whl (38 kB)
Collecting cachetools<5.0,>=2.0.0
  Downloading cachetools-4.1.0-py3-none-any.whl (10 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Requirement already satisfied, skipping upgrade: six>=1.9.0 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
google-auth<2.0dev,>=1.11.0->google-cloud-storage->-r
C:\Users\tgolde\Cellpose\condaenv.sv43puhv.requirements.txt (line 5))
(1.14.0)
Collecting google-api-core<2.0.0dev,>=1.16.0
  Using cached google_api_core-1.16.0-py2.py3-none-any.whl (70 kB)
Collecting pyasn1>=0.1.3
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting pytz
  Downloading pytz-2019.3-py2.py3-none-any.whl (509 kB)
Collecting protobuf>=3.4.0
  Using cached protobuf-3.11.3-cp37-cp37m-win_amd64.whl (1.0 MB)
Processing
c:\users\tgolde\appdata\local\pip\cache\wheels\4c\a1\71\5e427276ceeff277fd76878d1b19fbf4587a2845015d86864b\googleapis_common_protos-1.51.0-py3-none-any.whl
Installing collected packages: urllib3, idna, chardet, requests, graphviz,
mxnet-mkl, opencv-python, pyqtgraph, natsort, pyasn1, rsa, cachetools,
pyasn1-modules, google-auth, pytz, protobuf, googleapis-common-protos,
google-api-core, google-cloud-core, google-resumable-media,
google-cloud-storage, tqdm
Successfully installed cachetools-4.1.0 chardet-3.0.4
google-api-core-1.16.0 google-auth-1.13.1 google-cloud-core-1.3.0
google-cloud-storage-1.27.0 google-resumable-media-0.5.0
googleapis-common-protos-1.51.0 graphviz-0.8.4 idna-2.6 mxnet-mkl-1.5.0
natsort-7.0.1 opencv-python-4.2.0.34 protobuf-3.11.3 pyasn1-0.4.8
pyasn1-modules-0.2.8 pyqtgraph-0.10.0 pytz-2019.3 requests-2.18.4 rsa-4.0
tqdm-4.45.0 urllib3-1.22

#
# To activate this environment, use
#
#     $ conda activate cellpose
#
# To deactivate an active environment, use
#
#     $ conda deactivate


(base) C:\Users\tgolde\Cellpose>conda activate cellpose

(cellpose) C:\Users\tgolde\Cellpose>python -m cellpose
ERROR: GUI version is not installed, to install, run
     pip install cellpose[gui]

*And I tried to use intsall cellpose here as well:*

(cellpose) C:\Users\tgolde\Cellpose>pip install cellpose[gui]
Requirement already satisfied: cellpose[gui] in
c:\users\tgolde\appdata\roaming\python\python37\site-packages (0.0.1.25)
Requirement already satisfied: matplotlib in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
cellpose[gui]) (3.1.3)
Requirement already satisfied: Pillow<=7.0.0 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
cellpose[gui]) (7.0.0)
Requirement already satisfied: numpy in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
cellpose[gui]) (1.16.4)
Requirement already satisfied: opencv-python in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
cellpose[gui]) (4.2.0.34)
Requirement already satisfied: numba in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
cellpose[gui]) (0.48.0)
Requirement already satisfied: mxnet-mkl in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
cellpose[gui]) (1.5.0)
Requirement already satisfied: scikit-image in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
cellpose[gui]) (0.16.2)
Requirement already satisfied: tqdm in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
cellpose[gui]) (4.45.0)
Requirement already satisfied: scipy in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
cellpose[gui]) (1.2.1)
Requirement already satisfied: natsort in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
cellpose[gui]) (7.0.1)
Requirement already satisfied: PyQt5; extra == "gui" in
c:\users\tgolde\appdata\roaming\python\python37\site-packages (from
cellpose[gui]) (5.14.2)
Requirement already satisfied: google-cloud-storage; extra == "gui" in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
cellpose[gui]) (1.27.0)
Requirement already satisfied: pyqtgraph; extra == "gui" in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
cellpose[gui]) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
matplotlib->cellpose[gui]) (2.4.6)
Requirement already satisfied: kiwisolver>=1.0.1 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
matplotlib->cellpose[gui]) (1.1.0)
Requirement already satisfied: cycler>=0.10 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
matplotlib->cellpose[gui]) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
matplotlib->cellpose[gui]) (2.8.1)
Requirement already satisfied: llvmlite<0.32.0,>=0.31.0dev0 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
numba->cellpose[gui]) (0.31.0)
Requirement already satisfied: setuptools in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
numba->cellpose[gui]) (46.1.3.post20200330)
Requirement already satisfied: graphviz<0.9.0,>=0.8.1 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
mxnet-mkl->cellpose[gui]) (0.8.4)
Requirement already satisfied: requests<2.19.0,>=2.18.4 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
mxnet-mkl->cellpose[gui]) (2.18.4)
Requirement already satisfied: imageio>=2.3.0 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
scikit-image->cellpose[gui]) (2.8.0)
Requirement already satisfied: networkx>=2.0 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
scikit-image->cellpose[gui]) (2.4)
Requirement already satisfied: PyWavelets>=0.4.0 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
scikit-image->cellpose[gui]) (1.1.1)
Collecting PyQt5-sip<13,>=12.7
  Using cached PyQt5_sip-12.7.2-cp37-cp37m-win_amd64.whl (58 kB)
Requirement already satisfied: google-auth<2.0dev,>=1.11.0 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
google-cloud-storage; extra == "gui"->cellpose[gui]) (1.13.1)
Requirement already satisfied: google-cloud-core<2.0dev,>=1.2.0 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
google-cloud-storage; extra == "gui"->cellpose[gui]) (1.3.0)
Requirement already satisfied: google-resumable-media<0.6dev,>=0.5.0 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
google-cloud-storage; extra == "gui"->cellpose[gui]) (0.5.0)
Requirement already satisfied: six in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
cycler>=0.10->matplotlib->cellpose[gui]) (1.14.0)
Requirement already satisfied: idna<2.7,>=2.5 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
requests<2.19.0,>=2.18.4->mxnet-mkl->cellpose[gui]) (2.6)
Requirement already satisfied: certifi>=2017.4.17 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
requests<2.19.0,>=2.18.4->mxnet-mkl->cellpose[gui]) (2020.4.5.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
requests<2.19.0,>=2.18.4->mxnet-mkl->cellpose[gui]) (3.0.4)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
requests<2.19.0,>=2.18.4->mxnet-mkl->cellpose[gui]) (1.22)
Requirement already satisfied: decorator>=4.3.0 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
networkx>=2.0->scikit-image->cellpose[gui]) (4.4.2)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
google-auth<2.0dev,>=1.11.0->google-cloud-storage; extra ==
"gui"->cellpose[gui]) (4.1.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
google-auth<2.0dev,>=1.11.0->google-cloud-storage; extra ==
"gui"->cellpose[gui]) (0.2.8)
Requirement already satisfied: rsa<4.1,>=3.1.4 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
google-auth<2.0dev,>=1.11.0->google-cloud-storage; extra ==
"gui"->cellpose[gui]) (4.0)
Requirement already satisfied: google-api-core<2.0.0dev,>=1.16.0 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage; extra ==
"gui"->cellpose[gui]) (1.16.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.11.0->google-cloud-storage;
extra == "gui"->cellpose[gui]) (0.4.8)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage;
extra == "gui"->cellpose[gui]) (1.51.0)
Requirement already satisfied: pytz in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage;
extra == "gui"->cellpose[gui]) (2019.3)
Requirement already satisfied: protobuf>=3.4.0 in
c:\users\tgolde\anaconda3\envs\cellpose\lib\site-packages (from
google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage;
extra == "gui"->cellpose[gui]) (3.11.3)
Installing collected packages: PyQt5-sip
Successfully installed PyQt5-sip-12.7.2

*It didn't help:*

(cellpose) C:\Users\tgolde\Cellpose>python -m cellpose
ERROR: GUI version is not installed, to install, run
     pip install cellpose[gui]

Am Mi., 8. Apr. 2020 um 18:40 Uhr schrieb Marius Pachitariu <
notifications@github.com>:

**Comment by carsen-stringer** [comment]
I'm sorry I hid the error message from you, you may be running into one of the issues outlined in the readme. please `pip install cellpose --upgrade` and then when you run `python -m cellpose` you should see what the error is. You can also check if the pipeline itself works by running `python -m cellpose --dir images/` where your images are in a directory `images`.

**Comment by Tom-Didom** [comment]
Yes, that helped. I got:
`ERROR: No module named 'PyQt5.sip'`
I solved this error according to the readme by 
`pip uninstall pyqt5 pyqt5-tools
pip install pyqt5 pyqt5-tools pyqt5.sip`

Thank you very much! Looking forward to explore cellpose!
