### ISSUE TITLE
Question about min_size

### ISSUE THREAD

**Issue by GFleishman** [MouseLand/cellpose#423]
Hello Cellpose team,

As always, thank you for developing and maintaining such a crucial tool.

How exactly does min_size work in a do_3d=True context?
The average size of my cells is larger than 20x20x20 = 8000 voxels in 3D. I get some splits and fragments in my output. There are over 150K cells in the whole volume and the percentage of fragments is low, but I still need to get rid of them. I tried setting min_size=2000, but the output was totally blank - i.e. no cells were found at all.

That made me wonder, is min_size applied at the 2D stage somehow? Or am I misunderstanding something about how it's used?

Thanks in advance!

**Comment by carsen-stringer** [comment]
it is applied in the 3D case if `do_3d=True` and `stitch_threshold=0`, but if you're using stitch_threshold then it will be applied for each plane instead
