### ISSUE TITLE
GUI error on OS high Sierra 10.13.6

### ISSUE THREAD

**Issue by EdoDImp** [MouseLand/cellpose#43]
Hi, I am having troubles to run Cellpose from GUI. 

Installing it in base environment didn't work so I went for the installation in a new environment after cloning the package

eddimpri@sbmm299  /Applications/cellpose $ > `conda env create -f environment.yml`
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages
matplotlib-base-3.1. | 4.9 MB    | ########################################################################################################################## | 100% 
tornado-6.0.4        | 597 KB    | ########################################################################################################################## | 100% 
blas-1.0             | 45 KB     | ########################################################################################################################## | 100% 
scikit-image-0.16.2  | 22.5 MB   | ########################################################################################################################## | 100% 
pyparsing-2.4.6      | 64 KB     | ########################################################################################################################## | 100% 
olefile-0.46         | 49 KB     | ########################################################################################################################## | 100% 
readline-7.0         | 316 KB    | ########################################################################################################################## | 100% 
pip-20.0.2           | 1.7 MB    | ########################################################################################################################## | 100% 
certifi-2020.4.5.1   | 155 KB    | ########################################################################################################################## | 100% 
intel-openmp-2019.4  | 887 KB    | ########################################################################################################################## | 100% 
python-dateutil-2.8. | 224 KB    | ########################################################################################################################## | 100% 
tbb-2020.0           | 150 KB    | ########################################################################################################################## | 100% 
pywavelets-1.1.1     | 3.4 MB    | ########################################################################################################################## | 100% 
jpeg-9b              | 201 KB    | ########################################################################################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Ran pip subprocess with arguments:
['/Users/eddimpri/anaconda/envs/cellpose/bin/python', '-m', 'pip', 'install', '-U', '-r', '/Applications/cellpose/condaenv.h0nv61qp.requirements.txt']
Pip subprocess output:
Collecting mxnet-mkl
  Downloading mxnet_mkl-1.5.1.post0-cp37-cp37m-macosx_10_11_x86_64.whl (46.4 MB)
Collecting opencv_python
  Downloading opencv_python-4.2.0.34-cp37-cp37m-macosx_10_9_x86_64.whl (49.1 MB)
Collecting pyqtgraph
  Using cached pyqtgraph-0.10.0.tar.gz (1.5 MB)
Collecting natsort
  Using cached natsort-7.0.1-py3-none-any.whl (33 kB)
Collecting google-cloud-storage
  Using cached google_cloud_storage-1.27.0-py2.py3-none-any.whl (79 kB)
Collecting tqdm
  Using cached tqdm-4.45.0-py2.py3-none-any.whl (60 kB)
Collecting graphviz<0.9.0,>=0.8.1
  Using cached graphviz-0.8.4-py2.py3-none-any.whl (16 kB)
Requirement already satisfied, skipping upgrade: numpy<2.0.0,>1.16.0 in /Users/eddimpri/anaconda/envs/cellpose/lib/python3.7/site-packages (from mxnet-mkl->-r /Applications/cellpose/condaenv.h0nv61qp.requirements.txt (line 1)) (1.18.1)
Collecting requests<3,>=2.20.0
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting google-resumable-media<0.6dev,>=0.5.0
  Using cached google_resumable_media-0.5.0-py2.py3-none-any.whl (38 kB)
Collecting google-auth<2.0dev,>=1.11.0
  Using cached google_auth-1.13.1-py2.py3-none-any.whl (87 kB)
Collecting google-cloud-core<2.0dev,>=1.2.0
  Using cached google_cloud_core-1.3.0-py2.py3-none-any.whl (26 kB)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /Users/eddimpri/anaconda/envs/cellpose/lib/python3.7/site-packages (from requests<3,>=2.20.0->mxnet-mkl->-r /Applications/cellpose/condaenv.h0nv61qp.requirements.txt (line 1)) (2020.4.5.1)
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.8-py2.py3-none-any.whl (125 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.9-py2.py3-none-any.whl (58 kB)
Requirement already satisfied, skipping upgrade: six in /Users/eddimpri/anaconda/envs/cellpose/lib/python3.7/site-packages (from google-resumable-media<0.6dev,>=0.5.0->google-cloud-storage->-r /Applications/cellpose/condaenv.h0nv61qp.requirements.txt (line 5)) (1.14.0)
Collecting rsa<4.1,>=3.1.4
  Using cached rsa-4.0-py2.py3-none-any.whl (38 kB)
Collecting cachetools<5.0,>=2.0.0
  Using cached cachetools-4.1.0-py3-none-any.whl (10 kB)
Requirement already satisfied, skipping upgrade: setuptools>=40.3.0 in /Users/eddimpri/anaconda/envs/cellpose/lib/python3.7/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage->-r /Applications/cellpose/condaenv.h0nv61qp.requirements.txt (line 5)) (46.1.3.post20200330)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting google-api-core<2.0.0dev,>=1.16.0
  Using cached google_api_core-1.16.0-py2.py3-none-any.whl (70 kB)
Collecting pyasn1>=0.1.3
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting pytz
  Downloading pytz-2019.3-py2.py3-none-any.whl (509 kB)
Collecting protobuf>=3.4.0
  Downloading protobuf-3.11.3-cp37-cp37m-macosx_10_9_x86_64.whl (1.3 MB)
Collecting googleapis-common-protos<2.0dev,>=1.6.0
  Using cached googleapis-common-protos-1.51.0.tar.gz (35 kB)
Building wheels for collected packages: pyqtgraph, googleapis-common-protos
  Building wheel for pyqtgraph (setup.py): started
  Building wheel for pyqtgraph (setup.py): finished with status 'done'
  Created wheel for pyqtgraph: filename=pyqtgraph-0.10.0-py3-none-any.whl size=735679 sha256=3816cf1662502af8036cb63e0d71663befc2f4cbbf617c83b83eaf8aa58f0fe4
  Stored in directory: /Users/eddimpri/Library/Caches/pip/wheels/3f/e4/8d/8599d71cbae4524a96a756da5cae31f59db9523a307876c951
  Building wheel for googleapis-common-protos (setup.py): started
  Building wheel for googleapis-common-protos (setup.py): finished with status 'done'
  Created wheel for googleapis-common-protos: filename=googleapis_common_protos-1.51.0-py3-none-any.whl size=77592 sha256=b98671a622731e7ad0e30f3f5ffc26cf4d1fbf134079ae5416d8554c88845a88
  Stored in directory: /Users/eddimpri/Library/Caches/pip/wheels/4c/a1/71/5e427276ceeff277fd76878d1b19fbf4587a2845015d86864b
Successfully built pyqtgraph googleapis-common-protos
Installing collected packages: graphviz, chardet, urllib3, idna, requests, mxnet-mkl, opencv-python, pyqtgraph, natsort, google-resumable-media, pyasn1, rsa, cachetools, pyasn1-modules, google-auth, pytz, protobuf, googleapis-common-protos, google-api-core, google-cloud-core, google-cloud-storage, tqdm
Successfully installed cachetools-4.1.0 chardet-3.0.4 google-api-core-1.16.0 google-auth-1.13.1 google-cloud-core-1.3.0 google-cloud-storage-1.27.0 google-resumable-media-0.5.0 googleapis-common-protos-1.51.0 graphviz-0.8.4 idna-2.9 mxnet-mkl-1.5.1.post0 natsort-7.0.1 opencv-python-4.2.0.34 protobuf-3.11.3 pyasn1-0.4.8 pyasn1-modules-0.2.8 pyqtgraph-0.10.0 pytz-2019.3 requests-2.23.0 rsa-4.0 tqdm-4.45.0 urllib3-1.25.8 

I also managed to activate the environment 

(base) eddimpri@sbmm299  /Applications/cellpose $ > `conda activate cellpose`
(cellpose) eddimpri@sbmm299  /Applications/cellpose $ > python -m cellpose
Fontconfig warning: ignoring UTF-8: not a valid region tag
objc[16928]: Class RunLoopModeTracker is implemented in both /Users/eddimpri/anaconda/envs/cellpose/lib/python3.7/site-packages/cv2/.dylibs/QtCore (0x116a8a7f0) and /Users/eddimpri/anaconda/envs/cellpose/lib/libQt5Core.5.dylib (0x1a2b2efa80). One of the two will be used. Which one is undefined.
Downloading: "http://www.cellpose.org/models/cyto_0" to /Users/eddimpri/.cellpose/models/cyto_0
100%|████████████████████████████████████████████████████████████████████████████| 25.2M/25.2M [00:04<00:00, 6.60MB/s]
Downloading: "http://www.cellpose.org/models/cyto_1" to /Users/eddimpri/.cellpose/models/cyto_1
100%|████████████████████████████████████████████████████████████████████████████████████████████| 25.2M/25.2M [00:04<00:00, 5.30MB/s]
Downloading: "http://www.cellpose.org/models/cyto_2" to /Users/eddimpri/.cellpose/models/cyto_2
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25.2M/25.2M [00:03<00:00, 6.68MB/s]
Downloading: "http://www.cellpose.org/models/cyto_3" to /Users/eddimpri/.cellpose/models/cyto_3
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25.2M/25.2M [00:03<00:00, 6.80MB/s]
Downloading: "http://www.cellpose.org/models/size_cyto_0.npy" to /Users/eddimpri/.cellpose/models/size_cyto_0.npy
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.55k/3.55k [00:00<00:00, 8.17MB/s]
Downloading: "http://www.cellpose.org/models/nuclei_0" to /Users/eddimpri/.cellpose/models/nuclei_0
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25.2M/25.2M [00:03<00:00, 6.80MB/s]
Downloading: "http://www.cellpose.org/models/nuclei_1" to /Users/eddimpri/.cellpose/models/nuclei_1
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25.2M/25.2M [00:03<00:00, 6.88MB/s]
Downloading: "http://www.cellpose.org/models/nuclei_2" to /Users/eddimpri/.cellpose/models/nuclei_2
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25.2M/25.2M [00:03<00:00, 6.81MB/s]
Downloading: "http://www.cellpose.org/models/nuclei_3" to /Users/eddimpri/.cellpose/models/nuclei_3
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25.2M/25.2M [00:03<00:00, 6.83MB/s]
Downloading: "http://www.cellpose.org/models/size_nuclei_0.npy" to /Users/eddimpri/.cellpose/models/size_nuclei_0.npy
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.55k/3.55k [00:00<00:00, 8.67MB/s]

however there seem to be an issue with Qt because we I run 
`python -m cellpose` it returns

objc[16948]: Class RunLoopModeTracker is implemented in both /Users/eddimpri/anaconda/envs/cellpose/lib/python3.7/site-packages/cv2/.dylibs/QtCore (0x1a204d07f0) and /Users/eddimpri/anaconda/envs/cellpose/lib/libQt5Core.5.dylib (0x1a28f84a80). One of the two will be used. Which one is undefined. 

I see that there is a redundancy of Qt that messes up the GUI (it appears blank)

Could you please help me to fix this?

I am running on a macbook pro 2015; OS 10.13.6

**Comment by carsen-stringer** [comment]
This is one of the common install issues (I've recently added the fix to the readme, will add to the docs). You need to downgrade cv2 and then they won't conflict:
~~~~
pip install opencv-python==3.4.5.20
~~~~

**Comment by EdoDImp** [comment]
Thank you for the prompt reply and sorry for missing the cv2 issue in readme.  

I downgraded cv to `3.4.5.20` within cellpose env and the GUI seems working although in the terminal I still see warnings 

objc[17321]: Class QNSOpenSavePanelDelegate is implemented in both /Users/eddimpri/anaconda/envs/cellpose/lib/python3.7/site-packages/cv2/.dylibs/QtGui (0x119fda120) and /Users/eddimpri/anaconda/envs/cellpose/plugins/platforms/libqcocoa.dylib (0x1a3905b940). One of the two will be used. Which one is undefined.

**Comment by carsen-stringer** [comment]
no worries, because this is a mac-specific problem we haven't changed the dependency, I'm going to close this issue but comment if you're still having problems

**Comment by EdoDImp** [comment]
Just a short update: I had the same issue on a new laptop running Catalina 10.15.3. `pip install opencv-python==3.4.5.20` again solved the problem.

**Comment by pablooriol2** [comment]
Hi,

As soon as I press on 'Calibrate' or 'Run Segmentation' the software crashes and I get the following error.

```
OMP: Error #15: Initializing libiomp5.dylib, but found libomp.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
```

Has anyone got any idea how to deal with this??
