### ISSUE TITLE
Labels of U2OS cells and NIH3T3 

### ISSUE THREAD

**Issue by EdwardZhao1991** [MouseLand/cellpose#431]
Dear Cellpose,

Thanks for sharing the great work.

I have trouble converting the `xcf` annotations to `npy` format. Would it be possible for you to share the annotations of the following dataset that you used?

> We also used the image set from ISBI 2009, which consists of 97 fluorescent images of U2OS cells and NIH3T3 cells [52].

**Comment by carsen-stringer** [comment]
we do not have the rights to share the labels publicly but I can share them via email

**Comment by CalvinYang** [comment]
@carsen-stringer could you please kindly share the labels of U2OS cells and NIH3T3 to me? I also need them to train the model. Thanks a lot. 
717103445@qq.com is my email.

Jerry
