### ISSUE TITLE
LLVM ERROR: Symbol not found: __svml_sqrt4_ha

### ISSUE THREAD

**Issue by LiekevanRoon** [MouseLand/cellpose#432]
I installed anaconda and tried to follow the instructions, but when is try to use the python -m cellpose command it gives the following error:

LLVM ERROR: Symbol not found: __svml_sqrt4_ha

What can I do to fix this?

**Comment by carsen-stringer** [comment]
is there anything else with the error message? can you see if it's your pytorch install that's the problem? open python on the command line with `python`, then write `import torch` and see if you get the error. if that's the problem then I'd recommend installing pytorch with anaconda

**Comment by ved-sharma** [comment]
Hi @carsen-stringer, I am also getting the same error. pytorch looks fine. here is the screenshot...

![cellpose_Screenshot](https://user-images.githubusercontent.com/39934015/154508039-7259c149-c90c-470e-be83-981448f7eee5.png)
e

**Comment by carsen-stringer** [comment]
Hmm perhaps it's numba: https://github.com/numba/numba/issues/6012

It looks like on windows numba version 0.49 does not have this bug so you could try installing that version, you perhaps also want to install numba with conda

**Comment by ved-sharma** [comment]
Magic!!! 
Thank you so much for pointing me in this direction. It worked!
For people struggling with this issue, all I did was to roll back my numba in the cellpose environment by running
>conda install numba=0.49
