### ISSUE TITLE
Image upload not working correctly

### ISSUE THREAD

**Issue by AnnaVCB** [MouseLand/cellpose#433]
Hi, I just updated cellpose to the newest version and I cannot drop in the images from folders as I was able before - the cursor changes to the black crossed circle. 
In additon when I load the images via Ctrl+L, the phase image displayed is distorted (the bridgtness/contrast for each pixel line seems to be adjusted individually, please see attached image).  

Any ideas what is wrong and how to fix this? 

Thanks! 

![image](https://user-images.githubusercontent.com/89843923/151810786-dc538650-7405-40ec-98a4-7d92bcddd4d2.png)

**Comment by AnnaVCB** [comment]
UPDATE: the drag and drop was fixed with reinstalling Anaconda navigator. 
The image display issue was not solved by that, or by creating new environment and installing Cellpose from the beginning. 
How do install an older version of Cellpose?

**Comment by carsen-stringer** [comment]
sorry for the trouble I think this is fixed, please try the latest github version, `pip install git+https://github.com/mouseland/cellpose.git`. if not I'll reopen the issue

**Comment by DrTK** [comment]
Just tried it out: The stripes are gone, and nucleus segmentation seems to work again as expected.
Thank you so much!!!
