### ISSUE TITLE
Omnipose error: Omnipose not running

### ISSUE THREAD

**Issue by lacan** [MouseLand/cellpose#435]
Referencing this PR here as well
There is an error in the logger code that makes python crash here
https://github.com/MouseLand/cellpose/pull/434/files#diff-b58d8d01b3d308c1c513773b6c90ef942d2495462adbfa7b1b78d7aea6d15df1

**Comment by lacan** [comment]
Hi @carsen-stringer, Just letting you know that this is a rather critical issue as V1.0 basically won't run with Omnipose

**Comment by carsen-stringer** [comment]
sorry this is fixed in the github version and there will be a new release soon
