### ISSUE TITLE
Requirements issue

### ISSUE THREAD

**Issue by FiReTiTi** [MouseLand/cellpose#436]
Hi,
I'm trying to install cellpose along with other libraries.
When I look at cellpose [requirements](https://github.com/MouseLand/cellpose/blob/master/requirements.txt), I can see that cellpose requires _numpy~=1.19.3_.
But when I try to install it using pip, I get the following error:

    ERROR: Cannot install XXX and XXX ==5.3.1 because these package versions have conflicting dependencies.
    The conflict is caused by:
        XXX 5.3.1 depends on numpy<1.20 and >=1.19.3
        cellpose 1.0.0 depends on numpy>=1.20.0

So it seems that during the installation, cellpose requires _numpy>=1.20_, but it does not match what is in the requirements.
Does it come from a dependency?
How can I fix it?

**Comment by saskra** [comment]
These requirements are obsolete and should be removed. (The file is from one of my pull requests.) The environment.yml file, on the other hand, should be up to date.

**Comment by FiReTiTi** [comment]
Ok, thank you.
But yet, they're still there when installing using pip.

**Comment by saskra** [comment]
With "these requirements are obsolete" I meant only the requirements.txt file, which should not play a role with the pip package. There only the environment.yml should be relevant, which apparently requires a newer numpy version than the other package you want to install at the same time. So it's not straightforward to install these two packages together. But there is probably nothing the Cellpose authors can do about that. (Just my humble opinion, I'm just a user.) At most, you could install an older version of Cellpose that still works with an older numpy version.

**Comment by FiReTiTi** [comment]
> With "these requirements are obsolete" I meant only the requirements.txt file, which should not play a role with the pip package. There only the environment.yml should be relevant, which apparently requires a newer numpy version than the other package you want to install at the same time. So it's not straightforward to install these two packages together. But there is probably nothing the Cellpose authors can do about that. (Just my humble opinion, I'm just a user.) At most, you could install an older version of Cellpose that still works with an older numpy version.

Ok... maybe I'm confused.
When I create my own PyPi packages, the Requirements.txt file is automatically generated based on the setup.py file I created, so I expected it to be the same here.

**Comment by saskra** [comment]
That seems to be different here. The requirements.txt was generated by my Pycharm IDE. The current setup.py also says numpy>=1.20.0 
https://github.com/MouseLand/cellpose/blob/6d7a3f692206bf791e3ea7bd9524ee6df628ed8a/setup.py#L4

**Comment by FiReTiTi** [comment]
Ok, thank you for the information.
Then Requirements.txt should be removed or updated.
