### ISSUE TITLE
Instance nuclei segmentation from semantic segmentation as input?

### ISSUE THREAD

**Issue by athulrv** [MouseLand/cellpose#443]
Does cellpose support just instance segmentation from semantic stack as input? 

Attached is a crop volume of semantic segmentation output with a CNN network. Current cellpose network works poor on the original raw data. But luckily, an inhouse trained network works better on the raw data to generate a semantic segmentation.

I am looking for cellpose to take this semantic segmentation as input and generate an instance 3D segmentation of these 3D nuclei. 

![Screenshot from 2022-02-16 12-29-39](https://user-images.githubusercontent.com/49643312/154256005-2c142c0a-6520-4262-984d-8f5e613ee267.png)

**Comment by kevinjohncutler** [comment]
That's a good idea! Any transformations you can do to make your images to look more like the ones in the Cellpose training set _should_ help. It is not as good as just retraining Cellpose on your own ground truth data, but it is worth a try. You can use the `do_3D` option to perform 3D segmentation on this volume (see the documentation for details, you may have to slice the volume first for Cellpose to read it in as a 2D stack).

**Comment by athulrv** [comment]
Hi @kevinjohncutler the issue i raised here was making use if the pixel prediction values in the input stack for instance segmenting them using cellpose. 

These are already 2D slices. 

Let me explain my workflow: 
I obtain the pixel prediction of nuclei for the raw microscopic images using an inhouse nuclei model. As far as i understand, cellpose doesnt read those pixel predictions as input images and instance segment them. For this reason, i convert those informative images into a less informative RGB image using imageJ. Image/Color/Create composite, then Image/Color/Stack to RGB. I save that image and open it in cellpose such that it read the obtained pixel predictions as a raw image. Further what happends is cellpose repredict the nuclei and instance segment them. This seems to work fine in most of the cases, but I was wondering if cellpose could make use of the more informative pixel prediction image to generate the instance nuclei segmentation. 

Best,
Athul

**Comment by kevinjohncutler** [comment]
@athulrv, yes. If your in-house model produces 2D slices, you can stack them together again to give to cellpose. If your pixel predictions are the same shape as the original dataset you are giving to cellpose, it should work. It doesn't need to be RGB, monochrome images are fine.
