### ISSUE TITLE
Feature request - Define model ouput dir and/or name 

### ISSUE THREAD

**Issue by romainGuiet** [MouseLand/cellpose#444]
Dear @carsen-stringer, 

When training a model, it would be super convenient to be able to define the directory where one wants to save the model.
(If simpler to implement being able to save the name of the model, would be nice too...)

Thank you for your feedback,

Cheers,

Romain

**Comment by kevinjohncutler** [comment]
Great idea. So far I've just used the full directory and manually renamed it, but that sure is cumbersome. A tool to make custom models permanently available by their short names in the GUI would also be handy.

**Comment by carsen-stringer** [comment]
soon cellpose will allow you to the change the name I agree it's useful, but there's always been the option to change the directory where it is saved e.g. `model.train(save_path='path/to/save')`

**Comment by romainGuiet** [comment]
>model.train(save_path='path/to/save')
oh my !!!  I totally missed that in the documentation, I'm sorry for the silly issue 😄

**Comment by romainGuiet** [comment]
might be helpful to add this "save_path" to the cellpose help command though
