### ISSUE TITLE
The abnormal flow when using labelme to prepare dataset (binary classification)

### ISSUE THREAD

**Issue by ChanLoongSheh** [MouseLand/cellpose#446]
Hello, I want to use cellpose in my dataset, so I try to train from scratch. I marked the cells with **_labelme_** because my picture data is too large and it is very difficult to run on the GUI. The JSON file marked by labelme is converted into PNG. The following figure is an example:
![0006_0002_masks](https://user-images.githubusercontent.com/50733791/154895079-2b9ee3ec-31d8-4a9c-acc0-4c2019ecc68d.png)

This mask is 8bit and Indexed Color picture, and if i use it to train, program will report errors about the mismatch of input size and label size(or CUDA error: out of memory casue ), so I transform it to 16bit and GRAY using **_Adobe Photoshop 2020_**.  Then the program will run normally. the transformed picture as shown below:
![0006_0002_masks](https://user-images.githubusercontent.com/50733791/154893788-ec6cead4-b116-4682-bb50-ab3eb38ebd84.png)

However, the calculated flow is like: 
<img width="409" alt="1645420791(1)" src="https://user-images.githubusercontent.com/50733791/154894028-4f9bff53-eabb-494a-848a-82d37c263cbc.png">
Note that only the lower right corner of the picture has a mass of yellow. I try to use that to continue training, however, as a result of segmentation, the cellpose does not draw any outlines. I want to know how can I solve this problem, please take a look @carsen-stringer thanks!

**Comment by ChanLoongSheh** [comment]
well i think something wrong in the value of the pixels in masks. If using the **_photoshop_** to transform the original masks from **_labelme_**, the value of pixels will change, on a mask, pixels are not have the same value.

**Comment by sobek1886** [comment]
Hi, I think I'm having the same problem.

Before encountering Cellpose, I had created binary masks using LabelStudio. Now I'm having trouble using those masks for fine tuning.
When I'm trying to train the model, the flows come out either completely dark or match the mask only partly.

'After I changed the label of masks, it works'
Could you please explain how you did this?
