### ISSUE TITLE
Increasing Cellpose throughput

### ISSUE THREAD

**Issue by VarIr** [MouseLand/cellpose#447]
Dear Cellpose team, thanks for your great tool.

We love the quality of segmentation we obtain by using `Cellpose`. Currently, we are trying to figure out whether we can increase throughput to saturate our GPUs, without having to run multiple instances of Cellpose.

We use roughly the following code:
``` Python
from cellpose import io, models
model = models.Cellpose(gpu=True, model_type='nuclei')
images = [io.imread(x) for x in paths_of_2D_images]
_ = model.eval(images, ..., batch_size=10000)
```

Apparently, the `batch_size` parameter does not change throughput (and for `10000` I'd actually expect OOM errors). If I understand Cellpose' execution flow correctly [e.g., here](https://github.com/MouseLand/cellpose/blob/8a5360a7b7db7472d5dd21bd2cd5d050e421fea5/cellpose/models.py#L570), a batch is processed so that the `model.eval()`  is recursively called and each image in the batch processed individually (`batch_size` variable is not used in the [recursion anchor](https://github.com/MouseLand/cellpose/blob/8a5360a7b7db7472d5dd21bd2cd5d050e421fea5/cellpose/models.py#L614)).

1. Is it possible to perform segmentation on whole minibatches simultaneously, instead of iterating through individual images? If so, this should result in significantly better performance.

2. Orthogonally, in other parts of the code, I believe performance can be improved by simpler means. For example, the [`UnetModel._run_tiled(()`](https://github.com/MouseLand/cellpose/blob/8a5360a7b7db7472d5dd21bd2cd5d050e421fea5/cellpose/core.py#L578)  iterates over tiles of images that are extracted by [fancy indexing](https://numpy.org/doc/stable/user/basics.indexing.html#advanced-indexing) which creates copies of data, instead of views.
The following should result in slightly faster execution and lower memory footprint (`slice` instead of `np.arange`):
``` python
for k in range(niter):
    irange = slice(batch_size*k, batch_size*k+batch_size)
    y0, style = self.network(IMG[irange], return_conv=return_conv)
    y[irange] = y0
```
(I can create a PR for this, if there is interest).

**Comment by kevinjohncutler** [comment]
@VarIr that's great! Have you quantified the performance difference with the simple change (2) that you proposed?

**Comment by VarIr** [comment]
Not yet, this just caught my eye while reading the code. I'll have a closer look and actually implement & benchmark this.

**Comment by VarIr** [comment]
On a closer look `UnetModel.eval()` seems broken. For example, there are undefined variables used [here](https://github.com/MouseLand/cellpose/blob/8a5360a7b7db7472d5dd21bd2cd5d050e421fea5/cellpose/core.py#L253) (channel_axis, z_axis), and [here](https://github.com/MouseLand/cellpose/blob/8a5360a7b7db7472d5dd21bd2cd5d050e421fea5/cellpose/core.py#L319) (nolist). That is, the function raises a NameError. I suppose, vanilla UnetModel is currently used nowhere in cellpose, but only `CellposeModel` which inherits from UnetModel and overrides `eval()`. 

I'm wondering whether `UnetModel.eval()` could be made an abstract function when it's apparently unused?

**Comment by VarIr** [comment]
Imo, the benefit would be reduced maintenance effort in cellpose development. The optimization proposal (2) would be obsolete then. Users will anyway see no difference.
Proposal (1) about segmentation of minibatches is unrelated to that, and I think this is also more important and could give substantial speed-ups.

**Comment by greenmossball** [comment]
I'm experiencing the same issue with the batch size. I have a a GPU with a lot of memory and I would love to load batches rather than going one by one.

**Comment by sophiamaedler** [comment]
Are there any plans to reopen work on this issue?

We are also planning on using cellpose for segmenting large time course datasets (small image tiles but lots of tiles) and have very slow performance since we are not saturating our GPU.

**Comment by sophiamaedler** [comment]
> Dear Cellpose team, thanks for your great tool.
> 
> We love the quality of segmentation we obtain by using `Cellpose`. Currently, we are trying to figure out whether we can increase throughput to saturate our GPUs, without having to run multiple instances of Cellpose.
> 
> We use roughly the following code:
> 
> ```python
> from cellpose import io, models
> model = models.Cellpose(gpu=True, model_type='nuclei')
> images = [io.imread(x) for x in paths_of_2D_images]
> _ = model.eval(images, ..., batch_size=10000)
> ```
> 
> Apparently, the `batch_size` parameter does not change throughput (and for `10000` I'd actually expect OOM errors). If I understand Cellpose' execution flow correctly [e.g., here](https://github.com/MouseLand/cellpose/blob/8a5360a7b7db7472d5dd21bd2cd5d050e421fea5/cellpose/models.py#L570), a batch is processed so that the `model.eval()` is recursively called and each image in the batch processed individually (`batch_size` variable is not used in the [recursion anchor](https://github.com/MouseLand/cellpose/blob/8a5360a7b7db7472d5dd21bd2cd5d050e421fea5/cellpose/models.py#L614)).
> 
> 1. Is it possible to perform segmentation on whole minibatches simultaneously, instead of iterating through individual images? If so, this should result in significantly better performance.
> 2. Orthogonally, in other parts of the code, I believe performance can be improved by simpler means. For example, the [`UnetModel._run_tiled(()`](https://github.com/MouseLand/cellpose/blob/8a5360a7b7db7472d5dd21bd2cd5d050e421fea5/cellpose/core.py#L578)  iterates over tiles of images that are extracted by [fancy indexing](https://numpy.org/doc/stable/user/basics.indexing.html#advanced-indexing) which creates copies of data, instead of views.
>    The following should result in slightly faster execution and lower memory footprint (`slice` instead of `np.arange`):
> 
> ```python
> for k in range(niter):
>     irange = slice(batch_size*k, batch_size*k+batch_size)
>     y0, style = self.network(IMG[irange], return_conv=return_conv)
>     y[irange] = y0
> ```
> 
> (I can create a PR for this, if there is interest).

I quickly tested (2) and it gave me a 5X increase in speed on the same dataset. In case you want help implementing @VarIr I'd be happy to help.

**Comment by carsen-stringer** [comment]
thanks for catching that fix in 2! Would be happy to accept a pull request for it. For number 1 we'll have to think about how best to do this. I agree it would be faster but it would require some refactoring.

**Comment by Nespresso2000** [comment]
Was (1) ever implemented? @carsen-stringer

**Comment by carsen-stringer** [comment]
(1) is now implemented, please input your images with the `z_axis` option to make sure it's activated properly, e.g. a stack of size 15x500x500 would have `z_axis=0`
