### ISSUE TITLE
How to get cp_outlines.txt ?

### ISSUE THREAD

**Issue by quentin67100** [MouseLand/cellpose#448]
I try to install the last version, but when i used the same command as before, i didn't obtain the file cp_outlines.txt. Why? I need it to get the ROI on imagej.
I use the command: 
python -m cellpose --dir ${dir} --pretrained_model cyto --chan 0 --save_tif --diameter 100

**Comment by kevinjohncutler** [comment]
@quentin67100, this is now an option using the flag `--save_txt`.
