### ISSUE TITLE
Desktop Client not starting on MacBook Pro (Mac OS Monterey 12.2.1)

### ISSUE THREAD

**Issue by FridaPallapies** [MouseLand/cellpose#449]
Hello, 

I tried running the desktop client  through the latest version of the executable file on my MacBook Pro (Mac OS Monterey 12.2.1).
Processor: 2,2 GHz 6-Core Intel Core i7
RAM: 16 GB 2400 MHz DDR4

When I tried running the file the terminal gave me the following output:

```
qt.qpa.window: <QNSWindow: 0x7fd8f250aa30; contentView=<QNSView: 0x7fd8f250a770; QCocoaWindow(0x600002f1c0b0, window=QWidgetWindow(0x600003c75500, name="RangeSliderClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
```

Any help resolving this issue would be much appreciated.

Thanks in advance.

**Comment by carsen-stringer** [comment]
the mac executable will only work for older versions of Mac, please install cellpose the traditional way in the readme
