### ISSUE TITLE
Cellpose does not respond in GPU 

### ISSUE THREAD

**Issue by arkansertan** [MouseLand/cellpose#451]
Hi, 
When I use the GPU to work on cellpose,  GUI says that cellpose is not responding. On the other hand, I do not have such a problem when I use CPU 
My computer has 32 gb RAM.

It seems that my torch CUDA works properly.   
Is there anyone how to fix this problem ? 

best
Sertan
![Screenshot 2022-02-22 214101](https://user-images.githubusercontent.com/94022058/155215986-f7ac252e-3b4a-49d9-b906-afeb08ddf9af.jpg)

**Comment by kevinjohncutler** [comment]
How much VRAM does your GPU have, and how large (in MB) are your images? Try turning on 'fast mode' (_not_ average 4 nets) to see if that helps the GUI from hanging.

**Comment by arkansertan** [comment]
Hi  @kevinjohncutler ,
Thank you so much for your response 

VRAM 512 MB 
my images 2-3 mb  and tiff  format 

best
Sertan

**Comment by kevinjohncutler** [comment]
@arkansertan, looks like you should have enough VRAM. What happens if you try an even smaller image? And what is the behavior when segmenting via the jupyter notebook and not the GUI?

**Comment by carsen-stringer** [comment]
my suspicions are that 512 MB is too little (not sure which NVIDIA GPU you have), at least cellpose on my computer uses more than that (at least 1GB). I'd recommend testing in google colab and seeing if you use more memory than that for these images
