### ISSUE TITLE
Is there a way to segment membranes (borders) of the cells? 

### ISSUE THREAD

**Issue by danielavarelat** [MouseLand/cellpose#463]

**Comment by danielavarelat** [comment]
According to channels specification, one should hace either cyto or nuclei, but what if I have a green channel with just membranes? Can that be done with cellpose?

**Comment by kevinjohncutler** [comment]
You could train a model to do this. Feel free to post an example image and the results of the cyto2 model on it. I will be publishing a bacterial fluorescence model soon with both membrane and cytosol fluorescence in the training set. It may not be applicable to your data, but cellpose can definitely be trained to segment those kinds of images.
