### ISSUE TITLE
Allow turning off normalization in CLI

### ISSUE THREAD

**Issue by lacan** [MouseLand/cellpose#466]
Linked to a previous issue, wherere the cellpose team allowed for normalization to be turned off via a notebook, I would like to request that normalization be turned off via the command line call to cellpose with e.g. `--no_norm` so that we may implement our own normalization procedure. 
This is especially important when working with giant slabs of data where the prediction is done tile by tile.

**Comment by carsen-stringer** [comment]
good point @lacan , this is added now to the github version, will make a new pip soon
