### ISSUE TITLE
Contributing manually segmented data doesn't work

### ISSUE THREAD

**Issue by TheUwe** [MouseLand/cellpose#467]
Hello everybody :)
I am using cellpose on the structural channel of vivo calcium imaging data (partly in suite2p). However, it seems cellpose doesn't find a large proportion of cells (probably 30%+ missing). For that reason I manually segmented some FOVs to add them to the training data on the server. Unfortunately, the button to do so is not working (local cellpose installation on win10 from github). Is there another way to contribute manually segmented data? Help is appreciated.

**Comment by carsen-stringer** [comment]
sorry about that, thanks for catching this bug, please `pip install git+https://github.com/mouseland/cellpose.git` to use the send to server button (I'll also update the pip soon), or try retraining cellpose on your own data (just `pip install cellpose --upgrade`)
