### ISSUE TITLE
WinError 10022 

### ISSUE THREAD

**Issue by gabriel5222** [MouseLand/cellpose#47]
Hi
when I run python -m cellpose it return me: 
OSError: [WinError 10022] An invalid argument was supplied.

Apparently the issues is in line 589.

I'm currently using one of the lab computer by remote control from my house, could that be the problem ?

Thank you.

**Comment by carsen-stringer** [comment]
sorry can you post more of the error message here? The GUI should work in remote desktop, did you install the GUI enabled version?
```
pip install cellpose[gui]
```

**Comment by gabriel5222** [comment]
Hi, thank you for your answer, the problem solves itself
Because the previous computer had a malfunction I had to reinstall cellpose on another one, I did exactly the same thing but this time everything work at the first try.

**Comment by carsen-stringer** [comment]
glad it's working now! going to close this issue
