### ISSUE TITLE
no images in --dir folder (Google Colab)

### ISSUE THREAD

**Issue by yuc125** [MouseLand/cellpose#474]
**Why can't cellpose get read images in my good drive folder when I already mount my google drive?**
Here is what comment I put in for google colab.

!python -m cellpose --train --use_gpu --dir ~/content/gdrive/MyDrive/training/cell_line/cell_line_total --pretrained_model ~/content/gdrive/MyDrive/training/weights/cellpose_residual_on_style_on_concatenation_off_CP_2022_02_27_21_40_05.092817 --chan 0 --chan2 0 --n_epochs 200 --learning_rate 0.002 --batch_size 4 --min_train_masks 5

!NEW LOGGING SETUP! To see cellpose progress, set --verbose
No --verbose => no progress or info printed
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/cellpose/__main__.py", line 458, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/cellpose/__main__.py", line 366, in main
    output = io.load_train_test_data(args.dir, test_dir, imf, args.mask_filter, args.unet, args.look_one_level_down)
  File "/usr/local/lib/python3.7/dist-packages/cellpose/io.py", line 170, in load_train_test_data
    image_names = get_image_files(train_dir, mask_filter, image_filter, look_one_level_down)
  File "/usr/local/lib/python3.7/dist-packages/cellpose/io.py", line 129, in get_image_files
    raise ValueError('ERROR: no images in --dir folder')
ValueError: ERROR: no images in --dir folder

**Comment by chenzhao2016** [comment]
hi @yuc125  we encountered the exactly same problem as you have. May I ask how you solved this problem?

**Comment by yuc125** [comment]
I did a stupid mistake. I set my directory as from the current folder "~/" but my folder doesn't locate there.
I hope this help.

**Comment by chenzhao2016** [comment]
> I did a stupid mistake. I set my directory as from the current folder "~/" but my folder doesn't locate there. I hope this help.

Thank you very much!!
