### ISSUE TITLE
Faulty documentation

### ISSUE THREAD

**Issue by FrickTobias** [MouseLand/cellpose#475]
Documentation for CellPose output is not accurate and will fail at numerous points. 

[Non-working code snippet from CellPose docs](https://cellpose.readthedocs.io/en/latest/outputs.html#seg-npy-output)
```
import numpy as np
from cellpose import plot
dat = np.load('_seg.npy', allow_pickle=True).item()

# plot image with masks overlaid
mask_RGB = plot.mask_overlay(dat['img'], dat['masks'],
                        colors=np.array(dat['colors']))

# plot image with outlines overlaid in red
outlines = plot.outlines_list(dat['masks'])
plt.imshow(dat['img'])
for o in outlines:
    plt.plot(o[:,0], o[:,1], color='r')
```

# Solution

Thanks to some previous work in  #288 I was able to write a working example  and suggest changing the docs accordingly, although I have only done minimal testing.

```
#! /usr/bin/python3

import numpy as np
from matplotlib import pyplot as plt
from cellpose import utils

input_file = 'example_seg.npy'
dat = np.load(input_file, allow_pickle=True).item()

# plot image with masks overlaid 
outlines = utils.outlines_list(dat['masks'])

plt.imshow(dat['img'])
for o in outlines:
    plt.plot(o[:,0], o[:,1], color='r')
plt.show()
```

Changes:
 - Added `matplotlib.pyplot` import
 - Changed `plot.outlines_list()` to `utils.outlines_list()`
 - Changed `cellpose.plot` import to `cellpose.utils`
 - Added `plt.show()` to display image as docs indicated
 - Removed `mask_RGB` as it was not used and replaced with a working statement for fetching `outlines` which was used but not defined
 - Added shebang line

# Further issues?

To me this seem like a typical case of large changes to the program without having updated the documentation for a while, so it might be good to check if more docs are out of date.

**Comment by carsen-stringer** [comment]
thanks @FrickTobias ! I think this is fixed now in the latest documentation
