### ISSUE TITLE
Adherent cell

### ISSUE THREAD

**Issue by fanxiaochen456** [MouseLand/cellpose#476]
Hello, may I ask whether cellpose can well divide cytoplasmic boundaries for adherent cells? If the adhesion is too serious, can we only use cellpose to divide the nucleus?

**Comment by fanxiaochen456** [comment]
Or is Cellpose good for segmentation of cell data sets with fixed staining colors?

**Comment by kevinjohncutler** [comment]
@fanxiaochen456 so long as there are visible boundaries, cellpose can be trained to segment such cells. Feel free to post an example image.
