### ISSUE TITLE
Cellpose Trackmate ImageJ ingtegration not working

### ISSUE THREAD

**Issue by Jiraya-Aizen** [MouseLand/cellpose#477]
I have GFP fluorescence cells which are segmenting in the website of cellpose, but does not function when given in the Fiji-TrackMate plugin with cellpose detector. Can someone help me with the issue

**Comment by carsen-stringer** [comment]
sorry I do not know how the TrackMate plugin works, please open an issue in TrackMate, keep in mind you need to set the diameter in Cellpose to the diameter of your cells in pixels
