### ISSUE TITLE
--do_3D and changing threshold from commandline

### ISSUE THREAD

**Issue by EdoDImp** [MouseLand/cellpose#48]
Hi, first of all thanks a lot for releasing this software. It is really working well on some of my difficult fluorescent data.

I noticed that in quite some crowded confocal data the algorithm doesn't manage to recognize single cells: either too many false negatives or it doesn't separate nuclei. From the GUI the 3D analysis works smoothly however I would like to experiment different thresholds from the command line but I can't find `--do_3D` and  `--threshold` flags.

I am running Cellpose with environment file on OSX 10.15.3.

Cheers,

Edoardo

**Comment by carsen-stringer** [comment]
updated pip and readme with this info, going to close this issue, please comment if it's not working
