### ISSUE TITLE
Manual segmentation end up with index error

### ISSUE THREAD

**Issue by i-v-e** [MouseLand/cellpose#480]
Hello! 
I faced strange bug. In a paticular moment I wasn't able to stop outlining a cell. I pressed “enter” to make a “cell” out of this dotted line and then delete it. But I wasn't able to do this either. "Ctrl+z" option led to removing previously outlined cells. Then I decided to save file and get out of the programme.
After reentering cellpose gave this message.

7 (1150, 1150, 3)
Traceback (most recent call last):
  File "cellpose\menus.py", line 21, in <lambda>
  File "cellpose\io.py", line 542, in _load_seg
  File "cellpose\gui.py", line 1168, in draw_masks
IndexError: index 229 is out of bounds for axis 0 with size 229

And all options doesn't work properly (even zoom). Previously outlined cells "partially" disappeared. Partially because they appears after user click on the place where they were outlined.

It took too much time to create this segmentation. So, could you tell me how to fix this problem? And how to safe all segmented cells or at least larger part?

**Comment by i-v-e** [comment]
I got this problem one more time on the other file. This time I was able to screenshot the initial error.
![cellpose_bug2 2](https://user-images.githubusercontent.com/102369144/160304005-8da5667e-6566-4c04-ac32-bae122a12c38.PNG)

**Comment by carsen-stringer** [comment]
sorry I'm not sure what the error is here, but your _seg.npy file may be weirdly formatted now. you can load the masks in python and save them as a tif and then load them back in the gui and try to save them again
```
import numpy as np
from cellpose.io import imsave

dat = np.load('/path/name_seg.npy', allow_pickle=True).item()
imsave('masks.tif', dat['masks'].squeeze())
```

do you have any idea what you did before it stopped working? sorry it's hard to know without running the gui myself.

please also upgrade to the latest version `pip install cellpose --upgrade`

**Comment by carsen-stringer** [comment]
(or upgrade to the latest v1.0 version `pip install cellpose==1.0.2`)
