### ISSUE TITLE
Cellpose not working anymore with CUDA on Windows 10

### ISSUE THREAD

**Issue by koopa31** [MouseLand/cellpose#481]
Hi,
It seems Cellpose is not working anymore with Windows 10. I think it's because CUDA 10 is not compatible with Windows 10 anymore and Cellpose works with CUDA 10 only. I am not sure of this hypothesis. Would you have an explanation?
I haven't been able to use Cellpose for more than one week now.

**Comment by simonlsp** [comment]
The problem results from the update in pytorch channel.
Pytorch's stable version has been updated to 1.11.0, which needs cuda 11.3.
Change the install script could fix this.
```
# Original install script
python -m pip install cellpose
pip uninstall torch
conda install pytorch cudatoolkit=10.2 -c pytorch

# Use this
conda create -n cellpose pytorch=1.8.2 cudatoolkit=10.2 -c pytorch-lts
conda activate cellpose
pip install cellpose
```

**Comment by carsen-stringer** [comment]
thanks @simonlsp let me know if this solution doesn't work, closing the issue and adding to docs
