### ISSUE TITLE
Cant run on GPU

### ISSUE THREAD

**Issue by TiamHeydari** [MouseLand/cellpose#482]
Hi,
When I test the gpu, I get this error:

AttributeError: module 'cellpose.models' has no attribute 'use_gpu'

Would you please help me find out the problem? I am using Linux, cellprofiler plugin. 
Thanks,

**Comment by carsen-stringer** [comment]
sorry please place this issue on the cellprofiler plugin github, you can change the code to `from cellpose.core import use_gpu`
