### ISSUE TITLE
TORCH CUDA version not installed/working.

### ISSUE THREAD

**Issue by lguerard** [MouseLand/cellpose#484]
Hi all,

I installed Cellpose using Anaconda on one of our virtualized Windows machine and got it to work perfectly. I'm now trying to set up GPU support but don't manage.

As our VMs have to have a specific NVIDIA drivers (432.08), I checked [here](https://docs.nvidia.com/deploy/cuda-compatibility/index.html) for compatibility and installed CUDA 10.1 as well as Cellpose. I followed the installation guide from the readme but just changed to `conda install pytorch cudatoolkit=10.1 -c pytorch`. 

Cellpose is still working on CPU despite this. Everytime I start it, it says `TORCH CUDA version not installed/working.`. I googled around and found some threads but nothing worked so far. Any ideas ?

Thank you for your help !

**Comment by chenzhao2016** [comment]
Same question here. Tried conda install pytorch cudatoolkit=10.1 -c pytorch but it didn't work...

**Comment by pr4deepr** [comment]
which GPU do you guys have? 
From my experience, with the NVIDIA RTX 30 and 60 cards, we have to use CUDA 11.3 and PyTorch.
So, I used this:

`conda install pytorch cudatoolkit=11.3 -c pytorch`

Again, this depends on the GPU you have and may not work in all cases..

**Comment by chenzhao2016** [comment]
I have NVIDIA RTX6000.... conda install pytorch cudatoolkit=11.3 -c pytorch still doesn't work for me....

**Comment by pr4deepr** [comment]
Did you try configuring a new cellpose environment? 
When you get to this part for configuring the gpu version: https://github.com/MouseLand/cellpose#gpu-version-cuda-on-windows-or-linux
Run
`pip uninstall torch`
and instead of installing `cudatoolkit10.1,` you run this:
`conda install pytorch cudatoolkit=11.3 -c pytorch`

Does it still work?

**Comment by lguerard** [comment]
> which GPU do you guys have?

On a physical machine with RTX 2080, installing `cudatoolkit11.3` worked fine.

I am now trying to install it on a virtualized environment with VMs sharing resources from a RTX 8000, they have to have an older NVIDIA driver (432.08), I tried installing `cudatoolkit10.1` but didn't get it to work.

**Comment by lguerard** [comment]
This fixed it indeed, just changing `cudatoolkit=10.1` to make it work on our machines.

Thanks a lot ! :)
