### ISSUE TITLE
Omnipose models not available in Cellpose v2.0

### ISSUE THREAD

**Issue by bdiazroh** [MouseLand/cellpose#487]
The latest release Cellpose v2.0 does not have the option to use Omnipose. Will this option be added later, or will Omnipose no longer be a part of Cellpose? 

thanks

**Comment by marius10p** [comment]
Cellpose 2.0 is a new version that is not backwards compatible. We will not add Omnipose to v2.0, because it substantially complicates the codebase and our maintenance tasks. Omnipose will continue to be supported in Cellpose 1.0 and in its own separate repo.
