### ISSUE TITLE
livecell preprocess

### ISSUE THREAD

**Issue by JunMa11** [MouseLand/cellpose#488]
Dear cellpose authors,

Thanks for sharing the awesome cellpose 2.0.

Would it be possible for you to share the code of the following preprocessing for livecell dataset?

> the overlapping pixels were reassigned to the mask with the closest centroid. ROIs with more than 75% of their pixels overlapping with another ROI were removed.

**Comment by carsen-stringer** [comment]
yes, I've added the function here: https://github.com/MouseLand/cellpose/blob/2e05d45fe1658829f164426a43dc4cee378b88f4/paper/2.0/datasets.py#L225
