### ISSUE TITLE
Illegal instruction 4

### ISSUE THREAD

**Issue by qztseng** [MouseLand/cellpose#49]
Hello, 
I have problem to launch cellpose gui with:
`python -m cellpose`
got the "Illegal instruction 4" error 
I tried to uninstalled the mxnet-mkl following the instruction, but the error persisted:
`pip uninstall mxnet-mkl`
`pip uninstall mxnet`
`pip install mxnet==1.4.0`

Conda environment created by the yml file, with python 3.7.5 under osx=10.13.6

Thanks for your help

**Comment by carsen-stringer** [comment]
can you post more of the error please if there is more available?

**Comment by qztseng** [comment]
It turned out that I was working on an (updated?) machine that don't support Intel AVX instruction set while the mxnet packages on pypi was built with AVX. 
So the solution was to build mxnet from source by myself and the problem was solved!

Anyway , thanks for make such great tool available.

**Comment by carsen-stringer** [comment]
glad it's working now! going to close this issue
