### ISSUE TITLE
stitch_threshold in GUI

### ISSUE THREAD

**Issue by saskra** [MouseLand/cellpose#490]
I would like to pass on my self-trained models to cooperation partners who have no programming experience and therefore prefer to use the GUI rather than the command line. Unfortunately I can't find all parameters from the command line in the GUI, especially I miss the option "--stitch_threshold", because my 3D images are strongly anisotropic. Is there anywhere I can set this?

**Comment by carsen-stringer** [comment]
stitch threshold has never been an option in the gui but it's something we can add, I'll add the enhancement flag here

**Comment by carsen-stringer** [comment]
btw I think the CLI error with stitch_threshold is fixed now!

**Comment by saskra** [comment]
> btw I think the CLI error with stitch_threshold is fixed now!

Thank you very much for that! Then I can withdraw my pull request, right?

**Comment by saskra** [comment]
> stitch threshold has never been an option in the gui but it's something we can add, I'll add the enhancement flag here

Is there a rough time estimate of when I could expect to see this enhancement? Then I would know whether I would still have to look for my own alternative solution to tide me over while we wait for the official one.

**Comment by saskra** [comment]
> > btw I think the CLI error with stitch_threshold is fixed now!
> 
> Thank you very much for that! Then I can withdraw my pull request, right?

I rejoiced too soon, it doesn't seem to work after all.

**Comment by carsen-stringer** [comment]
this is implemented now
