### ISSUE TITLE
3D Labelling & Human-in-the-loop Approach

### ISSUE THREAD

**Issue by brendavasquez** [MouseLand/cellpose#491]
Hi, 

I'm excited to try the "human-in-the-loop" approach on my 3D two-photon data. 

I see that the ability to draw a stroke on a cell for each Z-plane it appears in is not available on the 2.0 version. 
I am wondering if it would be okay to use data where some cells have only been labelled in one z-plane (say out of 4 planes) with the human-in-the-loop approach. 

Additionally, when not using the human-in-the-loop approach and training from a pretrained model or from scratch, should most planes a given cell appears in be labelled? Is there a recommended percentage, say, label the cell in at least 50% of z-planes it appears in? 

Thanks!

**Comment by carsen-stringer** [comment]
We need to reimplement the single stroke option in 2.0 for labelling in 3D, this is on the to-do list.

For training in human-in-the-loop, it requires 2D data, not 3D data so please save some of your z-planes (probably decently far apart so there are different samples of cells), label in 2D and then re-train the 2D model. This 2D model then can be run in 3D in the GUI or in a notebook or in the CLI.

Note cellpose in 3D is always using a 2D model but running it on XY, XZ and YZ slices and combining the information.

**Comment by brendavasquez** [comment]
Got it, thank you!
