### ISSUE TITLE
update masks_flows_to_seg to not require diameter input

### ISSUE THREAD

**Issue by superwhat1** [MouseLand/cellpose#492]
I have trained a model using cellpose 2.0 GUI but I am running into errors getting it to run in notebook.
import skimage.io
import time, os, sys
#import matplotlib.pyplot as plt
#import matplotlib as mpl
#%matplotlib inline
#mpl.rcParams['figure.dpi'] = 300
from cellpose import utils, io
from os import listdir
from os.path import isfile, join

imgpath='C:\\Users\\labuser\\Documents\\David\\2p_images\\cleaned\\middle\\'
onlyfilename = [f for f in listdir(imgpath) if isfile(join(imgpath, f))]

files = []
count=0
for f in onlyfilename:
    files.append(imgpath+f)
    data = skimage.io.imread(files[count])
    print(data.shape)
    count+=1
print(files)

from cellpose import models

model_path = "C:\\Users\\labuser\\Documents\\David\\2p_images\\cleaned\\middle\\models\\Xenopus_tectum"
cell_model = models.CellposeModel(gpu=True, pretrained_model=model_path)
#size_model = models.SizeModel(cp_model = "", pretrained_size = model_path)
channels = [0,0]
for file in files:
    img = io.imread(file)
    masks, flows, styles, diams = cell_model.eval(img, channels=[0,0],
                                             cellprob_threshold=0.0, flow_threshold=0.4, resample =False)
    io.masks_flows_to_seg(img, masks, flows, diams, file, channels)
    io.save_masks(img, masks, flows, file, tif=True)

ValueError                                Traceback (most recent call last)
Input In [18], in <cell line: 8>()
      8 for file in files:
      9     img = io.imread(file)
---> 10     masks, flows, styles, diams = cell_model.eval(img, channels=[0,0],
     11                                              cellprob_threshold=0.0, flow_threshold=0.4, resample =False)
     12     io.masks_flows_to_seg(img, masks, flows, diams, file, channels)
     13     io.save_masks(img, masks, flows, file, tif=True)

ValueError: not enough values to unpack (expected 4, got 3)

**Comment by carsen-stringer** [comment]
please try ``masks, flows, styles = cell_model.eval(img, channels=[0,0],
cellprob_threshold=0.0, flow_threshold=0.4, resample =False)``

(the `CellposeModel` `eval` does not return a diameter, only the `Cellpose` class does since it has a size model)

**Comment by superwhat1** [comment]
Thank you for your quick reply.
I have tried that but then I get this:
TypeError                                 Traceback (most recent call last)
Input In [9], in <cell line: 8>()
      9 img = io.imread(file)
     10 masks, flows, styles = cell_model.eval(img, channels=[0,0],
     11                                          cellprob_threshold=0.0, flow_threshold=0.4, resample =False)
---> 12 io.masks_flows_to_seg(img, masks, flows, file, channels)
     13 io.save_masks(img, masks, flows, file, tif=True)

File ~\.conda\envs\cellpose\lib\site-packages\cellpose\io.py:301, in masks_flows_to_seg(images, masks, flows, diams, file_names, channels)
    299     flowi.append(np.concatenate((flows[1], flows[2][np.newaxis,...]), axis=0))
    300 outlines = masks * utils.masks_to_outlines(masks)
--> 301 base = os.path.splitext(file_names)[0]
    302 if masks.ndim==3:
    303     np.save(base+ '_seg.npy',
    304                 {'outlines': outlines.astype(np.uint16) if outlines.max()<2**16-1 else outlines.astype(np.uint32),
    305                     'masks': masks.astype(np.uint16) if outlines.max()<2**16-1 else masks.astype(np.uint32),
   (...)
    310                     'flows': flowi,
    311                     'est_diam': diams})

File ~\.conda\envs\cellpose\lib\ntpath.py:196, in splitext(p)
    195 def splitext(p):
--> 196     p = os.fspath(p)
    197     if isinstance(p, bytes):
    198         return genericpath._splitext(p, b'\\', b'/', b'.')

TypeError: expected str, bytes or os.PathLike object, not list

**Comment by superwhat1** [comment]
The masks_flows_to_seg requires the diams argument. But since cellposemodel doesn't output diams I'm stuck

**Comment by superwhat1** [comment]
> The masks_flows_to_seg requires the diams argument. But since cellposemodel doesn't output diams I'm stuck.
> 
> TypeError Traceback (most recent call last) Input In [10], in <cell line: 8>() 9 img = io.imread(file) 10 masks, flows, styles = cell_model.eval(img, channels=[0,0], 11 cellprob_threshold=0.0, flow_threshold=0.4, resample =False) ---> 12 io.masks_flows_to_seg(images=img, masks=masks, flows=flows, file_names =file, channels=channels) 13 io.save_masks(img, masks, flows, file, tif=True)
> 
> TypeError: masks_flows_to_seg() missing 1 required positional argument: 'diams'

I have input the diams argument manually based on the value from the user-trained model. I don't know if this is the best way to do this though.

**Comment by carsen-stringer** [comment]
thanks I will make that an optional argument from now on

**Comment by carsen-stringer** [comment]
added in new release
