### ISSUE TITLE
Suggested updates to GUI display

### ISSUE THREAD

**Issue by dwakefie** [MouseLand/cellpose#493]
Hello,

The updates for Cellpose 2.0 are really nice and are proving to be very helpful in the diversity of datasets I work with. I have just a couple small suggestions to aid the user experience with the GUI; apologies if these suggestions have already been made.

- Could you make it so that the selected model from the model zoo being applied is indicated?  I.e., have the GUI highlight (or indicate somewhere) the selected model after it is clicked? Perhaps even placing the full model zoo in a single dropdown would prove effective to thus display the single model being applied. 
- Could the number of segmented objects in the current image be displayed somewhere in the GUI?  Would be great to have a quick sense of how changing the model/inputs changes the total count without having to view this number in a terminal output.

Thank you!

**Comment by carsen-stringer** [comment]
good points these are added now!
