### ISSUE TITLE
Internal Sever Error when trying LC1 model from notebook

### ISSUE THREAD

**Issue by mayishazn** [MouseLand/cellpose#497]
I'm trying to run cellpose off a jypyter notebook with one of the newer models. I updated cellpose and changed the model from "cyto" to "LC1" as follows: 
model = models.Cellpose(gpu=False, model_type='LC1') 

It succesfully downloaded from https://www.cellpose.org/models/
but then it gave an HTTPError: HTTP Error 500: INTERNAL SERVER ERROR when trying the following:

Downloading: "https://www.cellpose.org/models/size_lc1torch_0.npy" to C:\Users\mayis\.cellpose\models\size_lc1torch_0.npy

Any help appreciated =) Thanks!

**Comment by carsen-stringer** [comment]
you need to use the class `models.CellposeModel` (the new models do not have size models like `models.Cellpose`), see more details here: https://cellpose.readthedocs.io/en/latest/models.html#other-built-in-models

I will make a new jupyter notebook with an example next week

**Comment by mayishazn** [comment]
Thank you so much!!! Here is what I am currently using in case it is useful to anyone:

`import numpy as np
import time, os, sys
from urllib.parse import urlparse
import skimage.io
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline
mpl.rcParams['figure.dpi'] = 300
from cellpose import utils
from cellpose import plot
from cellpose import models

from urllib.parse import urlparse
from cellpose import models, core
from cellpose.io import logger_setup
logger_setup();

import re

diam = 53
minarea = 100
filetype = '.tif'

folders = 'C:\\Users\\mayis\\Documents\\2DCells\\MDCK nonadhesive substrate\\October 27 2021\\7doWTecadcy5petridrop-4zimages'
folders = 'D:\\Glass032822\\20D Glass_1\\output'
#folders = 'C:\\Users\\mayis\\Documents\\2DCells\\TestKitchen\\testoneimg'

def list_files(dir):
    r = []
    all_data = list()
    for root, dirs, files in os.walk(dir):
        for name in files:
            if name.endswith(filetype):
                r0=os.path.join(root,name)
                r.append(r0)
                all_data.append(skimage.io.imread(r0, as_gray=True))
    return all_data, r

imgs, names = list_files(folders) 
nimg = len(imgs)

#plt.figure(figsize=(12,4))
#for k,img in enumerate(imgs):
#    plt.subplot(len(folders),6,k+1)
#    plt.imshow(img)

# RUN CELLPOSE

from cellpose import models, io


# DEFINE CELLPOSE MODEL
# model_type='cyto' or model_type='nuclei'
#model = models.Cellpose(gpu=False, model_type='cyto')
model = models.CellposeModel(gpu=False, model_type = 'LC1')

# define CHANNELS to run segementation on
# grayscale=0, R=1, G=2, B=3
# channels = [cytoplasm, nucleus]
# if NUCLEUS channel does not exist, set the second channel to 0
# channels = [0,0]
# IF ALL YOUR IMAGES ARE THE SAME TYPE, you can give a list with 2 elements
channels = [0,0] # IF YOU HAVE GRAYSCALE
# channels = [2,3] # IF YOU HAVE G=cytoplasm and B=nucleus
# channels = [2,1] # IF YOU HAVE G=cytoplasm and R=nucleus

# or if you have different types of channels in each image
#channels = [[2,1], [3,0], [1,0]]

# if diameter is set to None, the size of the cells is estimated on a per image basis
# you can set the average cell `diameter` in pixels yourself (recommended) 
# diameter can be a list or a single number for all images
#masks, flows, styles, diams = model.eval(imgs, diameter=diam, channels=channels, do_3D=False, min_size=minarea, resample=True, progress=True)
masks, flows, styles = model.eval(imgs, diameter=diam, channels=channels, do_3D=False, min_size=minarea, resample=True, progress=True)
#masks, flows, styles, diams = model.eval(imgs, diameter=130, channels=channels, do_3D=False)


# save results so you can load in gui
io.masks_flows_to_seg(imgs, masks, flows, names, channels)

## This part converts from npy to mat for use in matlab

#files = [file for file in os.listdir(folder) if file.endswith('.npy')]

for file in names:
    name = re.sub('.tif$','_seg.npy',file)
    dat = np.load(name, fix_imports=True,allow_pickle=True).item()

# plot image with masks overlaid
#mask_RGB = plot.mask_overlay(dat['img'], dat['masks'], colors=None)

# plot image with outlines overlaid in red
#outlines = plot.outlines_list(dat['masks'])

#plt.imshow(dat['img'])
#for o in outlines:
#    plt.plot(o[:,0], o[:,1], color='r')

    from scipy.io import savemat
    name = re.sub('npy$', 'mat', name)
    savemat(name, dat)`
