### ISSUE TITLE
Cannot Save 3D Outlines

### ISSUE THREAD

**Issue by brendavasquez** [MouseLand/cellpose#498]
I was able to save outlines as text for ImageJ for 2D images but not for 3D data. I get an error saying "Cannot save 3D outlines". 
Is this function not available yet? 

I tried the Labels to ROI plugin for ImageJ but it does not work well for 3D stacks. Does anyone know of an alternative?

**Comment by carsen-stringer** [comment]
it looks like there's a plugin for this? https://github.com/MouseLand/cellpose/issues/245 but I'm not sure what output it needs so I haven't written any support for it

**Comment by carsen-stringer** [comment]
if you have an idea for what you want please comment here and I will reopen the issue, for now I will close it
