### ISSUE TITLE
Performance and accuracy issue

### ISSUE THREAD

**Issue by cyf203** [MouseLand/cellpose#5]
Hi Cellpose team,

I am continuing trying more images. Although the accuracy of segmentation is fabulous, the processing speed for one image is a little slow. It took me about 2.5 min to just estimate cell diameters for one image and about the same time or longer for cell counting. Of course, my image is a very large image (2048 x 2048 pixels) and contains about 3k cells. I wonder if the speed is normal? I tried to reduce the quality of my image into (512 x 512). The speed is increased. But the accuracy decreases a lot and the result is not useable. I tried in both GUI and code version. Do you have any comments or suggestions on it? 

Thank you again for your wonderful tools!

**Comment by marius10p** [comment]
It seems a little slow to me, even on a CPU. What CPU and OS do you have? 

The only way to make it much faster is to use a GPU (see installation instructions), even a very basic one like GTX1660Ti or RTX2060.

**Comment by cyf203** [comment]
I run on our analysis server. I tried GPU mode on the GUI version. Our GPU is 2 RTX 2080 and we have 2 CPUs, which is a 32 Core AMD EPYC 7551 processor. I select GPU mode, but it's still slow.
Then I tired the code version of cellpose. Our Cuda version is 9.0. Then as instructed, I tried to install mxnet-cu90 but I cannot load this module for some reason. So, I have to go back to use standard mxnet (1.4.0). So, I am not sure I even used the GPU in code version or not.

**Comment by marius10p** [comment]
Did you install the GPU version of mxnet from [here](https://mxnet.apache.org/get_started?) ? This needs to overwrite the normal installed version from the cellpose configuration, so you have to do it after you install cellpose.

Also, what cell diameter are you using, and is this the cytoplasm or nuclear model?

**Comment by marius10p** [comment]
On the server, did you install the GPU version of mxnet after installing cellpose? This needs to overwrite the normal installed version from the cellpose configuration. Are you sure you have the 9.0 CUDA version? Maybe its 9.1 or 9.2 or smthng? Look on the mxnet website and issues to try to install the appropriate GPU version. 

Also, what cell diameter are you using, and is this the cytoplasm or nuclear model?

**Comment by carsen-stringer** [comment]
Sorry I should have added this to the instructions. After you install cellpose, you need to uninstall mxnet-mkl or mxnet before installing the CUDA version, otherwise it doesn't work:
~~~
pip uninstall mxnet-mkl
pip uninstall mxnet
pip install mxnet-cu90
~~~

In terms of the CPU version, it appears the MKL version didn't work, is that true? And what error message did you receive? Did you use the conda environment to install? The MKL version would make the CPU version faster, and it should work on AMD processors but I haven't tested it myself.

**Comment by cyf203** [comment]
I just ran 
$ nvcc -- version
to get the Cuda version and confirm that our version is V9.0.176. 
Then, I tried 
$ pip uninstall mxnet
$ pip uninstall mxnet-mkl
$ pip install mxnet-cu90==1.4.0
$ pip instlal mxnet-cu90mkl==1.4.0
Then I confirmed that I successfully installed these two packages by
$ pip list
I saw those two packages. But when I tried to import. There is an error. No matter importing which one mxnet or mxnet-cu90. I always get this problem. 
Do you have any suggestions?

**Comment by cyf203** [comment]
@marius10p  I forget to mention that the cell diameter is about 14 pixels, and I exclusively used cytoplasm as our cell cannot see a clear nuclear.

**Comment by carsen-stringer** [comment]
Can you try the latest version? So after the uninstall just say `pip install mxnet-cu90`, that will install the latest CUDA version. No need to install the CUDA version with mkl support (and I'm not sure if that is what is messing you up). The import for mxnet-cu90 to test the GPU would be

~~~
import mxnet as mx
import numpy as np

X = mx.nd.array(np.zeros(10), mx.gpu())
~~~

If this fails then the GPU version is not working.

In terms of CUDA paths, you will need to add CUDA libraries to your library path as well, e.g. my ~/.bashrc script contains the following lines

~~~
export PATH=$PATH:/usr/local/cuda-10.0/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-10.0/lib
~~~

**Comment by cyf203** [comment]
@carsen-stringer I tried 
`
import mxnet as mx
import numpy as np
x = mx.nd.array(np.zeros(10),mx.gpu())
print (x)
`
It passed and no error. But when I try the cellpose code. I got an error message. 
`
c:\jenkins\workspace\mxnet-tag\mxnet\src\operator\nn\./cudnn/cudnn_activation-inl.h:129: Check failed: e == CUDNN_STATUS_SUCCESS (8 vs. 0) : cuDNN: CUDNN_STATUS_EXECUTION_FAILED
`
Could you please give me more advice on that? Thank you so much

**Comment by carsen-stringer** [comment]
Is cuDNN installed correctly and is it the right version? Here are some instructions from mxnet to install cuDNN: https://mxnet.apache.org/get_started/ubuntu_setup.html (the CUDA dependencies part), or if you're on windows: https://mxnet.apache.org/get_started/windows_setup.html .

**Comment by marius10p** [comment]
@carsen-stringer: shouldn't mxnet also work without cuDNN? cuDNN makes it ~2x times faster but that won't matter compared to the rest of the code.

**Comment by cyf203** [comment]
@carsen-stringer I just downloaded the cuDNN. You are right our analysis server doesn't install the cuDNN. It only installed CUDA. I will try it later.

**Comment by cyf203** [comment]
@carsen-stringer @marius10p  I finally workout with CUDA. I used CUDA 10.1. But the speed is still very slow. I used to think estimation becomes a little faster than before like 1:55min. And take another maybe few minutes to finish the model evaluation and plot. As I mentioned, I worked with a relatively large image size, the image size is 2048*2048. The diameter of my cell is about 13-15pixels.

**Comment by marius10p** [comment]
Hmm, then maybe it is limited by the post-processing step on the CPU, not by the neural network. We are already using numba for that, so I don't think we'll be able to provide big speedups. 

Do you really need it to be faster than 2 minutes, how many images do you have? If you just need to test Cellpose, crop the image and try a smaller section. If you need to incorporate Cellpose into your  batch processing pipeline, then you can let it run and step away from the computer...

**Comment by cyf203** [comment]
@marius10p  Thank you for the insight.
