### ISSUE TITLE
Training formatting

### ISSUE THREAD

**Issue by flevet** [MouseLand/cellpose#50]
Hi Cellpose team,

First of all thanks for this very useful tool.
I would like to train the network and, if I'm not mistaking, the doc is missing information about the format of the files I will use for training.
How should be the images used for training? Can I use 8 bits, 16 bits, RGB?
What about the annotated images? Should they be only 8 bits? How sould I encode the different objects?

Thanks in advance,
Florian

**Comment by tkr789** [comment]
I 2nd this, some more documentation on training would be great, as referenced here: https://github.com/MouseLand/cellpose/issues/22#issuecomment-618190240

**Comment by carsen-stringer** [comment]
It expects the labels to be in separate tiffs e.g.
```
wells_000.tif
wells_000_masks.tif
```

or if you use the --img_filter
```
wells_000_img.tif
wells_000_masks.tif
```

Sorry will add this to the documentation!!

**Comment by carsen-stringer** [comment]
I'm going to close this for now, please comment if you're having problems

**Comment by lacan** [comment]
I would like to add something to this. 

If you set the `--test_dir` and use the format offered here, there is an error:
```
FileNotFoundError: [Errno 2] No such file or directory: '{TEST_FOLDER}\\{IMAGE}_masks_masks.tif'
```
I see in the __main__ method that you filter the images with the `_mask` label for the main images
https://github.com/MouseLand/cellpose/blob/694f4cb03cfe9307f78d77aad8ffb6fbfced2a8d/cellpose/__main__.py#L110

But that is not the case when loading the test images
https://github.com/MouseLand/cellpose/blob/694f4cb03cfe9307f78d77aad8ffb6fbfced2a8d/cellpose/__main__.py#L215

I wonder if anyone else has had this issue.

Best

Oli

**Comment by carsen-stringer** [comment]
sorry about this, fixed this in the github!
