### ISSUE TITLE
Cannot view TIFF images in the GUI

### ISSUE THREAD

**Issue by snayhulv** [MouseLand/cellpose#500]
Upgraded to Cellpose 2.0 (ENV Windows 10) after doing a clean pip install. Cannot open any of my own TIFF images (with .tiff extension) . However can open .tif images from cellpose's test dataset.
After converting images from my dataset from .tiff to .png, the GUI is able to open them. Please advise.

**Comment by carsen-stringer** [comment]
also, were you able to open them in the old GUI?

**Comment by snayhulv** [comment]
> also, were you able to open them in the old GUI?

Yes, i was able to open them in the old gui

**Comment by snayhulv** [comment]
> import tifffile
> 
> my_img = tifffile.imread('img.tiff')
> print(my_img.shape)

@carsen-stringer  yes, i can open it using tifffile. it's 1080x1080, could size be an issue ?

**Comment by snayhulv** [comment]
![imagecodes_error](https://user-images.githubusercontent.com/44235555/163461920-c0fb753a-2dec-49a0-9916-26cc4c9d0a4a.jpg)

**Comment by snayhulv** [comment]
separately pip installed imagecodes and it now works. Probably should be bundled together.

**Comment by carsen-stringer** [comment]
great thanks for catching this adding it to the dependency list
