### ISSUE TITLE
Deleting multiple labels in Cellpose

### ISSUE THREAD

**Issue by Eddymorphling** [MouseLand/cellpose#501]
Hello,
Thank for you the latest Cellpose release that has allowed me to self-label and train to create models on my own images. This has been immensely help as the my predictions are more accurate.

A quick question, currently I am using the Cellpose GUI and doing "CTRL + left click" to delete labels that are created with the cyto2 model. Is it possible to delete multiple labels at the same time from a larger area by creating a small region and then CTRL+left click on ROI to delete al labels inside the ROI? The cyto2 model creates a lot of false predictions that I am currently deleting one by one when self-training.

**Comment by Eddymorphling** [comment]
Just to add one more thing - when self training in the GUI, would it also be possible to choose the `initial model` to be one of a previously self-trained model? Currently the options are limited to the models found in the `model zoo` in Cellpose.

Thanks again for the awesome tool/interface!

**Comment by andrewbux** [comment]
I know this is comment is a year old, so I was wondering if this feature is currently in the works of being implemented? If so, that is great. If not, I would like to bring it back into discussion as a possible feature. I also have a lot of small inaccurate masks within a large image that are tedious to delete one at a time. This feature would greatly reduce the workload to manually fix each segmentation.

**Comment by mrariden** [comment]
Should be addressed in #718 and the newly added 'disable autosave in the dropdown menus' (#749).
