### ISSUE TITLE
Opening cellpose

### ISSUE THREAD

**Issue by maryebrown1** [MouseLand/cellpose#502]
When I attempt to open cellpose, I get the following error message:

``(cellpose-env) C:\Users\marye>cellpose
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

How do I rectify this problem? I'm not all sophisticated in coding. Thank you.
Mary

**Comment by carsen-stringer** [comment]
maybe you have two versions of numpy or another library installed? if you start the install from a clean environment this shouldn't happen hopefully. please let me know if this doesn't resolve the issue
