### ISSUE TITLE
can not auto calibrate cell diameter

### ISSUE THREAD

**Issue by pikanzz** [MouseLand/cellpose#506]
When I click 'calibrate' button, or using  `--diameter 0.`  , previous version worked, but this version comes out with :
`TypeError: expected dtype object, got 'numpy.dtype[float32]'`

**Comment by carsen-stringer** [comment]
I'm not sure why there would be a difference with the current version compared to before but please try `pip install numba --upgrade`. autocalibrate is working on windows and ubuntu with numba==0.55.0. if this doesn't work I'll reopen this issue.

**Comment by pikanzz** [comment]
Thank you for your reply, under your guidance, the bug was properly solved!
Hope cellpose gets better and better!

在 2022年5月1日，07:16，carsen-stringer ***@***.***> 写道：

﻿

I'm not sure why there would be a difference with the current version compared to before but please try pip install numba --upgrade. autocalibrate is working on windows and ubuntu with numba==0.55.0. if this doesn't work I'll reopen this issue.
