### ISSUE TITLE
Newer Version Has Funny Segmentations?

### ISSUE THREAD

**Issue by mayishazn** [MouseLand/cellpose#507]
Hello,

After updating cellpose and running the python notebook (resampling is still on) I found some strange segmentations on an image that looks like it should be "easy" for the algorithm to segment. In the following image, the black and white is the original image in reverse grayscale and the cyan is the outline from cellpose. 

![segmentationproblem](https://user-images.githubusercontent.com/43865608/166864045-ab3759fb-dfdc-44b9-8042-b274b7bad5fa.PNG)

Out of curiosity, I made a copy of an older folder I had segmented before to compare the notebook results now compared to the older version. The newer segmentation is on the left while the older segmentation is on the right. It seems the problem occurs after I updated cellpose. Do other people have similar issues and is there an easy way to get around this? Thanks!!! 

![OldNewCompare](https://user-images.githubusercontent.com/43865608/166864137-7f1a2bd4-beb5-4ec0-b048-0a939e83d3cd.PNG)

**Comment by carsen-stringer** [comment]
are you sure you used the same diameter size? the newest version is still passing the regression tests. going to close for now but can reopen
