### ISSUE TITLE
Human-in-the-loop for 3D

### ISSUE THREAD

**Issue by MathieuBo** [MouseLand/cellpose#508]
Hi, 

I was curious to know how would the human-in-the-loop training would work for a 3D picture? 
Would annotating on a single plane be sufficient for the network to learn?
Alternatively, should we only do the training on a single z plane and apply it to a 3D picture? 

Thanks for your help and all the effort put in cellpose, it is a great piece of software. 

-M

**Comment by Eddymorphling** [comment]
Hi @MathieuBo I have been doing something similar with Cellpose. I have been creating labels on single 2D images with the Cellpose GUI followed by training to create the model. Following this, I use the same model to predict on my 3D image datasets with the `stitch_threshold` set to `0.5`.

Cellpose only needs 2D annotations for training. The prediction with the model can be done in both 2D and 3D images.

**Comment by carsen-stringer** [comment]
yes this is the approach we would recommend, we will add info to the docs

**Comment by SomayehZ** [comment]
Hello! 

I'm currently using human-in-the-loop training, it looks nice. My problem is that as I started to use GPU, after training the first image, it doesn't go to the next image and stuck there! wonder how I can solve it!? Many thanks for any help.

**Comment by teh1m** [comment]
Can you point me to where this recommended approach is documented? I did not see it.
Thanks
