### ISSUE TITLE
Resolving Torch and Numpy?

### ISSUE THREAD

**Issue by mayishazn** [MouseLand/cellpose#518]
Any help launching cellpose after a new install appreciated:

python -m cellpose
C:\Users\mayis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\_masked\__init__.py:223: UserWarning: Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])

**Comment by carsen-stringer** [comment]
please use python=3.8 as recommended in the install options
