### ISSUE TITLE
GPU out of memory, CPU runs >6days

### ISSUE THREAD

**Issue by zhanglab2008** [MouseLand/cellpose#521]
Hi team,
Great work. I saw a lot of posts in this repo regarding the issue of handling large size figures with cellpose but couldn't find a satisfactory answer. So I posted my own issue here. My image has 28160 × 35949. I tried to run cellpose on it in GPU mode (gtx 1080 ti with 11 Gb memory) but failed with out of memory error. Then I ran it in cpu mode instead in my workstation (512GB ram, 32 cores) but it ran for 6 days and still running. Then I split the image into 50 parts and ran cellpose in each part separately. It finished within 4 hours with GPU mode. However, the problem is that when I stitched all parts into a whole image, the cells in the boundary of each chunk were divided into two cells artificially. Have you come up with a better solution to fix the large image size issue? Thanks!

**Comment by carsen-stringer** [comment]
@chrisroat has written a function to do this here: https://github.com/MouseLand/cellpose/blob/main/cellpose/contrib/distributed_segmentation.py, it takes as input a dask image
