### ISSUE TITLE
Is there a way to further train a custom model using the GUI?

### ISSUE THREAD

**Issue by mayishazn** [MouseLand/cellpose#522]
Hello,

Is there a way to say use cyto on an image -> fix what ever errors in segmentation appear -> train a new model called say experiment1 
-> open a new image -> run experiment1 the new model -> fix errors again -> train the model again on experiment1 ?

Thanks,

Mayisha

**Comment by carsen-stringer** [comment]
you can do this on the command line. 

We do not recommend starting from a custom model, unless you always want the images you just labelled to be weighted more than your older images -- it will start to unlearn your old images unless they are in the training set. therefore we recommend that you do human-in-the-loop in a folder with all your images and start from one of the pretrained models. I will add this
