### ISSUE TITLE
Problem saving masks as PNG in Cellpose2.0 GUI

### ISSUE THREAD

**Issue by TianxinZhu** [MouseLand/cellpose#524]
Great work. I successfully divided my cells by using Cellpose2.0 GUI. However, I couldn't find masks in my directory after clicking " Save masks as PNG" in Cellpose2.0 GUI. The Ananconda Prompt printed "saving 2D masks to PNG" but there were no PNG actually being saved. 
Txt and npy files can be saved when I tried to click "Save Outlines as text for ImageJ" and "Save masks and image (as *seg.npy)" respectively. Only PNG can not be saved successfully. I will really appreciate that if you can shed some light on my problem. Thank you!

**Comment by TianxinZhu** [comment]
FYI，the same problem occurred on both of my Windows PCs. I'm wondering if it is a general problem for Windows 10 users?

**Comment by jpylvanainen** [comment]
Same issue here, I posted to image.sc - let's see if we get responses: https://forum.image.sc/t/cellpose-2-0-gui-png-export/68427

I'm using windows 11, so cannot be a windows 10 thing.

**Comment by carsen-stringer** [comment]
do you have masks > 2**16? I've made it now so that it forces saving as tiff for images with many masks. please test out the github version, or later today, a new pip

**Comment by sri9s** [comment]
Hi @carsen-stringer , save as png is still saving them as tiffs.
