### ISSUE TITLE
Extracting single ROI from multilabel PNG cellpose output file in python

### ISSUE THREAD

**Issue by Betaglutamate** [MouseLand/cellpose#525]
Hi,

I was hoping you could let me know how I can select a single label from a cellpose multilabel PNG output file. So for example if I have 10 labelled cells in one image is it possible to get a binary mask of the image showing just one cell at a time?

Thank you in advance.

**Comment by Betaglutamate** [comment]
I Managed to write some code that seems adequately fast for the image size I am using.

```
image = io.imread('path_to_image')
color_array = np.empty((0, 4)) # 4 because I have four colour dimensions

for x, y, *c in image[:, :, :]:
    test_array = np.append(color_array, c, axis = 0)

unique_colours = np.unique(color_array, axis = 0)


list_of_cells = []

# Make mask of all pixels for a specific color
for colour in unique_colours:
    single_cell = np.all(image == colour, axis=-1)
    list_of_cells.append(single_cell)
```
The list of cells should then be a list of binarized images 1 per color label present in the image

**Comment by carsen-stringer** [comment]
I wouldn't recommend using the color output, but the int16 png, in the _masks.png each cell is a different integer value. but I'm glad this is working for you
