### ISSUE TITLE
Cellpose 2.0 GUI not resizing properly

### ISSUE THREAD

**Issue by rsenft1** [MouseLand/cellpose#526]
On a windows laptop, under Models > Train new model with image + masks in folder, the resulting pop-up window is cutting off important text and fields but can't be resized. See below:
![image](https://user-images.githubusercontent.com/28116530/173420259-13783def-c07a-4233-93bb-fb318c6f22bc.png)

Is there a way we can adjust window or text size to avoid this problem? 

Tagging @mgillis19 so she can follow as well.

**Comment by mgillis19** [comment]
Pip uninstalling and then pip installing cellpose worked, the window is now resizing. Thank you @Eddymorphling!

**Comment by carsen-stringer** [comment]
that's very weird, I'll make the default size bigger in the next release
