### ISSUE TITLE
save_outlines not working in cellpose 1.0 (executable file)

### ISSUE THREAD

**Issue by tmoreno15** [MouseLand/cellpose#527]
Hi,

I’m using cellpose 1.0 from the executable file cellpose_mac. I’m trying to use the save_outlines or save_txt arguments to save a file with the ROIs to open in FIJI/ImageJ’s ROI Manager, but these arguments are not recognized and I can’t figure out why/how to work around it.

e.g., if I run
./cellpose_mac --dir ~/Desktop/jpeg/test/ --pretrained_model cyto --chan 2 --chan2 3 --diameter 300 --save_png

I can successfully segment my images and save corresponding png files.

But if I run
./cellpose_mac --dir ~/Desktop/HeLa/jpeg/1/ --pretrained_model cyto --chan 2 --chan2 3 --diameter 300 --save_outlines

I get:
matplotlib not installed
usage: cellpose_mac [-h] [–check_mkl] [–mkldnn] [–train] [–dir DIR]
[–img_filter IMG_FILTER] [–use_gpu] [–do_3D]
[–pretrained_model PRETRAINED_MODEL] [–unet UNET]
[–nclasses NCLASSES] [–chan CHAN] [–chan2 CHAN2]
[–all_channels] [–diameter DIAMETER]
[–flow_threshold FLOW_THRESHOLD]
[–cellprob_threshold CELLPROB_THRESHOLD] [–save_png]
[–save_tif] [–fast_mode] [–no_npy] [–train_size]
[–mask_filter MASK_FILTER] [–test_dir TEST_DIR]
[–learning_rate LEARNING_RATE] [–n_epochs N_EPOCHS]
[–batch_size BATCH_SIZE] [–residual_on RESIDUAL_ON]
[–style_on STYLE_ON] [–concatenation CONCATENATION]
**cellpose_mac: error: unrecognized arguments: --save_outlines**

and no saved files.

Thanks in advance for your help.

**Comment by carsen-stringer** [comment]
sorry the save_outlines function is not available in the executable. please install the regular version following these instructions: https://github.com/MouseLand/cellpose#instructions. if you have problems with the install please comment here and we can help you
