### ISSUE TITLE
How to segment a DAPI image with blurred vision

### ISSUE THREAD

**Issue by rocketeer1998** [MouseLand/cellpose#529]
Hi @carsen-stringer , thanks for your excellent work! I used cellpose to segment my DAPI image successfully. One tile of my DAPI image is like this,
![image](https://user-images.githubusercontent.com/55828283/175190179-cf49ecce-9050-4c4e-8e86-a01705669b29.png)

I have two questions:
1. I trained my own model in which different DAPI patterns from three tiles were analyzed. I carefully labeled them and then used my own model to segment the whole image. Does one flow cell refer to a cell or a DAPI? The results are seemly plausible, and I'd like to confirm how can I segment a DAPI image with blurred vision more precisely? 
![image](https://user-images.githubusercontent.com/55828283/175191022-b612a98c-3922-4cdb-912a-67efcd2a59c7.png)

2. Does cellpose support expanding cell diameter automatically after DAPI segmentation? The expected output is like this:
![image](https://user-images.githubusercontent.com/55828283/175191238-cc0d424e-24ce-49d0-918f-f58ca8613421.png)

Thanks for your patience!

**Comment by carsen-stringer** [comment]
1. If cellpose was only given the DAPI channel, then the segmentation is only for the DAPI, not the cells. you might want to decrease the cellprob threshold and increase the flow threshold to get more ROIs.
2. cellpose does not have a built-in function for doing that. you could train the model to do that if you segment your images like that. in particular if you have any other channel with some type of marker -- cytoplasmic, membrane, etc -- giving that to cellpose would help achieve that sort of output.

going to close the issue but please comment if you have more questions
