### ISSUE TITLE
Segmenting overlapping circles

### ISSUE THREAD

**Issue by SalutVictor** [MouseLand/cellpose#530]
Thank you for the great work behind cellpose. It is amazing every time how well the segmentation of cells works.

In our research group, we would love to measure the area and circumference of droplets. The only problem is that overlapping masks are not allowed in cellpose. **Is it possible to adjust the overlap in the script manually?**

In this example, the droplets were segmented using cellpose 2.0/cyto2.
![image](https://user-images.githubusercontent.com/108118913/175487916-654fd922-41dd-4ac8-b6be-75d38562a43e.png)

Thank you very much,
Victor

**Comment by carsen-stringer** [comment]
sorry, cellpose does not have any parameter that can allow overlaps. here perhaps with a smaller diameter, the overlapping segments will always become separate smaller cells, after obtaining those you would have to write a merging algorithm.
