### ISSUE TITLE
No ROIs returned for segmenting tiny irregular shapes

### ISSUE THREAD

**Issue by Dnsibu** [MouseLand/cellpose#533]
Hello,

Thanks for all the amazing work you do on Cellpose!

I am  interested in using cellpose to segment malaria parasites in the images of blood samples. I have managed to successfully segment the blood cells in the images using the ctyo model and then human in the loop method to improve my model. However, I have been having issues successfully segmenting the actual malaria parasite in the images. I have tried training my model on manual annotations using nuclei and cyto as my initial model, with no avail. I outline the malaria parasite and run my model on the manual annotations in the GUI and I have tried adjusting the diameter as well as adjusting the flow_threshold, however, cellpose is not returning any ROIs back for anything.

I have attached some example images of malaria infected blood samples. As you can see the malaria are tiny and have a ring shape, but I do not outline the malaria in a circle.

Please let me know if there is anything I am dong wrong thus far. Thanks so much to anyone who is willing to help me. I greatly appreciate it!
![Pk_rings_thin_NY4](https://user-images.githubusercontent.com/57369957/177574208-b979af4d-1bef-4cdb-8371-b47a83b153d9.jpg)
<img width="583" alt="Screen Shot 2022-07-06 at 10 27 28 AM" src="https://user-images.githubusercontent.com/57369957/177574389-9a884621-1e7d-4254-ab2a-f1198091876b.png">

**Comment by carsen-stringer** [comment]
hmm I think for this problem I would recommend thresholding the image, keeping only the darker pixels (you can play around with the brightness for example in cellpose). you could then run the thresholded image through cellpose, or if they are always so well isolated, I'd recommend https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.label.html#scipy.ndimage.label

**Comment by carsen-stringer** [comment]
going to close the issue for now, but can reopen if this doesn't help
