### ISSUE TITLE
Unexpectedly large memory usage on empty image

### ISSUE THREAD

**Issue by kbarbary** [MouseLand/cellpose#534]
I have an image without cells where cellpose is consuming approximately 10 times the memory of other images of the same size. (approximately 10 GB vs less than 1 GB).

Why am I trying to run cellpose on an empty image? I am running it as part of a pipeline processing many images, and occasionally there are a few images like this that cause the machine to run out of memory. I could check the image contents before attempting to run cellpose, but if possible, it would be nice if cellpose handled these scenarios gracefully. 

Thanks!

### Version and environment

- Architecture: Mac M1
- OS: macOS Monterey 12.3.1
- cellpose 2.0.5 installed into new conda environment from conda-forge:
  - python 3.9.13
  - pytorch 1.11.0  build `cpu_py39h03f923b_2`
  - numpy 1.22.4

This seems to also happen on Linux  running on AWS, it also happened with cellpose 1.0.2.

### The image:

shape = `(2304, 2304)`,  dtype=`uint16`

![image](https://user-images.githubusercontent.com/970135/178376601-297bfd8d-5ff5-4ecb-ada3-cccba25b9636.png)

(I can email or include the image here if helpful.)

### Script run:

```python
import cellpose.models
import skimage.io

import logging

logging.basicConfig(level=logging.INFO)

image = skimage.io.imread("wH02_c2_f0.png")
model = cellpose.models.Cellpose(model_type="cyto2")
masks, _, _, _ = model.eval(
    [image],
    channels=[0, 0],
    flow_threshold=0.6,
    cellprob_threshold=1.0,
    diameter=None,
)
```

### Outcome:

Memory usage is < 1 GB while estimating cell diameters, but jumps to ~5GB in the "Finding Masks" step, and then slowly increases to ~10GB over the next 15 minutes. The system monitor indicates that the process is using 9 threads.
```
INFO:cellpose.core:>>>> using CPU
INFO:cellpose.models:>> cyto2 << model set to be used
INFO:cellpose.core:WARNING: MKL version on torch not working/installed - CPU version will be slightly slower.
INFO:cellpose.core:see https://pytorch.org/docs/stable/backends.html?highlight=mkl
INFO:cellpose.models:>>>> model diam_mean =  30.000 (ROIs rescaled to this size during training)
INFO:cellpose.models:~~~ ESTIMATING CELL DIAMETER(S) ~~~
INFO:cellpose.models:estimated cell diameter(s) in 81.65 sec
INFO:cellpose.models:>>> diameter(s) =
INFO:cellpose.models:[5.17, ]
INFO:cellpose.models:~~~ FINDING MASKS ~~~
INFO:cellpose.models:>>>> TOTAL TIME 1048.39 sec
```

**Comment by kbarbary** [comment]
Thanks for the quick reply; that makes a lot of sense. I probably should have thought of that. Any idea why the memory usage would slowly double over the course of the "finding masks" step? (Just curious.)

**Comment by JacobHayes** [comment]
I was looking into this too (not just for empty images) and I think it's because an empty list is created, and then appended to over each iteration (ie: slow growth), and then be converted to a numpy array (likely another doubling affecting peak memory, but then quick GC):
https://github.com/MouseLand/cellpose/blob/9a433ae6ba639847c99301a7e0baf350826448d3/cellpose/models.py#L649-L659

Any reason we don't pre-allocate with `np.zeros` up front and then assign in place? That should reduce the peak memory usage (no conversion at the end) and, if it is going to anyway, OOM sooner. I'll try to play around with this and check peak usage.
