### ISSUE TITLE
Differences between cellpose performance on the website and GUI

### ISSUE THREAD

**Issue by Leo1412** [MouseLand/cellpose#535]
Hi, I tried the exact same cellpose model on the website and in the GUI respectively on the same image (didn't change any of the settings), but the results are pretty different. Why is this happening?

Thank you very much!

<img width="1435" alt="Screenshot 2022-07-13 at 12 28 51 AM" src="https://user-images.githubusercontent.com/69981435/178545438-06730a8a-0549-45d0-97ff-bd667616c96b.png">
<img width="1440" alt="Screenshot 2022-07-13 at 12 29 00 AM" src="https://user-images.githubusercontent.com/69981435/178545454-ecd81fe9-a80d-4bcb-a192-dbde5f5c8370.png">

**Comment by carsen-stringer** [comment]
the website has a max size of 512 x 512, so your image was resized to that and then run with a cell diameter of 30. your cells are 100s of pixels in diameter, so you need to set the diameter accordingly in the GUI. in the box now it says 30, change it e.g. to 200 and click enter and you'll see the purple circle at the bottom of the image scale accordingly -- that's a reference to use to choose the diameter appropriately.

**Comment by Leo1412** [comment]
Thank you very much for your prompt response!

carsen-stringer ***@***.***> 於 2022年7月13日週三 上午3:27寫道：
