### ISSUE TITLE
3D segmentation training cv2 warpAffine error 

### ISSUE THREAD

**Issue by pr4deepr** [MouseLand/cellpose#54]
Hi Guys
  Firstly, thanks for this great software. I've been experimenting and playing around with for segmentation of 2D and 3D images. With 3D images, I would like to train using the pretrained model: cyto. My training and test images are single-channel 16-bit tiff stacks, dimensions: 65x600x600 ((Z x ) Ly x Lx ). 
Currently, I have 3 training stacks and 1 test stack with training images labelled with "_img" at the end and masks as "_masks". 
I used the command: 
python -m cellpose --train --dir C:\cellpose\training\ --test_dir C:\cellpose\test\ --img_filter img --pretrained_model cyto --chan 0 --chan2 0 --use_gpu --do_3D --mask_filter masks

It terminates with the following error:

>>>> using GPU
>>>> training starting with pretrained_model C:\Users\Pradeep\.cellpose\models\cyto_0
>>>> rescaling diameter for each training image to 30.5
NOTE: test data not provided OR labels incorrect OR not same number of channels as train data
flows precomputed
>>>> training network with 2 channel input <<<<
>>>> saving every 100 epochs
>>>> median diameter = 27
>>>> LR: 0.20000, batch_size: 8, weight_decay: 0.00001
>>>> ntrain = 3
(2, 65, 600, 600)
Traceback (most recent call last):
  File "C:\Users\Pradeep\Anaconda3\envs\cellpose\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Pradeep\Anaconda3\envs\cellpose\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Pradeep\Anaconda3\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 226, in <module>
    channels=channels, save_path=os.path.realpath(args.dir), rescale=rescale)
  File "C:\Users\Pradeep\Anaconda3\envs\cellpose\lib\site-packages\cellpose\models.py", line 674, in train
    rescale=rsc, scale_range=scale_range)
  File "C:\Users\Pradeep\Anaconda3\envs\cellpose\lib\site-packages\cellpose\transforms.py", line 465, in random_rotate_and_resize
    imgi[n,k] = cv2.warpAffine(img[k], M, (xy[0],xy[1]), flags=cv2.INTER_LINEAR)
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:2594: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'cv::warpAffine'

I am not sure why I am getting this warning either: 
>test data not provided OR labels incorrect OR not same number of channels as train data

as the test data images are in the C:\cellpose\test\ folder and have the same no of channels as training data. 

An additional point, I am using grayscale images exported from ImageJ/FIJI and when reading these images into python using imread, their shape was reported to be 65x600x600 instead of 65x600x600x1 i.e., it was missing the channel component. So, I wrote a quick script to add the channel component and resave the images: 
np.expand_dims(img, axis=-1)
Not sure if this is the reason why I get these errors.

**Comment by carsen-stringer** [comment]
For 3D images, you do not train on 3D data, in fact you train on 2D data. The cellpose model runs on XY, XZ, and YZ 2D slices and then combines them to create a 3D prediction. Therefore to improve 3D performance you want to take 2D slices from your 3D labelled data. The advantage of this approach means that you don't need to use 3D training data.

I am going to close this issue for now but please comment if you're having problems with this.

**Comment by pr4deepr** [comment]
Thanks @carsen-stringer for the reply.
Apologies, I thought that during the training process it converted them into the appropriate slices for training. 
How do you recommend I structure the data in the training and test folder for a 3D dataset? Do I just have the XY, XZ and YZ slices as separate images in the test folder with corresponding masks? Is there anything else I need to be mindful of, i.e, labels of mask being the same across all images (which will be the case anyway) etc?
