### ISSUE TITLE
How to use the command line to get the same information (cell number) displayed in the GUI

### ISSUE THREAD

**Issue by 2809654608** [MouseLand/cellpose#540]

**Comment by 2809654608** [comment]
First of all, thank you very much for maintaining cellpose, it helps me to get things done quickly.This is a great job.

In my work I ran into a problem: how to get the same information (cell number) that I get after batch processing the pictures using the command line and get a single photo after segmenting it in the GUI.

Although the segmentation effect I get with the command line is the same as the GUI version, I have tried many methods with imageJ and can't get the same number of cells as the GUI version shows.

Here is what shows in the GUI.
<img width="609" alt="a41c9197e2d39246f30c2e064788241" src="https://user-images.githubusercontent.com/53172694/182333287-8f5e13ec-110e-4cbc-ac9c-cf0eabc790c8.png">
<img width="661" alt="f945df18def447ac1631e6a5ca491f5" src="https://user-images.githubusercontent.com/53172694/182333349-ca588f74-6aa4-4ed7-b8c3-7d91cb6a28e1.png">

This is the mask picture I got with the command line when batch processing, and the count result I got from imageJ (I have used many segmentation methods and can't match the GUI display).
<img width="759" alt="6ae1e0b239f87257fa49bd5211e5c5a" src="https://user-images.githubusercontent.com/53172694/182334321-1cdf3bbf-12f1-4c6f-9eb6-9f4628143811.png">
<img width="497" alt="d80dc0e56417935e9e8098f6828ec05" src="https://user-images.githubusercontent.com/53172694/182334327-605af118-87f5-41da-b248-4ff518a978b9.png">

**Comment by 2809654608** [comment]
Or is there any way to print the cell count information when batch processing images ?

**Comment by carsen-stringer** [comment]
hmm this is a very common request. what if there is an option to make a txt file in the `--dir` that outputs two columns: the name of each file and the number of ROIs?

regarding imageJ import, are you using the `--save_outlines` option?

**Comment by Zymologist** [comment]
I'd also be interested in this feature, were it to be added. We're hoping to export a list of ROIs from images directly from the Colab notebook. Currently, we're having to save to `'_seg.npy'`, download, and load into the GUI to view the number of cells.

**Comment by mrariden** [comment]
Sounds like this is related to #581? @carsen-stringer, let me know what you need to complete #643 and get this functionality added.
