### ISSUE TITLE
cannot train model on 3D data

### ISSUE THREAD

**Issue by athulrv** [MouseLand/cellpose#541]
I have an interesting 3D nuclei dataset which I would like to train using cellpose to evaluate the performance compared to the pipeline used. Unfortunately, cellpose gui- Models/Train new model with images and masks in folder says "cannot train model on 3D data". 

Is there any reference about how to train 3D model using images from scratch on Cellpose.
Is Cellpose3D the way to go? https://github.com/stegmaierj/Cellpose3D
![image](https://user-images.githubusercontent.com/49643312/182586660-ff7fa8c9-2e63-4628-9b99-4183788ddc06.png)

**Comment by Eddymorphling** [comment]
Cellpose uses 2D images for training and creating models. The resulting model can then be used to predict 3D datasets. I have been doing something similar with 3D datasets and it works like a charm.

**Comment by carsen-stringer** [comment]
thanks @Eddymorphling yes several people have had success saving XY, YZ, XZ slices from their 3D images and labelling them, and training a custom model. see info here: https://cellpose.readthedocs.io/en/latest/gui.html#training-your-own-cellpose-model

**Comment by athulrv** [comment]
Thanks a lot @Eddymorphling @carsen-stringer
