### ISSUE TITLE
3D export the "Cellprob" channel

### ISSUE THREAD

**Issue by athulrv** [MouseLand/cellpose#542]
Looking for how to export the "Cellprob" channel from cellpose. Can this be exported as a tiff file? This is a z stack. 

![image](https://user-images.githubusercontent.com/49643312/182618104-5eaa1005-d752-42c8-9fb8-d23d83ebdc42.png)

**Comment by carsen-stringer** [comment]
this will be saved in the `_seg.npy` file under the `'flows'` key (save with CTRL+S). but we can also add an option to save as tiff

**Comment by athulrv** [comment]
Thanks a lot. Can one open the .npy file in image J or so and convert to tiff file? It would be really great if this can be saved as a tiff file directly from cellpose.

**Comment by carsen-stringer** [comment]
this is now added

**Comment by athulrv** [comment]
Thanks a lot.
