### ISSUE TITLE
Windows cannot be resized (Windows 10)

### ISSUE THREAD

**Issue by agclark12** [MouseLand/cellpose#545]
Playing around with the GUI on a workstation running Windows 11

I cannot resize any of the windows. For the main window containing the image this is not a huge deal. But for the windows that pop up from the menu (e.g. Models->Train new model..., Training instructions) I cannot see the whole window. Luckily I can still click the button on the left to train (I can just see the very top of the button). I also can't scroll down on these windows, so there is really no way for me to see the whole content.

Thanks! This is such a great tool!

Edit: sorry, earlier version said windows 10, but apparently this is windows 11 I am using.

Edit2: I can re-size windows when I first open the GUI (while I still have a normal cursor), but once I open the first image and then the cursor changes to a cross, I can no longer resize any windows. Thanks again!

**Comment by carsen-stringer** [comment]
good catch, this should be fixed now!

**Comment by agclark12** [comment]
Perfect! Thanks! It's fixed now!
