### ISSUE TITLE
CellposeTraining: IndexError: list index out of range

### ISSUE THREAD

**Issue by chenzhao2016** [MouseLand/cellpose#546]
Dear all, 

I have been trying to use the command line to train Cellpose. However, I kept getting "IndeError: list index out of range". In addition, the flow images look weird too....

Here are my test images [https://github.com/chenzhao2016/TestImages/blob/main/Test_images.rar](url)

Here is the error message
![image](https://user-images.githubusercontent.com/102878000/183634238-8f476fe9-e814-4d32-912b-398ea1f57851.png)

I would appreciate it if someone could give me some suggestions. Thank you very much!

**Comment by carsen-stringer** [comment]
it looks like your _masks images might be empty (the diameter is `nan`). did you save the training masks as indices 0=no cell, 1=cell 1, 2=cell 2,... etc

**Comment by chenzhao2016** [comment]
We changed the mask images to instance segmentation and indexed each mask by grayscale.

**Comment by BrandonSLockey** [comment]
I'm also having this issue... I'm on mac. Made the mask, saved NPY file... followed exactly online tutorial on [here](https://www.youtube.com/watch?v=5qANHWoubZU) 
<img width="917" alt="image" src="https://user-images.githubusercontent.com/72495991/186379619-5f869816-5a81-4b7f-8340-5da428566baf.png">

**Comment by BrandonSLockey** [comment]
What I figured out is if all your training images have fewer than 5 cells, then you'll produce this error. If you have at least 1 image with more than 5 cells segmented then its fine...
