### ISSUE TITLE
Use the models on our own dataset

### ISSUE THREAD

**Issue by bonaventuredossou** [MouseLand/cellpose#548]
Hi,

I wanted to know how to use the model on our own dataset. To be more specific, I have used the models available in your documentation on my set of images but that was unsuccessful i.e. very poorly performing. It is also not so sure which architecture you used, but from the training parameters, I assumed that it is a ResidualCNN.

Can you please provide a sample of the training process? From image processing to the definition of the model and training please?

Thanks in advance

**Comment by carsen-stringer** [comment]
our architecture is a u-net with residual blocks. please check out our latest colab notebook for Cellpose 2.0 for training with your own data: https://colab.research.google.com/github/MouseLand/cellpose/blob/main/notebooks/run_cellpose_2.ipynb; and the readthedocs: https://cellpose.readthedocs.io/en/latest/train.html

**Comment by bonaventuredossou** [comment]
Thanks for pointer
