### ISSUE TITLE
Cellpose on sparse populations

### ISSUE THREAD

**Issue by FrickTobias** [MouseLand/cellpose#549]
# Issue

I'm trying to use CellPose for segmenting sparse cell populations and I am getting really poor performance. The model only identifies dirt rather than cells. 

Could anybody offer any advice? Or does CellPose not handle these kinds of situations? In either case, does anyone have an idea of why it would not work?

![Screen Shot 2022-08-10 at 14 17 55](https://user-images.githubusercontent.com/17293950/183821500-1393b33a-4d39-419a-b281-582011246b19.png)

## CellPose command: 
```

cellpose --dir . --use_gpu --gpu_device 1 --check_mkl --verbose
```

## More info

I've run CellPose successfully on the same kind of sample with much higher degree of success when having higher cell densities (the image had the same sizes, I'm just showing a cropped version I had laying around).

<img width="231" alt="Screen Shot 2022-08-10 at 14 28 39" src="https://user-images.githubusercontent.com/17293950/183822688-91ae74dc-5d14-4564-b979-e2c3938404f3.png">

I've tried running CellPose 2.0.5, 2.0, 1.0.2.

**Comment by carsen-stringer** [comment]
hmm perhaps the diameter is estimated to be too large? could you try specifying the diameter on the command line? e.g. `--diameter 20`. another option is that we now have models for these types of cells, you can try a model trained on [livecell](https://www.nature.com/articles/s41592-021-01249-6) with `--pretrained_model livecell`

alternatively you could try high pass filtering the image, or some other preprocessing, to remove the lower frequency objects you don't care about

going to close but comment if still not working

**Comment by FrickTobias** [comment]
Since the other data worked better with the same `--diameter 30 ` I'm not sure it should be the issue. 

However, I did try using `livecell` instead which worked much better. Thank you!
