### ISSUE TITLE
Image saturation bar does not seem to work

### ISSUE THREAD

**Issue by rsenft1** [MouseLand/cellpose#550]
Hi! I'm trying to use cellpose 2.0 on a mac. For me, the contrast adjustment bar doesn't appear to exist: 
<img width="293" alt="image" src="https://user-images.githubusercontent.com/28116530/183969870-0363fe15-321a-4936-b5be-2a847a15f3f5.png">
And I can't select the higher flag and move it (I have to drag the invisible space in between the flags then readjust the lower flag). Is this a known issue?

**Comment by taehwangson** [comment]
I have the same issue

**Comment by giannoma** [comment]
Same issue. Is there a solve for this?

**Comment by taehwangson** [comment]
> Same issue. Is there a solve for this?

One trick that I found is to uncheck "auto-adjust" button before loading my image. Even after this, It may not work as it is supposed to be though.

**Comment by carsen-stringer** [comment]
I found a package to fix this. please try out the latest version `pip install git+https://github.com/mouseland/cellpose.git` and `pip install superqt`
