### ISSUE TITLE
Solution for PyQt5 error when start cellpose in Win8.1

### ISSUE THREAD

**Issue by rmd13** [MouseLand/cellpose#551]
Win8.1 cannot start cellpose because of the PyQt5 compatibility problem,

The solution is :

change
`from PyQt5.Qt import *
`
to 
```
import PyQt5
from PyQt5 import *
```
in any place of cellpose code that import PyQt5.

Another solution is renamed file C:\Python\Python38-32\Lib\site-packages\PyQt5\Qt\bin\Qt5Bluetooth.dll to _Qt5Bluetooth.dll.

More details see:

https://stackoverflow.com/questions/55205708/why-pyqt5-import-show-a-error-about-windows-and-bluetooth

**Comment by Corovaneer** [comment]
I  have the same issue. What is the scope of the problem for changing "in any place of cellpose code"? Is it some specific file or many files?

**Comment by rmd13** [comment]
> I have the same issue. What is the scope of the problem for changing "in any place of cellpose code"? Is it some specific file or many files?

Hi you can rename Qt5Bluetooth.dll and this solve the problem. 
I have not try the 1st method, but according to the stackoverflow post, it is cause by the syntax because some package are not supported in PyQt5.Qt.*. You can only import the upper root layer.

**Comment by carsen-stringer** [comment]
I've added the import statement, please let me know if there's still issues
