### ISSUE TITLE
How to evaluate the image gradient in new models after using human-in-the-loop

### ISSUE THREAD

**Issue by Crudeoil0** [MouseLand/cellpose#552]
Hi I am using cellpose to fit into my cardiac cell and I am wondering how to evaluate the image gradient in newly trained models after using human-in-the-loop.

**Comment by Crudeoil0** [comment]
Thank you for your comment, Carsen.
I am a biologist at the University of Auckland, a new hand in machine learning. Thank you for your useful tool. It helps a lot in my research. 
The cell, according to your paper, seems to generate seeds in the center and calculate the gradient around it to detect the boundary. What I wish to know is how to get the gradient on the human-in-the-loop trained model.

**Comment by carsen-stringer** [comment]
you can get it in the same way, the flows are saved in the `_seg.npy` file as a dictionary key, after you run the new model
