### ISSUE TITLE
training data or labels are not at least two-dimensional

### ISSUE THREAD

**Issue by binghama** [MouseLand/cellpose#553]
I've been trying to train a cellpose model from scratch using the following command in terminal:

python -m cellpose --train --train_size --use_gpu --dir /gpfs/gsfs8/users/annemb/image_prep/v7_segmentation/patches/train/image_1_4/ --pretrained_model None --verbose --mask_filter _masks --img_filter _img --chan 3

Cellpose calculates flows and progresses through all epochs but then fails at the end with this error:
ValueError: training data or labels are not at least two-dimensional

Any ideas what may be going wrong? A zip of my training files, flows from cellpose included, is attached.
[training.zip](https://github.com/MouseLand/cellpose/files/9354654/training.zip)

**Comment by Jooppie** [comment]
Hi, got the same error here 256x256 pixel patches

2022-08-22 16:11:45,617 [INFO] saving network parameters to E: 04_  23.086563

2022-08-22 16:11:45,682 [INFO] >>>> model trained and saved to E: 16_  04_  23.086563

2022-08-22 16:11:45,683 [CRITICAL] training data or labels are not at least two-dimensional

Traceback (most recent call last):

  File "C:    "_ _ main_ _ ", mod_ spec)

  File "C:    exec(code, run_ globals)

  File "C:    main()

  File "C:    batch_ size=args.batch_ size)

  File "C:    channels, normalize)

  File "C:    raise ValueError(error_ message)

ValueError: training data or labels are not at least two-dimensional

**Comment by wheelern** [comment]
FWIW, I'm running into the same thing. I'm annotating images with the GUI and then attempting to train remotely using GPUs.

**Comment by binghama** [comment]
Thanks for the help, I'm not exactly sure what was wrong but upon trying again it worked. Going to close.

**Comment by maulakhan** [comment]
Same error! it saves the model, but I get the same error. Upon running the second time when the flows are calculated and saved in the same folder, I don't get error. Do you why is it like that or if I am doing something wrong? @carsen-stringer

**Comment by yurigaid** [comment]
I also had this error training different image sets. The error is thrown on the training step of SizeModel (in transforms.reshape_train_test), after the model training is completed. It happens intermittently, hard to debug. After the error, the next training with the same dataset can succeed.
