### ISSUE TITLE
Complete Cellpose API

### ISSUE THREAD

**Issue by ved-sharma** [MouseLand/cellpose#554]
Where can I find the complete Cellpose API? I have been using the Cellpose API Guide at the following link:

https://cellpose.readthedocs.io/en/v1.0.2/api.html

But, seems to me that it is not complete, e.g. there is no mention of the io.save_masks() method at the above page. Would be nice to see all available methods.

Thank you,
Ved

**Comment by carsen-stringer** [comment]
good point this is added now

**Comment by ImageAnalysis-RockefellerUniversity** [comment]
Thanks!

**Comment by ved-sharma** [comment]
Thanks!
