### ISSUE TITLE
Cellpose does not work with .TIF files

### ISSUE THREAD

**Issue by wheelern** [MouseLand/cellpose#555]
The IO script is case-sensitive for image extensions (see: https://github.com/MouseLand/cellpose/blob/91dd7abce332a30ead85e10e7c244bfa876c9a2d/cellpose/io.py#L138). Our imager automatically uses .TIF, which means we have to rename everything to .tif to get images to work with cellpose. It's not the end of the world, but seems like an easy-ish fix on the cellpose side.

More to the point, I spent a long time trying to figure out errors during training via the command line (`'ERROR: no images in --dir folder'`). The directory wasn't empty, but it was full of images named .TIF. I had to dig into the code to find what was going on. I think there are a few options:

1. Make clear in the documentation that image extensions are case-sensitive.
2. Include a more informative error in `get_image_files()` when no images are found.
3. Add more potential extensions in `get_image_files()`
4. Maybe switch to regex instead of glob? One problem with glob is it's going to behave differently across Windows/Linux. See [here](https://stackoverflow.com/questions/8151300/ignore-case-in-glob-on-linux). 
5. Add a new argument that allows the user to provide the extension.

Using images with .TIF extensions hasn't caused me any problems elsewhere (i.e., cv2, scikit-image, etc.) so I doubt allowing them to be read would cause problems downstream, but I can't say for sure.

Thanks for the great tool! I'm excited to integrate it into our pipelines. Cheers.

**Comment by carsen-stringer** [comment]
sorry for the trouble. I've fixed this now by implementing (2) and (3) by making extensions non case sensitive

**Comment by wheelern** [comment]
Thanks!
