### ISSUE TITLE
Cellpose test data used in cellpose 1.0 paper

### ISSUE THREAD

**Issue by shan-stat** [MouseLand/cellpose#561]
Hi,
Hope all is well. In cellpose 1.0 paper, I think that the panel b in fig 4 is a crop of 001 test image, and it looks like the AP at 0.5 is for the crop, not for the whole test image. Am I understanding correctly? The other question is that did you use this kind of crops to make the panels d-g in fig 4? Or Did you use the original test image (not cropped image)?  Thanks.

**Comment by carsen-stringer** [comment]
the AP score is for the full image, the APs were always run on the full images and the full predictions for all the curves throughout the paper

**Comment by carsen-stringer** [comment]
here's the code for it: https://github.com/MouseLand/cellpose/blob/91dd7abce332a30ead85e10e7c244bfa876c9a2d/paper/1.0/performance_figs.py#L35
