### ISSUE TITLE
import/export in Json format for Cellpose

### ISSUE THREAD

**Issue by chenzhao2016** [MouseLand/cellpose#562]
Hi there, 

Does Cellpose take/export in Json format? If not, is there an easy way to convert Json to PNG (vise versa) quickly? Thank you very much!

**Comment by carsen-stringer** [comment]
you have a json with URLs to images? perhaps something like this? https://stackoverflow.com/questions/63720309/how-can-i-convert-from-json-to-png-in-a-dataset-labeled-with-labelbox

going to close but can reopen if you have questions
