### ISSUE TITLE
Multisession registration with cellpose ROIs

### ISSUE THREAD

**Issue by lanluo9** [MouseLand/cellpose#565]
Hi! I was wondering what tool we could use to align multiple sessions of calcium imaging after processing with cellpose. 

I've found [Fully Affine Invariant Methods for Cross-Session Registration of Calcium Imaging Data](https://github.com/chunyueli/FAIMCalcium) which uses cellpose extracted ROI masks to register ROIs from multiple sessions. 
There is also the [utils.stitch3D](https://github.com/MouseLand/cellpose/blob/06df602fbe074be02db3d716e280f0990816c726/cellpose/utils.py#L353) function as well as third party [Cellpose3D](https://github.com/stegmaierj/Cellpose3D), which might not apply in this case. 
Just wondering if there's a built-in or tried-and-true way to achieve multisession registration with cellpose.

Thanks for your help!

**Comment by carsen-stringer** [comment]
I would not recommend 3D stitching for this problem, there needs to be some kind of registration done. that repo may work although we haven't tested it, or we have some suggestions here: https://suite2p.readthedocs.io/en/latest/multiday.html
