### ISSUE TITLE
size mismatch error: RuntimeError: Error(s) in loading state_dict for CPnet

### ISSUE THREAD

**Issue by sri9s** [MouseLand/cellpose#567]
This is my cmd:

`python -m cellpose --use_gpu --verbose --train --dir cellpose/data/train --pretrained_model nuclei --chan 0 --chan2 0 --n_epochs 10 --learning_rate 0.1 --weight_decay 0.0001 --test_dir cellpose/data/test --mask_filter '_seg.npy' --save_png --all_channels`

I get the below error:

`    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CPnet:
        size mismatch for downsample.down.res_down_0.conv.conv_0.0.weight: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([3]).
        size mismatch for downsample.down.res_down_0.conv.conv_0.0.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([3]).
        size mismatch for downsample.down.res_down_0.conv.conv_0.0.running_mean: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([3]).
        size mismatch for downsample.down.res_down_0.conv.conv_0.0.running_var: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([3]).
        size mismatch for downsample.down.res_down_0.conv.conv_0.2.weight: copying a param with shape torch.Size([32, 2, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3]).
        size mismatch for downsample.down.res_down_0.proj.0.weight: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([3]).
        size mismatch for downsample.down.res_down_0.proj.0.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([3]).
        size mismatch for downsample.down.res_down_0.proj.0.running_mean: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([3]).
        size mismatch for downsample.down.res_down_0.proj.0.running_var: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([3]).
        size mismatch for downsample.down.res_down_0.proj.1.weight: copying a param with shape torch.Size([32, 2, 1, 1]) from checkpoint, the shape in current model is torch.Size([32, 3, 1, 1]).`
        
        What am I missing?

**Comment by sri9s** [comment]
@carsen-stringer , could you please help

**Comment by carsen-stringer** [comment]
you cannot start from a pretrained model if you want to use `--all_channels`. You have 3 channels in your images I'm guessing but the `nuclei` built-in model has only 2 input channels
