### ISSUE TITLE
Can't train size model with newest cellpose version

### ISSUE THREAD

**Issue by trongtuyen99** [MouseLand/cellpose#569]
I am using Cellpose v2.1.0, train from scatch, channel=0 and channel2=0. After training cp model had done, indexerror happend: out of bound for axis 0 with size 1200 (my image width).
In line 748, random_rotate_and_resize function - file transforms.py

I found that nchan variable in this functions is width of first image instead of image channel. After I have corrected the shape of input image, another bug found. 

Anyone successfully train size model with cellpose v2.x please help me fix this issue. Thanks

@carsen-stringer @kevinjohncutler @marius10p thanks for your support🤣🤣🤣

**Comment by sri9s** [comment]
Whats your input image dimension? are you using the gui or the command line?

**Comment by trongtuyen99** [comment]
@sri9s my input image dimensions are various, rgb image. I used command line to train.

**Comment by sri9s** [comment]
Try adding `--all_channel` argument to your command

**Comment by carsen-stringer** [comment]
Do you want grayscale or RGB inputs? (`--chan 0 --chan2 0` means grayscale and no nuclear channel)

can you report the full error message?

**Comment by sri9s** [comment]
@carsen-stringer what would be the commandline argument for RGB inputs?

**Comment by carsen-stringer** [comment]
yes `--all_channel` would be the option to train a network with 3 channels instead of 2, but we don't have support for size models currently with different channel configurations (more than 2 channels)

**Comment by carsen-stringer** [comment]
we recommend if possible that the user provides the diameter for the images
