### ISSUE TITLE
Training new model error

### ISSUE THREAD

**Issue by ninawu20** [MouseLand/cellpose#571]
Hi,

I'm having some trouble training a new model in Cellpose. When I click on the "train new model" option, here is the script that comes up: 

Traceback (most recent call last):
  File "/Users/ninawu/opt/anaconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/gui/gui.py", line 1612, in new_model
    image_names = self.get_files()[0]
  File "/Users/ninawu/opt/anaconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/gui/gui.py", line 866, in get_files
    idx = np.nonzero(np.array(fnames)==f0)[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0

Please let me know if you know how to fix this; thank you for your time!

Best,
Nina

**Comment by carsen-stringer** [comment]
have you loaded any files into the GUI before training? I think that's the problem, if not please comment and I'll try to help

**Comment by comoriarty** [comment]
Hi,
I am just starting on Cellpose and had a similar issue. I get the following error when I try to train a new model on Colab:

IndexError                                Traceback (most recent call last)
[<ipython-input-14-62e7dc082075>](https://localhost:8080/#) in <module>
     21                               weight_decay=weight_decay,
     22                               nimg_per_epoch=8,
---> 23                               model_name=model_name)
     24 
     25 # diameter of labels in training images
-----
[/usr/local/lib/python3.7/dist-packages/cellpose/transforms.py](https://localhost:8080/#) in reshape_train_test(train_data, train_labels, test_data, test_labels, channels, normalize)
    420         raise ValueError(error_message)
    421         return
--> 422     if train_labels[0].ndim < 2 or train_data[0].ndim < 2:
    423         error_message = 'training data or labels are not at least two-dimensional'
    424         transforms_logger.critical(error_message)

IndexError: list index out of range

Any help would be greatly appreciated!
Thanks :)

**Comment by Vaclav-Bocan** [comment]
I encountered the same issue, I've created a image.sc question about that: [https://forum.image.sc/t/cellpose-list-index-out-of-range-when-training-new-models/78587](url)
