### ISSUE TITLE
Cellpose update issues

### ISSUE THREAD

**Issue by ninawu20** [MouseLand/cellpose#572]
Hello,

I needed to update the version of Cellpose on my computer so that I could use the human in the loop method of training. However, after updating it, when using the models, it said "numpy not available". 

To address this issue, I tried updating numpy using "pip install --upgrade numpy". After using this script, when I opened Cellpose, it would open the old version - there was no option to train the model anymore. It also displayed an error when I started it that said "TORCH CUDA version not installed/working". Again, Cellpose would still open, but I'm pretty sure it was the previous version.

I saw someone else had posted about the same issue, and they addressed it using the following script: 
conda create -n cellpose pytorch=1.8.2 cudatoolkit=10.2 -c pytorch-lts
conda activate cellpose
pip install cellpose

However, once I used this script, I couldn't open cellpose anymore, and the error says "No module named cellpose.__main__; 'cellpose' is a package and cannot be directly executed"

Sorry this is so long, but I wanted to detail what I did because I'm not sure what step exactly is the issue right now! My goal is to be able to use the updated version of Cellpose!

Best,
Nina

**Comment by carsen-stringer** [comment]
sorry for the trouble you're having, I'd recommend starting from scratch, creating a new environment (following the instructions here: https://github.com/MouseLand/cellpose#instructions), e.g. call your environment `cellpose2`

if that doesn't work please comment
