### ISSUE TITLE
image saturation not customizable throughout all z-layers in [GUI]

### ISSUE THREAD

**Issue by klingann** [MouseLand/cellpose#573]
Hey Cellpose, 

thank you for the great tool and for leaving tedious ROI drawing behind us.

Right now we are analysing 3D with 50-200 z-lanes. For analysis I am running the latest version of cellpose.

When I set up the brightness in the GUI, it only adjustes one z-layer. When I'm running through all z-layers, the brightness jumps back to default setting. Only saving the brightness for that one ajusted z-layer. This problem also occurs also when turning off auto-adjust in the GUI. 

Is there a possibility to keep the adjusted image saturation throughout all z-layer, after adjusting it to one z-layer? 

Looking forward to hear from your suggestions.

**Comment by carsen-stringer** [comment]
good point this should be fixed now
