### ISSUE TITLE
How to save outlines as text for ImageJ from folder of npy files (in bulk)

### ISSUE THREAD

**Issue by brendavasquez** [MouseLand/cellpose#574]
Hi, 

I have run many images on cellpose and have the corresponding npy files. Is there a way to load these npy files in bulk and save the outlines file (text for ImageJ) for each file? I have been doing this one file at a time but it is pretty time consuming. Please advise if it's possible to do this bulk saving. 

Thanks!

**Comment by carsen-stringer** [comment]
sorry there is no option prebuilt, when you run cellpose please use the `--save_outlines` option in the future
