### ISSUE TITLE
issue to start the GUI (Windows)

### ISSUE THREAD

**Issue by FrenchSauce** [MouseLand/cellpose#577]
hi,

I tried to start the GUI from the anaconda command line terminal but I get this error message:

```
[INFO] WRITING LOG OUTPUT TO C:\Users\Imageanalysis\.cellpose\run.log
AObject::moveToThread: Current thread (0x2e83e04f70) is not the object's thread (0x2de90c87070).
Cannot move to target thread (0x2de83e04f70)

qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found.
This application failed to start because no Qt platform plugin could initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreenm webgl, windows.

```
I tried what was suggested here [https://stackoverflow.com/questions/41994485/how-to-fix-could-not-find-or-load-the-qt-platform-plugin-windows-while-using-m](url) and [https://cellpose.readthedocs.io/en/latest/installation.html#common-issues](url) without any success

I would appreciate any idea I could try to solve this issue
Thanks!

**Comment by MatthieuVermeren** [comment]
Same issue here: Win10 machine, fresh installation of Anaconda, fresh installation of CellPose in its own environment, installation of the appropriate CUDA... I then tried pip install cellpose[gui] and got the following:

![image](https://user-images.githubusercontent.com/66070535/193312618-cae31ac6-d788-4fcf-aebb-68de949ab546.png)

Not sure what I'm doing wrong...

**Comment by carsen-stringer** [comment]
are you using a clean conda environment? sometimes the installed conda version has issues

**Comment by carsen-stringer** [comment]
(clean meaning `conda create --name cellpose python=3.8`, this makes an environment with only python)

**Comment by carsen-stringer** [comment]
please see some help here: https://github.com/MouseLand/cellpose/issues/564#issuecomment-1268061118
