### ISSUE TITLE
running cellpose on offline cluster 

### ISSUE THREAD

**Issue by soodabehghaffari** [MouseLand/cellpose#580]
Dear Cellpose Community,
I am running cellpose on an offline cluster and I get an error message when running the line "model= models.Cellpose(gpu=True, model_type='cyto2'). I am attaching the screenshots of the errors.
<img width="1067" alt="Screen Shot 2022-09-23 at 3 13 30 PM" src="https://user-images.githubusercontent.com/54602378/192040841-6512f983-7fab-4dac-881a-8f8a7c3d9e62.png">
<img width="1055" alt="Screen Shot 2022-09-23 at 3 13 24 PM" src="https://user-images.githubusercontent.com/54602378/192040844-660925bd-9793-4072-8f04-2d828e1cd1e5.png">

**Comment by carsen-stringer** [comment]
please pre-download the models with these instructions: https://github.com/MouseLand/cellpose#download-of-pretrained-models
