### ISSUE TITLE
Export of native ImageJ .roi files via roifile

### ISSUE THREAD

**Issue by Etherian** [MouseLand/cellpose#581]
Importing Cellpose outlines into ImageJ currently requires an ImageJ macro and non-standard text file format. The process could be simplified if Cellpose could export the .roi files and zipped .roi collections that ImageJ supports natively, which shouldn't be hard to implement with help from the [roifile](https://github.com/cgohlke/roifile/) library.

**Comment by carsen-stringer** [comment]
thanks for the pointer! we will add this to our to-do list
