### ISSUE TITLE
error writing outlines file when no masks are found

### ISSUE THREAD

**Issue by tralfalmadaan** [MouseLand/cellpose#584]
Hi,
we are analysing nuclei in images acquired by a tile scan. This means that some of our images are empty and cellpose doesn't detect any masks.
When running cellpose from the command line to process the directory, it runs into an error and breaks when using the --save_outlines flag. Absence of detected masks doesn't seem to be a problem for the --save_png flag, or writing the .npy file.
My command is:
`>python -m cellpose --dir D:\Projects\test_cp1 --pretrained_model cyto2 --diameter 95 --save_png --save_outlines --exclude_on_edges --use_gpu --verbose`
Running on Win11 in a conda environments (python 3.8.3) using both cellpose and cellpose2.

The error it gives is this:
```
Traceback (most recent call last):
  File "D:\conda_environments\cellpose\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\conda_environments\cellpose\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\conda_environments\cellpose\lib\site-packages\cellpose\__main__.py", line 458, in <module>
    main()
  File "D:\conda_environments\cellpose\lib\site-packages\cellpose\__main__.py", line 344, in main
    io.save_masks(image, masks, flows, image_name, png=args.save_png, tif=args.save_tif,
  File "D:\conda_environments\cellpose\lib\site-packages\cellpose\io.py", line 437, in save_masks
    imsave(os.path.join(outlinedir, basename + '_outlines' + suffix + '.png'),  imgout)
  File "D:\conda_environments\cellpose\lib\site-packages\cellpose\io.py", line 94, in imsave
    arr = cv2.cvtColor(arr, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.5) d:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.simd_helpers.hpp:94: error: (-2:Unspecified error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<3,4,-1>,struct cv::impl::A0xca0061f2::Set<3,4,-1>,struct cv::impl::A0xca0061f2::Set<0,2,5>,2>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Unsupported depth of input image:
>     'VDepth::contains(depth)'
> where
>     'depth' is 6 (CV_64F)
```

Is there a way to check for masks and maybe saving an empty png or txt file?

**Comment by carsen-stringer** [comment]
thanks for noticing this, it will now skip saving files other than NPY if no masks are found

please try it with `pip install git+https://github.com/mouseland/cellpose`

**Comment by tralfalmadaan** [comment]
Thanks, that's great!
