### ISSUE TITLE
urllib error when change the type of model

### ISSUE THREAD

**Issue by soodabehghaffari** [MouseLand/cellpose#585]
Hello,
I ran Cellpose successfully on my images with the model cyto2, however, when I change the model type to cyto or nuclei, I receive an error message regarding the URLopen (please see below). Of note, I am changing the model type to resolve the issue I wrote about the other day that some of the images are not well constructed and I receive a warning "no mask found."

![Screen Shot 2022-10-04 at 2 28 48 PM](https://user-images.githubusercontent.com/54602378/193897206-37ccf54d-9e2c-4630-a05b-75945f383aeb.png)

**Comment by carsen-stringer** [comment]
hmm sorry it's not working, please try: https://github.com/MouseLand/cellpose#download-of-pretrained-models
