### ISSUE TITLE
Using GPU (Intel HD Graphics 530) to train custom model

### ISSUE THREAD

**Issue by Mahajan30** [MouseLand/cellpose#588]
Hey

I am using the Cellpose GUI to train a custom model in 2D but each training step takes forever as it uses just the CPU. How can I make it utilise the GPU on the Intel processor?

Thanks for your help!

Vaibhav

**Comment by carsen-stringer** [comment]
The Intel HD Graphics 530 is not an NVIDIA-CUDA capable GPU so it cannot be used for acceleration, please try google colab if you want free GPU access with CUDA support
