### ISSUE TITLE
ROI Manager Error after ImageJ Macros on some, but not all, masks

### ISSUE THREAD

**Issue by davalencia0914** [MouseLand/cellpose#589]
I've been inconsistently getting the below error when using the imagej_roi_converter.py file in macros on ImageJ, followed by inputting the .txt file of the CellPose outlines, where some of the masks will be uploaded on the image, but some or most won't be for some reason. The segmentation goes well and similarly to other images where all the masks are easily overlayed on the image in ImageJ.

Roi[Polygon, x=686, y=0, width=240, height=58]
 
Roi[Polygon, x=1044, y=0, width=336, height=167]
 
Traceback (most recent call last):
  File "<string>", line 19, in <module>
ValueError: invalid literal for int() with base 10: ''

In the above case, 2 of the 8 masks that were outlined were overlayed on the image, while the other 6 don't appear at all on the image. In this specific example, I did manually segment one of the cells and then save the outlines to a txt file after that, but other times I just have it automatically segment all the cells and then save it as a txt file and get the same error after a certain number of masks uploaded to the image. In this specific case, I tried deleting the two cells that it was overlaying on the image from the CellPose outlines, resaved the txt file and then tried running the macros and then no cells were overlayed with outlines. The other cells not being overlayed aren't necessarily oddly shaped either.

**Comment by carsen-stringer** [comment]
I'm sorry I am not an expert an ImageJ, perhaps you can post this on forum.image.sc or try a cellpose plugin for FIJI? https://github.com/BIOP/ijl-utilities-wrappers

**Comment by phorve** [comment]
Hi @davalencia0914, I've had this happen a couple of times to me as well. I went to the actual text file that is exported from cellpose and found that the error is caused by empty lines in the outputted text file. If you get rid of these empty lines, all of the ROI should then import. Hope this helps! I just happened to come across this looking for something else!
