### ISSUE TITLE
Numbering cells on image

### ISSUE THREAD

**Issue by atreyiChak** [MouseLand/cellpose#59]
Hi there,  
I am segmenting neurons in brain slices using Cellpose and it works very well. I would like a way to visualise which mask/outline belongs to which cell on the original image. Is there already a function that would allow plotting numbered labels on top of the detected cells for example? 
Any tips would be wonderful!
Thanks, 
Atreyi

**Comment by carsen-stringer** [comment]
modifying this example:
~~~
import numpy as np
from cellpose import plot
dat = np.load('_seg.npy', allow_pickle=True).item()
import matplotlib.pyplot as plt
masks = dat['masks']

# plot image with outlines overlaid in red
outlines = plot.outlines_list(masks)
plt.figure(figsize=(8,8))
plt.imshow(dat['img'])
for i,o in enumerate(outlines):
    y,x = np.nonzero(masks == (i+1))
    ymed = np.median(y)
    xmed = np.median(x)
    plt.text(xmed, ymed, '%d'%(i+1))
    plt.plot(o[:,0], o[:,1], color='r')
~~~
