### ISSUE TITLE
Prediction on sparse image data (cytoplasm segmentation)

### ISSUE THREAD

**Issue by maulakhan** [MouseLand/cellpose#590]
@carsen-stringer 
I am trying to segment cytoplasm in a 3D image (isotropic) with 2 channels (nucleus and cytoplasm). It has two cells in the middle (sparsely distributed over the image). I used `cyto` model with a diameter of `20` on the full image, it gives me this:
<img width="1913" alt="full_seg" src="https://user-images.githubusercontent.com/17739639/196733840-bd3fee17-a894-494a-9831-a06341ec60cf.png">

So, one can see that it tries to detect a lot of small objects in background too. However, when I crop the image as follows:

<img width="371" alt="orig_crop" src="https://user-images.githubusercontent.com/17739639/196734957-f3e5236c-4dcf-4c8f-93ec-b82f18dff4a2.png">

The segmentation results are quite good using exactly same settings as used for a cropped image (see below):

<img width="1911" alt="cropped_seg" src="https://user-images.githubusercontent.com/17739639/196735156-c0612c14-0c62-491c-b493-53b6bc5af23d.png">

Is this the expected behavior? What if one wants to work on a full image data?

Best,
Arif

**Comment by carsen-stringer** [comment]
I think there will be quite a bit of variability when the diameter is poorly scaled, like in your example. The purple disk is the estimated size of the objects you are giving to cellpose, you can see that's much smaller than your actual cells, please set that in the diameter box and click enter to change it and then rerun the segmentation

**Comment by maulakhan** [comment]
I used the `calibrate` function. it gives me a diameter of 50.8 and the following result:

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/17739639/200274073-b68803e2-9944-4f65-a4ed-ea56dd9cbd9a.png">


 or do you mean greater than 50? I selected 70 and the result is:

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/17739639/200273564-437f78a6-b070-4b47-b76a-9bfb39f56670.png">

Seems like it gets worse at higher diameter for uncropped image
