### ISSUE TITLE
Error: AttributeError: 'NoneType' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by fpiumi** [MouseLand/cellpose#593]
I can open the Cellpose software window but couldn't drag-and-drop any image in it. Each time, I got the following error message in the anaconda terminal : "AttributeError: Nonetype object has no attribute ndim'. 
The image type is jpg, coming from a export from Zeiss ZEN software.

**Comment by carsen-stringer** [comment]
I'm sorry I could not replicate this error with jpg or jpeg files, could you attach the file here?

**Comment by fpiumi** [comment]
Thank you Carsen, It seems that .tif files are doing all right instead of .jpg
