### ISSUE TITLE
Adding the ability to configure normalization parameters

### ISSUE THREAD

**Issue by Etherian** [MouseLand/cellpose#596]
We have a image set that Cellpose performed very badly on, much worse than it did on other image sets we have used it with, especially on images with very sparse cell density. However, manually tweaking Cellpose's normalization range, as described in #454, greatly improved Cellpose's models' efficacy on this image set.

I would like to request the ability to set the normalization range parameters in the API, CLI and GUI, so we can tweak them in a more standardized way.

Alternatively, the ability to turn off the normalization step, à la the `normalize` parameter and `no_norm` switch, could be exposed to the GUI, so we could instead perform the normalization step ourselves beforehand.

**Comment by carsen-stringer** [comment]
this is currently in the works, try out the `dev` branch for these options in the GUI (still in development)
