### ISSUE TITLE
Installing jupyter after installing cellpose[gui] breaks the ability to use cellpose gui

### ISSUE THREAD

**Issue by DebrajGhose** [MouseLand/cellpose#599]
After installing cellpose gui by running 

`python -m pip install cellpose[gui]`

If I do:

`conda install jupyter`

it breaks the ability to bring up cellpose gui by using the command `cellpose` in the cellpose environment. I can get around this by using two different environments, one for the gui and the other to use the API, but is there a way to have both functionalities in one environment?

**Comment by carsen-stringer** [comment]
what operating system and python version is this? can you please print the error message?

you could also try
```
pip install notebook
```

this installs jupyter-notebooks without conda

**Comment by DebrajGhose** [comment]
I am running Windows 10 and Python 3.8. The error message was: 
```
QObject::moveToThread: Current thread (0x1ddc84c2ed0) is not the object's thread (0x1ddcad69e00).
Cannot move to target thread (0x1ddc84c2ed0)

qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreen, webgl, windows.
```
I tried to reinstall it, but that led to further errors.

Nevertheless, your suggestion to try `pip install notebook` worked for me. Thank you!

**Comment by carsen-stringer** [comment]
great! added it to the readme, closing the issue
