### ISSUE TITLE
Send manual segmentation to server

### ISSUE THREAD

**Issue by cyf203** [MouseLand/cellpose#6]
Hi, Cellpose team,

I want to contribute our manual counting result to the model. But, I am a little confused about which is the correct data I should send to the server:
1. Do automatic segmentation and manually correct all possible cells, including add or remove the segmentation outline. And click send to the server.
2. Do automatic segmentation and manually correct some cells, including add or remove the segmentation outline. And click send to the server.
3. Do manual segmentation for all possible cells in the image. And click send to the server
4. Do particular segmentation in an image. And click send to the server.

Could you please advise me which action above will help and which one you may not recommend me to send? Thank you.

**Comment by marius10p** [comment]
It has to be 3. Thanks!

**Comment by cyf203** [comment]
Will do! Thank you!
