### ISSUE TITLE
add resizing to pipeline (original: Optimise RAM and GPU usage)

### ISSUE THREAD

**Issue by athulrv** [MouseLand/cellpose#60]
I have a strong system with 16 gb NVIDIA P5000 GPU, cellpose is only using 1GB and is taking around 30 min for processing my nuclei stack of size (477, 1848, 1848). Can i allocate more GPU to cellpose and make the workflow fast? I have cellpose installed from env file. 
![image](https://user-images.githubusercontent.com/49643312/81579122-0bcf1480-93ac-11ea-8020-5b2875716810.png)

**Comment by athulrv** [comment]
![image](https://user-images.githubusercontent.com/49643312/81578810-9cf1bb80-93ab-11ea-8241-1e67cf6382d2.png)

At the end, it resulted in memory error. I have 94 Gb RAM and cellpose was using more than 70 GB while running.

**Comment by carsen-stringer** [comment]
can you downsample these images first if you do not have enough RAM? the cells look to be over 100 pixels in diameter, so you could downsample the stack by a factor of 3 => 27 times smaller stack since it's a 3D stack

**Comment by athulrv** [comment]
Great, I could 3D segment hese nuclei after they are downsampled. How do you ideally downsample images for cellpose? I did it in imageJ -> scale image with interpolation Bilinear and Average while downsampling.

Anyway, there is no changes to GPU usage. It still uses only 1 GB GPU. Thanks a lot.

**Comment by carsen-stringer** [comment]
that downsampling approach sounds good, in cellpose we use that same approach for resizing (but implemented in the function cv2.resize). adding downsampling to the pipeline is doable and something we had in the past - I will add the enhancement tag to the issue.

To use more GPU you can increase the batch_size. This parameter can be set if you run cellpose from the command line but is not currently an option in the GUI.

**Comment by watsaig** [comment]
> To use more GPU you can increase the batch_size. This parameter can be set if you run cellpose from the command line but is not currently an option in the GUI.

In `__main__.py`, the `batch_size` parameter is never used: models are constructed without passing that parameter. Is it possible you forgot to add that functionality, or did I miss something?

**Comment by carsen-stringer** [comment]
oops thanks for catching that! it's implemented now in the github

**Comment by mgheirat** [comment]
Hi. Thank you for the great tool. Does the above update on including the batch_size in main apply by updating the cellpose package (for gpu: pip install --no-deps cellpose --upgrade), or an installation from the Github version is needed? Thank you.

**Comment by carsen-stringer** [comment]
I've changed the pipeline so that the resized version (based on diameter) is used through to the end of the computation, reducing RAM requirements. Also for 3D computation the batches are concatenated across patches to improve speed.

**Comment by athulrv** [comment]
Awesome. I will update my cellpose.

**Comment by athulrv** [comment]
Cellpose couldnt load my original image; it says "images not compatible". I downsampled it to 4x (in fiji-scale image) small making a final size of 327 planes of size (564, 564). At the end the error was- 

"Traceback (most recent call last):
  File "/home/snz/anaconda3/envs/cellpose/lib/python3.7/site-packages/cellpose/gui.py", line 1288, in compute_model
    interpolation=cv2.INTER_NEAREST)
  File "/home/snz/anaconda3/envs/cellpose/lib/python3.7/site-packages/cellpose/transforms.py", line 422, in resize_image
    imgs = cv2.resize(img0, (Lx, Ly), interpolation=interpolation)
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-dglzv4yn/opencv/modules/imgproc/src/resize.cpp:3572: error: (-215:Assertion failed) !dsize.empty() in function 'resize'" 

The segmentation is then not completed.

**Comment by carsen-stringer** [comment]
hmm, sorry about this error, can you try the github version of cellpose? I think I've fixed this
