### ISSUE TITLE
CellPose GPU installation issue

### ISSUE THREAD

**Issue by tischi** [MouseLand/cellpose#600]
Hi!

We are using this to install CellPose:

```
conda create --yes --name cellpose python=3.8
conda run --name cellpose python -m pip install cellpose[all] scikit-image
```

This used to work well, but now (_maybe_ due to torch version being `1.13` and not `1.12` anymore) we are getting this error when running Cellpose:

```
OSError: /opt/conda/envs/cellpose/lib/python3.8/site-packages/torch/lib/../../nvidia/cublas/lib/libcublas.so.11: undefined symbol: cublasLtGetStatusString, version libcublasLt.so.11
```

Do you have a recommendation for installing CellPose such that we could avoid issues?
We would be fine to fix versions of dependencies during installation.

In fact, ideally, we would maintain several working versions of CellPose (we could name the conda environments accordingly).

**Comment by carsen-stringer** [comment]
thanks for pointing this out! did you run?
```
conda install pytorch cudatoolkit=11.3 -c pytorch
```

It looks like pytorch is now using 11.7. Can you please try 
```
conda install pytorch pytorch-cuda=11.7 -c pytorch
```

and if that works I'll change the instructions

**Comment by tischi** [comment]
So in total:
```
conda create --yes --name cellpose python=3.8
conda run --name cellpose install pytorch pytorch-cuda=11.7 -c pytorch
conda run --name cellpose python -m pip install cellpose[all] scikit-image
```

or in some other order?

**Comment by carsen-stringer** [comment]
yes that should work, as long as you have 11.7 cuda installed on your computer

alternatively:
```
conda install pytorch==1.12.1 cudatoolkit=11.3 -c pytorch
```

I will suggest this option for now

thanks for catching this issue!

**Comment by maulakhan** [comment]
```
conda create --yes --name cellpose python=3.8 && \
conda run --name cellpose python -m pip install cellpose[all]
```
This works with GPU (`cuda 11.7`)
