### ISSUE TITLE
Explicit version printing

### ISSUE THREAD

**Issue by FrickTobias** [MouseLand/cellpose#602]
# Issue
CellPose does not currently have any explicit version except through its distribution channels, like conda (from what I can find).

If this information is accessible directly in an installation this could make it easier to make sure results are reproducible, make it easier to trace problems in issues and reduce mistakes caused by using outdated versions.

# Suggested solution
I suggest adding a version flag in the code which is printed in
- log files at CellPose start
- GUI window
- help message in API

If this is of interest I could use some spare time to make a draft in a fork with the suggested changes.

**Comment by carsen-stringer** [comment]
thanks for suggesting this, I've added 1 and 2 and CLI: `python -m cellpose --version`, or it prints when verbose
