### ISSUE TITLE
Cellpose Google Colab gives omni error

### ISSUE THREAD

**Issue by lillianhorin** [MouseLand/cellpose#603]
Hi cellpose team,

Thanks for writing such a great program. I am currently using the [cellpose google colab notebook](https://colab.research.google.com/github/MouseLand/cellpose/blob/main/notebooks/Cellpose_cell_segmentation_2D_prediction_only.ipynb#scrollTo=h_iAN7cAthma) for 2D segmentation but am receiving an error at step 6 (attached image below). We aren't using the omni models so I'm not sure why it's throwing this error. 

![image](https://user-images.githubusercontent.com/24489520/201413870-e55b91df-1dc9-4b4f-b939-d7ab548b1901.png)

Thank you for your help!

**Comment by davidbuzz** [comment]
in the 'show code' block, delete this specific bit:   , omni=omni
it should end up looking like this:
model = models.Cellpose(gpu=use_GPU, model_type=model_type)

**Comment by carsen-stringer** [comment]
sorry about this, this is now fixed
