### ISSUE TITLE
Install: Anaconda vs. Conda with minimal requirements

### ISSUE THREAD

**Issue by AndreZeug** [MouseLand/cellpose#605]
Dear Cellpose Community,
does anybody has experience with minimal installation size of Anaconda (Conda), which is necessary to run Cellpose (including GUI)?
Would e.g., [miniconda](https://www.educative.io/answers/anaconda-vs-miniconda) be enough? 
Or, is there an easy way to install a minimal conda with the [packages](https://github.com/MouseLand/cellpose#dependencies) Cellpose requires?

Thanks
Andre

**Comment by jasonkena** [comment]
The exact virtualenv distribution (miniconda/anaconda/mambaforge/etc.) used does not matter. The packages that cellpose requires can be installed by using `python -m pip install cellpose[gui]`, or equivalent commands given in the README.

**Comment by carsen-stringer** [comment]
thanks @jasonkena that is correct, miniconda will also work
