### ISSUE TITLE
Fail to launch the GUI in Ubuntu 22.04

### ISSUE THREAD

**Issue by BennyGinger** [MouseLand/cellpose#606]
Hi,
I'm using Ubuntu 22.04.1 LTS, and I try to launch the gui but I always get this error:
`GUI ERROR: /home/ben/Softwares/miniconda3/envs/cp_gui/lib/python3.8/site-packages/PyQt5/QtGui.abi3.so: undefined symbol: qt_version_tag, version Qt_5.15
GUI FAILED: GUI dependencies may not be installed, to install, run
     pip install cellpose[gui]`

I obviously tried to install cellpose as suggested by the error message. I've also checked that I have the latest version of PyQt5 installed in my env. Is this some sort of package that I need to have on my local machine?
I can run cellpose without the gui, no pb, but I wanted to use this human-in-the-loop annotation to increase my segmentation.
Thanks for the help

**Comment by carsen-stringer** [comment]
I haven't encountered this issue before, you could try installing it through apt? https://gist.github.com/ujjwal96/1dcd57542bdaf3c9d1b0dd526ccd44ff

**Comment by BennyGinger** [comment]
Hi! Thanks for the suggestion, but it doesn't work. I'm also running a Matlab runtime and it seems that there's a conflict with qt5... So, I'm using another computer for the GUI :)
Btw, I love your work!

**Comment by BennyGinger** [comment]
Hi @carsen-stringer,
Sorry me again, I've sort of located the error, but it's way beyond my expertise to solve it. However, it works with PyQt6, any chance I could overwrite PyQt5 to 6 when I use cellpose? If so any idea how to do it?
Thanks!

**Comment by carsen-stringer** [comment]
sorry I don't have a solution, other than to fork the repo, open VSCode, and search for every `PyQt5` reference and replace it with `PyQt6`. But this is not guaranteed to work. if it does I'll link the fork here

**Comment by ebouilhol** [comment]
Hi, 

I ran into the same error :

```(cellpose) xxx$ python -m cellpose
GUI ERROR: xxxx/mambaforge/envs/cellpose/lib/python3.8/site-packages/PyQt5/QtGui.abi3.so: undefined symbol: _ZdaPvm, version Qt_5
GUI FAILED: GUI dependencies may not be installed, to install, run
     pip install cellpose[gui]
```
I used mamba to create the environment instead of conda but then I used pip to install cellpose and cellpose[gui] as recommended in the installation procedure of cellpose. 

`pip uninstall pyqt5`

 followed by 

 `mamba install pyqt`
 
 did the trick for me, but I don't know why... I found the idea on this issue : https://github.com/OpenShot/openshot-qt/issues/5214

It installed the following version : 
```
pyqt                      5.15.9           py38hffdaa6c_4    conda-forge
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.12.2                  pypi_0    pypi
```

Hope it helps.

Kind regards

**Comment by mrariden** [comment]
There will be a cellpose release out soon that will address some pyqt issues. I'm going to close this for now.
