### ISSUE TITLE
Handling Normalization of Large Images

### ISSUE THREAD

**Issue by gatordevin** [MouseLand/cellpose#608]
To train cell pose, I take my whole slide large tif file and tile it into 300x300 sections that can be easily annotated and have the model run against. I then trained the model, and it gave excellent results against similarly prepared data. However, running the model on the whole slide image using the model's built-in tiling method fails to detect all the cells even with the diameter parameter manually set. It stumped me for a while until I realized the image was being normalized differently. When the model runs on a 300x300 image, it normalizes with only the information from that image. When I run on the WSI image, which has a lot of dark low intense pixels, it also normalizes with this data. This causes the image being fed into the model to have different intensity values than what it was trained on. 

To test this, I dove into the cellpose model code and moved the normalization step after the image gets tiled. Here is the result.
![896PixelNormalizationEveryTile](https://user-images.githubusercontent.com/5672778/202259808-7cdfbd7c-5013-4eff-a1cb-216b151131df.PNG)
We can see it correctly detects all the cells but also creates weird lines between each tile due to the different normalization of the adjacent images. Now here is the output of the model with normalization before tiling. 
![image](https://user-images.githubusercontent.com/5672778/202260081-d8eefdea-1993-4375-82f1-5796c091b9d6.png)
It detected a lot fewer cells. It also had more false positives in the low-intensity image region due to normalizing those images brighter. The lines between different tiles are also a lot more consistent and defined.

How should I run the CellPose model on an image skewing the normalization to be different from the dataset? Should I turn off normalization for training and normalize manually before tiling the images for training?

Any help would be greatly appreciated.

**Comment by carsen-stringer** [comment]
yes it seems like the best strategy would be to turn off normalization and normalize yourself manually before processing. there is a  CLI option `--no_norm` or in a notebook in the `eval` function set `normalize=False`

**Comment by remybonnav** [comment]
If I train with --no_norm it stil ldoes not work on large images. any clues? Also if using --no_norm during inference it always fail to find objects. Any clue?
