### ISSUE TITLE
Edit ROI in 3D? 

### ISSUE THREAD

**Issue by phorve** [MouseLand/cellpose#609]
Hi CellPose team, 

I recently came across this program when I ran into some tough segmentation problems and overall it has worked amazingly (better than many of the other available programs)! I trained my own model using individual slices from a 3D dataset and am now testing that model on 3D confocal stacks. It works fairly well but is there a way to edit the 3D ROI? 

For example, there is an occasional slice where the cell is split into multiple roi but only for that slice. It seems to happen more right at the start or end of cells, right when the cell is coming into view. The slices before and after correctly call it a single ROI but it gets split in this single slice (see picture). Is there any way to adjust this? And similarly, how can I add or delete just single slices without affecting all the other slices? Would changing the ```stitch_threshold``` help with this at all?

Thanks! 

Correctly called roi: 
<img width="208" alt="Screen Shot 2022-11-17 at 8 03 08 AM" src="https://user-images.githubusercontent.com/58669720/202496445-042ebbc5-2183-42c9-bd66-5bebe13698c9.png">

Miscalled roi I want to fix: 
<img width="241" alt="Screen Shot 2022-11-17 at 7 59 18 AM" src="https://user-images.githubusercontent.com/58669720/202495598-4c3e27ca-4087-45a2-8032-93ec0963679c.png">

**Comment by phorve** [comment]
A quick update: 

It appears that there is a workaround with ImageJ/Fiji. 
1. Save the 3D masks as a .TIF
2. Open .Tif in ImageJ/Fiji
3. Use the [BIOP plugin](https://github.com/BIOP/ijp-LaRoMe) to convert the image to ROIs
4. Edit ROIs in ImageJ/Fiji on a slice by slice basis 

While this works, you lose the information of how ROIs are connected between slices. It would be really nice to be able to edit the ROIs directly in the CellPose GUI as well as export the ROIs from CellPose as a 3D ROI instead of needing to then manually merge ROIs by hand after the fact, especially since they are merged (I think) in CellPose already.

**Comment by carsen-stringer** [comment]
You can edit in 3D yes. but you have to draw the cell from scratch. You can delete the cell with CTRL+click, then turn off single stroke in the drawing section and circle the ROI on a plane, then click the up/down arrow keys to move up and down. then press enter when you're done drawing the planes. it will interpolate across planes so you don't have to draw each plane one at a time
