### ISSUE TITLE
Cellpose on ubuntu server 18.04

### ISSUE THREAD

**Issue by athulrv** [MouseLand/cellpose#61]
Is there any special requirements for installing cellpose in ubuntu server? Does the GUI still work in the ubuntu server version? If not, how does one work with non GUI version of cellpose?

**Comment by carsen-stringer** [comment]
in the documentation there is info on how to run on the command line and also in a jupyter-notebook. the GUI will run in "ssh -X" mode if you can ssh into your server with graphical access
