### ISSUE TITLE
Cellpose kernel dies on M2 mac

### ISSUE THREAD

**Issue by muskin29** [MouseLand/cellpose#610]
Using cellpose 2.0 on M2 mac, kernel crashes and dies everytime even with test data provided by developer

**Comment by carsen-stringer** [comment]
M1 Macs in general have to use rosetta to run python, maybe it's the same with the M2? some install info here: https://forum.image.sc/t/cellpose-on-macos-m1-pro-apple-silicon-arm64/68018

sorry I don't know much about macs, you can also search the issues here but without more info it will be difficult to diagnose
