### ISSUE TITLE
Question about data augmentation

### ISSUE THREAD

**Issue by tischi** [MouseLand/cellpose#613]
Hi,

I guess when we train a new model in CellPose some data augmentation is done automatically during the training?! Is there a list somewhere of what is done exactly? For example, are rotations included in the augmentation?

**Comment by carsen-stringer** [comment]
correct, the augmentations are the same as in the original paper (random rotation and scaling and flipping). you can also see them in transforms.py random_rotate_and_resize: https://github.com/MouseLand/cellpose/blob/02b83a5aa3173c60ffce67be08df56d7e86930f8/cellpose/transforms.py#L667
