### ISSUE TITLE
Does preprocessing the raw image help in better segmentation?

### ISSUE THREAD

**Issue by athulrv** [MouseLand/cellpose#62]
![image](https://user-images.githubusercontent.com/49643312/81583761-155b7b00-93b2-11ea-96cc-4d6362373fdf.png)
![image](https://user-images.githubusercontent.com/49643312/81583800-27d5b480-93b2-11ea-8791-4705e5b85bc6.png)

**Comment by carsen-stringer** [comment]
can you comment on the preprocessing you did? what is the question?

**Comment by athulrv** [comment]
I have made median filter and gaussian blurring with small radius. The question is if cellpose already tries to make several of these filtering to understand the data? Filtered dataser is visually appealing and much promssing than the raw data, but the point here is if it helps in better segmentation than just providing the raw unprocessed data.

**Comment by carsen-stringer** [comment]
Since most of the training data looks more like the filtered version it should help to use the filtered version over the unfiltered version. Does it work better in practice? We don't do any filtering in cellpose.
