### ISSUE TITLE
GUI options disappearing when fullscreened and inaccesible on minimized screen

### ISSUE THREAD

**Issue by mayishazn** [MouseLand/cellpose#620]
Hi Folks,

When my GUI is fullscreened the model zoo and the custom model options disappear:
![image](https://user-images.githubusercontent.com/43865608/206019403-3c02672f-7097-4ff3-ac93-3ee775a50ba3.png)

And when the window is smaller I can access the model zoo but not the custom models:

![image](https://user-images.githubusercontent.com/43865608/206019663-ac737728-9ac7-4d84-8085-7600222f3c32.png)

Is it possible to introduce a scroll bar on the side? 

Thanks,

Mayisha

**Comment by carsen-stringer** [comment]
can you try the latest version? I've reduced the vertical space which should help
`pip install git+https://github.com/mouseland/cellpose.git`
