### ISSUE TITLE
Impossible to train if mask images have less than 5 regions

### ISSUE THREAD

**Issue by TAspert** [MouseLand/cellpose#627]
This seems to be a feature and not a bug, but this is very problematic for datasets in which images contain only one object to segment.

Suggested solution: make an option in the training GUI to change the value of _models.train.rescale_ or _models.train.min_train.masks_

**Comment by carsen-stringer** [comment]
good point, I've set min_train_masks option to 1 for the train GUI please `pip install git+https://github.com/mouseland/cellpose.git` to try it out
