### ISSUE TITLE
Cannot run cellpose in ImageJ (Fiji)

### ISSUE THREAD

**Issue by joebear33** [MouseLand/cellpose#628]
Hi
I am trying to run the cellpose wrapper within ImageJ but get an error returned. I have attached pictures of the error code and the packages installed within the cellpose environment. Any advice as to overcome this would be appreciated

![Fault](https://user-images.githubusercontent.com/120960899/208309356-94e5bd01-838c-4860-8c69-76b8688db445.JPG)
![List of installed packages](https://user-images.githubusercontent.com/120960899/208309358-d7796798-8c60-4b3f-bd31-16ce51905c68.JPG)

**Comment by carsen-stringer** [comment]
it looks like this is the wrapper you are using: https://github.com/BIOP/ijl-utilities-wrappers

please post the issue there. 

but it looks like they don't support cellpose 2, so you could try `pip uninstall cellpose` then `pip install cellpose==1.0.2`
