### ISSUE TITLE
Using different diameters for different channels. 

### ISSUE THREAD

**Issue by lacan** [MouseLand/cellpose#63]
In the cellpose.org site, several examples mention
> smallest diameter actually used is 15 pixels for cytoplasm model and 7.5 pixels for nuclei model to reduce computation time

Is this something that can be set somewhere?

Thanks for the great tool.

**Comment by carsen-stringer** [comment]
the website only allows diameters that small to reduce computation time, you can set diameter to whatever you want in the python package when you install it. 

If you want to segment the nucleus and the cytoplasm, you would have to run cellpose TWICE: once with the nucleus model on the nucleus channel using the diameter you can choose, and then once with the cytoplasm model on the cyto and nucleus channel using a different diameter you can choose. cellpose doesn't segment both at the same time.
