### ISSUE TITLE
 TypeError: __init__() got an unexpected keyword argument 'omni'

### ISSUE THREAD

**Issue by slives-lab** [MouseLand/cellpose#635]
When running the notebook (Cellpose_cell_segmentation_2D_prediction_only.ipynb) , I encounter the error when evaluating any image, including the example dataset (breast_vectra_0.tif): 

 TypeError: __init__() got an unexpected keyword argument 'omni'

Every combination of channel for segmentation was tried (channel 1 or 2). Are there specific requirements for the input tif images? Even generating the output files from the GUI and importing into the notebooks to output the respective images doesn't work (*npy, *png, *txt). The GUI can generate the images but there is no option to directly export all of the images. the *npy file should be able to be plotted, but they cannot be plotted easily using the notebooks. A clear explanation would be helpful

**Comment by carsen-stringer** [comment]
sorry please download the notebook again, this was a bug

**Comment by slives-lab** [comment]
I downloaded the notebook (https://github.com/MouseLand/cellpose/blob/main/notebooks/Cellpose_cell_segmentation_2D_prediction_only.ipynb), and ran it in colab. It uses a test image file, located in (/content/gdrive/MyDrive/test_imgs/).  However, running the "USE CELLPOSE TO SEGMENT CELLS" section results in an error:

NameError: name 'omni' is not defined

Any suggestions? thanks

**Comment by carsen-stringer** [comment]
oops sorry I missed that reference please try again, also I fixed the COLAB link at the top
