### ISSUE TITLE
Train new model

### ISSUE THREAD

**Issue by LuisaVossl** [MouseLand/cellpose#636]
Hii .. I try to train a new Model for my 3D tissue Cellcount, but when I do ctrl+T or go to“Models” menu in the File bar at the top and click “Train new model…” nothing happend. I just have one channel and so the nuclei channel is the first channel and not the CHAN2 is that a problem?

Best,
Luisa

**Comment by carsen-stringer** [comment]
sorry you cannot train a model on 3D images, you need to take 2D slices of the volume and train on those. then you can run your model with the 3D version of cellpose
