### ISSUE TITLE
Find classes in two packages

### ISSUE THREAD

**Issue by pburnham50** [MouseLand/cellpose#64]
Hi, I've been using cellpose for the past couple of months. But recently have been running into the following error:

Class RunLoopModeTracker is implemented in both /Users/pburnham/miniconda3/envs/cellpose/lib/python3.7/site-packages/cv2/.dylibs/QtCore (0x1a2e1be7f0) and /Users/pburnham/miniconda3/envs/cellpose/lib/libQt5Core.5.dylib (0x1a333b6a80). One of the two will be used. Which one is undefined.

I've tried uninstall/reinstalling cellpose as well as anaconda. Can you advise on how to address?

**Comment by pburnham50** [comment]
Running python -m cellpose produces a blank python pop-up windown when I get this warning/error.

**Comment by carsen-stringer** [comment]
have you tried downgrading cv2 (see install instructions)? are you using mac?

**Comment by carsen-stringer** [comment]
Is this what's happening in #69 @lauraluebbert ?

**Comment by lauraluebbert** [comment]
Yes, only that I get a white pop-up window. I am using a mac. Downgrading cv2 worked, thank you!

**Comment by carsen-stringer** [comment]
hurray! I'm going to close these issues but please comment if there are still problems
