### ISSUE TITLE
GPU version in Windows 11 not working - Torch issue?

### ISSUE THREAD

**Issue by morphogenetic2** [MouseLand/cellpose#640]
Hello there, I have been trying to run cellpose 2.2 with GPU acceleration in Windows 11. The CPU version works fine, but it's extremely slow when it comes to fine-tuning models.
My setup is as follows: Windows 11, driver 456.71 with CUDA 11.1, it's a 2060 super with 8 Gb VRAM.
```
 nvidia-smi
Sat Jan 14 13:31:00 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 456.71       Driver Version: 456.71       CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 206... WDDM  | 00000000:0A:00.0  On |                  N/A |
|  0%   44C    P8    21W / 175W |   1054MiB /  8192MiB |     27%      Default |
+-------------------------------+----------------------+----------------------+
```

I am using miniconda3 with python 3.9, and using the cellpose GUI version.
I am following the instructions from the github repo, installing cellpose and then uninstalling the pytorch CPU version and installing cudatoolkit 11.3 and pytorch with the command mentioned there. When I run the GUI, I get the following message:
```
2023-01-14 13:26:46,792 [INFO] WRITING LOG OUTPUT TO C:\Users\user\.cellpose\run.log
2023-01-14 13:26:46,792 [INFO]
cellpose version:       2.2
platform:               win32
python version:         3.10.8
torch version:          1.13.1
2023-01-14 13:26:47,022 [INFO] TORCH CUDA version not installed/working.
```

It used to work in the past (few months ago, maybe cellpose 2.0?) with the exact same setup, is there anything obvious I am missing?

Thanks in advance

**Comment by carsen-stringer** [comment]
Torch updated so the default version does not work with cudatoolkit 11.3,

please try 

```conda install pytorch==1.12.1 cudatoolkit=11.3 -c pytorch```

I will update the readme

**Comment by morphogenetic2** [comment]
It is working now, thank you very much!
