### ISSUE TITLE
Missing most cells in sparsely populated image [BUG]

### ISSUE THREAD

**Issue by binghama** [MouseLand/cellpose#645]
I have a sparsely-populated image of a membrane marker, which only binds to a few cells in the image. There is a low level of background from all the surrounding cells. When I ran segmentation using the built-in "cyto" model, it only segmented the cells with a much lower, background intensity and missed most of the cells I was actually trying to segment. I assumed this may be due to some normalization process where my brighter-than-background signal is being classified as noise and therefore is ignored during segmentation. If so, it there a way to disable this normalization step?

Here's what I did:
Ran the following on the command line with my one attached input image (grayscale, single channel tif):
`python -m cellpose --dir /gpfs/gsfs12/users/Zhaolab/4_Picasso-Mouse/2_ROIcrop/tumor_ex_membrane/ --pretrained_model cyto --chan 0 --chan2 0 --diameter 0. --save_tif --verbose --no_npy`

I've attached the input image, the output mask file from cellpose, and an overlay I made in napari that visualizes how several bright membranes were missed (called CD8_overlay.png) as a zip.

Thanks in advance.

[CP_issue.zip](https://github.com/MouseLand/cellpose/files/10504653/CP_issue.zip)

**Comment by binghama** [comment]
UPDATE (no answer yet):

My current images only have a few cells that are relevant to segment. Thinking the sparse number of cells in the image may be a problem, I tried creating an image where I pasted a number of one relevant cell (seen at the top of the image on the left) all around the image (see image on the right). The contrast limits were not altered in the doctored image.

![image](https://user-images.githubusercontent.com/80488082/214930701-b5567719-4a0f-448d-93ba-6abcc3bf4799.png)

What I found is that in the doctored image, the membranes are segmented beautifully while in the original image, even the cell copied everywhere in the doctored image was not detected (see screenshot below).

![image](https://user-images.githubusercontent.com/80488082/214931736-a22a2046-1fad-496a-8f99-3beade58ee77.png)

Is there a way to more successfully segment sparsely populated images in Cellpose? I tried running both my original and doctored images with the "--no_norm" argument but when I did this the model found no cells in either image.

When running with normalization, this was my command: `cellpose --dir /gpfs/gsfs12/users/Zhaolab/4_Picasso-Mouse/2_ROIcrop/tumor_ex_membrane/Chen_test/ --pretrained_model cyto --chan 0 --chan2 0 --diameter 0. --save_png --verbose --no_npy --use_gpu`


Without normalization, this was my command: `cellpose --dir /gpfs/gsfs12/users/Zhaolab/4_Picasso-Mouse/2_ROIcrop/tumor_ex_membrane/Chen_test_noNorm/ --pretrained_model cyto --chan 0 --chan2 0 --diameter 0. --save_png --verbose --no_npy --use_gpu --no_norm`

The files I ran and outputs are in the attached zip. Thanks again.

[PD1_test.zip](https://github.com/MouseLand/cellpose/files/10512761/PD1_test.zip)

**Comment by Wulin-Tan** [comment]
same question. bright parts are missing.

**Comment by FrickTobias** [comment]
@Wulin-Tan @binghama I do not think this is a bug. Did you search for solutions in previous issues or the documentation? I believe there are **very similar questions** which have been asked before which you will find if you look into the search function in the issues tab.

I would recommend this issue to be closed.

FYI: The `.tif` image you attached seems to be corrupt and cannot be opened.

**Comment by binghama** [comment]
Solved, see: https://forum.image.sc/t/cellpose-missing-most-cells-in-sparsely-populated-image/76444
