### ISSUE TITLE
cell body and celluar processes segmentation

### ISSUE THREAD

**Issue by Wulin-Tan** [MouseLand/cellpose#648]
Hi, cellpose team
this tool is wonderful for my projects.
Is there any way to segment cell body as well as cellular processes with cellpose?
I found that when I restricted the cell size, cellpose could work pretty well to recognize cell body, but ignoring cellular processes. When I increase the restriction, cellpose just recognize the background.
And suggestions for both cell body and celluar processes segmentation?
Thank you.
Wulin

**Comment by carsen-stringer** [comment]
I think you need to label your data and try to train a custom model, using the approach of Cellpose 2 (https://www.youtube.com/watch?v=5qANHWoubZU). let us know if this still doesn't work
