### ISSUE TITLE
Run cellpose from command line gives IndexError

### ISSUE THREAD

**Issue by qztseng** [MouseLand/cellpose#65]
By running the following command:
`python -m cellpose --use_gpu --dir /home/lis-paul/cellpose/test_image/ --pretrained_model nuclei --diameter 0. --save_png`

I got the error:
```Traceback (most recent call last):
  File "/home/lis-paul/miniconda3/envs/cellpose/lib/python3.7/runpy.py", line 193, in _run_module_as_main,  "__main__", mod_spec)

  File "/home/lis-paul/miniconda3/envs/cellpose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)

  File "/home/lis-paul/cellpose/cellpose/__main__.py", line 174, in <module>
    io.masks_flows_to_seg(images, masks, flows, diams, image_names, channels)

  File "/home/lis-paul/cellpose/cellpose/io.py", line 62, in masks_flows_to_seg
    flowi.append(np.zeros(flows[1][0].shape, dtype=np.uint8))

IndexError: list index out of range
```

After checking the io.py source code, I think the line62 might miss a [n] index:
`flowi.append(np.zeros(flows[n][1][0].shape, dtype=np.uint8))`
Since I cannot figure out what was your intention here to append an empty array to flowi, that is my best guess.....

By the way, it would be nice to have a command line option to only save the mask.png without the npy file, since it is very often what user really need in batch process and the npy file is relatively large.

**Comment by carsen-stringer** [comment]
sorry this is fixed in the github but not yet in the pip. zeros are for Z flows (set to zero for 2D images).

good point I've added a flag --no_npy to suppress npy output.
