### ISSUE TITLE
Collective cell dynamics from masks

### ISSUE THREAD

**Issue by directysj** [MouseLand/cellpose#652]
Hello cellpose developers,

A great cell segmentation package. I would like to analyze cellular dynamics from the masks obtained from cellpose. I read the manual but couldn't find it there. Please refer if I missed it. Can I ask if you know any package/code to use for the dynamics? Any suggestions/comments? 

Thanking you in advance!

Regards,
Jalim

**Comment by carsen-stringer** [comment]
what are the sorts of dynamics that are expected? do you have a reference paper?

generally speaking we recommend using something like TrackMate for stitching across time with cellpose and for trajectory analysis

**Comment by directysj** [comment]
Thank you so much. TrackMate looks cool...

I would like to compute like cellular mean-squared displacement.
