### ISSUE TITLE
[BUG] Typo in the code

### ISSUE THREAD

**Issue by ariannaravera** [MouseLand/cellpose#658]
Hello,
in line 354 of file "io.py" in folder "cellpose":
 _'masks': masks.astype(np.uint16) if **outlines**.max()<2**16-1 else masks.astype(np.uint32)_

I think it should be:
 _'masks': masks.astype(np.uint16) if **masks**.max()<2**16-1 else masks.astype(np.uint32)_

**Comment by mrariden** [comment]
I understand the change for consistency, but the functionality should be the same. `masks` and `outlines` should be indexed the same. The check in that line is to use a larger data type if there are too many masks/outlines in the image. 

Do you notice a change in functionality when you test it either way?

**Comment by carsen-stringer** [comment]
this is not a bug
