### ISSUE TITLE
win10 numpy requirement  incompatible

### ISSUE THREAD

**Issue by EkilGitHub** [MouseLand/cellpose#66]
![image](https://user-images.githubusercontent.com/29229492/81802132-1de5ba00-9548-11ea-81e6-0b74968cea5b.png)

**Comment by carsen-stringer** [comment]
can you try downgrading mxnet-mkl?
~~~
pip install mxnet-mkl==1.5.0
~~~

**Comment by EkilGitHub** [comment]
yes, 1.5.0 works.

**Comment by EkilGitHub** [comment]
> 您可以尝试降级mxnet-mkl吗？
> 
> ```
> pip install mxnet-mkl==1.5.0
> ```

yes, 1.5.0 works.

**Comment by carsen-stringer** [comment]
great going to close this issue then
