### ISSUE TITLE
Image resolution reduction issue

### ISSUE THREAD

**Issue by wang748** [MouseLand/cellpose#665]
Thanks to the developer for inventing such a powerful cell segmentation software, which makes me admire from the bottom of my heart. Now I have a tissue image with a resolution of 30,000×30,000. If I directly import this image into cellpose for cell segmentation, my computer will run out of memory and cannot get the result (i9-10920X CPU and RTX4090 GPU) . So if I change the resolution of this image to 10,000×10,000, will it reduce the segmentation effect of cellpose?

**Comment by mrariden** [comment]
It depends on the size of the objects in the image. By default, the pretained models are tuned to segment object that are 30 pixels in diameter. Cellpose is designed to resize the image and force the objects to be 30 pixels even if you have extremely high resolution images. There is some more information for the diameter resizing here: https://cellpose.readthedocs.io/en/latest/settings.html

Without knowing about your data, my guess is that downscaling before using cellpose is not an issue.
