### ISSUE TITLE
ValueError: labels not provided with correct --mask_filter

### ISSUE THREAD

**Issue by huyen-spec** [MouseLand/cellpose#667]

**Comment by huyen-spec** [comment]
I was running the notebook on training a with custom dataset.

file name is like this;

img_0_masks.tif
img_0.tif

**Comment by CHANYUKUO** [comment]
Try: "_masks"
from the code, it seems like only npy file need to specify extension
if you have .png or tif, just use "_masks"

**Comment by carsen-stringer** [comment]
thanks @CHANYUKUO for the answer, yes that's correct
