### ISSUE TITLE
[BUG] Training model - slash vs. antislash in file path

### ISSUE THREAD

**Issue by ctolosal** [MouseLand/cellpose#671]
Hi !

I'm trying to train a model to fit my livecell images from the pre-existing livecell model.

I chose an image from a folder and ran livecell segmentation, after doing some corrections I saved the masks (Ctrl+S). I then clicked on Models -> Train new model with image+ masks in folder and named the model. When clicking on Ok, I can see the training happening in the prompt window, however the training stops at the following command : "saving networks parameters to C:/Users/....../folder_name\models/model_name"

After that, I have some command lines and finally the following error : "RuntimeError: Parent directory C:/Users/.../folder_name\models does not exist"

I can see that there's an antislash instead of a forward slash right before the newly created models folder and guess that's why the folder can't be found... Do you guys know how can I fix this problem ?

Thank you !

**Comment by carsen-stringer** [comment]
I have not seen this happen on windows before can you please give your full environment info? (the output of `conda list`)

**Comment by TheSoulMaker** [comment]
The same problem happens after updating with "pip install cellpose --upgrade", should I reinstall evrything ?

**Comment by mrariden** [comment]
I not sure if this will work but, @TheSoulMaker can you go to the `core.py` file, open it with a text editor, and edit line 858 to not have a slash after `'models/'`? So it will be just `'models'`.

The file should be at `C:\Users\Vladimir\.conda\envs\cellpose\lib\site-packages\cellpose\core.py` for you.

**Comment by TheSoulMaker** [comment]
Thank you for your answer. I tried and I have the same error but this time it doesn't seem to find the folder, even if it exists. 
![image](https://github.com/MouseLand/cellpose/assets/106664267/bc63daac-4651-4b99-8c8c-d8903c442206)

**Comment by TheSoulMaker** [comment]
Hi ! I figured out the problem ! 
There was an accent in the name of one of the folders in the path "Thèse".
I removed it and it worked  ! 
To be clear there is no need to change the core.py  !
THank you for your help !
