### ISSUE TITLE
[INSTALL] Cellpose froze after install and upon open 

### ISSUE THREAD

**Issue by Notoobad** [MouseLand/cellpose#672]
**Install problem**
Cellpose froze after install and upon open. No error message was given and is just stuck. NVIDIA RTX A4500. 

**Environment info**
(cellpose2) C:\Users\Lab_WStation>conda list
$ # packages in environment at C:\Users\Lab_WStation\anaconda3\envs\cellpose2:
Name                    Version                   Build  Channel
blas                      1.0                         mkl
ca-certificates           2023.01.10           haa95532_0
cellpose                  2.2                      pypi_0    pypi
certifi                   2022.12.7        py39haa95532_0
click                     7.1.2                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
cudatoolkit               10.2.89              h74a9793_1
fastremap                 1.13.4                   pypi_0    pypi
flit-core                 3.6.0              pyhd3eb1b0_0
imagecodecs               2023.1.23                pypi_0    pypi
intel-openmp              2021.4.0          haa95532_3556
libuv                     1.44.2               h2bbff1b_0
llvmlite                  0.39.1                   pypi_0    pypi
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py39h2bbff1b_0
mkl_fft                   1.3.1            py39h277e83a_0
mkl_random                1.2.2            py39hf11a4ad_0
natsort                   8.3.1                    pypi_0    pypi
ninja                     1.10.2               haa95532_5
ninja-base                1.10.2               h6d14046_5
numba                     0.56.4                   pypi_0    pypi
numpy                     1.23.5           py39h3b20f71_0
numpy-base                1.23.5           py39h4da318b_0
opencv-python-headless    4.7.0.72                 pypi_0    pypi
openssl                   1.1.1t               h2bbff1b_0
packaging                 23.0                     pypi_0    pypi
pip                       22.3.1           py39haa95532_0
pygments                  2.14.0                   pypi_0    pypi
pyqt5                     5.15.4                   pypi_0    pypi
pyqt5-plugins             5.15.4.2.2               pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.11.1                  pypi_0    pypi
pyqt5-tools               5.15.4.3.2               pypi_0    pypi
pyqtgraph                 0.13.2                   pypi_0    pypi
python                    3.9.16               h6244533_1
python-dotenv             1.0.0                    pypi_0    pypi
pytorch                   1.8.2           py3.9_cuda10.2_cudnn7_0    pytorch-lts
qt5-applications          5.15.2.2.2               pypi_0    pypi
qt5-tools                 5.15.2.1.2               pypi_0    pypi
qtpy                      2.3.0                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                65.6.3           py39haa95532_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.40.1               h2bbff1b_0
superqt                   0.4.1                    pypi_0    pypi
tifffile                  2023.2.28                pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
typing_extensions         4.4.0            py39haa95532_0
tzdata                    2022g                h04d1e81_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.38.4           py39haa95532_0
wincertstore              0.2              py39haa95532_2

**Run log**
(cellpose2) C:\Users\Lab_WStation>cellpose
2023-03-06 12:52:35,110 [INFO] WRITING LOG OUTPUT TO C:\Users\Lab_WStation\.cellpose\run.log
2023-03-06 12:52:35,110 [INFO]
cellpose version:       2.2
platform:               win32
python version:         3.9.16
torch version:          1.8.2

**Comment by carsen-stringer** [comment]
please give the full install information? your torch version is pretty old, please try our default install instructions in a clean environment (probably want python=3.8) and see if you don't get an error: https://github.com/MouseLand/cellpose#instructions
