### ISSUE TITLE
specify model name from command line for training

### ISSUE THREAD

**Issue by directysj** [MouseLand/cellpose#673]
Hello,

I segmented the first image using `cellpose[gui]` with the `LC1 `model and saved the masks as `"_seg.npy"` and then trained the model which is saved in the models directory within the images directory. I segmented the next image using this model, which is working fine. As a next step, I am training on other images and training new models on the HPC cluster (where I can utilize the GPU option) using command line options in a bash script, which are provided below:

```
source activate cellpose
 ```
 ################### Define Cellpose parameters #####################
```
 diam=0.0
 flowth=0.65
 cpth=1.5
```
 
 Option (1)
```
 python -m cellpose --use_gpu --verbose --train --mask_filter _seg.npy --dir ${dirImgs}/ --pretrained_model ${dirImgs}/models/CP_allCondsJS_1 --add_model ${mDir}  --n_epochs  100  --chan 0 --chan2 1 --diameter ${diam} --flow_threshold ${flowth} --cellprob_threshold ${cpth}
```
Option (2)
```
 python -m cellpose --use_gpu --verbose --train --mask_filter _seg.npy --dir ${dirImgs}/ --pretrained_model LC1 --add_model ${mDir} --n_epochs 100 --chan 0 --chan2 1 --diameter  ${diam} --flow_threshold ${flowth} --cellprob_threshold ${cpth}
```

Here, `$dirImgs` and `$mDir` are absolute paths. The training is completed as usual without any errors. After training, using any one of these command line options, I copied the model file to my desktop and tried to segment any new image which is not segmenting as it was doing in the GUI mode above. 

One more thing, can a user-defined model name be possible using command line options because by default the cellpose is providing a very long model name in the models directory? 

Thank you in advance!

Regards,
Jalim

**Comment by directysj** [comment]
> Hello,
> 
> I segmented first image using `cellpose[gui]` with the `LC1 `model and saved the masks as `"_seg.npy"` and then trained the model which is saved in the models directory within the images directory. I segmented next image using this model, which is working fine. As a next step, I am training on other images and training new models on the HPC cluster (where I can utilize the GPU option) using command line options in a bash script, which are provided below:
> 
> ```
> source activate cellpose
> ```
> 
> ################### Define Cellpose parameters #####################
> 
> ```
>  diam=0.0
>  flowth=0.65
>  cpth=1.5
> ```
> 
> # Option (1)
> ```
>  python -m cellpose --use_gpu --verbose --train --mask_filter _seg.npy --dir ${dirImgs}/ --pretrained_model ${dirImgs}/models/CP_allCondsJS_1 --add_model ${mDir}  --n_epochs  100  --chan 0 --chan2 1 --diameter ${diam} --flow_threshold ${flowth} --cellprob_threshold ${cpth}
> ```
> 
> Option (2)
> 
> ```
>  python -m cellpose --use_gpu --verbose --train --mask_filter _seg.npy --dir ${dirImgs}/ --pretrained_model LC1 --add_model ${mDir} --n_epochs 100 --chan 0 --chan2 1 --diameter  ${diam} --flow_threshold ${flowth} --cellprob_threshold ${cpth}
> ```
> 
> Here, `$dirImgs` and `$mDir` are absolute paths. The training is completed as usual without any errors. After training, using any one of these command line options, I copied the model file to my desktop and tried to segment any new image which is not segmenting as it was doing in the GUI mode above.
> 
> One more thing, can a user-defined model name be possible using command line options because by default the cellpose is providing a very long model name in the models directory?
> 
> Thank you in advance!
> 
> Regards, Jalim

The model file was correct, the problem was how I was implementing it. When I added the newly trained model through GUI, it works with option (2) described above.

However, the cellpose is giving the longer name of the model file with the command-line option, like cellpose_residual_on_style_on_concatenation_off_dirName_2023_03_15_19_56_16.772848 .  Is there any possibility to give a user-defined model file name in the command-line?

**Comment by mrariden** [comment]
You should be able to specify the absolute path of any local model using just the `--pretrained_model` flag. You do not need to use the `--add_model` flag when doing this.

**Comment by carsen-stringer** [comment]
thanks @mrariden for helping here. @mrariden can you please add a flag to the training from the CLI to specify a name for the model for the user?
