### ISSUE TITLE
Exporting measurements from a segmented image

### ISSUE THREAD

**Issue by richardwfrancis-pyc** [MouseLand/cellpose#676]
Thank you for your work on this excellent software.
Please forgive my ignorance here but is there a way to export a set of measurements from the segmented images? Our interest is mainly in obtaining geodesic diameter and cell density. I've not been able to find anything in the docs other than the output of files to be read by ImageJ or similar to calculate these kinds of things. It would be useful to know if I've missed something obvious here.
Many thanks in advance.

**Comment by mrariden** [comment]
Thanks for your interest! Cellpose does not have the functionality to output the measurements you mention. While the purpose of cellpose is strictly for instance segmentation, you can string together other libraries to complete the task you have in mind after using cellpose to compute the image segmentation. For example, you can use the API to calculate masks and then use something like scikit-image or cv2 to get your measurements of interest. An example of using the API can be found here: https://cellpose.readthedocs.io/en/latest/notebook.html. 

Alternatively, you can output your segmented image masks and do further processing in ImageJ like you mentioned.
