### ISSUE TITLE
[FEATURE] Extracting Cellpose segment coordinates from the .npy files to be used for a new SarcApp program

### ISSUE THREAD

**Issue by davalencia0914** [MouseLand/cellpose#678]
**Describe the solution you'd like**
I work with cardiomyocytes and a new program, SarcApp, was released that allows for deep-learning binarization of images, followed by many automated measurements for sarcomeres in these cells. SarcApp has their own segmentation code within the program, but it's not nearly as good as Cellpose. I would like to extract the coordinates of the cell segments from Cellpose, likely from the _seg.npy file, to incorporate into the SarcApp program that I use so I can get clear, single-cell measurements. The creator of SarcApp gave me a template to work with and I just needed to add a method to extract the coordinates of the outlines in an array of some sort. I'm still very novice at coding and honestly used Chat GPT to help produce some of the below code for the CellPoseEdge function. If you have any advice on what more to do, it would be greatly appreciated. I've been currently getting the below error:

contour = measure.find_contours(label_mask[i-1], 0.5)
  File "/Users/nakanolab/opt/anaconda3/envs/sarcApp/lib/python3.10/site-packages/skimage/_shared/utils.py", line 282, in fixed_func
    return func(*args, **kwargs)
  File "/Users/nakanolab/opt/anaconda3/envs/sarcApp/lib/python3.10/site-packages/skimage/measure/_find_contours.py", line 138, in find_contours
    raise ValueError("Input array must be at least 2x2.")
ValueError: Input array must be at least 2x2.

Here's the link to the SarcApp github for reference: https://github.com/abbieneininger/sarcApp

I was considering using reshape to reshape the array, but think that would definitely mess up the locations of the cell outlines. The code is below (what is ##'ed out was me trying to troubleshoot the array size):

import numpy as np
import os
from alpha_shapes.alpha_shapes import Alpha_Shaper
from scipy import ndimage
from skimage import measure

#make a list to store the loaded masks
masks = []

#loading the .npy files from Cellpose for the segmentation coordinates to be extracted from
for file in os.listdir("/Users/nakanolab/Desktop/Cellpose_Outlines"):
    if file.endswith(".npy"):
        mask = np.load(os.path.join("/Users/nakanolab/Desktop/Cellpose_Outlines", file), allow_pickle=True).item()
        #mask_data = list(mask.values())
        #mask = np.array(mask_data)[:, np.newaxis]
        #mask = mask.astype(float)
        #print(mask.dtype)
        #print(mask.shape)
        #Currently (12,1) shape 2D Array w/ np.newaxis text
        masks.append(mask)
    
def CellPoseEdge(mask, xres):
    contours = []
    labels, num_features = ndimage.label(mask)
    slices = ndimage.find_objects(labels)
    for s in slices:
        if s is not None:
            label_mask = (labels[s] == np.arange(1, num_features+1)[:,None,None])
            for i in range(1, num_features+1):
                contour = measure.find_contours(label_mask[i-1], 0.5)
                contours.append(contour[0] + np.array(s.start))
    for contour in contours:
        contour[:, 0] += s[0].start
        contour[:, 1] += s[1].start
    x = contour[0]
    y = contour[1] / xres #don't forget to account for the pixel size
    points = np.stack((x,y), axis=1)
    shaper = Alpha_Shaper(points)
    alpha_opt, alpha_shape = shaper.optimize()
    alpha = 6.0 #this is a good starting point for alpha, see below
    while alpha > 0:
        alpha_shape = shaper.get_shape(alpha = alpha)
        try:
            edgeX, edgeY = alpha_shape.exterior.coords.xy
        except AttributeError:
            alpha -=1
        else:
            break
    edgeX = np.array(edgeX)
    edgeY = np.array(edgeY)
    return edgeX, edgeY, alpha_shape

**Comment by carsen-stringer** [comment]
The cells are saved in the `masks`, or do you need a list of outlines? I would use this function: https://github.com/MouseLand/cellpose/blob/b709064b47fde7c3fb0011c71905c11a75b956e2/cellpose/utils.py#L222

but this is not something for us to support, please ask the developer of the other application for help as we don't know their needs
