### ISSUE TITLE
[BUG] IndexError when training sizemodel on dataset with empty masks

### ISSUE THREAD

**Issue by jraufeisen** [MouseLand/cellpose#679]
**Describe the bug**
While trying to train a `SizeModel` myself, I encountered runtime errors in the `train()` method.

**To Reproduce**
Here is a sample to reproduce this error. For the sake of simplicity, this is just artificial data here.
The first element of `labels` is a full-zero matrix (-> no masks)

```
model = models.Cellpose(model_type='cyto')
image_shape = (3, 256, 256)
images = [np.ones(image_shape), np.ones(image_shape)]
labels = [np.zeros(image_shape), np.ones(image_shape)]
model.sz.train(images, labels, n_epochs=2, batch_size=1)
```

**Run log**
The stacktrace points to `cellpose/models.py`
```
# remove images with no masks
for i in range(len(diam_train)):
    if diam_train[i]==0.0:
>       del train_data[i]
E       IndexError: list assignment index out of range
```

**Comment by carsen-stringer** [comment]
it looks like you have images with no masks, therefore you can't train a size model
