### ISSUE TITLE
Multiplex image segmentation; cells lacking nuclear DAPI staining

### ISSUE THREAD

**Issue by JessicaP94** [MouseLand/cellpose#684]
Hello, I am trying to cell segment a 7-channels multiplex image training a model on the CP one. Some of my cells do not have any DAPI signal so I would like to overlap multiple cell segmentations by manually drawing the more difficult ones. When trying the CP model, I could detect only few cells.

![image](https://user-images.githubusercontent.com/113768413/229929726-b81beb74-4276-425e-87a0-2dbc87acc472.png)

Thank you for your work

**Comment by mrariden** [comment]
I'm not sure I understand your request. I think you want to use different channels to segment using cellpose. For this you can add together channels that are morphologically similar and run cellpose on the result. Cellpose can only segment 2 channels at a time. You can do this combination with something like ImageJ.

If you want to use different channels to segment your image and combine the resulting masks, there is no way to do this using Cellpose. You would have to export the masks and combine them in another program. 

Please clarify if I'm misunderstanding you.

**Comment by JessicaP94** [comment]
Hello Michael,
yes, I wanted to combine the resulting masks ideally. Thank you for your
time.

**Comment by mrariden** [comment]
I see; unfortunately there is no way to do this currently in cellpose. But this is a potential enhancement that may be added in the future.

In the meantime, it would be possible to combine distinct mask files using an image processing tool like ImageJ or even cellprofiler. If you want to load the masks back into the cellpose GUI, you will have to make sure that the masks are in the same format as cellpose outputs, (png with 0 background and each object with a unique label with no gaps in the IDs). Also, you will have to ensure that the output is a single channel/BW image. Then, you could use the "load from PNG" option in the GUI to load this processed mask with the original image.
