### ISSUE TITLE
How does diameter affect the running results of cellpose?

### ISSUE THREAD

**Issue by Tianshuiyue** [MouseLand/cellpose#686]
In my images, diameter estimation is not very accurate and frequently requires empirical setting of diameter values. I want to know how does diameter affect the running results of cellpose and which function does the diameter affect the cell segmentation results in the codes. I hope to make modifications directly in the code, so I want to understanding this issue. Thank you!

**Comment by carsen-stringer** [comment]
we recommend to set the diameter manually, the network has been trained with all images made to have cells with the same diameter size, so the algorithm is sensitive to how you set it
