### ISSUE TITLE
How to manually label 3D images?

### ISSUE THREAD

**Issue by Tianshuiyue** [MouseLand/cellpose#687]
I want to annotate my 3D image. After manually labeled on each plane in the Cellpose graphical user interface, the mask file can only be saved as *_seg.npy. Can it be saved as PNG/tif?

In your paper, it says 'We allowed the annotator to potentially skip ‘easy’ planes while drawing a cell, with an algorithm automatically interpolating the shapes of cells in those planes.' in Methods section. 

How to skip ‘easy’ planes while drawing a cell? I tried to turn off 'single stroke' and skip one plane after drawing one. Then the result was bad as the picture below. Is my operation incorrect?
![image](https://user-images.githubusercontent.com/97023245/230302205-f2ccaeca-c276-4f88-aa47-bfe90205f99b.png)

And where is the automatically interpolation algorithm in the codes? How does it work?

**Comment by mrariden** [comment]
Closed due to inactivity
