### ISSUE TITLE
Transition from training to application in research

### ISSUE THREAD

**Issue by babbleh** [MouseLand/cellpose#690]
I'm using cellpose for research in a genomics lab that does not have much experience with DL/image segmentation tasks. I've struggled to find a consensus online for when to transition a model from training to application in research so I wanted to ask this community: how/when do you move the model into application? 

I'd planned on achieving >95% accuracy and >0.8 IoU in comparison to a small set annotated images (only used to benchmark model performance, not train). Is there a best practice standard for these metrics that should be met before the model is implemented? Specifically, is there a consensus on a quantitative threshold for a model to be successful or is it inevitably a combination of quantitative analysis and a qualitative assessment of model performance?

**Comment by carsen-stringer** [comment]
There is some discussion of this on forum.image.sc: [evaluation discussion](https://forum.image.sc/t/how-to-interpret-cellposes-average-precision-model-evaluation-value/75231/3)

Generally speaking you want to do as well as a human -- so if you label the same image twice what is the accuracy? It actually is likely not to be that high. You can see our results from this analysis in our Cellpose 2 [paper](https://www.nature.com/articles/s41592-022-01663-4)

Maybe this is good info for the FAQ @mrariden ?
