### ISSUE TITLE
nuclei Model

### ISSUE THREAD

**Issue by AlexandraLoewe** [MouseLand/cellpose#691]
i want to run cellpose on a hpc where scripts have no rights to load for example models from the internet. therefore i have to load the models beforehand and copy them to the hpc. the nuclei model achieves the best results in the gui variant, however i can only load the nucleitorch models which achieve much worse results. can i still download the nuclei model somewhere?

**Comment by mrariden** [comment]
When you click on the nuclei button in the GUI, cellpose downloads and uses the model found at https://www.cellpose.org/models/nucleitorch_0. If you are getting different results when you use the nucleitorch model without the GUI, I'd double check that you're defining the correct channels. Here's info on setting the correct channels for CLI/API usage: https://cellpose.readthedocs.io/en/latest/settings.html.

Also, the default is to auto adjust the saturation in the CLI/API which you may have turned off in the GUI. I'd try running the code with using the `--no_norm` flag in the CLI or `normalize` set to `False` in your `Cellpose.eval()`call. Additionally, the `diameter`, `flow_threshold`, `cellprob_threshold`, and `stitch_threshold` parameters will need to be adjusted if you change them in the GUI.

**Comment by carsen-stringer** [comment]
thanks @mrariden for answering this. 

btw @mrariden  can we please add this [info](https://github.com/MouseLand/cellpose#download-of-pretrained-models) to an FAQ on how to download all the models and use them on a computer without download permissions?
