### ISSUE TITLE
large cells issues

### ISSUE THREAD

**Issue by HernandoMV** [MouseLand/cellpose#692]
Hi, I am not sure if there is anything I am doing wrong but here is the behaviour I am seeing with images that contain only one large cell. I am retraining the model, but I cannot get it to correctly show the mask, even though that the prediction (cell probability) is very good. Maybe there are some issues with the edges of the image, I don't know. A few screenshots to illustrate the problem. Note that the decrease in threshold removes the predicted ROI.

**1. Image with 2.3 threshold.**
![image](https://user-images.githubusercontent.com/6049065/232517458-0fbaa3e9-5042-4e12-a385-665b903f363a.png)

**2. Cell probability**
![image](https://user-images.githubusercontent.com/6049065/232518391-62c59efb-7922-49d3-8b14-162165887f90.png)

**3. Decrease in threshold** -> mask gone
![image](https://user-images.githubusercontent.com/6049065/232518567-e2114e2b-009b-47f3-a929-9373b2ed2023.png)

**Comment by ashishUthama** [comment]
Does changing flow_threshold help get it back?

**Comment by HernandoMV** [comment]
no, I played around with many parameters for the other two threholds and they don't seem to influence the results whatsoever

**Comment by HernandoMV** [comment]
I ended up extracting the flows from the _seg.npy files and thresholding them to get the masks.

**Comment by Svidro** [comment]
Cross posting this here since I found this issue when looking for the previous post about a similar issue. https://forum.image.sc/t/cellpose-failing-to-produce-masks-despite-obvious-flows-and-cellprobs/86849/4?u=research_associate
