### ISSUE TITLE
Recomendations for small vessels segmentation 

### ISSUE THREAD

**Issue by Yasmin-Kassim** [MouseLand/cellpose#694]
First question: I need to segment small vessels, I would like to know which parameters need to be changed in the training and also in the testing process to make it suitable to such task given that my vessels are different in length, see the image 

Second question: In one of your notebooks there is a variable, called 'omni'
omni= False #@param {type:"boolean"} If cells are elongated or have branches, tick this. It will use omnipose
what is this parameter ? and I don't see it as input neither to the training process nor the the eval process, I don't see anything called omnipose, please clarify how am I suppose to use it

**Comment by mrariden** [comment]
Hi @Yasmin-Kassim, omnipose and any omni references should be phased out of cellpose, but is still available at their github repo. Their post processing is different that the current implementation of cellpose, and is designed to be more effective for large aspect ratio objects (long, spindly things). For current, supported version of cellpose you should not need any references to omnipose/omni. **Can you point to where it is so we can amend those notebooks?**

As for training new models, there isn't anything from a first-principles answer that will predict what you need to change. Playing with the options available in the GUI is a good place to start. There is a forum at https://forum.image.sc/tag/cellpose for many already answered issues relating to training/tuning new models.
