### ISSUE TITLE
Installation of new pytorch version via Anaconda prevents GUI from opening 

### ISSUE THREAD

**Issue by naboughali** [MouseLand/cellpose#699]
I received a "TORCH CUDA version not installed/working" error in Cellpose and installed the newest version of Pytorch via Anaconda using this line: 
**conda install pytorch torchvision -c pytorch**

When I open the user interface using the 'python -m cellpose' line, I get a traceback with this error as the final line: 
**'SystemError: initialization of _internal failed without raising an exception'**

Any ideas on how to get Cellpose up and running again?

**Comment by mrariden** [comment]
cellpose installs pytorch via pip, so switching to a conda installation might be the source of this issue. 

You can (1) try to install the `pytorch` and `torchvision` packages via `pip` by calling `pip install torch torchvision` while in your activated cellpose environment. Or (2) wipe the existing and problematic conda env and reinstall it using the installation instruction on the readme/docs. 

Let me know if that works!

**Comment by carsen-stringer** [comment]
I actually think this error may be caused by a conflict between numba (too old) and numpy (>=1.24.0), although pytorch could be the culprit too. I fixed this error on my local computer with `pip install numba --upgrade`

**Comment by naboughali** [comment]
Hi all, I tried to install the pytorch and torch vision packages as well as update numba. Both attempts failed to load the UI- I will remove the problematic env and re-install through conda.

Thanks for your help!

From: Michael Rariden ***@***.***>
Date: Friday, May 5, 2023 at 8:31 PM
To: MouseLand/cellpose ***@***.***>
Cc: Naira Abou-Ghali ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [MouseLand/cellpose] Installation of new pytorch version via Anaconda prevents GUI from opening (Issue #699)

cellpose installs pytorch via pip, so switching to a conda installation might be the source of this issue.

You can (1) try to install the pytorch and torchvision packages via pip by calling pip install torch torchvision while in your activated cellpose environment. Or (2) wipe the existing and problematic conda env and reinstall it using the installation instruction on the readme/docs.

Let me know if that works!
