### ISSUE TITLE
Heterogeneous cells and diameter choice 

### ISSUE THREAD

**Issue by Dana162001** [MouseLand/cellpose#700]
Hi, first of all, I want to thank you for creating such a great segmentation tool! I use it intensively to improve our segmentation of heart tissue and I was hoping maybe you can help me to solve a few problems.

Heart tissue is very heterogeneous and there are cells of all different sizes from 35 up to 700 pixels in diameter in one image when I use a higher value of diameter small cells are not detected (even if there is DAPI staining inside), and with a lower value of diameter, the situation is consequently opposite. I also used higher flow_threshold = 0.8, as a result, there are more segmented cells, but not a small one. Could you suggest a possible solution to this problem? I would be grateful for any information.

If I do training and use a pre-trained cyto2 model the mean diameter can not be changed from 30, but as I already mentioned in our tissue most of the cells are bigger than 300 pixels. How strongly does it affect the final result of the training and is there any way how to overcome it?

Thank you in advance for your help! I am also attaching some of the images of the tissue on which I am currently working and the results of the segmentation.

![Screenshot 2023-05-05 at 10 25 40](https://user-images.githubusercontent.com/104983076/236410672-abf322b8-4774-4219-956e-ccd52e42ca34.png)
![Screenshot 2023-05-05 at 10 26 23](https://user-images.githubusercontent.com/104983076/236410762-e69b54db-9420-4397-bd65-21f2392f84d9.png)
![Screenshot 2023-05-05 at 10 27 24](https://user-images.githubusercontent.com/104983076/236410941-bae032ad-7512-45ab-8ab3-0d5d0fe4fc6c.png)
![Screenshot 2023-05-05 at 10 28 10](https://user-images.githubusercontent.com/104983076/236411085-d2c110de-565a-4ee3-bcf9-3589a508c7e2.png)

**Comment by ashishUthama** [comment]
Have you considered combining results from two (or more) runs with different diameters? 

You may need to do some additional post-processing ("non max suppression") in a different tool/environment in case you end up with overlapping detections.

**Comment by Dana162001** [comment]
Thank you for your answer! Exactly the overlapping is a problem, but we will try to explorer it more.

**Comment by Dana162001** [comment]
Thank you for your answer! Exactly the overlapping is a problem, but we will try to explorer it more.
