### ISSUE TITLE
[FEATURE] Disable autosave in GUI

### ISSUE THREAD

**Issue by pvtodorov** [MouseLand/cellpose#703]
**Is your feature request related to a problem? Please describe.**
I would like to not autosave my masks after every manual edit in the Cellpose GUI. This appears to write a massive GB-sized file each time I edit a single mask. This is slowing me down as Cellpose writes and I am concered it is putting too many write operations on my laptop's SSD.

**Describe the solution you'd like**
A flag to disable autosave when starting up the gui.

**Comment by carsen-stringer** [comment]
@mrariden maybe we can integrate this request with your suggestion to decrease the size of the saved files?
