### ISSUE TITLE
Saving .txt files via GUI or CLI takes extremely long

### ISSUE THREAD

**Issue by yassinharim** [MouseLand/cellpose#704]
I am using Cellpose in an ImageJ macro workflow for large scans of entire developing mouse brains (~20-25k cells counted). In the macro, my images are first processed, then I call Cellpose via the CLI to segment the individual channels using my pretrained models, then I export the masks as a .txt, import them back into ImageJ using the provided python script and then perform colocalisation analysis in ImageJ. 

My issue is that writing the .txt files takes extremely long - in case of an image with ~25k cells, it is around 1h on a machine with i7-11700K, RTX 3060 Ti and NVMe SSD storage. The time is pretty much identical when exporting via the menu item in the GUI. 
Of course we can run the macro overnight, but I'm just wondering why it takes so long to write the file. 

Is there anything that can be done to speed up this export? Or will the direct .roi export submitted in #643 (I'm really looking forward to this functionality!) already be faster?

Update: I manually implemented the changes from #643 and compared exporting times - .txt took 49 minutes, while .roi export completed after 44 minutes. So there doesn't seem to be a large difference between those methods. In the entire workflow, of course, I can save some time because I don't need to run the ROI importer script anymore. But an overall faster export would still be great. 

Thanks a lot!

**Comment by yassinharim** [comment]
I dug a bit more into the code and I found that the function that needs much, much more time with bigger images is `cv2.findContours()`. So I guess this is outside the hands of Cellpose...

**Comment by mrariden** [comment]
@yassinharim I experimented with adding multithreading to the `cv2.findContours()` call and saw up to a 2x speed up. The speedup will be system/hardware dependent. 

@carsen-stringer does this sound like something I should finish and implement?

**Comment by carsen-stringer** [comment]
Thanks @mrariden yes please do! We will still want to check speed up on windows if you haven't already, sometimes multithreading can be a bit weird there

**Comment by yassinharim** [comment]
This sounds great, thank you so much! @mrariden if you would be willing to share the required changes to enable multithreading already, I would be very happy to implement and test on a few different Windows setups and report back.

**Comment by mrariden** [comment]
@yassinharim that would be great! Either clone #712 locally and run `pip install -e .[gui]` in the cloned directory. Or `pip install git+https://github.com/mrariden/cellpose.git`, cloning locally isn't necessary for the latter.

**Comment by yassinharim** [comment]
Thank you so much @mrariden! I've implemented the changes on the first system (i7-9750H, 64GB RAM, NVMe SSD, Nvidia GTX 1650, Win11 Pro) and I was able to cut down the time for exporting the ZIP from 44 minutes to 13 minutes. This is an amazing improvement!

I will continue testing also with .txt export, and on more (Intel 11th Gen Laptop and Desktop) machines.

**Comment by carsen-stringer** [comment]
thanks @mrariden ! great to hear it's working well @yassinharim
