### ISSUE TITLE
[BUG] Found no NVIDIA driver on your system

### ISSUE THREAD

**Issue by lambda-science** [MouseLand/cellpose#705]
**Describe the bug**
When running CellPose on CPU on a machine without a GPU I get the following error: 
```
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

**To Reproduce**
The command I used to run Cellpose:
`cellpose --image_path cpu-run/tritc_00.tif --save_tif --diameter 0 --verbose --pretrained_model cyto2 --no_npy &`

**Run log**
Please post all command line/notebook output for us to understand the problem. For this please make sure you are running with verbose mode on. So command line, with `--verbose` tag, or in a notebook first run 
```python-traceback
2023-05-10 11:40:08,117 [INFO] WRITING LOG OUTPUT TO /home/meyer/.cellpose/run.log
2023-05-10 11:40:08,118 [INFO] 
cellpose version: 	2.2 
platform:       	linux 
python version: 	3.10.9 
torch version:  	1.13.1+cu117
2023-05-10 11:40:08,118 [INFO] >>>> using CPU
2023-05-10 11:40:08,118 [INFO] >>>> running cellpose on 1 images using chan_to_seg GRAY and chan (opt) NONE
2023-05-10 11:40:08,118 [INFO] >>>> using CPU
2023-05-10 11:40:08,118 [INFO] >> cyto2 << model set to be used
2023-05-10 11:40:08,368 [INFO] >>>> model diam_mean =  30.000 (ROIs rescaled to this size during training)
2023-05-10 11:40:08,369 [INFO] >>>> estimating diameter for each image
2023-05-10 11:40:08,371 [INFO] 0%|          | 0/1 [00:00<?, ?it/s]
2023-05-10 11:40:08,419 [INFO] ~~~ ESTIMATING CELL DIAMETER(S) ~~~
2023-05-10 11:48:44,748 [INFO] estimated cell diameter(s) in 516.33 sec
2023-05-10 11:48:44,749 [INFO] >>> diameter(s) = 
2023-05-10 11:48:44,749 [INFO] [ 79.44 ]
2023-05-10 11:48:44,749 [INFO] ~~~ FINDING MASKS ~~~
2023-05-10 12:04:12,324 [INFO] 0%|          | 0/1 [24:03<?, ?it/s]
Traceback (most recent call last):
  File "/enadisk/maison/genomics18/meyer/code-project/MyoQuant/.venv/bin/cellpose", line 8, in <module>
    sys.exit(main())
  File "/enadisk/maison/genomics18/meyer/code-project/MyoQuant/.venv/lib/python3.10/site-packages/cellpose/__main__.py", line 251, in main
    out = model.eval(image, channels=channels, diameter=diameter,
  File "/enadisk/maison/genomics18/meyer/code-project/MyoQuant/.venv/lib/python3.10/site-packages/cellpose/models.py", line 239, in eval
    masks, flows, styles = self.cp.eval(x, 
  File "/enadisk/maison/genomics18/meyer/code-project/MyoQuant/.venv/lib/python3.10/site-packages/cellpose/models.py", line 552, in eval
    masks, styles, dP, cellprob, p = self._run_cp(x, 
  File "/enadisk/maison/genomics18/meyer/code-project/MyoQuant/.venv/lib/python3.10/site-packages/cellpose/models.py", line 652, in _run_cp
    outputs = dynamics.compute_masks(dP[:,i], cellprob[i], niter=niter, cellprob_threshold=cellprob_threshold,
  File "/enadisk/maison/genomics18/meyer/code-project/MyoQuant/.venv/lib/python3.10/site-packages/cellpose/dynamics.py", line 731, in compute_masks
    mask = remove_bad_flow_masks(mask, dP, threshold=flow_threshold, use_gpu=use_gpu, device=device)
  File "/enadisk/maison/genomics18/meyer/code-project/MyoQuant/.venv/lib/python3.10/site-packages/cellpose/dynamics.py", line 581, in remove_bad_flow_masks
    if masks.size * 20 > torch.cuda.mem_get_info()[0]:
  File "/enadisk/maison/genomics18/meyer/code-project/MyoQuant/.venv/lib/python3.10/site-packages/torch/cuda/memory.py", line 594, in mem_get_info
    device = torch.cuda.current_device()
  File "/enadisk/maison/genomics18/meyer/code-project/MyoQuant/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 552, in current_device
    _lazy_init()
  File "/enadisk/maison/genomics18/meyer/code-project/MyoQuant/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
``` 

This error occured both with torch 1.13.1 and torch 2. Maybe it's torch related and not Cellpose ?
More context on my testing: when I use a machine WITH a GPU but also run Cellpose on CPU, it works. It's only for a machine WITHOUT GPU.

**Comment by mrariden** [comment]
Recent installs work on machine without GPUs. Can you confirm that you install according to the conda-based installation suggestions? 

I'd guess this is because you have a GPU torch install instead of the CPU one, you can go to pytorch to find how to pip install it on their website.

**Comment by alix-simon** [comment]
I get the same error, it occurs when the masks too big and cellpose tries to switch to cpu:

In dynamics.py, line 580:
`     if masks.size > 10000*10000:
        
        major_version, minor_version, _ = torch.__version__.split(".")
        
        if major_version == "1" and int(minor_version) < 10:
            # for PyTorch version lower than 1.10
            def mem_info():
                total_mem = torch.cuda.get_device_properties(0).total_memory
                used_mem = torch.cuda.memory_allocated()
                return total_mem, used_mem
        else:
            # for PyTorch version 1.10 and above
            def mem_info():
                total_mem, used_mem = torch.cuda.mem_get_info()
                return total_mem, used_mem
        
        if masks.size * 20 > mem_info()[0]:
            dynamics_logger.warning('WARNING: image is very large, not using gpu to compute flows from masks for QC step flow_threshold')
            dynamics_logger.info('turn off QC step with flow_threshold=0 if too slow')
        use_gpu = False`

The defined mem_info() functions use cuda, which fails if there is no GPU available.

My quick fix was to replace 
`if masks.size > 10000*10000:` by `if masks.size > 10000*10000 and use_gpu: `

**Comment by lambda-science** [comment]
> Recent installs work on machine without GPUs. Can you confirm that you install according to the conda-based installation suggestions?
> 
> I'd guess this is because you have a GPU torch install instead of the CPU one, you can go to pytorch to find how to pip install it on their website.

No I'm not installing Cellpose with the given conda instruction because I don't like conda (neither the conda venv system nor the package management) and also because I'm building a tool on top of Cellpose, it's a dependancy for my project. https://github.com/lambda-science/MyoQuant

Basically I have a simple pyproject.toml (Poetry) file that set  the environnement with a simple `cellpose = "^2.1.0"` And Cellpose is supposed to install torch by itself because it's a Cellpose dependency. With it does, by looking at the lock file:
```python
[[package]]
name = "torch"
version = "1.13.1"
description = "Tensors and Dynamic neural networks in Python with strong GPU acceleration"
category = "main"
optional = false
python-versions = ">=3.7.0"
files = [
    {file = "torch-1.13.1-cp310-cp310-manylinux1_x86_64.whl", hash = "sha256:fd12043868a34a8da7d490bf6db66991108b00ffbeecb034228bfcbbd4197143"},
    {file = "torch-1.13.1-cp310-cp310-manylinux2014_aarch64.whl", hash = "sha256:d9fe785d375f2e26a5d5eba5de91f89e6a3be5d11efb497e76705fdf93fa3c2e"},
    {file = "torch-1.13.1-cp310-cp310-win_amd64.whl", hash = "sha256:98124598cdff4c287dbf50f53fb455f0c1e3a88022b39648102957f3445e9b76"},
    {file = "torch-1.13.1-cp310-none-macosx_10_9_x86_64.whl", hash = "sha256:393a6273c832e047581063fb74335ff50b4c566217019cc6ace318cd79eb0566"},
    {file = "torch-1.13.1-cp310-none-macosx_11_0_arm64.whl", hash = "sha256:0122806b111b949d21fa1a5f9764d1fd2fcc4a47cb7f8ff914204fd4fc752ed5"},
    {file = "torch-1.13.1-cp311-cp311-manylinux1_x86_64.whl", hash = "sha256:22128502fd8f5b25ac1cd849ecb64a418382ae81dd4ce2b5cebaa09ab15b0d9b"},
    {file = "torch-1.13.1-cp37-cp37m-manylinux1_x86_64.whl", hash = "sha256:76024be052b659ac1304ab8475ab03ea0a12124c3e7626282c9c86798ac7bc11"},
    {file = "torch-1.13.1-cp37-cp37m-manylinux2014_aarch64.whl", hash = "sha256:ea8dda84d796094eb8709df0fcd6b56dc20b58fdd6bc4e8d7109930dafc8e419"},
    {file = "torch-1.13.1-cp37-cp37m-win_amd64.whl", hash = "sha256:2ee7b81e9c457252bddd7d3da66fb1f619a5d12c24d7074de91c4ddafb832c93"},
    {file = "torch-1.13.1-cp37-none-macosx_10_9_x86_64.whl", hash = "sha256:0d9b8061048cfb78e675b9d2ea8503bfe30db43d583599ae8626b1263a0c1380"},
    {file = "torch-1.13.1-cp37-none-macosx_11_0_arm64.whl", hash = "sha256:f402ca80b66e9fbd661ed4287d7553f7f3899d9ab54bf5c67faada1555abde28"},
    {file = "torch-1.13.1-cp38-cp38-manylinux1_x86_64.whl", hash = "sha256:727dbf00e2cf858052364c0e2a496684b9cb5aa01dc8a8bc8bbb7c54502bdcdd"},
    {file = "torch-1.13.1-cp38-cp38-manylinux2014_aarch64.whl", hash = "sha256:df8434b0695e9ceb8cc70650afc1310d8ba949e6db2a0525ddd9c3b2b181e5fe"},
    {file = "torch-1.13.1-cp38-cp38-win_amd64.whl", hash = "sha256:5e1e722a41f52a3f26f0c4fcec227e02c6c42f7c094f32e49d4beef7d1e213ea"},
    {file = "torch-1.13.1-cp38-none-macosx_10_9_x86_64.whl", hash = "sha256:33e67eea526e0bbb9151263e65417a9ef2d8fa53cbe628e87310060c9dcfa312"},
    {file = "torch-1.13.1-cp38-none-macosx_11_0_arm64.whl", hash = "sha256:eeeb204d30fd40af6a2d80879b46a7efbe3cf43cdbeb8838dd4f3d126cc90b2b"},
    {file = "torch-1.13.1-cp39-cp39-manylinux1_x86_64.whl", hash = "sha256:50ff5e76d70074f6653d191fe4f6a42fdbe0cf942fbe2a3af0b75eaa414ac038"},
    {file = "torch-1.13.1-cp39-cp39-manylinux2014_aarch64.whl", hash = "sha256:2c3581a3fd81eb1f0f22997cddffea569fea53bafa372b2c0471db373b26aafc"},
    {file = "torch-1.13.1-cp39-cp39-win_amd64.whl", hash = "sha256:0aa46f0ac95050c604bcf9ef71da9f1172e5037fdf2ebe051962d47b123848e7"},
    {file = "torch-1.13.1-cp39-none-macosx_10_9_x86_64.whl", hash = "sha256:6930791efa8757cb6974af73d4996b6b50c592882a324b8fb0589c6a9ba2ddaf"},
    {file = "torch-1.13.1-cp39-none-macosx_11_0_arm64.whl", hash = "sha256:e0df902a7c7dd6c795698532ee5970ce898672625635d885eade9976e5a04949"},
]
```

It should be able to detect automatically if it should install torch gpu or cpu. I'm not giving it any other instructions other than "install Cellpose".
I'll try to find a way to fix this by maybe installing torch CPU before installing Cellpose so it does not try to resolve its own dependencies. But that's seem's like a temporary fix

**Comment by mrariden** [comment]
Great catch @alix-simon, I'll make a PR and get this fixed in the main branch. 

@lambda-science, I suspect this will solve your issue as well, but won't be available via PyPI until the next release.

**Comment by lambda-science** [comment]
> Great catch @alix-simon, I'll make a PR and get this fixed in the main branch.
> 
> @lambda-science, I suspect this will solve your issue as well, but won't be available via PyPI until the next release.

I can specify a commit instead of a package version so it will do the trick ! 😄 Thanks

**Comment by carsen-stringer** [comment]
Thanks @mrariden , it's merged
