### ISSUE TITLE
Interpreting cell probability maps

### ISSUE THREAD

**Issue by noahpettit** [MouseLand/cellpose#71]
Hi,
First of all, thanks so much for developing this tool and sharing the software - this is a really awesome tool and approach!

I was wondering how to interpret the cell probability map values returned by model.eval: i.e. flows[k][2] 

I'm getting values between around -15 and +10 and I've gathered from the documentation that these are zero-centered around the threshold. What do these values actually correspond to and how would I convert them to conventional 0  to 1.0 probability of a pixel being part of a cell? 

On a side note (but somewhat adding to my confusion), I've noticed a potential discrepancy between the desciption in the github readme and the docs webpage. In the readme it says "flows[1] is the cell probability in range 0-255 instead of 0.0 to 1.0". Are flows in *_seg.npy different from the flows returned by model.eval? 

Thanks in advance!

**Comment by carsen-stringer** [comment]
Here's the function conversion from the cellpose cellprob output, to the cell probabilities that it is attempting to predict from the images:
![image](https://user-images.githubusercontent.com/15067541/82148022-c8e3c580-981f-11ea-901b-2ff58afc5db9.png)

I've converted them to a plottable format there. Now it also keeps the true cellprob output around so the user can load it in the GUI to modify the segmentation (upgrade cellpose if you don't have cellprob + flow threshold sliders in your GUI). So now flows[3][-1] is the cellprob output (flows[3][-2] is dX, flows[3][-3] is dY, and if 3D, flows[3][0] is dZ. flows[4] is where the pixels end up after running the dynamics, you can ignore that output, that's just for the slider.

I will update the docs.

**Comment by noahpettit** [comment]
Thanks so much Carsen!
