### ISSUE TITLE
[BUG] Right mouse button only zooms

### ISSUE THREAD

**Issue by christianrickert** [MouseLand/cellpose#711]
**Describe the bug**
The right mouse button only zooms the image in and out and doesn't allow for the drawing of nucleus/cell outlines. No combination with [CTRL|SHIFT|ALT] will change this behavior. I've also tried the middle mouse button.
Installation of `cellpose` was straightforward with the current [instructions](https://github.com/MouseLand/cellpose#instructions).

**To Reproduce**
1. Load a grayscale image.
2. Select 'gray' from the dropdown menu.
1. Select 'nuclei' from the model zoo.
3. Wait for the classification to complete.
4. Right-click on the image, move the mouse up and down.
5. Notice how the image is zoomed-in and -out, respectively. 

**Run log**
```
(cellpose) C:\Users\Christian Rickert>cellpose
2023-05-18 16:24:58,674 [INFO] WRITING LOG OUTPUT TO C:\Users\Christian Rickert\.cellpose\run.log
2023-05-18 16:24:58,675 [INFO]
cellpose version:       2.2.1
platform:               win32
python version:         3.8.16
torch version:          2.0.1+cpu
2023-05-18 16:24:59,066 [INFO] TORCH CUDA version not installed/working.
GUI_INFO: loading image: C:/Users/Christian Rickert/Desktop/dsDNA.tif
(5143, 5568, 4)
GUI_INFO: auto-adjust enabled, computing saturation levels
2023-05-18 16:25:33,684 [INFO] >> nuclei << model set to be used
2023-05-18 16:25:33,685 [INFO] >>>> using CPU
2023-05-18 16:25:33,833 [INFO] >>>> model diam_mean =  17.000 (ROIs rescaled to this size during training)
2023-05-18 16:30:25,770 [INFO] 10169 cells found with model in 292.220 sec
GUI_INFO: 10169 masks found
GUI_INFO: creating cellcolors and drawing masks
```

<details>
<summary> conda packages </summary>

```terminal
# packages in environment at C:\ProgramData\Miniconda3\envs\cellpose:
#
# Name                    Version                   Build  Channel
ca-certificates           2023.01.10           haa95532_0
cachetools                5.3.0                    pypi_0    pypi
cellpose                  2.2.1                    pypi_0    pypi
certifi                   2023.5.7                 pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
fastremap                 1.13.5                   pypi_0    pypi
filelock                  3.12.0                   pypi_0    pypi
google-api-core           2.11.0                   pypi_0    pypi
google-auth               2.18.1                   pypi_0    pypi
google-cloud-core         2.3.2                    pypi_0    pypi
google-cloud-storage      2.9.0                    pypi_0    pypi
google-crc32c             1.5.0                    pypi_0    pypi
google-resumable-media    2.5.0                    pypi_0    pypi
googleapis-common-protos  1.59.0                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imagecodecs               2023.3.16                pypi_0    pypi
importlib-metadata        6.6.0                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
libffi                    3.4.4                hd77b12b_0
llvmlite                  0.40.0                   pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
natsort                   8.3.1                    pypi_0    pypi
networkx                  3.1                      pypi_0    pypi
numba                     0.57.0                   pypi_0    pypi
numpy                     1.24.3                   pypi_0    pypi
opencv-python-headless    4.7.0.72                 pypi_0    pypi
openssl                   1.1.1t               h2bbff1b_0
packaging                 23.1                     pypi_0    pypi
pip                       23.0.1           py38haa95532_0
protobuf                  4.23.1                   pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pygments                  2.15.1                   pypi_0    pypi
pyqt5                     5.15.9                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.12.1                  pypi_0    pypi
pyqtgraph                 0.13.3                   pypi_0    pypi
python                    3.8.16               h6244533_3
qtpy                      2.3.1                    pypi_0    pypi
requests                  2.30.0                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                66.0.0           py38haa95532_0
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
superqt                   0.4.1                    pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
tifffile                  2023.4.12                pypi_0    pypi
torch                     2.0.1                    pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
urllib3                   1.26.15                  pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.38.4           py38haa95532_0
zipp                      3.15.0                   pypi_0    pypi
```
</details>

I'm running on Windows 10 (recent) without a dedicated GPU.

There is a similar issue #701, but @mrariden's [suggestion](https://github.com/MouseLand/cellpose/issues/701#issuecomment-1537281650) didn't resolve the issue.

Chris

**Comment by mrariden** [comment]
Does clicking without moving the mouse work?

**Comment by christianrickert** [comment]
Interesting! Clicking with the right mouse button and waiting two seconds draws a red circle with a purple square. Moving the cursor then produces more squares along the track:

![image](https://github.com/MouseLand/cellpose/assets/19319377/8836374b-3373-4144-af01-bb4a6e41efe4)

**Comment by christianrickert** [comment]
Some 15 attempts later to draw circles on the screen:

![image](https://github.com/MouseLand/cellpose/assets/19319377/9c97cf2c-ca1b-498a-b9d9-d1cf3d1f1551)

I don't see this being workable unfortunately.

Any ideas on how to increase the GUI's responsiveness?

**Comment by carsen-stringer** [comment]
do you right-click then hover and draw? you cannot right-click then drag to draw. we cannot reproduce this error. also drawing will be slow if you have a really large image and a slow CPU

**Comment by christianrickert** [comment]
> do you right-click then hover and draw? you cannot right-click then drag to draw. we cannot reproduce this error. also drawing will be slow if you have a really large image and a slow CPU

Right-click, then moving the cursor. - The image is 5000x5000 pixels, the CPU sufficiently fast.

[Screencast](https://olucdenver-my.sharepoint.com/:v:/g/personal/christian_rickert_cuanschutz_edu/ET70xSNV01pEjQfQPlLzKRIB77I6EGNaJOVkGVOqfMd6WA?e=91RO48)

I've noticed that zooming in and out is very smooth, but drawing the outlines seems to be very computing-intensive: surprisingly, a single CPU core is maxed out while `cellpose` is tracing the mouse movement.

**Comment by kageazusa** [comment]
I have the same problem with an M1 mac with GPU.
I installed Cellpose as below and the GPU seemed to work.
https://forum.image.sc/t/cellpose-on-macos-m1-pro-apple-silicon-arm64/68018/17

Right-clicking and then moving a mouse leads to purple dotted tracks (as in christianrickert's picture) and I cannot correct masks. The first mask after right-clicking might be working, though I am not sure (the track looks closed, but disappears?). After that the track becomes dotted. I cannot find the way I quit drawing tracks. Esc key doesn't work.
The image size is 4000x3000 pixels. Any help?
