### ISSUE TITLE
Documentation - broken link to test images on the step-by-step section

### ISSUE THREAD

**Issue by wreillo** [MouseLand/cellpose#713]
**Describe the bug**
From the [step-by-step demo](https://github.com/MouseLand/cellpose#step-by-step-demo) section, the `folder` hyperlink/URL is broken.

**To Reproduce**
1. Follow the URL to 'https://drive.google.com/open?id=18syVlaix8cIlrnNF20pEWKMWUsKx9R9z'
2. Get 404

**Run log**
N/A

**Screenshots**
[Self explanatory]

**Comment by carsen-stringer** [comment]
thanks for catching this, google drive links reset occasionally, here's a new permanent link: http://cellpose.org/static/images/demo_images.zip

**Comment by LNatb** [comment]
Hi @carsen-stringer , I wanted to try the demo too, both links (in README and in the comment section) no longer work. If you could make it  available again I would appreciate it! Thank you

**Comment by carsen-stringer** [comment]
seems like the website requires www now, will fix the readme: https://www.cellpose.org/static/images/demo_images.zip
