### ISSUE TITLE
[INSTALL]

### ISSUE THREAD

**Issue by jzinski** [MouseLand/cellpose#716]
**Install problem**
Hello, after I install cellpose2.0, when I run 'python -m cellpose' I receive the error:

GUI ERROR: libGL.so.1: cannot open shared object file: No such file or directory
GUI FAILED: GUI dependencies may not be installed, to install, run
     pip install cellpose[gui]

I install by running:
conda create --name cellpose python=3.8
conda activate cellpose
python -m pip install cellpose[gui]
pip uninstall torch
conda install pytorch pytorch-cuda=11.6 -c pytorch -c nvidia

Please advise!

**Environment info**
conda list
# packages in environment at /home/jzinski/miniconda3/envs/cellpose:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
blas                      1.0                         mkl
ca-certificates           2023.01.10           h06a4308_0
cachetools                5.3.0                    pypi_0    pypi
cellpose                  2.2.1                    pypi_0    pypi
certifi                   2023.5.7                 pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
cmake                     3.26.3                   pypi_0    pypi
cuda                      11.6.1                        0    nvidia
cuda-cccl                 11.6.55              hf6102b2_0    nvidia
cuda-command-line-tools   11.6.2                        0    nvidia
cuda-compiler             11.6.2                        0    nvidia
cuda-cudart               11.6.55              he381448_0    nvidia
cuda-cudart-dev           11.6.55              h42ad0f4_0    nvidia
cuda-cuobjdump            11.6.124             h2eeebcb_0    nvidia
cuda-cupti                11.6.124             h86345e5_0    nvidia
cuda-cuxxfilt             11.6.124             hecbf4f6_0    nvidia
cuda-driver-dev           11.6.55                       0    nvidia
cuda-gdb                  12.1.105                      0    nvidia
cuda-libraries            11.6.1                        0    nvidia
cuda-libraries-dev        11.6.1                        0    nvidia
cuda-memcheck             11.8.86                       0    nvidia
cuda-nsight               12.1.105                      0    nvidia
cuda-nsight-compute       12.1.1                        0    nvidia
cuda-nvcc                 11.6.124             hbba6d2d_0    nvidia
cuda-nvdisasm             12.1.105                      0    nvidia
cuda-nvml-dev             11.6.55              haa9ef22_0    nvidia
cuda-nvprof               12.1.105                      0    nvidia
cuda-nvprune              11.6.124             he22ec0a_0    nvidia
cuda-nvrtc                11.6.124             h020bade_0    nvidia
cuda-nvrtc-dev            11.6.124             h249d397_0    nvidia
cuda-nvtx                 11.6.124             h0630a44_0    nvidia
cuda-nvvp                 12.1.105                      0    nvidia
cuda-runtime              11.6.1                        0    nvidia
cuda-samples              11.6.101             h8efea70_0    nvidia
cuda-sanitizer-api        12.1.105                      0    nvidia
cuda-toolkit              11.6.1                        0    nvidia
cuda-tools                11.6.1                        0    nvidia
cuda-visual-tools         11.6.1                        0    nvidia
fastremap                 1.13.5                   pypi_0    pypi
filelock                  3.12.0                   pypi_0    pypi
gds-tools                 1.6.1.9                       0    nvidia
gmp                       6.2.1                h295c915_3
gmpy2                     2.1.2            py38heeb90bb_0
google-api-core           2.11.0                   pypi_0    pypi
google-auth               2.18.1                   pypi_0    pypi
google-cloud-core         2.3.2                    pypi_0    pypi
google-cloud-storage      2.9.0                    pypi_0    pypi
google-crc32c             1.5.0                    pypi_0    pypi
google-resumable-media    2.5.0                    pypi_0    pypi
googleapis-common-protos  1.59.0                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imagecodecs               2023.3.16                pypi_0    pypi
importlib-metadata        6.6.0                    pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46305
jinja2                    3.1.2            py38h06a4308_0
ld_impl_linux-64          2.38                 h1181459_1
libcublas                 11.9.2.110           h5e84587_0    nvidia
libcublas-dev             11.9.2.110           h5c901ab_0    nvidia
libcufft                  10.7.1.112           hf425ae0_0    nvidia
libcufft-dev              10.7.1.112           ha5ce4c0_0    nvidia
libcufile                 1.6.1.9                       0    nvidia
libcufile-dev             1.6.1.9                       0    nvidia
libcurand                 10.3.2.106                    0    nvidia
libcurand-dev             10.3.2.106                    0    nvidia
libcusolver               11.3.4.124           h33c3c4e_0    nvidia
libcusparse               11.7.2.124           h7538f96_0    nvidia
libcusparse-dev           11.7.2.124           hbbe9722_0    nvidia
libffi                    3.4.4                h6a678d5_0
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libnpp                    11.6.3.124           hd2722f0_0    nvidia
libnpp-dev                11.6.3.124           h3c42840_0    nvidia
libnvjpeg                 11.6.2.124           hd473ad6_0    nvidia
libnvjpeg-dev             11.6.2.124           hb5906b9_0    nvidia
libstdcxx-ng              11.2.0               h1234567_1
lit                       16.0.5                   pypi_0    pypi
llvmlite                  0.40.0                   pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
mkl                       2023.1.0         h6d00ec8_46342
mpc                       1.1.0                h10f8cd9_1
mpfr                      4.0.2                hb69a4c5_1
mpmath                    1.3.0                    pypi_0    pypi
natsort                   8.3.1                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
networkx                  3.1                      pypi_0    pypi
nsight-compute            2023.1.1.4                    0    nvidia
numba                     0.57.0                   pypi_0    pypi
numpy                     1.24.3                   pypi_0    pypi
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.2.10.91               pypi_0    pypi
nvidia-cusolver-cu11      11.4.0.1                 pypi_0    pypi
nvidia-cusparse-cu11      11.7.4.91                pypi_0    pypi
nvidia-nccl-cu11          2.14.3                   pypi_0    pypi
nvidia-nvtx-cu11          11.7.91                  pypi_0    pypi
opencv-python-headless    4.7.0.72                 pypi_0    pypi
openssl                   1.1.1t               h7f8727e_0
packaging                 23.1                     pypi_0    pypi
pip                       23.0.1           py38h06a4308_0
protobuf                  4.23.1                   pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pygments                  2.15.1                   pypi_0    pypi
pyqt5                     5.15.9                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.12.1                  pypi_0    pypi
pyqtgraph                 0.13.3                   pypi_0    pypi
python                    3.8.16               h7a1cb2a_3
pytorch                   2.0.1               py3.8_cpu_0    pytorch
pytorch-cuda              11.6                 h867d48c_1    pytorch
pytorch-mutex             1.0                         cpu    pytorch
qtpy                      2.3.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0
requests                  2.31.0                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                66.0.0           py38h06a4308_0
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0
superqt                   0.4.1                    pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
tbb                       2021.8.0             hdb19cb5_0
tifffile                  2023.4.12                pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
tqdm                      4.65.0                   pypi_0    pypi
triton                    2.0.0                    pypi_0    pypi
typing-extensions         4.6.0                    pypi_0    pypi
typing_extensions         4.5.0            py38h06a4308_0
urllib3                   1.26.15                  pypi_0    pypi
wheel                     0.38.4           py38h06a4308_0
xz                        5.4.2                h5eee18b_0
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0

**Comment by mrariden** [comment]
Can you successfully install without uninstalling torch? Please report if you can using a fresh conda environment:
``` bash
conda env remove -n cellpose -y
conda create --name cellpose python=3.8
conda activate cellpose
python -m pip install cellpose[gui]
```
and then try to run the GUI with `python -m cellpose`.

**Comment by jzinski** [comment]
Hello!  same results:
GUI ERROR: libGL.so.1: cannot open shared object file: No such file or directory
GUI FAILED: GUI dependencies may not be installed, to install, run
     pip install cellpose[gui]

**Comment by jzinski** [comment]
I completely uninstalled WSL and Ubuntu and Anaconda and reinstalled each, still same message.

**Comment by mrariden** [comment]
You are running Ubuntu on a Windows OS via WSL? That is not a configuration we have tested, and you may run into issues. Can you install conda to Windows and try that route?

**Comment by jzinski** [comment]
Solved thank you

**Comment by annatrzcinski** [comment]
@jzinski I am using anaconda in WSL and encoutering the same error. What was your fix? Did you end up downloading to anaconda in windows?
