### ISSUE TITLE
[INSTALL] - preparing metadata error 

### ISSUE THREAD

**Issue by clairepiperr** [MouseLand/cellpose#719]
Hi, 

I am running into the following error when trying to install the GUI: 

  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by clairepiperr** [comment]
This seems to be an error with the install PyQt5

**Comment by mrariden** [comment]
Hi,

Please share the details of your system. What OS are you working on? Are you following the conda install instructions in our docs?

**Comment by clairepiperr** [comment]
Hi, 
I am using a Mac with the M2 chip and I think this may be the problem. 
I have read the help for installing on M1 but this doesn't seem to work either and I continually run into the error with PyQt5.

**Comment by mrariden** [comment]
Can you try the instructions [here](https://stackoverflow.com/a/71669996), and let us know if they work for you? This solution solves the problem by installing PyQt5 separately.

**Comment by christianrickert** [comment]
@clairepiperr Please try these commands to install `cellpose` (2.0.5 or 2.2.2) with `conda` (23.5.0) and `python` (3.11.4) from `brew` (4.0.21), tested on a MacBook Pro (Apple M1 Max, Ventura 13.4):

```zsh
# remove previous conda environment (optional)
conda deactivate
conda remove --name cellpose --all

# create your `cellpose` environment
conda create --name cellpose

# install dependencies and `cellpose[gui]` package from `conda-forge`
conda activate cellpose
conda install -c conda-forge pyqt pyqtgraph 'cellpose[gui]'

# add missing new dependencies and update `cellpose[gui]` to the latest version
conda install -c conda-forge roifile superqt
pip install --no-deps --upgrade 'cellpose[gui]'
```

Use `conda` from the Anaconda environment as much as possible, avoid `pip` like the plague. Please see: [Using pip in a conda environment](https://www.anaconda.com/blog/using-pip-in-a-conda-environment).

**Comment by TomPJWyatt** [comment]
@christianrickert you solution worked for me with (Apple M1 Pro, Ventura 13.3), thanks!

**Comment by clairepiperr** [comment]
Hi,

Yes that works great on M2 aswell.
Thanks

From: TomPJWyatt ***@***.***>
Date: Thursday, 22 June 2023 at 17:01
To: MouseLand/cellpose ***@***.***>
Cc: Claire Piper ***@***.***>, Mention ***@***.***>
Subject: Re: [MouseLand/cellpose] [INSTALL] - preparing metadata error (Issue #719)

@christianrickert<https://github.com/christianrickert> you solution worked for me with (Apple M1 Pro, Ventura 13.3), thanks!
