### ISSUE TITLE
Cellpose gui not starting mklml.dll

### ISSUE THREAD

**Issue by Bioimaging** [MouseLand/cellpose#72]
Hello,

I have installed cellpose with `pip install cellpose[gui] ` It seems to be ok.
However when I do `python -m cellpose`  I have an error windows poping-up with 
"The ordinal 191 could not be located in the dynamic link library C:\ProgramData\Anaconda3\lib\site-packages\mxnet\mklml.dll"

However this dll is there... Do you know what I am doing wrong?

Thank you!

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cellpose\__main__.py", line 2, in <module>
    import mxnet as mx
  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\base.py", line 213, in <module>
    _LIB = _load_lib()
  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\base.py", line 204, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 182] The operating system cannot run %1

**Comment by carsen-stringer** [comment]
Are you using anaconda? Can you try installing with the environment? What version of mxnet-mkl is this? I think I've seen this issue before and I think the environment will fix this.

**Comment by Bioimaging** [comment]
Thank you for your reply. Yes anaconda on a Win10 machine. I have created an environment (your yml file has a unicode problem I think for my computer) by copy-pasting what was into your file.
I have activated the new environment and when I ran `python -m cellpose` this is what I got: `Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll`, with a slightly different  error window:  "The ordinal... \cellpose\Library\bin\mkl_intel_thread.dll" this time
On my default and cellpose environment it is both mxnet-mkl version 1.5.0 installed.

**Comment by carsen-stringer** [comment]
hmm seems like updating anaconda and setting some environment variables might help: https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed

I've seen that pop-up box on windows before but haven't since I've updated anaconda

**Comment by Bioimaging** [comment]
still the same :( I am not a conda nor a python expert, is there any debug mode to track where this is coming from?

**Comment by carsen-stringer** [comment]
there is an executable version of cellpose now available I'd recommend trying that (see [readme](https://github.com/MouseLand/cellpose))
