### ISSUE TITLE
[INSTALL]

### ISSUE THREAD

**Issue by NWood4** [MouseLand/cellpose#722]
**Install problem**
Having issues with basic installation of Cellpose. Steps 1-5 ran well I believe. Getting the same error in step 6 every time I try. "Preparing metadata (pyproject.tom1) did not run successfully."

**Environment info**
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h620ffc9_4  
ca-certificates           2023.01.10           hca03da5_0  
cellpose                  2.2.2                    pypi_0    pypi
fastremap                 1.13.5                   pypi_0    pypi
filelock                  3.12.0                   pypi_0    pypi
imagecodecs               2023.3.16                pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
libffi                    3.4.4                hca03da5_0  
llvmlite                  0.40.0                   pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
natsort                   8.3.1                    pypi_0    pypi
ncurses                   6.4                  h313beb8_0  
networkx                  3.1                      pypi_0    pypi
numba                     0.57.0                   pypi_0    pypi
numpy                     1.24.3                   pypi_0    pypi
opencv-python-headless    4.7.0.72                 pypi_0    pypi
openssl                   1.1.1t               h1a28f6b_0  
pip                       23.0.1          py310hca03da5_0  
python                    3.10.11              hc0d8a6c_2  
readline                  8.2                  h1a28f6b_0  
roifile                   2023.5.12                pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                67.8.0          py310hca03da5_0  
sqlite                    3.41.2               h80987f9_0  
sympy                     1.12                     pypi_0    pypi
tifffile                  2023.4.12                pypi_0    pypi
tk                        8.6.12               hb8d0fd4_0  
torch                     2.0.1                    pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
typing-extensions         4.6.2                    pypi_0    pypi
tzdata                    2023c                h04d1e81_0  
wheel                     0.38.4          py310hca03da5_0  
xz                        5.4.2                h80987f9_0  
zlib                      1.2.13               h5a0b063_0 

Unfortunately I struggle with all things coding and this is the best I can do. Any help would be much appreciated.

**Comment by mrariden** [comment]
Hi,

Please share the details of your system. What OS are you working on? Are you following the conda install instructions in our docs?

**Comment by NWood4** [comment]
Hello, 

Yes, I am following the doc. 

My OS is MacOS Ventura 13.3.1

Thank you

**Comment by mrariden** [comment]
Hi NWood4, 

Sorry for the delay. Were you able to install successfully? Based on your error it may be that your conda setup is incorrect. Are there any other outputs that we can use to debug your install?

**Comment by NWood4** [comment]
Hi there, Thankfully I got it installed and working!Thank you!On Aug 24, 2023, at 19:51, Michael Rariden ***@***.***> wrote:﻿
Hi NWood4,
Sorry for the delay. Were you able to install successfully? Based on your error it may be that your conda setup is incorrect. Are there any other outputs that we can use to debug your install?
