### ISSUE TITLE
Cellpose using multiple GPUs 

### ISSUE THREAD

**Issue by Eddymorphling** [MouseLand/cellpose#725]
Has anyone tried using Cellpose to train and predict using multiple GPUs? This would make training and segmentation faster. We have 4x RTX5000A and currently, I have noticed that it only uses one GPU out of the four GPUs during training or prediction.

I also made the same [post ](https://forum.image.sc/t/cellpose-or-n2v-using-multiple-gpus/82187)in the ImageJ forum, just in case :)

Thanks!

**Comment by mrariden** [comment]
This is on the docket for things to implement but we don't have a timeline at the moment. It would require a significant refactor to implement, see #447
