### ISSUE TITLE
Segmenting images with a nuclear stain and membrane stain

### ISSUE THREAD

**Issue by jzinski** [MouseLand/cellpose#727]
Could cellpose be trained to identify cell boundaries using a cell membrane stain and a nuclear stain such as the below example?  If so, which model should I start with to iteratively train?  Or should I start from scratch?  Thanks!

![acvr1l venus g acvr2bb r 1-1 tif (RGB)](https://github.com/MouseLand/cellpose/assets/40038338/d9872d8d-f73d-4c1b-b06d-46655eb1f799)

**Comment by ashishUthama** [comment]
The cyto2 model works with this data.
Results below using just the green channel (mid) and with adding the optional nuclear blue channel (right). 
(Cell diameter set at 80)

![image](https://github.com/MouseLand/cellpose/assets/2106392/876319f3-8e4b-44d5-a00d-28e07cc0d4ef)

**Comment by jzinski** [comment]
Thank you!  I tried cyto2 with cell diameter at 80 and the green and optional nuclear channels set as you recommended.  There is a caveat, this image is actually once slice in a 3D stack, and it works significantly less well when I run it on the whole stack.  A couple of questions:

1.  Why are some of the borders of my 3d segmented imaged (below) so jagged and oversegmented?  Do I need to smooth my images before running cellpose?

2.  If I do start iteratively building a model for 3D stacks, how to I inform the model that called ROIs on different z-planes are part of the same object?  Or should I stick to 2-d and assemble them into 3d objects in post?

![image](https://github.com/MouseLand/cellpose/assets/40038338/d4680088-db45-4885-8f42-bb0507854794)

Thanks!

**Comment by jzinski** [comment]
Update:  I know now that cellpose trains only in 2D, but that the 2D training enhances the 3D accuracy.

I also realized that to segment in 3D i needed to run 'python -m cellpose --do_3D'.  This gave better results.

**Comment by CQ981001** [comment]
When I split the image below, how should chan be set?Thanks.
![DAPI-1](https://github.com/MouseLand/cellpose/assets/87350192/de0ed8d6-bf9a-46db-a551-847f39f4b9d1)

**Comment by mrariden** [comment]
@jzinski @CQ981001 please look for usage-related help (ie things that are not bugs) on the [image.sc](https://forum.image.sc/tag/cellpose) forum
