### ISSUE TITLE
Add tiling as an option for CLI 

### ISSUE THREAD

**Issue by lguerard** [MouseLand/cellpose#728]
Hi,

I have images with more than 15kx15k pixels and would love to run Cellpose on them, but always get an out of memory error. I'm using the [Fiji wrapper](https://github.com/BIOP/ijl-utilities-wrappers) to call Cellpose which uses the CLI call.

I found on [the API documentation](https://cellpose.readthedocs.io/en/latest/api.html) that using python, it's possible to use the `--tile` option to avoid this but couldn't find this using the [CLI](https://cellpose.readthedocs.io/en/latest/cli.html).

Is that on purpose or could this be added somehow ? I'm really curious to see Cellpose working with tiles and dealing with the overlap instead of me fiddling around afterwards.

Thanks for your help !

**Comment by Myrkgod** [comment]
Would it be possible to tile the images beforehand? That's what I do for our 3D images and it works pretty well. [Here is the script I use](https://github.com/Myrkgod/cellpose-image-processing/blob/main/preprocessing.py) And while I haven't used it on a 2D images you should just be able to use --crop_size 1 y_len x_len and then --strides 1 y_overlap x_overlap as the flags.

**Comment by mrariden** [comment]
Sorry for the delay, the docs are updated and should be much more clear now. The default (and hard-coded) CLI behavior is to run Cellpose with `tile` set to `true`. The vast majority of cases would benefit from this being default to true, so I think we'll leave it as it is. 

For the OOM issues, that is related to the way the tiling is kept in memory and we're working on that.
