### ISSUE TITLE
Duplicates of trained models in GUI drop-down custom model menu [BUG]

### ISSUE THREAD

**Issue by b-faith** [MouseLand/cellpose#729]
Hello!

I'm currently training cellpose from a pre-trained model, and have been working over the span of multiple days. When I start open cellpose each day, I start training a new model based on the one I was working with the day before (so in my models folder I have 4 total models). However, in the custom model drop-down menu in the GUI, there is a long list with multiples of those 4 models. 

I'm unsure if they are saving multiple times, or why there are multiple.

Any ideas how to fix this?

Thanks!

**Comment by mrariden** [comment]
Hi can post screenshots that capture this behavior? Every time you do training, a new model file will be generated.

**Comment by carsen-stringer** [comment]
I think this should be fixed now but let me know if not
