### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by mafsousa** [MouseLand/cellpose#73]
Hi,

I've tried to train a new model with my set of images, including 24 images + labelled_masks.
I used:
`python -m cellpose --train --dir D:\Training_Images\ --pretrained_model None --save_png`
A file was generated inside folder models.
But now, how can I use the created model to test other images?
I also tried --test_dir with no success.

Thank you
Mafalda

**Comment by carsen-stringer** [comment]
after you train, run cellpose from the command line but set --pretrained_model to your model
~~~
python -m cellpose --dir NEW_IMAGES --pretrained_model D:\Training_Images\models\YOUR_MODEL --save_png
~~~

**Comment by mafsousa** [comment]
Thank you

**Comment by adrtsc** [comment]
Hi,

I am using cellpose inside a script. In this case, how can I specify a retrained model that should be used?

Thanks
