### ISSUE TITLE
How to avoid training time getting longer

### ISSUE THREAD

**Issue by b-faith** [MouseLand/cellpose#730]
Hello!

I've been using cellpose for the past few days and training it using the human-in-the-loop approach. So far I've used 44 images, and I was wondering if there was a way to speed up the training time. 

I'm using a GPU, and when I first started it was taking 5-6 minutes to train. Now my training time is 12 minutes, and I haven't changed any settings. It says it's still using the GPU, and I've checked to make sure there are no processes running in the background. Also, all of my images are in one folder. 

I've attached a screenshot of the anaconda terminal after training!

Would training also work well if I annotate the cells first and saved the seg.np files all in the same folder, and then use "train on image + masks in folder", or would this change how effective it is?

Any ideas would be appreciated!
Thank you!

<img width="716" alt="Screenshot 2023-06-14 at 11 53 13 AM" src="https://github.com/MouseLand/cellpose/assets/124455829/6082ec39-2152-4bf1-a245-db7991dc1db4">

**Comment by mrariden** [comment]
Training time is proportional to the number of images you have. When you first start with unlabeled images, there are very few images and training is quick. As you label more images using HITL, training time will increase. 

Depending on your image size, 12 minutes is very reasonable for 44 images.
