### ISSUE TITLE
[FEATURE] Retrain a trained model!

### ISSUE THREAD

**Issue by Soroush-aali-bagi** [MouseLand/cellpose#731]
Hello,
Firstly, I would like to express my appreciation for the comprehensive and user-friendly GUI implementation.
I have a question regarding training models. I have successfully trained a model, let's say the "cyto model," but I am unable to find it when I navigate to the "train new model" section. Although I can see the trained models under the custom models tab, they are not available for retraining with new image samples. (see the pictures below).

<img width="272" alt="image" src="https://github.com/MouseLand/cellpose/assets/22675983/b3ad013e-f1f0-45d5-987f-2234527c9ba9">
---------------------------------
<img width="506" alt="image" src="https://github.com/MouseLand/cellpose/assets/22675983/537bf102-fcf1-45be-9fa5-865e2cab1f10">

I'm unsure if this is a bug or a feature that could potentially be added in the future. If there is a technical limitation or any specific reason behind this behavior, I would greatly appreciate it if you could provide an explanation.

**Comment by mrariden** [comment]
Please read #723, if that doesn't address your question feel free to reopen.
