### ISSUE TITLE
Option for Dilated Expansion of Nuclear Segmentation

### ISSUE THREAD

**Issue by jonhsussman** [MouseLand/cellpose#738]
Hello, 

I am interested in using Cellpose2 to segment brain tumor cells, in which case a nuclear dilation approach is most effective for dealing with tightly packed cells which do not contain a membrane marker. In this case, I'm wondering if Cellpose2 has the option to impose a specified pixel dilation around the nuclei mask in order to capture some of the cytoplasm for each cell despite there not being a specific membrane marker, similar to the options from the Mesmer package which directly enables this? 

Do you have any suggestions on how to apply Cellpose2 to perform segmentation of this type of tissue using a nuclear dilation approach?

Thanks, 
Jonathan

**Comment by mrariden** [comment]
No, cellpose does not implement this. There are many options available in opencv and scikitlearn via python libraries. You can look for further help in the [image.sc forum](https://forum.image.sc/tag/cellpose)
