### ISSUE TITLE
CellPose nucleus and cytoplasm mask- clumping

### ISSUE THREAD

**Issue by microscopytime** [MouseLand/cellpose#739]
Hi all,
I am writing because I have found a problem uploading mask from Cellpose to image analysis program (human skin analysis). The same problem exists when there are 2 nucleus/cytoplasm next to each other/overlaping (or more).

I will upload 2 pictures: the example of DAPI staining and how the segmentation looks in CellPose and second one in which I show then how the mask looks like (clumped nuclues) in the image analysis software.

Has anyone had this type of problem using Cellpose or at least can offer some advice.

Protocol: I used nucleus segmentation option in CellPose and then saved the mask as PNG that I converted online to TIFF file to upload it to image analysis program.
Thank you

**Comment by mrariden** [comment]
It sounds like the issue is either in the conversion step or with your analysis software. Can you verify the segmentation with other image viewers, eg FIJI?
