### ISSUE TITLE
Multidimensional 3D stacks_segmentation issue

### ISSUE THREAD

**Issue by pr4deepr** [MouseLand/cellpose#74]
Hi
  I am having issues when using a multidimensional 3D stack. 
Say, if the stack is 1024x1024x23 (X*Y*Z) and has 3 channels, when running the segmentation,
It prints dimensions as : 23 (1024, 1024, 3)
but, when running segmentation across each plane, it runs it as:
running XY (23, 1024)
running XZ (3, 1024)
running YZ (3, 23)
It crashes after it runs YZ.

I don't have issues when I try a single channel 3D stack or multichannel 2D images.

If it helps, not sure if its something to do with reshape function in transforms.py. 
I added print statements for data.shape at the start and end of the reshape function and the output I got was:
Shape of the input image before reshape: (23, 1024, 1024, 3)
Shape of the image after reshape:  (3, 23, 1024, 2)

Thanks
Pradeep

**Comment by carsen-stringer** [comment]
Are you using the jupyter-notebook or the command line? Are you specifying the channels input?

I've fixed this in the github so if you don't specify the channels input it doesn't crash for 3D in the notebook (it will print a warning):
~~~
model = Cellpose()
out = model.eval(img, do_3D=True)
~~~

is this the use case you had?

**Comment by pr4deepr** [comment]
Hi
  Aah, sorry. I had this issue in both the GUI and notebook. 
I did specify the channels in both cases (GUI: drop down box, notebook: manually).
Thanks

**Comment by carsen-stringer** [comment]
oops I was missing a ... for compatibility with 3D when channels is not [0,0], please try now

**Comment by pr4deepr** [comment]
Perfect!  It seems to be working now.. 
Thanks for the prompt response times!

**Comment by carsen-stringer** [comment]
now in pip
