### ISSUE TITLE
[BUG] Possible issue with discontinuous masks

### ISSUE THREAD

**Issue by yassinharim** [MouseLand/cellpose#740]
I'm experiencing an issue with a model to recognise DAPI-stained nuclei in 2D images. If a certain mask is affected, it is correctly generated to mark a nucleus - but then, there is one more pixel, completely detached from the original mask, that Cellpose considers as a part of this mask as well. The issue already happens at the standard settings of `flow_threshold = 0.4` and `cell_prob_threshold = 0.0`, but is pronounced at settings of `flow_threshold = 0.6` and `cell_prob_threshold = -1.0` that generally improve detection of cells in the model. 
This causes issues in my downstream analysis, as I am importing ROIs into ImageJ from label images and this situation would then generate two separate ROIs from one gray value in the label image, throwing off the ROI counting. 

This issue seems to be restricted to several versions (including the most current ones) of the model - earlier versions do not have this problem. I could train another model to resolve this issue, I guess - but in general, I thought Cellpose would not be supposed/able to generate discontinuous masks? Or is this an issue with my settings?

I'm attaching some screenshots below for you to recognise the issue, as well as attaching the model and a sample image (ZIP because the file types were not allowed). 

![Bug1](https://github.com/MouseLand/cellpose/assets/127263444/b39274f4-c2d3-4962-9a4d-61917753dbda)
![Bug2](https://github.com/MouseLand/cellpose/assets/127263444/6fe10cd8-0779-4c10-b548-b82c937037b9)

Here's another example of a mask from a model with `flow_threshold = 0.9` and `cell_prob_threshold = -3.0` that is basically a line, and is also split in two different parts:

![One-dimensional mask](https://github.com/MouseLand/cellpose/assets/127263444/d8b39523-66ad-4877-b815-9e8cd2c15042)

[DAPI_40X.zip](https://github.com/MouseLand/cellpose/files/11870893/DAPI_40X.zip)
[Sample image.zip](https://github.com/MouseLand/cellpose/files/11870903/Sample.image.zip)

**Comment by mrariden** [comment]
We're going to implement a connected components post-processing step per #516. I'm closing this issue, but feel free to follow up in the other issue.
