### ISSUE TITLE
[BUG] Improper image clipping when plotting

### ISSUE THREAD

**Issue by eigenvivek** [MouseLand/cellpose#744]
**Describe the bug**
Order of clipping and multiplying by 255 are backwards, producing black images

https://github.com/MouseLand/cellpose/blob/869f16018ff82f0914c139a7eeb705a1da3c8da5/cellpose/plot.py#L104

Should be
```{python}
img0 = np.uint8(np.clip(img0, 0, 1) * 255)
```

**Comment by mrariden** [comment]
Thanks for the catch, can you submit a PR and we'll get this integrated?
