### ISSUE TITLE
Not able to train a model on a 3D stack

### ISSUE THREAD

**Issue by TroySeman** [MouseLand/cellpose#745]
I spent several hours annotating about 10 of 50 frames of a 50 frame stack and attempted to update the CF model which did run on the entire stack.  It threw an error.  Is this a bug or is this a missing feature?

If this cannot be fixed, could a potential work around be to annotate each frame as a separate image, then update the CF model as a custom model and run that model on the 3D stacks?

Thank you.

**Comment by Myrkgod** [comment]
From my understanding, you are trying to train a cellpose model on a 3D image? Cellpose will only take in 2D images so you need to split the image into individual layers. I have a similar script [here](https://github.com/Myrkgod/cellpose-image-processing/blob/main/preprocessing.py).

**Comment by mrariden** [comment]
Cellpose is capable of 3d segmentation as described in the documentation on [this page](https://cellpose.readthedocs.io/en/latest/gui.html) and [this page](https://cellpose.readthedocs.io/en/latest/inputs.html). 

@TroySeman what exactly was the error you encountered?

**Comment by TroySeman** [comment]
You ignored my request for help then regurgitated two links which I did read over a month ago and closed my ticket.  I've been in IT for over 25 years because I do not "handle" customers this way.

That is also the reason your documentation is sketchy and unusable.  Its not been given to neophytes to review, you haven't learned how to make it mean something.

I already know I cannot train a 3D model in cellpose.  that was not the request.  I have a trained 2D model that seems to be running.  The software appears to be confused about the axes.

I'm attaching two more images that may describe the problem better.  The software seems to be confuses about axes.  the segmented layers appear orthogonal to the image. 

In absence of real human help, I've asked chat GPT to provide some code.  I haven't had time to try it yet, My intention is to explicitly direct Napari to load the images to defined coordinates instead of having the software guess at it.  I do not expect meaningful assistance from this forum based upon your delayed reply and the lack of legible documentation. Indeed after my criticisms here I expect my posts to be deleted entirely.
