### ISSUE TITLE
[INSTALL]The test accuracy does not match what is written in the paper

### ISSUE THREAD

**Issue by ACNicotine** [MouseLand/cellpose#746]
**use problem**
When using the model you provide and a test graph of cellpose, I found that the mask cannot reach the accuracy of 0.69 in the paper, and it seems that the result is very poor. What is the reason?

Here is the test result, this image is the 53rd in the test set.
![test](https://github.com/MouseLand/cellpose/assets/51805029/ea0b130a-9cd6-42ca-b1b0-293407544c96)

Here is the result in the paper.
![paper](https://github.com/MouseLand/cellpose/assets/51805029/8d50bbfa-20e4-4146-b51e-8c97d1e47931)

**Comment by carsen-stringer** [comment]
the paper uses the cyto model
