### ISSUE TITLE
Cannot select all possible cells.

### ISSUE THREAD

**Issue by Peichao** [MouseLand/cellpose#75]
Hi Carsen and Marius, 
Thank you for developing this great tool for the community!  I have tried Suite2P with my data during the Neural Data Science course last year; the segmentation is not good. So I am still manually segmenting cells, which wastes a lot of time. I think cellpose will save me from this.
Basically, I want to segment as many as possible cells from an image, just based on morphology, even a cell looks dim.  From the 'cellprob' image, I think cellpose detects a lot of cells(maybe all the cells that can be detected by eye!), but even I set the cell prob threshold at the lowest, cellpose cannot choose all possible cells. For example, in the following image, I want to choose every 'blob' (a possible cell), no matter how dim (low prob) it is.  Any suggestions?
![image](https://user-images.githubusercontent.com/11894630/82378721-861a1d00-99da-11ea-86fb-11e813e15d6f.png)

**Comment by Peichao** [comment]
I am wondering whether this 'cellprob' image can be export as png file? After filtering and contrast enhancement (e.g. CLAHE, a little like match cell's probability), this image alone is helpful for my manual segmentation. Of course, automatic is preferred!
![image](https://user-images.githubusercontent.com/11894630/82407905-39a50080-9a1f-11ea-8d82-b22fb221e1e0.png)

**Comment by Peichao** [comment]
I am wondering whether this 'cellprob' image can be export as png file? After filtering and contrast enhancement (e.g. CLAHE, a little like match cell's probability), load this image into cellpose to do segmentation will increase the number of ROIs, but the cell border detection maybe not very accurate. I would like to try this trick.

**Comment by carsen-stringer** [comment]
Can you describe the type of filtering you did? We could add these steps as an option to cellpose. Also can you put a screenshot of your image without the segmentation so I can try it out?

**Comment by Peichao** [comment]
The filtering I did is LPF. I think CLAHE plays the main role to improve the visibility of dim cells. Please make sure you add this function. 
The original image is attached
![013](https://user-images.githubusercontent.com/11894630/82764399-387b2700-9dc3-11ea-9bcd-3949e4ea2a93.png)

This image is a screenshot of 'cellprob' image after CLAHE. I used this image as input for second round cellposing.
![test_enhanced](https://user-images.githubusercontent.com/11894630/82764507-1504ac00-9dc4-11ea-8e03-05d2b16c70aa.png)

Thank you for your time!



.

**Comment by Peichao** [comment]
Hi Carsen,

 

I was wondering how did the test go? If you think this is not a good idea, could you add a function to export the ‘cellprob’ image (png, tif, or matrix)? 

 

Thank you!

Peichao

**Comment by carsen-stringer** [comment]
hey peichao the cellprob is exported in the `_seg.npy` file. I am not sure the best solution here, I tried a few different filtering types and none of them were perfect.

have you tried looking at the max_proj image from the calcium imaging data as well?

**Comment by Peichao** [comment]
Thank you for trying, Carsen! Yes, I tried that, but I prefer to use cellpose to generate the cellprob image, then use CLAHE filtering, and manually segment. I have hacked your code to save the cellprob image, but it is better to have this function in the official version, so I can update my cellpose.
