### ISSUE TITLE
[BUG] Exported ImageJ ROIs are slightly inconsistent with (and often smaller than) labeled masks

### ISSUE THREAD

**Issue by ktong25** [MouseLand/cellpose#757]
Hi Cellpose team, 

Thanks for the fantastic work! I used cellpose v2.2.2 to run cell segmentation on my images and exported PNG labeled masks and ImageJ-compatible ROI zip files. After loading PNG and ROIs in ImageJ (see screenshot below), I found that the ROIs are often slightly smaller than the labeled masks, i.e., the cells are touching each other in the labeled image while the cell ROIs are separated by a 1px-wide line. This can cause inconsistent cellular measurement results between measuring based on labeled masks versus based on ImageJ ROIs. 

![image](https://github.com/MouseLand/cellpose/assets/62230171/98665beb-df11-4396-a438-3cdcbba8060d)

In fact, I noticed this when I was running some final tests for an image analysis pipeline, where I take the cellpose-exported ImageJ ROIs and first filter them in ImageJ and export filtered ROIs in the form of labeled masks in PNG (using ImageJ's LOCI plugin's ROI Map function), and then I imported this PNG file in Cellpose GUI for manual correction and then exported results as ImageJ ROIs. Now the final ROIs are separated by 2px-wide lines (see screenshot below, showing original cellpose masks overlayed by new ROIs), potentially because the ROIs are exported from Cellpose twice. 

![image](https://github.com/MouseLand/cellpose/assets/62230171/a0918eb7-cbff-4ca9-8b9d-a1f2dfde5d37)

Is there any way I can fix the inconsistency between PNG labeled masks and ImageJ ROIs exported by Cellpose? Or is there a simple and fast (and ideally ImageJ macro-compatible) way to convert labeled masks into ImageJ ROIs?

Thanks a lot in advance!

**Comment by mrariden** [comment]
The library we're using to implement the ImageJ ROI exporting makes polygons based on points that are always in the top right of a pixel. ImageJ's ROIs are sub-pixel while those in cellpose are full pixels, which is the reason for the discrepancy. Because of this, the 'adjustment' should be consistent across the entire mask and resulting measurements should be identical. 

If the measurements are not similar please let us know.
