### ISSUE TITLE
diameter not correctly calculated for precomputed flow

### ISSUE THREAD

**Issue by qztseng** [MouseLand/cellpose#76]
If we use the `dynamics.labels_to_flows` to precompute the flows and use them for training, the diameter estimation would be wrong (thus the rescaling factor). 

In the source code, `utils.diameters` function need the original label, as a result , feed the train function with precomputed flow become impractical. 

Have you considered make the precomputed flows as extra inputs in addition to the labels ? so that diameter estimation and rescaling could still work.

**Comment by carsen-stringer** [comment]
oh that's a good point thanks for bringing that up, I will change it so that flows can be an input distinct from labels. Are you running this in a notebook or the command line? I won't make this a command line option as well unless you need it
