### ISSUE TITLE
Let user define a custom name for the output image.

### ISSUE THREAD

**Issue by VictorDidier** [MouseLand/cellpose#763]
**Is your feature request related to a problem? Please describe.**

Currently the name of the output image is only built by adding the suffix cp_masks to the name of the input image, i.e. _name_input_image_cp_masks.tif._ .  That naming convention is fixed and cannot be customized.

**Describe the solution you'd like**
Include a new flag as part of the output arguments that enables the user to define the name of the output image.

**Describe alternatives you've considered**
For example a flag called --output_name.

Type in the CLI:
--output_name "_custom_sample_name_"

In the output folder one should get the file:

_cutom_sample_name.tif_

**Additional context**
Standardizing input and output names comes in handy when pipelining.  Some pipelines that are already built have standardized names.  Hence, adding an output name flag will allow using cellpose within already established pipelines, e.g. MCMICRO.

**Comment by mrariden** [comment]
Hi @VictorDidier, how do you imaging implementing this for running Cellpose on a directory of images? Maybe this would only work when running on a single image?

**Comment by VictorDidier** [comment]
Hi @mrariden, yes you are right, this should be only implemented when running the segmentation on a single image.

**Comment by carsen-stringer** [comment]
this is implemented now as `--model_name_out`
