### ISSUE TITLE
Cellpose is taking a long time to process masks (upward of 300 seconds) 

### ISSUE THREAD

**Issue by naboughali** [MouseLand/cellpose#766]
Hi all, 

My version of cellpose (outlined below) is taking a few minutes to process masks. I am loading a 4X4 tile of images (16 bit depth) into the GUI for masking by cyto 2. I'm wondering why my system is slow, and if it has anything to do with the way I've configured cellpose (I'm using a 2020 Macbook Pro): 

cellpose version: 	2.2.1 
platform:       	darwin 
python version: 	3.8.16 
torch version:  	2.0.1
2023-08-17 10:59:50,634 [INFO] TORCH CUDA version not installed/working.

Thanks!

**Comment by naboughali** [comment]
Hi Nate, my images are 3789x3789 pixels and do complete processing.

Thanks for sharing!

________________________________
From: Nate ***@***.***>
Sent: Thursday, August 17, 2023 9:31 PM
To: MouseLand/cellpose ***@***.***>
Cc: Naira Abou-Ghali ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [MouseLand/cellpose] Cellpose is taking a long time to process masks (upward of 300 seconds) (Issue #766)


How large is the image and have you been able to successfully compute the masks? I've never run cellpose on my MacBook, but even with a GPU my 392x1500x1800 image takes around 1000 seconds to compute the masks, so it sounds relatively normal for CPU

**Comment by mrariden** [comment]
Closing for now, reopen if necessary
