### ISSUE TITLE
[BUG] Loading 3D images in GUI without auto-adjust

### ISSUE THREAD

**Issue by maulakhan** [MouseLand/cellpose#767]
**Describe the bug**
`Cellpose` GUI throws error when you load a new 3D image after you already have one loaded and unchecked `auto-adjust` button 

**To Reproduce**
1. Open `cellpose` GUI
2. Load a 3D tif image using  __File > Load image ( *.tif, *.png, *.jpg)__ 

<img width="599" alt="image" src="https://github.com/MouseLand/cellpose/assets/17739639/398ed920-5fe4-4de6-acba-4f867bb2082c">

3. Uncheck **auto-adjust** in **"Image saturation:"** section of GUI

<img width="607" alt="image" src="https://github.com/MouseLand/cellpose/assets/17739639/c2a1259f-5b3d-425b-b8b4-3adc6171c64e">

4. Load a 3D image using  __File > Load image ( *.tif, *.png, *.jpg)__ 
5. See error in terminal window

```
GUI_INFO: loading image: C:/Users/ak/C02_Image_34_Airyscan_Processing_s01_n001_t0008.tif
2023-08-21 13:59:13,242 [INFO] reading tiff with 61 planes
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 61/61 [00:00<00:00, 7626.69it/s]
GUI_INFO: converted to float and normalized values to 0.0->255.0
(60, 44, 4)
Traceback (most recent call last):
  File "C:\Users\ak\Miniconda3\envs\cellpose\lib\site-packages\cellpose\gui\menus.py", line 13, in <lambda>
    loadImg.triggered.connect(lambda: io._load_image(parent))
  File "C:\Users\ak\Miniconda3\envs\cellpose\lib\site-packages\cellpose\gui\io.py", line 129, in _load_image
    _initialize_images(parent, image, resize=parent.resize, X2=0)
  File "C:\Users\ak\Miniconda3\envs\cellpose\lib\site-packages\cellpose\gui\io.py", line 207, in _initialize_images
    parent.slider.setLow(0)
AttributeError: 'QRangeSlider' object has no attribute 'setLow'
``` 
@carsen-stringer

**Comment by carsen-stringer** [comment]
this is fixed in the new release
