### ISSUE TITLE
[BUG] Training Error

### ISSUE THREAD

**Issue by LIANGKE23** [MouseLand/cellpose#768]
This work is really nice. But I meet a problem during training.

I have tried the following commands for training.

python -m cellpose --train --use_gpu --dir D:/file/20180209_SEM_70_nm_HT_sintering/train/train/ --chan 2 --chan2 1 --n_epochs 600 --pretrained_model None --batch_size 8 --dir_above --save_each --verbose --img_filter '_img' --mask_filter '_masks'

However, I get the error below:

  File "C:\Users\liang\Anaconda3\envs\cellpose\lib\site-packages\cellpose\io.py", line 183, in get_image_files
    raise ValueError("ERROR: no images in --dir folder with extensions '.png', '.jpg', '.jpeg', '.tif', '.tiff'")
ValueError: ERROR: no images in --dir folder with extensions '.png', '.jpg', '.jpeg', '.tif', '.tiff'

While in our folder there are lots of png files together with the masks, which are also in png format. (See figure below)

<img width="405" alt="1692621016389" src="https://github.com/MouseLand/cellpose/assets/55468383/7019e12b-36a1-4b31-b503-ab90d92a6ac8">

I don't know how to figure the problem. Can you help me~?

**Comment by LIANGKE23** [comment]
I have figured it out!
Thank you!

**Comment by LIANGKE23** [comment]
I have figured it out!
Thank you!

**Comment by FCgogogo** [comment]
I have same problem,could you show how to reslove~
