### ISSUE TITLE
image analysis in imageJ

### ISSUE THREAD

**Issue by Git1919** [MouseLand/cellpose#77]
thank you for this great tool! I would like to import the segmented image in imageJ and perform further analysis. For instance, is it possible to load the information from the png image to ROI manager?

**Comment by carsen-stringer** [comment]
I've added a `save outlines` option to the GUI that creates a text file that ImageJ can then read. Also if you run cellpose with the `--save_png` option from the command line it will create that outline file. Here's how you use that text file in ImageJ. You will need to "run" as a macro the `imagej_roi_converter.py` file in the main repository:
![cellpose_to_imagej](https://user-images.githubusercontent.com/15067541/85233759-d5d37600-b3d6-11ea-82f1-c12e57223cea.gif)

**Comment by carsen-stringer** [comment]
I've added this to the documentation, see: https://cellpose.readthedocs.io/en/latest/outputs.html

**Comment by engineeringjoy** [comment]
Where can I find the imagej_roi_converter.py file? I would like to run it from ImageJ as in the demo but I don't see the file anywhere.
