### ISSUE TITLE
[Question] Does floating point precision matter?

### ISSUE THREAD

**Issue by BrosnanYuen** [MouseLand/cellpose#770]
Currently, everything is hard coded to use floating point 64 bit. However, some GPUs and CPUs do not support floating point 64 bit.
https://github.com/MouseLand/cellpose/pull/668
I changed the numpy and pytorch code to use floating point 32 bit, and they seem to produce the same predictions for segmentation.
I was thinking of submitting a PR for adding float 32 bit, bfloat16, and float16. 

Would this be a good idea?

**Comment by carsen-stringer** [comment]
I'm confused, everything is hard-coded to be FLOAT32, not FLOAT64. Float32 is the default float in pytorch. We do not recommend going below float32 in terms of precision, the speed ups are not huge either -- NVIDIA GPUs are well-optimized for float32

**Comment by BrosnanYuen** [comment]
@carsen-stringer 

https://github.com/MouseLand/cellpose/blob/a097ecc931ffb8abb44f99579e4f67edde5ff42b/cellpose/dynamics.py#L75

The tensors are initialized as torch.double which is float 64 bit

https://github.com/MouseLand/cellpose/blob/a097ecc931ffb8abb44f99579e4f67edde5ff42b/cellpose/utils.py#L115

Moreover, numpy initializations are also np.float64 which fails on certain CPU and GPUs that only support floating point 32 bit


It would be good to have a selector that allows for the change in precision.
