### ISSUE TITLE
[BUG] - resample=False causes Value Error

### ISSUE THREAD

**Issue by jimmib78** [MouseLand/cellpose#774]
**Describe the bug**
A Value Error Occurs on some images `ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (59, 2) + inhomogeneous part.`
The issue appears if 'resample=False' and there is an image_set that contains no identifiable cells.
If resample is left to the default (True), no error occurs.  I would like to leave this as false as the images are already being downsampled and I having to set diameter=90 to prevent the over-segmentation of larger cells. _Of note I tried using diameter to optimise different sized images (different resolution), but the results are very different to if I downsample the image and use the same  diameter._ 

**To Reproduce**
1. Run cellpose from Jupyter Notebook on blank image
2. set resample=False

**Run log**
```
Frame 58: 1 trajectories present.
processing file: 230823_L1_Akt-GAB-SHP_CS1_Series_10.tiff
2023-08-29 16:36:38,152 [INFO] >>>> loading model Z:/Proj_ERK/Adaptors + Akt/Training 2/models/CP_TIRF10_100x
2023-08-29 16:36:38,153 [INFO] ** TORCH CUDA version installed and working. **
2023-08-29 16:36:38,154 [INFO] >>>> using GPU
2023-08-29 16:36:38,349 [INFO] >>>> model diam_mean =  30.000 (ROIs rescaled to this size during training)
2023-08-29 16:36:38,350 [INFO] >>>> model diam_labels =  56.894 (mean diameter of training ROIs)
2023-08-29 16:36:38,451 [INFO] multi-stack tiff read in as having 59 planes 1 channels
2023-08-29 16:36:38,459 [INFO] 0%|          | 0/59 [00:00<?, ?it/s]
2023-08-29 16:36:38,568 [INFO] 7%|6         | 4/59 [00:00<00:01, 37.03it/s]
2023-08-29 16:36:38,678 [INFO] 14%|#3        | 8/59 [00:00<00:01, 36.63it/s]
2023-08-29 16:36:38,784 [INFO] 27%|##7       | 16/59 [00:00<00:00, 54.07it/s]
2023-08-29 16:36:38,894 [INFO] 42%|####2     | 25/59 [00:00<00:00, 65.16it/s]
2023-08-29 16:36:39,005 [INFO] 58%|#####7    | 34/59 [00:00<00:00, 71.21it/s]
2023-08-29 16:36:39,112 [INFO] 73%|#######2  | 43/59 [00:00<00:00, 75.30it/s]
2023-08-29 16:36:39,223 [INFO] 88%|########8 | 52/59 [00:00<00:00, 77.21it/s]
2023-08-29 16:36:39,309 [INFO] 100%|##########| 59/59 [00:00<00:00, 69.56it/s]
2023-08-29 16:36:39,309 [INFO] network run in 0.85s
2023-08-29 16:36:39,453 [WARNING] WARNING: no mask pixels found
2023-08-29 16:36:39,454 [INFO] No cell pixels found.
2023-08-29 16:36:40,656 [INFO] No cell pixels found.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[9], line 59
     57 print ("processing file:", file)
     58 input_file_path = os.path.join(input_folder, file)
---> 59 measurements = process_tiff_file(input_file_path, cellpose_model, output_folder, properties)
     61 if measurements is None:  # check if process_tiff_file returned None
     62     continue  # skip to the next iteration if no cells were detected

Cell In[8], line 385, in process_tiff_file(file_path, cellpose_model, output_folder, properties)
    381     use_rescale = True
    384 #Generate Masks
--> 385 masks = run_cellpose_on_images(images, metadata)
    387 #Perform background subtraction
    388 images = subtract_background_global(images)

Cell In[8], line 293, in run_cellpose_on_images(images, metadata)
    290 cell_diameter = get_diameter(metadata)
    292 #masks, flows, styles = cellpose_model.eval(images_avg, diameter=cell_diameter, resample=False, channels=[0, 0], do_3D=False,stitch_threshold=0.2)
--> 293 masks, flows, styles = cellpose_model.eval(images_avg, diameter=cellpose_cell_diameter, resample=False, channels=[0, 0], do_3D=False, stitch_threshold=0.2)
    294 #Identify if masks are empty
    295 if np.any(masks):

File ~\anaconda3\envs\cellpose2\lib\site-packages\cellpose\models.py:552, in CellposeModel.eval(self, x, batch_size, channels, channel_axis, z_axis, normalize, invert, rescale, diameter, do_3D, anisotropy, net_avg, augment, tile, tile_overlap, resample, interp, flow_threshold, cellprob_threshold, compute_masks, min_size, stitch_threshold, progress, loop_run, model_loaded)
    549     diameter = self.diam_labels
    550     rescale = self.diam_mean / diameter
--> 552 masks, styles, dP, cellprob, p = self._run_cp(x, 
    553                                               compute_masks=compute_masks,
    554                                               normalize=normalize,
    555                                               invert=invert,
    556                                               rescale=rescale, 
    557                                               net_avg=net_avg, 
    558                                               resample=resample,
    559                                               augment=augment, 
    560                                               tile=tile, 
    561                                               tile_overlap=tile_overlap,
    562                                               flow_threshold=flow_threshold,
    563                                               cellprob_threshold=cellprob_threshold, 
    564                                               interp=interp,
    565                                               min_size=min_size, 
    566                                               do_3D=do_3D, 
    567                                               anisotropy=anisotropy,
    568                                               stitch_threshold=stitch_threshold,
    569                                               )
    571 flows = [plot.dx_to_circ(dP), dP, cellprob, p]
    572 return masks, flows, styles

File ~\anaconda3\envs\cellpose2\lib\site-packages\cellpose\models.py:659, in CellposeModel._run_cp(self, x, compute_masks, normalize, invert, rescale, net_avg, resample, augment, tile, tile_overlap, cellprob_threshold, flow_threshold, min_size, interp, anisotropy, do_3D, stitch_threshold)
    656     p.append(outputs[1])
    658 masks = np.array(masks)
--> 659 p = np.array(p)
    661 if stitch_threshold > 0 and nimg > 1:
    662     models_logger.info(f'stitching {nimg} planes using stitch_threshold={stitch_threshold:0.3f} to make 3D masks')

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (59, 2) + inhomogeneous part.
```

**Screenshots**

**Comment by mrariden** [comment]
I think the reason you're getting this error is that CP isn't set up to expect a z stack with 59 slices and not get any cells. Does this still happen when your images have cells in them?

**Comment by jimmib78** [comment]
Hi @mrariden ,
This is part of afairly long script but the key parts are
`# Instantiate the Cellpose model with the custom model
cellpose_model = models.CellposeModel(pretrained_model=model_file, gpu=True)
 masks, flows, styles = cellpose_model.eval(images_avg, diameter=cellpose_cell_diameter, resample=False, channels=[0, 0], do_3D=False, stitch_threshold=0.2)
        `

> CP isn't set up to expect a z stack with 59 slices and not get any cells.

If so , why does the issue only occur if  resample=False? If  I run 
` masks, flows, styles = cellpose_model.eval(images_avg, diameter=cellpose_cell_diameter,  channels=[0, 0], do_3D=False, stitch_threshold=0.2)`  - I dont get the issue.

> Does this still happen when your images have cells in them?

It does if the cell does not produce a mask.  For example for these experiments I am using diameter = 90 and some images have cells too small and this leads to the same error as a blank image.

Cheers,
James

**Comment by mrariden** [comment]
> > CP isn't set up to expect a z stack with 59 slices and not get any cells.
>
> If so , why does the issue only occur if `resample=False`? 

I was moreso attempting to say that the testing data used to validate the code all has detectable cells. I'm not exactly sure why there is a difference in producing an error when `resample=False`. I'd guess that cellpose is finding cells with `resample=True` and because you're finding cells, you're not getting 'empty' output inside the `.eval()`. The purpose/theory of the resampling step is described [here](https://cellpose.readthedocs.io/en/latest/settings.html#resample). Basically, you're more likely to find cells with it on because the dynamics will be more fine-grained. 

I'm not able to reproduce the error with my data, yet. Can you share what your `images_avg` input is when calling `.eval()`? In particular any `.shape` information and the type (numpy array, list of numpy array, torch, etc.). There is some axes finagling to guess the shape of the input. 

Finally, and just to confirm, your `cellpose_cell_diameter` variable is set to `90`, and not a list of different diameters?

**Comment by jimmib78** [comment]
Hi @mrariden ,
>I'd guess that cellpose is finding cells with resample=True and because you're finding cells, you're not getting 'empty' output inside the .eval(). 

This is not correct.  I can run cellpose with resample=True on blank images and the output is a blank mask. With resample=false the result is the error.
The images are tiffs loaded with tifffile.
The shape of these images are (59, 290, 290). The image resolution is 2.27 pixels/um and as part of the script they are rescaled to 1.38 pixels/micron, so the size will be (59, 176, 176).  
array type = uint16

This was done as I was not getting consistent output when using different diameter to account for different image resolutions.
 I have tried uploading one but tiffs are not supported here.  
I am happy to share these in an appropriate format.

Cheers
James

**Comment by mrariden** [comment]
Thanks for providing that information about your input images. 

I'm still not able to reproduce the error from a minimal example. I need to reproduce the error in order to debug and provide a fix. Does the following code produce an error on your machine? 

```python
from cellpose.models import CellposeModel
import numpy as np

img = np.zeros((59, 176, 176), dtype=np.uint16)
diameter = 90
model = CellposeModel(model_type='cyto', gpu=True)

masks, flows, styles = model.eval(img, diameter=diameter, resample=False, channels=[0, 0], do_3D=False, stitch_threshold=0.2)
```
If that does not produce an error, is there some minimal and complete example that you can provide that does?  

To attach your file, I think you can put it in a zip archive an attach it.

**Comment by jimmib78** [comment]
Your code works fine. So  I have done some further exploration.
As I am scaling the images using skimage, the data type is changed to float 64.  
I thought this was the issue. but if I change your  example to scale the data it still works fine. The story is different for this image.

[230823_L1_Akt-GAB-SHP_CS1_Series_10.zip](https://github.com/MouseLand/cellpose/files/12482794/230823_L1_Akt-GAB-SHP_CS1_Series_10.zip)

```
from cellpose.models import CellposeModel
import numpy as np
from skimage import transform
import tifffile

#path_to_file = "Z:/Proj_ERK/Adaptors + Akt/230823_L1_Akt-GAB-SHP/230823_L1_Akt-GAB-SHP_CS1_tiffs/230823_L1_Akt-GAB-SHP_CS1_Series_10.tiff"
#tiff_file = tifffile.TiffFile(path_to_file)
img = tiff_file.asarray()
#img = np.zeros((59, 176, 176), dtype=np.uint16)
diameter = 90
model = CellposeModel(model_type='cyto', gpu=True)

masks, flows, styles = model.eval(img, diameter=diameter, resample=False, channels=[0, 0], do_3D=False, stitch_threshold=0.2)
```

This works fine but., if we rescale this image


```
rescale_factor = 0.8

new_height = int(img.shape[-2] * rescale_factor)
new_width = int(img.shape[-1] * rescale_factor)

output_shape=(59, new_height, new_width)

rescaled_image = transform.resize(img, output_shape, mode='reflect', anti_aliasing=True, preserve_range=True)

model = CellposeModel(model_type='cyto', gpu=True)
masks, flows, styles = model.eval(rescaled_image, diameter=diameter, resample=False, channels=[0, 0], do_3D=False, stitch_threshold=0.2)

```
Now we get an error.    Note that this is not true for all images. Other images from the same dataset are fine, so the issue does not seem to be the transform itself.

**Comment by mrariden** [comment]
Fantastic, I've identified the bug. Thanks for your help!

We'll get the fix integrated into the main branch soon. In the meantime, you can use the fix branch immediately by:
`conda activate <your_env>`
`pip install git+https://github.com/mrariden/cellpose@dynamics_reshape_fix`

But, you will need git installed.

**Comment by jimmib78** [comment]
Thanks mate.
Works for me!
