### ISSUE TITLE
Cyto2 Dataset?

### ISSUE THREAD

**Issue by NathanMalta** [MouseLand/cellpose#777]
Hi, thank you for your work on CellPose!

Do you have a link to the cyto2 training set with the user-submitted images?  What cell types are included in this dataset?

Thank you again

**Comment by carsen-stringer** [comment]
Sorry Nathan, we received images anonymously, and so we don't know what kind of images were included in the dataset. Generally these images were slightly lower SNR than the original cellpose dataset. We will look into releasing them.
