### ISSUE TITLE
Persisting Index Error when using cellpose from command line 

### ISSUE THREAD

**Issue by adrtsc** [MouseLand/cellpose#78]
Hi,

Im working with a freshly installed github version of cellpose and I am experiencing the same problem as the closed issue #65. The solution proposed in this issue to add an n-index in io.py on line 61 solves the problem for me:

`flowi.append(np.zeros(flows[n][1][0].shape, dtype=np.uint8))`

but also replacing the [1] index with [n] seems to solve the problem:

`flowi.append(np.zeros(flows[n][0].shape, dtype=np.uint8))`

Would be great if this could get a fix.
Thanks

**Comment by carsen-stringer** [comment]
done! sorry should be `n`
