### ISSUE TITLE
Expression does not seem to have any effect.

### ISSUE THREAD

**Issue by etasnadi** [MouseLand/cellpose#792]
This expression does not seem to have any effect. If the convergence centroids assumed to be sorted based on the number of pixels drained, then this may have to be eventually fixed.

https://github.com/MouseLand/cellpose/blob/5fb74fde155c35dafcd096fd66118b3cfdd174a0/cellpose/dynamics.py#L670

Similarly (it is done properly a few lines below, and it may not introduce any unexpected behavior anyways):

https://github.com/MouseLand/cellpose/blob/5fb74fde155c35dafcd096fd66118b3cfdd174a0/cellpose/dynamics.py#L680

Also, the boundary condition may not have any effect:

https://github.com/MouseLand/cellpose/blob/5fb74fde155c35dafcd096fd66118b3cfdd174a0/cellpose/dynamics.py#L695

**Comment by etasnadi** [comment]
IMO the whole loop here:

https://github.com/MouseLand/cellpose/blob/5fb74fde155c35dafcd096fd66118b3cfdd174a0/cellpose/dynamics.py#L682

is probably dead code since it updates `pix[k]` (that is a copy of the `seeds`) in line
https://github.com/MouseLand/cellpose/blob/5fb74fde155c35dafcd096fd66118b3cfdd174a0/cellpose/dynamics.py#L699
with the pixels in `newpix` (containing `pix[k]` and neighbors of `pix[k]`) having `h` value > 2. This can only be satistied by `pix[k]` because in line 
https://github.com/MouseLand/cellpose/blob/5fb74fde155c35dafcd096fd66118b3cfdd174a0/cellpose/dynamics.py#L666
we selected the seeds such that none of them can have first and second order neighbors.

**Comment by carsen-stringer** [comment]
will be fixed in new release
