### ISSUE TITLE
Inquiry Regarding Obtaining Cell Position Information in Cellpose

### ISSUE THREAD

**Issue by MistSnow** [MouseLand/cellpose#794]
I have found it to be quite useful for segmenting cell boundaries. However, I have encountered a problem.

After successfully segmenting the cell contours, I am now looking for a way to obtain the positional information for each segmented cell. I have thoroughly explored the functionalities of cellpose but I couldn't find a method to extract this information. So is there such a method in cellpose?

**Comment by mrariden** [comment]
No, cellpose does not currently provide this information. You can look at the [image.sc](https://forum.image.sc/tag/cellpose) forum for how other people have acquired it from segmented masks.

**Comment by MistSnow** [comment]
OK, thank you very much.
