### ISSUE TITLE
Users should be able to control the image normalization parameters [FEATURE]

### ISSUE THREAD

**Issue by giocard** [MouseLand/cellpose#795]
Currently all the images are normalized between the 1st and 99th percentile (by the function _normalize_img_ in _transforms.py_) before running the prediction.
However, these settings are suboptimal when there are few objects in the field of view, in particular for 3D volumes (see [https://forum.image.sc/t/normalization-in-stardist/41696](url) where this topic is discussed)
In this image I show an example of how the percentile range affects the segmentation. The comparison is performed on simulated 3D data, but the results perfectly mimic my experience on recent images acquired from a light-sheet microscope

![effect_of_image_normalization-3D](https://github.com/MouseLand/cellpose/assets/25342529/40ab0b89-e0db-4a1a-a9c5-6e68ea13cc84)

It would be useful to have the percentile range as an additional input parameter. In general the default values work well, but in some cases this kind of control could be really beneficial.

Thank you.

**Comment by mauripops** [comment]
This is not only an issue for 3d images but removing the normalization(changed it to a simple minmax) improved my segmentation results significantly. I feel this could even be a feature to add in the GUI

**Comment by carsen-stringer** [comment]
this is soon to be merged into cellpose in the GUI

**Comment by Pascal-bucketbreaker** [comment]
How can I do this in python api？

**Comment by mrariden** [comment]
@Pascal-bucketbreaker You can input a dictionary to the `normalize` parameter in the .eval() call: 

”lowhigh”=None : pass in normalization values for 0.0 and 1.0 as list [low, high] (if not None, all following parameters ignored)

”sharpen”=0 ; sharpen image with high pass filter, recommended to be 1/4-1/8 diameter of cells in pixels

”normalize”=True ; run normalization (if False, all following parameters ignored)

”percentile”=None : pass in percentiles to use as list [perc_low, perc_high]


So something like: 
```python
my_norm_dict = {
    'percentile' : [10, 80]
}
```
