### ISSUE TITLE
Human-in-the-loop model segmenting worse than pre-trained model

### ISSUE THREAD

**Issue by ecs13** [MouseLand/cellpose#797]
I have been working on applying Cellpose to Nissl-stained pyramidal neurons and found the pre-trained cyto model to work decently well. I have now been trying to apply the human-in-loop model and have tried training it twice, the first time it was trained with 5 2500x2500 pixel images of my area of interest and applied to a separate data set with manual stereology counts for validation. This model had lower numbers than the pre-trained model and the pre-trained model was already underestimating compared to the manual stereology counts. I attempted to train the human-in-the-loop-model again with 10 512x512 pixel images (since this is the size mentioned in the Cellpose 2.0 paper) and the numbers were even lower than the first human-in-the-loop model. I also tried training a model on just one image, and then rerunning that image through the model to see if the segmentations are coming out the same after I edit them, and the two segmentations were different for the same image. Is there any reason why the model might be getting worse or other ways to try and improve the accuracy?

**Comment by mrariden** [comment]
There are many potential issues ranging from the distributions of your train/test data to the training parameters. You will get much more interactive help on the image.sc forum. This space is primarily for feature requests, bug reports, and installation issues
