### ISSUE TITLE
[BUG] ValueError when launching io.save_masks on Windows with 80 cores

### ISSUE THREAD

**Issue by AndreasB01** [MouseLand/cellpose#798]
I am running the notebook [run_cellpose_2.ipynb] with the sample data on a Windows server 2022 computer with 40 cores (80 logical processors). It runs well until trying to save the output masks  using:

io.save_masks(images,
masks,
flows,
files,
channels=channels,
png=True, # save masks as PNGs and save example image
tif=True, # save masks as TIFFs
save_txt=True, # save txt outlines for ImageJ
save_flows=False, # save flows as TIFFs
save_outlines=False, # save outlines as TIFFs
)

I receive the following error:

Exception in thread Thread-11 (_handle_workers):
Traceback (most recent call last):
File “C:\Users\bruckb01\miniforge3\envs\cellpose\lib\threading.py”, line 1016, in _bootstrap_inner
self.run()
File “C:\Users\bruckb01\miniforge3\envs\cellpose\lib\threading.py”, line 953, in run
self._target(*self._args, **self._kwargs)
File “C:\Users\bruckb01\miniforge3\envs\cellpose\lib\multiprocessing\pool.py”, line 522, in _handle_workers
cls._wait_for_updates(current_sentinels, change_notifier)
File “C:\Users\bruckb01\miniforge3\envs\cellpose\lib\multiprocessing\pool.py”, line 502, in _wait_for_updates
wait(sentinels, timeout=timeout)
File “C:\Users\bruckb01\miniforge3\envs\cellpose\lib\multiprocessing\connection.py”, line 879, in wait
ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
File “C:\Users\bruckb01\miniforge3\envs\cellpose\lib\multiprocessing\connection.py”, line 811, in _exhaustive_wait
res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 82

This seems to be a multi-processor issue with python on Windows, see 
[https://forum.image.sc/t/cellpose-multi-processor-issue/87021](https://forum.image.sc/t/cellpose-multi-processor-issue/87021)
which is not solved in the most recent python versions. I am running python 3.10

Can the code for **io.save_mask**s be changed to restrict the number of cores on Windows machines?

Thank you!

**Comment by mrariden** [comment]
this should be fixed with #811. You can try it by installing that branch, or wait until the branch is merged into main followed by updating cellpose. 

Reopen if necessary
