### ISSUE TITLE
Cellpose results slightly different on my computer vs. website

### ISSUE THREAD

**Issue by ninning** [MouseLand/cellpose#80]
Hi all,

First off thank you for sharing this great tool for cell segmentation.
Ive been testing it out on my Mac (10.14.16 Mojave), both the GUI and non-gui version and I did have to downgrade my cv2 to 4.1.2.30 and add in this line
```
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
```
as suggested in previous posts to get it working on my mac.
After testing it out a bit i noticed that my results for the same image are different depending on whether i use the cellpose.org website vs. in a notebook on my computer.

The website shows:
<img width="1316" alt="Screen Shot 2020-06-02 at 2 50 13 PM" src="https://user-images.githubusercontent.com/24235120/83558703-69550d80-a4e1-11ea-8ff1-7f4f269d1c7b.png">
Just using the default settings. And I think it looks quite good already.

But running it on the notebook shows:
<img width="1037" alt="Screen Shot 2020-06-02 at 2 50 31 PM" src="https://user-images.githubusercontent.com/24235120/83558746-78d45680-a4e1-11ea-9df3-4ff944188413.png">
I did try to manually adjust the cell diameter but it didnt seem to help.

The closest i got to the website result was running the GUI, letting it automatically select the cell diameter and adjusting some of the parameters, but its still not exactly the same:
<img width="1150" alt="Screen Shot 2020-06-02 at 1 03 16 PM" src="https://user-images.githubusercontent.com/24235120/83558804-943f6180-a4e1-11ea-99b1-c8e1132d9db8.png">

I was wondering if the cellpose.org website was doing something different, or maybe its a mac specific issue due to the multiple .dylib files.

I havent tested it on the google colab notebook yet. 

Thank you!

**Comment by ninning** [comment]
Update:
It turns out I had the channels set incorrectly previously. Setting it to just [0,0] largely fixed the issue as shown here:

<img width="1051" alt="Screen Shot 2020-06-02 at 11 21 49 PM" src="https://user-images.githubusercontent.com/24235120/83592273-fcb13180-a527-11ea-9d24-d87550c0980d.png">

Done in the google colab notebook.

There are still some really minor differences and Ive been testing some different settings in therms of cell diameter and flow threshold. However I would still be curious to learn what the settings cellpose.org uses for its example segmentation. Thanks.

**Comment by carsen-stringer** [comment]
for the website the test-time augmentations (tiling) do not occur. Also we resize the image so that it's at most 512 pixels on a given size. otherwise the settings should be the same (default flow threshold used, diameter set by user (not autoset))
