### ISSUE TITLE
Why is it that after modifying the original code, the information on the GUI interface generated by running the cli file has not changed, who can help me answer the following, thanks~

### ISSUE THREAD

**Issue by FCgogogo** [MouseLand/cellpose#803]
Why is it that after modifying the original code, the information on the GUI interface generated by running the cli file has not changed, who can help me answer the following, thanks~

**Comment by mrariden** [comment]
You need to reinstall with pip. Either `pip install .` or `pip install -e .` you can read the documentation or other forums for more details.
