### ISSUE TITLE
Message - TORCH CUDA version not installed/working even though running on CPU

### ISSUE THREAD

**Issue by DCBITTEL** [MouseLand/cellpose#809]
Im running cell pose locally on my Mac laptop (CPU) and I've followed the instructions listed on the Github page (i.e. installed Anaconda, created the python 3.8 environment, installed cell pose and the GUI on the zsh server, upgraded cell pose and then started the GUI by running  python -m cellpose. I can load my image, and can run it through (albeit slowly). However, after analyzing one image or so, I start getting the message in the terminal window - TORCH CUDA version not installed/working. Since I'm running this on the CPU, why am I getting this message? Does it matter or can I ignore it? I am unsure if this message is causing Cellpose to not work on subsequent images as the processing of the image by the software seems to no longer work/finish? Any help or insight would be great.

thanks,
Dabn

**Comment by mrariden** [comment]
That message is displayed on all systems and indicates if GPU acceleration is enabled. Since your Mac doesn't have it, the message says it's not enabled. 

Cellpose will operate as normally in CPU only mode. You can ignore it.
