### ISSUE TITLE
3D segmentation in collab - wrong tif input?

### ISSUE THREAD

**Issue by Jiburii** [MouseLand/cellpose#81]
I hope everyone here is OK, its a very difficult time right now. 

Happy to make your acquiantance. I am a post doc in the lab of Dr. Emily Mace at Columbia, and increasingly we are testing segmentation methods to separate fluorescent nuclei in 3D/2D organoids/iPSC derived cultures.

I have been trying cellpose, and have succeeded in segmenting my 2D timelapse data (NK cells differentiating from iPSCs) in the GUI on the CPU.

For the 3D timelapse data, i then tried first a single z stack in the GUI, which seemed to succeed. 

As I want to do batch 3D processing, I tried the same z stack in the google collab, and it seemed to work OK, and I got it to save an .npy file (screenshot shows how i altered the collab script).

Here’s the cell I altered in the collab script.

files = ['/content/drive/My Drive/CellPose_3D/TEST_EXPORT_%N_XY%P_C%C_T%T_Z%Z_C1onlyTIFFSTACK_onezstack/1Zstack.tif']
    
imgs = [skimage.io.imread(f) for f in files]
nimg = len(imgs)

# test 3D stack

# in this example I'm using a random matrix, put your own data here
data = np.random.randn(120,512,512).astype(np.float32)

# with 3D you have to set the diameter manually (no auto detect)
masks, flows, styles, diams = model.eval(imgs, channels=[0,0], diameter=17, do_3D=True)

from cellpose import io

io.masks_flows_to_seg(imgs, masks, flows, diams, files, channels)

When I open this .npy file in the cellpose GUI, it just looks like the raw file, with no masks. I notice an error, too, suggesting that the structure of the .npy file is wrong, probably due to the structure of the original .tif stack being wrong?

(cellpose) E:\DATA\MichaelShannon\cellpose-master\notebooks>python -m cellpose

E:/DATA/MichaelShannon/SEUNGMAE_/Fluorescence/pos1_c1only_singlexy_zstack_STACK_collab/Pos1_c1only.tif
10 (1024, 1024, 3)
Traceback (most recent call last):
  File "C:\Users\3i\.conda\envs\cellpose\lib\site-packages\cellpose\menus.py", line 22, in <lambda>
    loadManual.triggered.connect(lambda: io._load_seg(parent))
  File "C:\Users\3i\.conda\envs\cellpose\lib\site-packages\cellpose\io.py", line 333, in _load_seg
    parent.ChannelChoose[0].setCurrentIndex(dat['chan_choose'][0])
TypeError: setCurrentIndex(self, int): argument 1 has unexpected type 'list'

As I am not a python expert, it is hard for me to see what I would do next: I want to 1) check that the input file was correct, and get it working to spit out 3D masks 2) run this on a tif stack containing z but also time. 3) Do number 2 in batch over many different xy and conditions. 

If anyone could help me with the above, I would be most grateful.

Google drive containing example data (z stack of 10 planes, single time point, single xy): https://drive.google.com/drive/folders/1Vx-km55-Et3pgR2PTiEmy31LFGmbEkg8?usp=sharing

**Comment by carsen-stringer** [comment]
I'm sorry for the delay on this. It should have thrown an error when you tried to run `io.masks_flows_to_seg` I believe. I've fixed it for 3D so it should now work correctly. please comment if it's still erroring
