### ISSUE TITLE
Reason for 'self.unet = False'

### ISSUE THREAD

**Issue by Soroush-aali-bagi** [MouseLand/cellpose#812]
I wonder the reason for making 'self.unet = False' just after creating a UNet model in CellposeModel:
https://github.com/MouseLand/cellpose/blob/5fb74fde155c35dafcd096fd66118b3cfdd174a0/cellpose/models.py#L370C9-L370C26

**Comment by mrariden** [comment]
That variable is used to control if a CPnet or a UNet is created. Regular usage will always be a CPnet. The UNet is included for backwards compatibility. 

You can find the code for those classes in the repo, and you can read more about their structure in the CP1 paper.
