### ISSUE TITLE
RGB on >3 Layer Image

### ISSUE THREAD

**Issue by matthew-lee1** [MouseLand/cellpose#816]
**Is your feature request related to a problem? Please describe.**
When I use the cellpose GUI and I have an H&E image stacked with a multiplex IF image, I would like to be able to view the H&E image as RGB (first three channels) but then still be able to segment on channels 4 and 5. Is this possible? 

**Describe the solution you'd like**
The solution is mostly in the viewer. I know that it converts >3 channels to z-stack. however then I am unable to combine z=0,1,2 for the RGB H&E image.

**Comment by matthew-lee1** [comment]
This might not be an enhancement... it might already be possible?

**Comment by mrariden** [comment]
This is possible without modifying cellpose by making the H&E image greyscale in channel 0 and then segmenting on channels 1 and 2. You'd have to use another program like ImageJ to make the H&E grayscale and then convert the image to a stack or RGB

**Comment by matthew-lee1** [comment]
Yes I have tried that. But I am asking specifically for the RGB H&E image, not the grayscale.

**Comment by carsen-stringer** [comment]
sorry this will not be possible in the GUI. you are only able to segment channels that are loaded into the GUI
