### ISSUE TITLE
Cannot run a 3D segmentation for multi-channel, multi-Z tiff's

### ISSUE THREAD

**Issue by gabriel5222** [MouseLand/cellpose#82]
Hello,

I'm having trouble for running a 3D segmentation for multi-channel, each time I try to just open the tiff files Cellpose shut down and I have this message on the Anaconda prompt: 
-type error: data.shape[2] must be <= 4

The tiff file doesn't countain multi-time, so normally it's just a cxyz file.

Do I need to do something specific before I can import the file on Cellpose ?

Thank you.

**Comment by bioinfbloke** [comment]
I would also like to see this feature. I am working on multi channel data from mass spec derived images, where each channel is a marker/protein. Ideally would be able to select 1 or more channels at a time.

**Comment by carsen-stringer** [comment]
How many channels is your image? Can you please tell me the shape of the tiff when it is loaded into python with tifffile or skimage? or share an example tiff with me? You're using the GUI? It assumes that the loaded image is Z x channels x X x Y or channels x Z x X x Y or Z x X x Y x channels. It also currently assumes that you have 3 or fewer channels

**Comment by bioinfbloke** [comment]
It can have up to ~45 channels but in practice we probably initially only use 3 that would be equivalent to nucleus, cytoplasm and membrane. I can send examples offline if that helps. The data is from the Hyperion platform.

**Comment by gabriel5222** [comment]
I have tried with 3 channels image, yes I'm using the GUI and for Z x channels x X x Y I can't change that setting that way on ImageJ, X x Y always come first.

![Capture](https://user-images.githubusercontent.com/64024066/85554200-f85ace80-b624-11ea-8803-dafcf570f0a3.PNG)

You can download one of my tiff here: https://filesender.renater.fr/?s=download&token=f6efcc64-25e7-4d83-8c81-9acea200416d

**Comment by carsen-stringer** [comment]
I've made it possible to specify the channel axis when you load the tiff into the napari gui: https://cellpose-napari.readthedocs.io/en/latest/running.html#d-segmentation

I will not support changing the channel axis in the native cellpose GUI
