### ISSUE TITLE
Unable to export model to ONNX using PyTorch ONNX Exporter

### ISSUE THREAD

**Issue by shoyip** [MouseLand/cellpose#821]
**Describe the bug**
I am trying to (naively) export my `CellposeModel` Unet/ResNet `nn.Module` subclass but I am unable to.
Trying to use the `torch.onnx.export` function yields the following error:
```
RuntimeError: Tried to trace <__torch__.torch.utils.mkldnn.MkldnnBatchNorm object at 0x5598e38bd140> but it is not part of the active trace. Modules that are called during a trace must be registered as submodules of the thing being traced.
```

Is there any way to easily export the model? I would like to use it on OpenCV, but in a setup where the backend codebase is in C++ instead of Python.

**To Reproduce**
1. Import my pretrained cellpose model: `mymodel = models.CellposeModel(pretrained_model='/content/drive/MyDrive/folder_of_model/model_file')`
2. Generate a random variable: `generated_input = torch.autograd.Variable(torch.randn(0, 0, 512, 512))`
3. Issue the command for model export `onnx.export(mymodel.net, generated_input, '/content/drive/MyDrive/folder_of_model/model.onnx', verbose=True, input_names=['input'], output_names=['output'], opset_version=11)`
4. See error.

**Comment by mrariden** [comment]
The CellposeModel is composed of much more than just a CNN. There are preprocessing and postprocessing steps that can't be converted into the ONNX framework

**Comment by shoyip** [comment]
Thanks @mrariden! I see that preprocessing and postprocessing parts are important, and I guess that they are also what adds the complexity to the results of Cellpose. However I was looking to export only the network that could predict the masks (which, I guess from a quick look at the code, is the role of the `CPnet` object). Thanks to your suggestion, I was able to get over the error but I got another one which I cannot understand what is related to:

```
UnsupportedOperatorError: Exporting the operator 'aten::to_mkldnn' to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
```

Do you have any clue of how I could overcome this? Should I really open an issue on the PyTorch Github?
Thanks for the help!

**Comment by mrariden** [comment]
It looks like the ONNX opset doesn't support one of the operations in the CPnet. What if you try a different opset?

**Comment by shoyip** [comment]
I was unable to do the export with any version. Do you have any other clue? Maybe related to `aten::to_mkldnn`? Following suggestion on a [SO question](https://stackoverflow.com/questions/71220867/pytorch-to-onnx-export-aten-operators-not-supported-onnxruntime-hangs-out), I have succeded in exporting the CPnet by however leaving the ATen parts 'as is', which I do not fully understand whether it makes them work or not.
Thanks in advance.

**Comment by carsen-stringer** [comment]
Hi @shoyip I'm sorry we don't have time to help with this, pytorch is well supported and fast and we recommend using it instead of converting out of pytorch

**Comment by Achuan-2** [comment]
@shoyip 
Did you succeed? I also want to use Matlab to call the Cellpose model

**Comment by vinjk** [comment]
> @shoyip Did you succeed? I also want to use Matlab to call the Cellpose model

https://www.mathworks.com/help/medical-imaging/cellpose-support.html?s_tid=CRUX_lftnav

**Comment by Achuan-2** [comment]
Wow, thank you so much !!!!
Before you tell me, I simplifie cellposed  into a python module by myself to call cellpose with pyenv in Matlab.

**Comment by Achuan-2** [comment]
> > @shoyip Did you succeed? I also want to use Matlab to call the Cellpose model
> 
> https://www.mathworks.com/help/medical-imaging/cellpose-support.html?s_tid=CRUX_lftnav

Wow, thank you so much !!!!
Before you tell me, I simplified cellpose  into a python module by myself to call cellpose with pyenv in Matlab.

**Comment by reality-h** [comment]
Excuse me, how can I port Cellpose to C++?
