### ISSUE TITLE
[FEATURE] Multi channel image contrast

### ISSUE THREAD

**Issue by manerotoni** [MouseLand/cellpose#823]
**Problem**
We have multi channel images. The intensity range for each channel is very different with one channel (nuclei) being very bright and one channel (cellular specific marker) being very low. This is not uncommon in fluorescence microscopy. To pick the cells to segment I need to see both channels. Currently there exists only one contrast for both channels.

**Feature Request**
Two sliders for the contrast (one for each channel) or something that remembers the setting for each channel. 

**Describe alternatives you've considered**
Normalize the images  for the training and labeling phase. Use the GT labels to train a model on  the original images. This works but is not convenient.

**Comment by mrariden** [comment]
This is actively being developed. You can try it out in the dev branch if you want in the meantime

**Comment by manerotoni** [comment]
Great! Thanks for letting me know. I will try it as soon as possible.
