### ISSUE TITLE
Labeling outlines as a semantic segmentation class

### ISSUE THREAD

**Issue by motviybletb** [MouseLand/cellpose#824]
Hi!
I have a question about how I can label edges of cells in my pictures.
Are there any functions in cellpose for it?
And if not, is it possible to use outlines from .npy file for it?

**Comment by mrariden** [comment]
Yes, you can export an image that has only the cell outlines. There is information on how to do this on the [docs here](https://cellpose.readthedocs.io/en/latest/cli.html).

You could use the .npy file to do it if you've already ran CP on your images; the same information is in the file
