### ISSUE TITLE
Reopening issue #818: Combining multiple trained models.

### ISSUE THREAD

**Issue by clemyyyy** [MouseLand/cellpose#825]
Hi there,

Thanks for getting back to me. I checked the thread and paper you mentioned. Here is your answer to the previous issue: 

"A new model is made each iteration through the HITL loop. You can read more about this in the CP2 paper or in this issue: #723 . 

Closing for now, feel free to reopen.

_Originally posted by @mrariden in https://github.com/MouseLand/cellpose/issues/818#issuecomment-1802164787_"

Unfortunately, it doesn't solve my issue. I observed that when training in the Cellpose GUI on my computer, the newly trained model is saved as a single, unified model. However, when I close and reopen the GUI later, the model gets divided into multiple models, all with the exact same names. The strange part is that the number of models it's split into matches the number of images I used to train the model. I'm a bit puzzled about what's happening.

Appreciate any insights you might have.

**Comment by mrariden** [comment]
I'm reopening the original issue, so we don't need this one
