### ISSUE TITLE
[FEATURE] When running from code give a message if GPU/CUDA is used

### ISSUE THREAD

**Issue by manerotoni** [MouseLand/cellpose#826]
Hello 
**Problem**
I had a python environment where the cellpose GUI was running using the GPU and the prediction was really fast. 
When running evaluation in a notebook using ```model.eval``` I realized that it was very slow compared to the GUI.
I was not expecting that the two accessed the GPU differently and it took me a while to realize that some torch packages had the CPU version.

**Describe the solution you'd like**
When calling 
```models.CellposeModel(gpu = True, pretrained_model = model_path)```
it would be nice if the user get a printed feedback like for the GUI. 

Thanks

**Comment by carsen-stringer** [comment]
please say `io.logger_setup()` then you will get all the cellpose messages in a notebook too. sorry this isn't more clear in the documentation

**Comment by manerotoni** [comment]
Thanks!
