### ISSUE TITLE
optimal use of batch_size in evaluation

### ISSUE THREAD

**Issue by chrisroat** [MouseLand/cellpose#83]
How is batch size used in eval?   Does it affect evaluation for 3d in all orientations?  If I have one short dimension, is there anyway to speed up the evals using that dimension via batching?  Meaning, could we imagine batch_size being optionally a tuple/dict for the various orientations?

My case is a 16 x 3k x 3k image, where I'd like to take advantage of 24G of GPU memory to speed up the slow xz and yz sections.

**Comment by carsen-stringer** [comment]
unfortunately batch size is the same for all dimensions, I will add this as a feature request
