### ISSUE TITLE
[FEATURE]Get Stuck and force quit when using GUI from terminal

### ISSUE THREAD

**Issue by xieaq** [MouseLand/cellpose#841]
Hello,

I have a question regarding an issue I encountered after dragging a picture. While I can usually open it without any problems, it seems to became unresponsive when I dragged a .tif file into it. Is this issue related to the size of my document, which is 600MB? I'm also curious to know if there's a limit to the picture size.

Thank you for your assistance!

**Comment by carsen-stringer** [comment]
it could be that the tiff is not in a shape/type that cellpose recognizes. check out how it loads in a jupyter-notebook e.g. `from cellpose import io; io.imread("img.tif")` and see how many dims it has / channels. going to close for now but if you have issues I'll reopen
