### ISSUE TITLE
Website Error

### ISSUE THREAD

**Issue by zhipeng-wei** [MouseLand/cellpose#847]
Thanks for your excellent work.
Your website https://www.cellpose.org/ returns error after uploading image.
![Uploading a8731bda70f16123878c3d0fecf7583.jpg…]()

**Comment by zhipeng-wei** [comment]
![a8731bda70f16123878c3d0fecf7583](https://github.com/MouseLand/cellpose/assets/58925637/8bfac2ff-2ca6-4683-a64a-32d440ca58b9)

**Comment by carsen-stringer** [comment]
thanks it's fixed now. fyi the website is only for testing, you can install the software to run many images
