### ISSUE TITLE
Providing spatial gradients

### ISSUE THREAD

**Issue by carlosuc3m** [MouseLand/cellpose#848]
**Is your feature request related to a problem? Please describe.**
Hello,
First of all amazing work, congrats to the team!
I liked a lot the spatial gradient approach to create instance segmentations and I was wondering if it was possible that the ones used for training were provided. As the paper states they were generated by a human annotator, thus creating them is a tedious process. It would be amazing if they were publicly available so people could experiment with them.

**Describe the solution you'd like**
If possible, release the spatial gradient masks together with the training and test data.

**Describe alternatives you've considered**
Creating them myself, it is a long tedious process.

Thanks a lot for your time and attention and keep up the good work!
Regards,
Carlos

PD: sorry if they are already publicly availble, but I have not been able to find them

**Comment by carlosuc3m** [comment]
I just saw that the flows can also be computed automatically with https://github.com/MouseLand/cellpose/blob/4f5661983c3787efa443bbbd3f60256f4fd8bf53/cellpose/dynamics.py#L287

I guess that with that manual annotation is not necessary, right?

**Comment by carsen-stringer** [comment]
yes they are automatically computed when you run `python -m cellpose --train` , so we don't share the flows with the masks. the first time they are created they are saved so it won't happen again.
