### ISSUE TITLE
Number of Epochs to run training is not propagated

### ISSUE THREAD

**Issue by adrtsc** [MouseLand/cellpose#85]
Hi,

When trying to retrain a cellpose model I realised that even if the number of epochs to train is increased, the default (500 epochs) is used. The n_epochs argument in `__main__.py `is apparently not used. Adding `n_epochs=args.n_epochs`  to model.train(line 231/232) solved the issue for me.

**Comment by carsen-stringer** [comment]
thanks, arg fixed now!
