### ISSUE TITLE
Custom model suffers in 3d

### ISSUE THREAD

**Issue by jelrod14** [MouseLand/cellpose#853]
Hi all,
I am currently running into an issue where I have trained a model on 2D max projections of my z-stack images, and the model performs extremely well (first image below, I would consider this pretty much perfect for my purposes). Upon apply this model to the full 3D z-stacks, the performance suffers significantly (second image below, looks pretty similar to this throughout, has some areas where it is better, like in the third image). Is the solution just more training? This model is trained on ~800 nuclei labeled via human in the loop training.
cellpose1
[cellpose11193×940 235 KB](https://global.discourse-cdn.com/business4/uploads/imagej/original/3X/4/f/4fcb426c8e3439a7480af188918ed258a9388a37.jpeg)

bad image
[image1179×945 154 KB](https://global.discourse-cdn.com/business4/uploads/imagej/original/3X/3/f/3f1c0968d511f65d86c6e5c555fdecf2f0b9cedb.png)

slightly better image
![66da1ffb321b91adc6e4c73ef5651b2e91b02762](https://github.com/MouseLand/cellpose/assets/97682578/1d459a02-7835-4d4b-9337-6f9361281a47)

**Comment by carsen-stringer** [comment]
I would recommend stitching by setting the stitch_threshold to 0.25 or higher. I am guessing that the XZ and YZ views are difficult for cellpose to segment hence the issues with the cellpose3D XY, XZ, YZ method (which is the default).
