### ISSUE TITLE
Regarding datasets used for training the models

### ISSUE THREAD

**Issue by anwai98** [MouseLand/cellpose#854]
Hi,

I would be willing to know the datasets used for training the respective generalist CellPose models ([`cyto`](https://cellpose.readthedocs.io/en/latest/models.html#cytoplasm-model-cyto), [`cyto2`](https://cellpose.readthedocs.io/en/latest/models.html#cytoplasm-2-0-model-cyto2))? (to specify my interests, I am interested to know if the models have been trained with `LiveCell` / `TissueNet` / both)

PS. - Just to be sure, the specialized CellPose models ([`TissueNet`](https://cellpose.readthedocs.io/en/latest/models.html#tissuenet-models) and [`LiveCell`](https://cellpose.readthedocs.io/en/latest/models.html#livecell-models)) have been trained using all the training data from the respective domains (?)

Thanks! :)

**Comment by carsen-stringer** [comment]
Hi @anwai98 cyto and cyto2 are our datasets (cyto now available at https://www.cellpose.org/dataset, cyto2 will be posted soon). They have not been trained with Livecell or Tissuenet. And yes the Tissuenet and Livecell models were trained with all their images.
