### ISSUE TITLE
error saving seg_npy and png for 3D images 

### ISSUE THREAD

**Issue by glossdrop** [MouseLand/cellpose#86]
Dear @carsen-stringer and @marius10p,
I come around again because I have troubles with the analysis of 3D images. 

I successfully completed the segmentation of several 3D images in a folder (from jupyter notebook), I get an error message when I try to store the result:
1) function io.save_to_masks:
![1](https://user-images.githubusercontent.com/47526010/84248309-8e610600-ab09-11ea-92eb-a0629c5103cc.png)

2) function io.save_to_png:
![2](https://user-images.githubusercontent.com/47526010/84248370-9f117c00-ab09-11ea-8504-a1c87a7878b0.png)

Any idea how that comes about?
Thanks in advance for your support!

Davide

**Comment by glossdrop** [comment]
a brief update: 

for one image, saving works by adding `io.save_to_png(imgs[0], masks[0], flows[0][0], files[0]`

Unfortunately the same strategy does not hold for `io.masks_flows_to_seg(imgs[0], masks[0], flows[0][0], diams, files[0], channels[0])`

`
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-76-48e128903c32> in <module>
      6 os.chdir(save_direc)
      7 # from cellpose import io
----> 8 io.masks_flows_to_seg(imgs[0], masks[0], flows[0][0], diams, files[0], channels[0])
      9 # io.save_to_png(imgs[0], masks[0], flows[0][0], files[0])

c:\users\gloss\anaconda3\envs\cellpose\lib\site-packages\cellpose\io.py in masks_flows_to_seg(images, masks, flows, diams, file_names, channels)
     65         if len(flows[n])>2:
     66             flowi.append(flows[n][3])
---> 67             flowi.append(np.concatenate((flows[n][1], flows[n][2][np.newaxis,...]), axis=0))
     68         outlines = masks[n] * plot.masks_to_outlines(masks[n])
     69         base = os.path.splitext(file_names[n])[0]

ValueError: all the input arrays must have same number of dimensions
`

**Comment by carsen-stringer** [comment]
-.- sorry about this, see #81 , this is now fixed (in the github). please comment if it's not working
