### ISSUE TITLE
How to get and convert pixel cell probability to object cell probability?

### ISSUE THREAD

**Issue by marcelopedras** [MouseLand/cellpose#868]
Cellpose 2.2.3 - References, issue #71

Where to get the probability of the pixel being a cell? flows[3] (https://github.com/MouseLand/cellpose/issues/71)? flows[1] (https://cellpose.readthedocs.io/en/latest/outputs.html#seg-npy-output).

I'm very confused with documentation.
I think it would be the flows[2].

- Script to convert to 0.0 to 1.0 range pixel probability.

cell_probability_function = lambda x: 1 / (1 + pow(np.e, -x))
cell_probability_function_vec = np.vectorize(cell_probability_function)

confidence_matrix = flows[2]
confidence_matrix = cell_probability_function_vec(confidence_matrix)

Is correct? 
I thank you for your help.

**Comment by carsen-stringer** [comment]
I've updated the documentation, flows[3] has the outputs from the network (cellprob + flows) that we use directly to run the dynamics. flows[1] is the third output from the network rescaled from -10.0 to 10.0 to between 0-255 to allow visualization of it in the GUI. We do not put it through a sigmoid in the code, we just threshold this (-10.0 to 10.0) output from the network. (conversion here: https://github.com/MouseLand/cellpose/blob/943ca95ce458d28a37bb6007b0da0b34e9456412/cellpose/io.py#L532).

**Comment by marcelopedras** [comment]
Eval method in the cellpose/models.py file, the Cellpose class has this comment:

Returns:
            tuple containing
                - masks (list of 2D arrays or single 3D array): Labelled image, where 0=no masks; 1,2,...=mask labels.
                - flows (list of lists 2D arrays or list of 3D arrays): 
                    - flows[k][0] = XY flow in HSV 0-255
                    - flows[k][1] = XY flows at each pixel
                    - flows[k][2] = cell probability (if > cellprob_threshold, pixel used for dynamics)
                    - flows[k][3] = final pixel locations after Euler integration
                - styles (list of 1D arrays of length 256 or single 1D array): Style vector summarizing each image, also used to estimate size of objects in image.
                - diams (list of diameters or float): List of diameters or float (if do_3D=True).



I'm using cellpose as a dependency for my own project, without a graphical interface. It is not clear in the documentation how to get the probability of a pixel being a cell. but from the comment, I believe it should be flows[2]. I'm using cellpose as a dependency for my own project, without a graphical interface. It is not clear in the documentation how to get the probability of a pixel being a cell. but from the comment, I believe it should be flows[2].

**Comment by carsen-stringer** [comment]
Yes from the API that is correct, I thought you were using the seg.npy
