### ISSUE TITLE
Class RunLoopModeTracker is implemented in both...

### ISSUE THREAD

**Issue by Orohena** [MouseLand/cellpose#87]
Hello,

I am trying to install cell pose and I have an issue.
I followed the procedure, installing the gui, then installing cellpose. I have no problem here.
But then, when I try to run cellpose, I only have a grey window that opens (cellpose written on top)

and I get the following message:
objc[82953]: Class RunLoopModeTracker is implemented in both /opt/anaconda3/envs/cellpose/lib/python3.8/site-packages/cv2/.dylibs/QtCore (0x12029f7f0) and /opt/anaconda3/envs/cellpose/lib/libQt5Core.5.dylib (0x12a21fa80). One of the two will be used. Which one is undefined.

I tried to uninstall cellpose package with conda, then reinstall again but I have the same issue.

Thank you in advance for your help !

**Comment by carsen-stringer** [comment]
I think this is the cv2 issue described in the readme, please downgrade cv2

**Comment by Orohena** [comment]
Hello, 

Sorry for not mentioning, but I did try that already and it gives me this error message:

ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.5.20 (from versions: 3.4.8.29, 3.4.9.31, 3.4.9.33, 4.1.2.30, 4.2.0.32, 4.2.0.34)
ERROR: No matching distribution found for opencv-python==3.4.5.20

As I had this error message and my initial error was not the same mentioned in the cv2 issue, I just thought it was something different and forgot to mention it in my previous issue.

Would you have any idea as how I could get around that new error.

Thank you !

**Comment by carsen-stringer** [comment]
Sorry, can you try

pip uninstall opencv-python
pip install opencv-python-headless

**Comment by Orohena** [comment]
> Sorry, can you try pip uninstall opencv-python pip install opencv-python-headless
> […](#)

I did, and it now seem to work perfectly ! 
Thank you very much !
