### ISSUE TITLE
[BUG] Google Collab notebook - no attribute 'train'

### ISSUE THREAD

**Issue by superwormz** [MouseLand/cellpose#872]
Hi Carsen,

Sorry, I feel like I'm bombarding you with bugs!

When using the colab notebook this error is produced when training:

'CellposeModel' object has no attribute 'train'

My assumption, based on your comment of "we will update the documentation soon. the train function is no longer a method of the CellposeModel class, it's now a standalone function in train.py called train_seg" in another post is that some code in the notebook isnt up to date with the new V3. To get around this I have used "pip install cellpose==2.2.3" to revert to an earlier version and it now works.

Thanks for all your work on this. Best of luck with the bug squishing!

**Comment by carsen-stringer** [comment]
thanks your feedback is very helpful! I will update the google colab notebooks today, but in the meantime, yes please use a cellpose 2 release

**Comment by carsen-stringer** [comment]
this is updated now to work with v3
