### ISSUE TITLE
Run cellpose on many pictures

### ISSUE THREAD

**Issue by felixlouchez** [MouseLand/cellpose#874]
Hello,

I have many images that I want to segment using cellpose and I would like to know if there is a way to run cellpose on a group of pictures instead of running it on each picture one by one.

My images are .tif, single channel, grey scale.
I set the cell diameter to 0
and use the cyto model to segment my cells
and save the masks as PNG (ctrl+N)

then moove to the next picture.

Thanks in advance.

**Comment by superwormz** [comment]
You can do this if you run from the command line interface (CLI). 
I have done this and it's very useful. Afterwards, I take a number of the images into the GUI for manual inspection to check everything is ok.

So you would run something like this:

python -m cellpose --dir ~/path/to/images/ --pretrained_model cyto --chan 0 --diameter 0 --save_png

--dir = paste in the file path here
--chan = 0 as grey scale


More info here: https://cellpose.readthedocs.io/en/latest/command.html

**Comment by carsen-stringer** [comment]
thanks @superwormz yes this is available on the CLI
