### ISSUE TITLE
Align for multi fov result combined

### ISSUE THREAD

**Issue by ustc-fmh** [MouseLand/cellpose#877]
Hi, Due to the large memory consumption of the experimental data, I am currently using manual segmentation into n small fov for cellpose 2D cell segmentation, but there are obvious mis-segmentation at the edge of each small fov, I would like to know how to solve the problem of merging 2D cell segmentation results at the edge area to reach align to generate the final cell segmentation result?

**Comment by carsen-stringer** [comment]
I would make sure there is some tile overlap in your slices, and we will share code for this soon - the function will work for manual segmentations as well but we are focusing on cellpose outputs
