### ISSUE TITLE
upper and lower LUT sliders completely overlap[BUG]

### ISSUE THREAD

**Issue by derekthirstrup** [MouseLand/cellpose#878]
**Describe the bug**
The channel display LUT sliders overlap and can not be modified in many dim live cell images.  Please add option to set values by actual pixel values and keep these settings for subsequent images.

**Screenshots**
Here is an example to demonstrate the issue.

![image](https://github.com/MouseLand/cellpose/assets/20077409/f39e3127-b19d-4418-aa77-06f39ed1ffc8)

**Comment by carsen-stringer** [comment]
how many channels do you have in these images? is it fixed by turning off "auto-adjust"?

**Comment by carsen-stringer** [comment]
also please try `pip install cellpose --upgrade`, there was a bug in the saturation I thought I fixed

**Comment by derekthirstrup** [comment]
@carsen-stringer It appears to be fixed now in 3.0.6.  I trained a label-free cell segmentation model so the image was a composite of brightfield and H2B endogenous EGFP channels.  CP2 LUTs always needed to be adjusted depending on if H2B or the brightfield cell seg channels were being tested which is apparently fixed and each channel lower and upper LUT values now correctly get set.  
![image](https://github.com/MouseLand/cellpose/assets/20077409/8e28aaf5-ac08-4477-9179-fdfcfed3f3c3)
