### ISSUE TITLE
[BUG] No controls for Z slice position in latest GUI

### ISSUE THREAD

**Issue by msymeonides** [MouseLand/cellpose#883]
When I load a TIFF image that has multiple Z slices into Cellpose 3.0.5 (whether by drag-and-drop or by file-load) there is no box to adjust Z slice anywhere in the GUI. Opening the same image in Cellpose 2.3.2 has the Z slice box and adjusting it works, so the image is fine.

![image](https://github.com/MouseLand/cellpose/assets/12733002/4ab99b6c-9c68-45f2-a851-3b7c88a5bcc3)

**Comment by carsen-stringer** [comment]
please run `python -m cellpose --Zstack`

**Comment by msymeonides** [comment]
Thanks - sorry I tried searching issues for this but it was unsuccessful... did not know Zstack defaults to False now but I expect it will return to True once denoising works in 3D?

**Comment by msymeonides** [comment]
OK, it works as expected when I drag-and-drop to open the image, if I use file-load to open the image it does what I described above.

**Comment by carsen-stringer** [comment]
ah good catch, fixing the load from File now. From now on, the 3D and 2D GUIs are separated, so please use the `python -m cellpose --Zstack` for 3D data

**Comment by msymeonides** [comment]
Great, works properly now! TYSM
