### ISSUE TITLE
[FEATURE] - add back in old models to GUI

### ISSUE THREAD

**Issue by ABCarvalho** [MouseLand/cellpose#885]
**Describe the bug**
From the cellpose2, the generalist model CPx did not remain to Cellpose3. However, for my image data, CPx is the best model, even outperforming cyto3 it terms of rigor for the ROIs drawn. Therefore, I had it back to cellpose3 through custom models. However, I wanted to give it some tweaks by furhter training it with my data. Howeber **I cannot access it in the Models section of the training**

Thank you very much!!

**Screenshots**
<img width="1087" alt="Sem título" src="https://github.com/MouseLand/cellpose/assets/132283402/6ffd09af-c22b-4b95-b407-e97db075a647">

**Comment by arodriguezgama** [comment]
I want to follow up on this. Is there a way to select custom models as initial model during training?

**Comment by lsxucsf** [comment]
I do not believe it's possible using the GUI. It does, however, seem possible using the command line. Please check the cellpose documentation for more details.

**Comment by carsen-stringer** [comment]
you can do this on the command line yes, I can add back in the other models

**Comment by carsen-stringer** [comment]
I added back in CPx, cyto and cyto2 to the GUI. the other tissuenet and livecell models (e.g. LC1, TN1,...) do not outperform the new cp3 models so I did not add them back in
