### ISSUE TITLE
Two style vector normalizations

### ISSUE THREAD

**Issue by Soroush-aali-bagi** [MouseLand/cellpose#888]
https://github.com/MouseLand/cellpose/blob/509ffca33737058b0b4e2e96d506514e10620eb3/cellpose/core.py#L234
I wonder why you normalize the style vector for the second time (link above), when you have already did it earlier here:
https://github.com/MouseLand/cellpose/blob/509ffca33737058b0b4e2e96d506514e10620eb3/cellpose/core.py#L334

**Comment by carsen-stringer** [comment]
we are averaging the styles across tiles which doesn't guarantee they remain unit norm
