### ISSUE TITLE
[INSTALL] pip upgrade form cellpose 2 to cellpose 3 results in segmentation fault

### ISSUE THREAD

**Issue by amichaut** [MouseLand/cellpose#895]
**Install problem**
Running a simple upgrade using pip `python -m pip install cellpose --upgrade` leads to a segmentation fault when launching cellpose. 
This was fixed by starting from a fresh environment. However, a few errors were generated during installation. The following packages were not installed properly by pip and had to be installed independently: 
- numpy
- scikit-image
- protobuf==3.19.6 (I had to look for a compatible version as several packages such as tensorflow, google-api-core, tensorboard have conflicting dependencies)

**Misc info**
macOS 13.6.4
cellpose version: 	3.0.7 
platform:       	darwin 
python version: 	3.8.18 
torch version:  	2.2.1

**Environment info**
Name                    Version                   Build  Channel
bzip2                     1.0.8                h10d778d_5    conda-forge
ca-certificates           2024.2.2             h8857fd0_0    conda-forge
cellpose                  3.0.7                    pypi_0    pypi
certifi                   2024.2.2                 pypi_0    pypi
fastremap                 1.14.1                   pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
fsspec                    2024.3.1                 pypi_0    pypi
google-api-core           2.17.1                   pypi_0    pypi
google-auth               2.28.2                   pypi_0    pypi
google-cloud-core         2.4.1                    pypi_0    pypi
google-cloud-storage      2.16.0                   pypi_0    pypi
google-crc32c             1.5.0                    pypi_0    pypi
google-resumable-media    2.7.0                    pypi_0    pypi
googleapis-common-protos  1.63.0                   pypi_0    pypi
imagecodecs               2023.3.16                pypi_0    pypi
imageio                   2.34.0                   pypi_0    pypi
lazy-loader               0.3                      pypi_0    pypi
libblas                   3.9.0           21_osx64_openblas    conda-forge
libcblas                  3.9.0           21_osx64_openblas    conda-forge
libcxx                    16.0.6               hd57cbcb_0    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           13_2_0_h97931a8_3    conda-forge
libgfortran5              13.2.0               h2873a65_3    conda-forge
liblapack                 3.9.0           21_osx64_openblas    conda-forge
libopenblas               0.3.26          openmp_hfef2a42_0    conda-forge
libsqlite                 3.45.2               h92b6c6a_0    conda-forge
libzlib                   1.2.13               h8a1eda9_5    conda-forge
llvm-openmp               18.1.1               hb6ac08f_0    conda-forge
mpmath                    1.3.0                    pypi_0    pypi
ncurses                   6.4                  h93d8f39_2    conda-forge
numpy                     1.23.5                   pypi_0    pypi
opencv-python-headless    4.9.0.80                 pypi_0    pypi
openssl                   3.2.1                hd75f5a5_1    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
protobuf                  3.19.6                   pypi_0    pypi
pyqt6                     6.6.1                    pypi_0    pypi
pyqt6-qt6                 6.6.2                    pypi_0    pypi
pyqt6-sip                 13.6.0                   pypi_0    pypi
pyqtgraph                 0.13.3                   pypi_0    pypi
python                    3.8.18          h5ba8234_1_cpython    conda-forge
python_abi                3.8                      4_cp38    conda-forge
readline                  8.2                  h9e318b2_1    conda-forge
scikit-image              0.21.0                   pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                69.2.0             pyhd8ed1ab_0    conda-forge
superqt                   0.6.2                    pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
tk                        8.6.13               h1abcd95_1    conda-forge
torch                     2.2.1                    pypi_0    pypi
typing-extensions         4.10.0                   pypi_0    pypi
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge

**Comment by carsen-stringer** [comment]
sorry I think python=3.8 could be the issue here, we are now recommending 3.9 or higher, I will reopen if this doesn't resolve it

**Comment by amichaut** [comment]
thanks! this was the issue indeed
