### ISSUE TITLE
Using --no_norm with CLI slows down 3D segmentation[BUG]

### ISSUE THREAD

**Issue by derekthirstrup** [MouseLand/cellpose#898]
The segmentation of 3d tif stacks is taking 5-6 minutes to process 1 image when --no_norm is used.  When the same stacks are processed without --no_norm argument then it takes roughly 20 seconds.  I previously denoised and rescaled the images so they do not need to be rescaled again during segmentation.  Any ideas why it takes significantly more time with --no_norm option?   Seems like it should be faster.

**Comment by carsen-stringer** [comment]
hmm this is strange, is the output exactly the same with and without `--no_norm`?

**Comment by carsen-stringer** [comment]
this could be due to type-casting, if your images are not float32, we've updated the type-casting to occur on the GPU which may speed things up, but let us know if this is still an issue
