### ISSUE TITLE
Export of Cellpose Masks into FIJI

### ISSUE THREAD

**Issue by paoloM1990** [MouseLand/cellpose#9]
Hello,

I am a biologist and I am using Cellpose GUI to segment cells. 
I then save the masks in .npy file
I would like to load the mask on FIJI for measuring fluorescence intensity or other parameters. However, FIJI does not read .npy format (as far as I know)

Is there a possibility to export the masks on FIJI?

Any help would be very much appreciated

Thank you

**Comment by marius10p** [comment]
Do you know what format the masks have to be to load in Fiji?

**Comment by Goran-L** [comment]
Hello everyone,

ImageJ/FIJI masks are black&white 8bit images with inverting LUT (white is 0 and black is 255).

.npy arrays seem to me closer to ROIs (Region of Interest) in ImageJ/FIJI.

This webpage might help about the ROI file format and its decoding
https://javadoc.scijava.org/ImageJ1/?ij/io/RoiDecoder.html
(Java)

Hope this helps.

(bytheway, very impressed with cellpose, looking forward to its integration/crosstalk with Fiji...)

**Comment by paoloM1990** [comment]
Hi Marius, sorry for the late reply.
I'd like the masks in TIFF format to load in Fiji. 

Best regards

**Comment by VolkerH** [comment]
@paoloM1990 
I suggest you don't save masks which just have the information foreground/background.
Instead, save the label images as tiff files. In the label image, each distinct object is filled with one unique integer value. This way, you can distinguish separate objects when they are clumped and touching (not possible with the mask). You can simply save the label numpy array as a tifffile and open it in Fiji. If you really need to go back to a binary mask just threshold to find all areas with label greater than 0.
To save the label array you can use (for exmaple) `skimage.io.imsave`.

**Comment by carsen-stringer** [comment]
The GUI now also has an option to save the cellpose segmentation as a png (in the File menu) which you can upload into imagej, or load elsewhere. Please update with `pip install cellpose --upgrade`

**Comment by paoloM1990** [comment]
That's amazing! Thank you!
