### ISSUE TITLE
Target shape must have the same size as current shape when recording with autograd

### ISSUE THREAD

**Issue by TomerSternGit** [MouseLand/cellpose#90]
Hi!

First - many thanks for this development, I'm sure it will be a game changer in biological image analysis.

So I'm very happy about the pretrained model cyto, but I'd like to make it even better by using the training function you provide.

My data is composed of 3D images with size [978   410   408] uint16. I prepared several pairs of images, where in each pair one image is the raw data and the other is the masked labels (a simple positive integer for every cell and zero for background).
No matter what combination of commands / files I'm using, I always end up getting the error below.

What did I do wrong?

Many thanks,
Tomer

THE ERROR:

python3 -m cellpose --train --dir "/mnt/home/tstern/ceph/Data/CellPose Training/Training set/" --use_gpu --do_3D --chan 0 --mask_filter masks --img_filter img --pretrained_model None
>>>> using GPU
>>>> training from scratch
>>>> rescaling diameter for each training image to 30.0
NOTE: test data not provided OR labels incorrect OR not same number of channels as train data
flows precomputed
>>>> training network with 2 channel input <<<<
>>>> saving every 100 epochs
>>>> median diameter = 26
>>>> LR: 0.20000, batch_size: 8, weight_decay: 0.00001
>>>> ntrain = 1
(2, 408, 978)
Traceback (most recent call last):
  File "/cm/shared/sw/pkg/devel/python3/3.7.3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/sw/pkg/devel/python3/3.7.3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/home/tstern/.local/lib/python3.7/site-packages/cellpose/__main__.py", line 232, in <module>
    channels=channels, save_path=os.path.realpath(args.dir), rescale=rescale)
  File "/mnt/home/tstern/.local/lib/python3.7/site-packages/cellpose/models.py", line 699, in train
    loss = criterion(y[:,:-1] , veci) + criterion2(y[:,-1] , lbl)
  File "/mnt/home/tstern/.local/lib/python3.7/site-packages/mxnet/gluon/block.py", line 693, in __call__
    out = self.forward(*args)
  File "/mnt/home/tstern/.local/lib/python3.7/site-packages/mxnet/gluon/block.py", line 1158, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "/mnt/home/tstern/.local/lib/python3.7/site-packages/mxnet/gluon/loss.py", line 146, in hybrid_forward
    label = _reshape_like(F, label, pred)
  File "/mnt/home/tstern/.local/lib/python3.7/site-packages/mxnet/gluon/loss.py", line 72, in _reshape_like
    return x.reshape(y.shape)
  File "/mnt/home/tstern/.local/lib/python3.7/site-packages/mxnet/ndarray/ndarray.py", line 1505, in reshape
    ctypes.byref(handle)))
  File "/mnt/home/tstern/.local/lib/python3.7/site-packages/mxnet/base.py", line 255, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [20:54:47] src/ndarray/ndarray.cc:269: Check failed: shape_.Size() == shape.Size() (20371456 vs. 100352) : NDArray.Reshape: target shape must have the same size as current shape when recording with autograd.
Stack trace:
  [bt] (0) /mnt/home/tstern/.local/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x6b8b5b) [0x2aaada741b5b]
  [bt] (1) /mnt/home/tstern/.local/lib/python3.7/site-packages/mxnet/libmxnet.so(mxnet::NDArray::ReshapeWithRecord(mxnet::TShape const&)+0x177) [0x2aaadda8c5c7]
  [bt] (2) /mnt/home/tstern/.local/lib/python3.7/site-packages/mxnet/libmxnet.so(MXNDArrayReshape64+0x190) [0x2aaadd7b3a10]
  [bt] (3) /lib64/libffi.so.6(ffi_call_unix64+0x4c) [0x2aaad4ebedcc]
  [bt] (4) /lib64/libffi.so.6(ffi_call+0x1f5) [0x2aaad4ebe6f5]
  [bt] (5) /cm/shared/sw/pkg/devel/python3/3.7.3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so(_ctypes_callproc+0x47d) [0x2aaad4caaf6d]
  [bt] (6) /cm/shared/sw/pkg/devel/python3/3.7.3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so(+0x8fdc) [0x2aaad4ca1fdc]
  [bt] (7) /cm/shared/sw/pkg/devel/python3/3.7.3/lib/libpython3.7m.so.1.0(_PyObject_FastCallKeywords+0xc3) [0x2aaaaad6a163]
  [bt] (8) /cm/shared/sw/pkg/devel/python3/3.7.3/lib/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x7b67) [0x2aaaaad41387]

**Comment by TomerSternGit** [comment]
Just discovered that training is only in 2D. Thanks!

**Comment by rz0012** [comment]
Hello,
I am having the same issue when training 3d images. "target shape must have the same size as current shape when recording with autograd."
What do you mean by "training is only in 2d" 
Does it mean, we cannot train 3d images using cellpose?
if so, were you able to solve the issue ?
I am using tiff files for processing images. 
it tested that image precisely, but could not train. 
thanks in advance.
