### ISSUE TITLE
AttributeError: 'CellposeModel' object has no attribute 'diam_labels'[BUG]

### ISSUE THREAD

**Issue by VerbeekM** [MouseLand/cellpose#901]
I am training a model using the GUI. When I train the model using my annotated set of images with nuclei as an initial model all is well. However, when I swap the initial model for the scratch model I get the following error without changing the input images. I am using cellpose 3.

LOG:
2024-03-26 17:34:59,427 [INFO] 90, train_loss=0.0459, test_loss=0.0000, LR=0.1000, time 72.43s
Traceback (most recent call last):
  File "*/.conda/envs/cellposeyml/lib/python3.12/site-packages/cellpose/gui/gui.py", line 1958, in new_model
    self.train_model(restore=restore, normalize_params=normalize_params)
  File "*/.conda/envs/cellposeyml/lib/python3.12/site-packages/cellpose/gui/gui.py", line 1992, in train_model
    diam_labels = self.model.diam_labels #.copy()
                  ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CellposeModel' object has no attribute 'diam_labels'

Any idea how I could solve this? Thank you!

**Comment by tanpancodes** [comment]
I had a similar issue before... can you send a picture of the code you used//commands you executed (more log info)

**Comment by XylotrupesGideon** [comment]
I found a fix by setting recale =1.0

masks,flows,styles= model.eval(imgs, rescale=1.0,
                                    stitch_threshold=cp_stitch_threshold,
                                    z_axis=0)

when the diameter is set to None this code checks for the rescale factor and if that is set to None it tries to read the diam_labels.
by settign rescale to 1.0 (which is the default anyways the elif is not execuded and diam_labels is never looked up so the code runs

````
 if diameter is not None and diameter > 0:
                rescale = self.diam_mean / diameter
elif rescale is None:
                diameter = self.diam_labels
                rescale = self.diam_mean / diameter
```

**Comment by XylotrupesGideon** [comment]
I ran into the same issue when I forgot to use the keyword pretrained_model in cellpose_models_CellposeModel

it occured when i did:
`cellpose.models.CellposeModel(cp_pretrained_model)`
instread of 
`cellpose.models.CellposeModel(pretrained_model = cp_pretrained_model)`

**Comment by carsen-stringer** [comment]
I think this shouldn't be an issue in Cellpose3 but please let us know if you're still having issues
