### ISSUE TITLE
Cellpose model site down?

### ISSUE THREAD

**Issue by Nina-ICCE** [MouseLand/cellpose#902]
I've been trying to use the bact_fluor_cp model in the RunOmnipose module and have encountered some unexpected problems.
It seems to me that Cellprofiler tries to download the model from the cellpose site, but the site is not available? This doesn't happen with other models like cyto, so I don't think it's a general problem with my installation or CellProfiler. The website where it tries to download the model (https://www.cellpose.org/models/bact_fluor_cptorch_0) seems to be down? 
Any help or solution is welcome.  

![RunOmnipose_error2](https://github.com/MouseLand/cellpose/assets/165265979/db99b599-f4ed-4953-8274-3bc84d7f602d)

Thanks a lot for your help,
Nina

**Comment by hahia** [comment]
I also meet this problem. The site unable to open. It return:

![image](https://github.com/MouseLand/cellpose/assets/49113803/cb042242-da84-40d9-a47d-6164ac9f45a5)

**Comment by carsen-stringer** [comment]
these models are now hosted by omnipose, if you have issues downloading them in the future please contact them

**Comment by Nina-ICCE** [comment]
Thanks for updating and clarifying!
