### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jinshachen** [MouseLand/cellpose#905]
ImportError: cannot import name 'train' from 'cellpose' (/usr/local/lib/python3.10/dist-packages/cellpose/__init__.py)

**Comment by sugan89** [comment]
I also have the same issue. 
Code that produces the error - `from cellpose import train`
OS -Windows 10
Cellpose version - 2.2.2
The error that I get - ImportError: cannot import name 'train' from 'cellpose' (c:\Users\XXXXX\Anaconda3\envs\cellpose\lib\site-packages\cellpose\__init__.py)

**Comment by carsen-stringer** [comment]
this module is only available in cellpose3, otherwise you should train through the CLI or read the source code
