### ISSUE TITLE
significantly different counts form cyto-2 to cyto-3

### ISSUE THREAD

**Issue by tanpancodes** [MouseLand/cellpose#911]
I am using Cellpose to count cell culture images (black background with mostly non adjacent cells in white)

![10-1-red](https://github.com/MouseLand/cellpose/assets/165830253/4265dc74-720a-41b7-b05e-beeb7d1d573a)

However, between the two models, there can be up to 15-30% difference in the number of ROIs regenerated/cells counted.  How can I know which model will be best to use?

Is there a particular dataset that is best for cell culture images?

**Comment by mrariden** [comment]
There is no complete heuristic for determining exactly which model is best for your data because only you know your data best. 

GH issues are only for code bugs or installation issues, so I'll close this. Please use the image.sc forum for advise.
