### ISSUE TITLE
cellpose on large .tif images (1GB-10GB) 

### ISSUE THREAD

**Issue by Nespresso2000** [MouseLand/cellpose#917]
Hi,

I want to use cellpose on some rather large .tif files of sizes ranging from 1GB-10GB. They are **2-d RGB images**. I have a Tesla T4 GPU and 32GB RAM. Following #356  and #244 I first used openslide to convert my image and write them on my disk as zarr arrays; so now, I have a folder of zarr arrays corresponding to _one _ image. To be honest, I am not able to understand exactly whats going on in this new piece of code and would appreciate a small explanation of the following points:
1. Does this even work for 2d images? or only 3d? If not, is there anything I can do to process such large 2d images? Before finding this, I saw https://forum.image.sc/t/loading-whole-slide-image-and-running-cellpose-in-python/69992/7 according to which I'd need an obscene amount of RAM which is not possible. 
2. What does the block_size parameter mean in distributed_eval?
3.  How do I access / see what the segmented image looks like after? I could do that following the docs when I was saving a .npy file but I'm not able to find similar documentation

Apologies in advance if the questions are obvious but any help is appreciated!

**Comment by zsamadi** [comment]
1. I don't suppose there is any difference between 3D and 2D. Take a look at [this link ](https://github.com/MouseLand/cellpose/blob/0c0d00a2bb0daa91e3983124db698230ea887828/cellpose/contrib/distributed_segmentation.py) on how to use Cellpose on Dask arrays. 

2. I don't know exactly what you mean by block_size or distributed_eval.

3. The method mentioned in the above link results in a dask array of labels. You can view separate segmentation chunk results by iterating through them and computing them.

**Comment by camilolaiton** [comment]
Hello! @Nespresso2000 we just released a [package](https://pypi.org/project/aind-large-scale-cellpose/) for large-scale segmentation with cellpose (works with 3D just as the original cellpose). Still in development but it'd be nice if you give it a shot. Unfortunately, you'd have to convert your data to OMEZarr.

**Comment by Eddymorphling** [comment]
> Hello! @Nespresso2000 we just released a [package](https://pypi.org/project/aind-large-scale-cellpose/) for large-scale segmentation with cellpose (2D/3D images). Still in development but it'd be nice if you give it a shot. Unfortunately, you'd have to convert your data to OMEZarr.

Hi @camilolaiton I am interested in trying this out! How would I go about testing this? I have large datasets for Cellpose segmentation saved as `zarr `arrays. Do you have a tutorial on how to run your package in python? Thank you.

**Comment by camilolaiton** [comment]
Hi @Eddymorphling, not yet. I'll include a notebook with examples this week. In the meantime, you could take a look at this function [main](https://github.com/AllenNeuralDynamics/aind-large-scale-cellpose/blob/main/code/run_capsule.py#L8). We are using the OME-NGFF convention for the zarr (OME-Zarr) to get the image metadata (e.g., resolution).

Please, let me know if you have following questions. Make sure to properly set the parameters for the machine you're using.

**Comment by vadori** [comment]
> Hi Vadori,
> 
> I'm not sure how interpolation works, the way I ended up using to deal with large, tiled dataset is that I segment tiles or patches separately and at the same time use BigStitcher to stitch original patches together and use the output xml file from BigStitcher to map segmentation coordinates to their original WSI coordinates and join segmentation labels using a method similar to the [link ](https://github.com/MouseLand/cellpose/blob/0c0d00a2bb0daa91e3983124db698230ea887828/cellpose/contrib/distributed_segmentation.py) I provided earlier as well.

Dear @zsamadi,
Thank you for your response. Are you running all the steps through a Python script or notebook, or is BigStitcher available as a standalone application in your setup?

**Comment by camilolaiton** [comment]
Hi @vadori, @zsamadi's solution seems also feasible. If you want to give it a shot, our implementation loads entire 2D planes of the data (XY, ZX, ZY) to predict the gradients which are then combined downstream. You can directly [change the model weights](https://github.com/AllenNeuralDynamics/aind-large-scale-cellpose/blob/feat-single-tile-pipeline/code/run_capsule.py#L23) as long as is compatible with Cellpose. No need of stitching, and if you only need cell centroids, you can skip the last step which builds the segmentation mask. However, you will need to convert the image to a multiscale OMEZarr format and pick the scale of the image pyramid that works best with your model (we are using near isotropic resolution, 1 microns in Z, 1.16 microns in XY, internally there's interpolation to make everything fully isotropic).

**Comment by ashishUthama** [comment]
> Is anyone aware of other code, packages, or notebooks that support applying Cellpose (in particular Cellpose-SAM) on large images?
If you have access to MATLAB: [Detect Nuclei in Large Whole Slide Images Using Cellpose](https://www.mathworks.com/help/medical-imaging/ug/detect-nuclei-in-large-wsi-using-cellpose.html)
- Scales to large data. Works best with tiled TIFF inputs.
- Works best for computing cell level stats. If you have a workflow where you really need individually labelled output, you will have to do a post-process call (happy to help with that if you have a need)

**Comment by zsamadi** [comment]
Hi @vadori

I'm using BigStitcher incorporated in imagej as a separate pipeline and use
the output xml file in my python script. I needed to use BigStitcher
because we had more than 180 tiles, each of them more than 1GB, so we can't
load all of them at once to computer RAM. If your tiles are smaller, maybe
you can use simpler alternatives.

**Comment by MichaelSNelson** [comment]
Has anyone tried using QuPath to run CellPose on whole slide images? Or is the intermediate step of writing the tiles to files before reading the results in as objects too slow? That _seems_ like yhe easiest option for large 2D images.

**Comment by camilolaiton** [comment]
> Hi [@camilolaiton](https://github.com/camilolaiton), thanks for your reply! I noticed that the notebooks in the Cellpose repo outline two main approaches for 3D segmentation: the one you mentioned, and another that involves making predictions on 2D planes (XY, if I'm not mistaken), followed by label stitching.
> 
> However, my current focus isn’t on 3D segmentation but rather on 2D segmentation of very large images (tens of thousands of pixels per side). With other models (not Cellpose), I typically segment smaller patches, merge the results to reconstruct the full prediction, and then apply post-processing.
> 
> In the Cellpose context, I imagine this would involve predicting the gradients for each patch, merging the gradient maps (using interpolation to minimize boundary artifacts - I usually heavily borrowed from https://github.com/Vooban/Smoothly-Blend-Image-Patches), and then applying the gradient tracking algorithm on the full image to obtain the final segmentation labels.
> 
> So my question is: does your solution support this kind of use case? And if not, do you think it could be adapted to handle it?
> 
> I believe the solution you're referring to is here: https://github.com/AllenNeuralDynamics/aind-large-scale-cellpose/tree/feat-single-tile-pipeline — is that correct? Thanks again!

Hi @vadori , yes, all you need to do is to transform the image to a pyramidal Zarr format and run it. You could get some ideas from [here](https://github.com/AllenNeuralDynamics/aind-smartspim-data-transformation/blob/main/src/aind_smartspim_data_transformation/compress/zarr_writer.py). If it's easier for you, we can have a call at some point.
