### ISSUE TITLE
Issue running Cellpose

### ISSUE THREAD

**Issue by CalvinLeeUBIC** [MouseLand/cellpose#92]
This is the error message I get when trying to run cellpose from the base environment. Is it due to an installation error?

![Screen Shot 2020-06-20 at 7 02 21 PM](https://user-images.githubusercontent.com/44824300/85215324-d95df300-b32b-11ea-9ba2-50b76b25983c.png)

**Comment by marius10p** [comment]
Yes, it is. Try installing in a separate environment, and if you're on Mac, take a look at the special Mac instructions in the readme.

**Comment by carsen-stringer** [comment]
closing this issue please comment if you are still having issues with this
