### ISSUE TITLE
[BUG] Model zoo (cyto2) not available in cellpose GUI

### ISSUE THREAD

**Issue by iamlll** [MouseLand/cellpose#922]
**Describe the bug**
In the new cellpose GUI, there doesn't seem to be a "model zoo" section where I can choose between pre-built (non-custom) models. As a result, even though cyto2 works better for my data sets I can only test segmentation using cyto3 (see screenshot, left column). I can use cyto2 just fine in my code itself (i.e. ```import cellpose...```), but it would be really helpful to be able to test the same models on the GUI as the ones I'm actually using to segment my data in bulk.
![Screenshot from 2024-04-22 12-58-11](https://github.com/MouseLand/cellpose/assets/9868001/a887acdf-b0d0-4c9a-a861-02ee2d66ca50)
Could it be that in cellpose v3 the "model zoo" feature is no longer supported? That seems unlikely, and my GUI looks qualitatively different from the GUI layout page in the "Help" section (see second screenshot below), so I am wondering if there is just a bug in my installation of it.
![Screenshot from 2024-04-22 13-04-26](https://github.com/MouseLand/cellpose/assets/9868001/83e457f8-89d6-4a13-a1a8-8635727e9ac2)

**Comment by SamHawkens2** [comment]
Hello, what you have installes is the cellposev3, the GUI from the Help sections is the "old" one from cellposev2.
You can still find the model zoo in the new GUI in the dataset_specific models. There should be the cyto2 model as well.
![image](https://github.com/MouseLand/cellpose/assets/101874356/4138a0c9-56d9-4c01-a09f-2ead8f62a77d)

**Comment by iamlll** [comment]
Ok, I see, thank you!
