### ISSUE TITLE
Training argument --save_each not working using Cellpose 3

### ISSUE THREAD

**Issue by dfgdgdfgd** [MouseLand/cellpose#924]
Hi,

in Cellpose 2 you could use the training argument --save_every xx and --save_each to automatically save after a given number of epochs, which worked very nicely.
Unfortunately, the last argument --save_each no longer works in Cellpose 3 (error: __main__.py: error: unrecognised arguments: --save_each). If I omit the argument and only use --save_every xx, then just one model is saved at the end.

Any idea how to solve the problem?

Thanks & best,
Mario

**Comment by alscunha** [comment]
The problem now with 3.0 is that it uses the same model name to save regardless of epoch iteration number, `iepoch` in the code. While we wait for an update on that I patched lib/pythonX.XX/site-packages/cellpose/train.py under the cellpose installation directory to save current model using filename 'model_path_save' as below
```
       if iepoch > 0 and iepoch % save_every == 0: 
            model_path_save = f"{model_path}_{iepoch}"
            net.save_model(model_path_save)
```

This will append the epoch number to the output name provided by either `--model_name_out` or the default one.

**Comment by dfgdgdfgd** [comment]
Great, thank you very much!!

**Comment by carsen-stringer** [comment]
this is fixed now, thanks for reporting it

**Comment by dfgdgdfgd** [comment]
Thank you very much!!
