### ISSUE TITLE
[BUG] After training model with cellpose 3 the diameter is reset to 30

### ISSUE THREAD

**Issue by MARGINMB** [MouseLand/cellpose#925]
**Describe the bug**
In cellpose 3 GUI, during the model training step, the diameter is reset to 30 and fewer ROIs are detected in the field of view. Not sure why this is the case and what to do to prevent it.

**Screenshots**
I attach a screenshot.
![cellpose 3 gui - diameter reset_Redacted](https://github.com/MouseLand/cellpose/assets/16368584/725a5c90-4fd1-4c5a-86a9-33b9421ce187)

**Comment by arodriguezgama** [comment]
I have experienced the same issue. I haven't found a solution.

**Comment by carsen-stringer** [comment]
sorry this should be fixed now `pip install git+https://github.com/mouseland/cellpose.git`
