### ISSUE TITLE
[FEATURE] - better documentation of and/or integration for use with training-run-tracking tools

### ISSUE THREAD

**Issue by bethac07** [MouseLand/cellpose#927]
**Is your feature request related to a problem? Please describe.**
We love making Cellpose models, like, a lot, but especially on the trickier ones, it can be hard to remember what the magic secret sauce was for training. 

**Describe the solution you'd like**
In other projects in the lab, we're big users of Neptune.ai , and have colleagues who are more into WeightsAndBiases. It would be nice to get a sense of the least-worst way to use Cellpose with either one of these tools - unfortunately, Cellpose's awesome encapsulation of its training at the command line I think makes it harder to easily incorporate it that way, though I suspect it's easier when training in a notebook. 
We will almost certainly get into doing this ourselves, and can contribute back how easy (or not) it was if/when we do, but if it's something you already are aware of people supporting or doing, we're always happy to copy off of someone else's homework. 

Thanks!

**Comment by carsen-stringer** [comment]
With Cellpose 3, we've put our training functions in a separate module, so these sorts of logging programs may be easier to deploy, but we are not using them and don't know anyone else using them. The losses are useful, but I'm guessing you probably want to run AP metrics when the training ends anyway, so this would come after calling the [train_seg](https://github.com/MouseLand/cellpose/blob/ba9e403bd658d0dae73b2851c83ebf82be4f359b/cellpose/train.py#L325) function I think.

**Comment by carsen-stringer** [comment]
we've added the train_losses and test_losses as outputs to train_seg - I think this should be enough for some amount of wrapping, let us know if there's more info you'd like from this function

**Comment by bethac07** [comment]
You're an angel, thank you!
