### ISSUE TITLE
Runtime Error [BUG]

### ISSUE THREAD

**Issue by mayishazn** [MouseLand/cellpose#928]
Trying to just change the diameter to 75 and click cyto3 and this happens twice:

![image](https://github.com/MouseLand/cellpose/assets/43865608/68c22b6e-4801-48be-ae09-4e6de0c4889b)
 
![image](https://github.com/MouseLand/cellpose/assets/43865608/ef809268-d78f-4d07-91f2-53ee1123ea60)

**Comment by mrariden** [comment]
Can you try fully installing cellpose from scratch? Either completely remove the existing environment or make a new one

**Comment by mayishazn** [comment]
I've tried reinstalling anaconda, making new environments, and reinstalling cellpose at least a dozen times

**Comment by carsen-stringer** [comment]
that is a very old torch version, please try upgrading, closing the issue for now but I'll reopen if there are still issues
