### ISSUE TITLE
Extracting the contours

### ISSUE THREAD

**Issue by AmirHosseinZeraati** [MouseLand/cellpose#93]
Do you know any way that we will be able to extract contours from the output of Cellpose?
trying the OpenCV_find_contours on the Mask output of Cellpose is not good enough for my purpose because it is not giving me the correct contours for nuclei or cells that touching each other or close to each other. I was wondering if it's possible to extract the contours that the Cellpose shows in the outlines Images? (like the output of OpenCV find contours)  
thank you very much

**Comment by carsen-stringer** [comment]
The outlines are saved in the `_seg.npy` file as a key 'outlines' where 0=background, 1,2...=mask outlines. We use the findContours function but loop over each mask one at a time to compute it.
