### ISSUE TITLE
Memory issue using cellpose for TMA ome.tiff 

### ISSUE THREAD

**Issue by Mona-Khorani** [MouseLand/cellpose#933]
Hi,
I have an ome.tiff image from Xenium instrument and I am using cellpose to do segmentation. However, the file is too heavy and I can not do so even under server access.
I would be thankful to know if anyone had the same issue and what are recommendations. Thank you.

**Comment by zsamadi** [comment]
Hi, if the file is too big, you may need to convert it to Zarr dataset and use Cellpose to segment the tiles.

**Comment by Mona-Khorani** [comment]
Thank you.
You mean to ome.zarr? and introduce the entire image without splitting to cellpose?  The image is 35GB.
This step is taking alot of my time because of memory issues, I can not figure it out even under server access.
Any help would be greatly appreciated.
Mona

________________________________

**Comment by zsamadi** [comment]
Sure, Zarr naturally converts image to dataset with the tile size you specify. You probably need to get familiar with Zarr and Dask packages to be able to handle those files, see [this link](https://github.com/MouseLand/cellpose/blob/0c0d00a2bb0daa91e3983124db698230ea887828/cellpose/contrib/distributed_segmentation.py) for an example of applying cellpose on a big image using Zarr.

**Comment by Mona-Khorani** [comment]
Thank you so much, then you do not suggest splitting the image, doing segmentation, and putting them back together? Thank you.

10X support suggested this:
“If your TMA sections are well separated so it should be possible define a rectangular bounding box for each core. The range of X and Y coordinates for each core can be determined from Xenium Explorer, and those coordinates can then be used to subset the data. For example, say one section has 100 < X < 300 and 300 < Y < 500. You can use that information to filter x_location and y_location, and look up the valid cell_id of cells belonging to that sections. At this point, you can either analyze all the detected transcripts directly, or you can use the set of cell_id to filter the complete h5 file. For combining them again after splitting. We need to aggregate the matrices. This is probably the easiest part and alternately some third-party tools can probably perform this.”

**Comment by zsamadi** [comment]
With splitting the image, you may have issues with the cells lying on the boundary of your sections. Using Dask, you can create overlapping tiles from Zarr dataset. Cellpose uses those overlaps to reconstruct labeling at the boundaries. If you don't have cells lying on the boundary, you can safely split your image and run segmentation on the sections independently.

**Comment by camilolaiton** [comment]
Hi @Mona-Khorani @zsamadi check this package out: [Large-scale cellpose](https://github.com/AllenNeuralDynamics/aind-large-scale-cellpose). Works with OME-Zarr.

**Comment by melonora** [comment]
@Mona-Khorani If you would like a standardized storage / api to the spatial omics data and a pipeline for analyzing the data, I am one of the core devs of [SpatialData](https://github.com/scverse/spatialdata) and there is a pipeline called [SOPA](https://github.com/gustaveroussy/sopa) that uses spatialdata also to keep the memory footprint low. Let me know if you would like mor information.

**Comment by carsen-stringer** [comment]
closing this issue for now, we will also have native support for this in cellpose in the near future
