### ISSUE TITLE
[FEATURE]Request for Data Processing and Training Code of Cellpose3

### ISSUE THREAD

**Issue by smacaijicoder** [MouseLand/cellpose#936]
Hi,

I hope this message finds you well.

I'm a user of your project and I've been impressed by the work you've done on cellpose. I've noticed the impressive results you've achieved and I'm particularly interested in the data processing and training methodologies you've employed.

I was wondering if you could kindly share the code for training the super-generalist model or any resources related to data processing of six datasets in your paper (especially tissuenet) and training that you used in your project. I believe studying your approach would greatly benefit my own work and contribute to the broader community.

Thank you very much for your time and consideration. I look forward to hearing from you.

Best regards,

**Comment by carsen-stringer** [comment]
Thanks! For tissuenet we used the training images they provided and normalized per channel (the default setting in cellpose). The training info is now here: https://github.com/MouseLand/cellpose/blob/main/paper/3.0/README.md

**Comment by smacaijicoder** [comment]
已收到邮件，将尽快回复！
