### ISSUE TITLE
Help segmenting bright field images 

### ISSUE THREAD

**Issue by Bassetyabrag** [MouseLand/cellpose#941]
![Uploading screen9-amoeba-4h-emdm_A1_N_Bf_Processed_1b9605cd-1c68-4ae2-9365-c17ad83229a4.jpg…]()
Hello!
I am trying to segment brightfield images, such as the one I provided. The problem I am facing is that the cellpose 3 is not able to segment these images correctly. does anyone have any kind of advice on how to segment these kinds of images?
Thanks for the help.

**Comment by Bassetyabrag** [comment]
![screen9-amoeba-4h-emdm_A1_N_Bf_Processed_1b9605cd-1c68-4ae2-9365-c17ad83229a4](https://github.com/MouseLand/cellpose/assets/123891766/93b39ce1-7bb3-4671-a49e-a7dd1d98adf6)

**Comment by carsen-stringer** [comment]
you may need to try training a model if the livecell models aren't working for you, check out our info on Cellpose2: https://github.com/MouseLand/cellpose?tab=readme-ov-file#star2-v20-april-2022-star2
