### ISSUE TITLE
Code quality standards

### ISSUE THREAD

**Issue by JoshuaSchlucke** [MouseLand/cellpose#943]
When trying to extend the code I noticed that the code doesn't conform to PEP 8 or PEP 257 and generally the internal code documentation is few and far between, it makes the code very hard to understand.

Would it be possible to introduce linters like flake8 or pylint with especially flake8-docstrings so that at least the functions are documented and the code is more easily understood. It could be added as github workflow and checked on PR the --diff option would probably be needed.

Alternatively tools like darker would be nice since it automates the whole formatting as I guess the codebase is not reformatted with Black as it ruins git blame ([not always](https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html#avoiding-ruining-git-blame)) but alas it would be nice if the code could be easier to extend and understand.

**Comment by carsen-stringer** [comment]
We are using yapf, although it is not currently auto-running, which makes the code readable for those familiar with python.

We have docstrings for many of the functions and methods in the algorithm, and there are several videos and tutorials for using cellpose in addition to the paper (see our readme) -- is there a specific part of the algorithm that you're having trouble running?
