### ISSUE TITLE
get mask from flow-maps

### ISSUE THREAD

**Issue by phisanti** [MouseLand/cellpose#948]
Hi, I like the approach of using flow masks for bacterial cell segmentation. It works really well in highly dense areas. However, I am not getting the expected output. When I pass a labelled image (0 for background and int-n for each cell), I get a 4 dimension image: source, pmap, flow1, flow2. If I understand your documentation, the flow map should encode background as -5, but in my case, it comes as 0. Also, I am not able to reconvert the flow maps into pmaps. Ideally, I would like to train my model to output two channels (pmaps) and then convert to pmap.

Please let me know if you can help; any advice will be highly appreciated.

This is how I get the flow maps:
```python
test=labels_to_flows(batch_img_tensor, use_gpu=False, device=None, redo_flows=True)
```
And this is how I get the mask back from the flows (channels 2 and 3 from the previous image)

```python
flows=test[2:]
z2=get_masks(flows)
```

**Comment by carsen-stringer** [comment]
the background is encoded as 0, correct, the flows go positive and negative (e.g. leftward and rightward for X flows). I'm not sure I understand the question, to get the cells back, the get_masks function also takes as input the pmap (what we call the cellprob): ``get_masks(p, iscell=cellprob>cellprob_threshold)``
