### ISSUE TITLE
HTTP Error 500: INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by Shrishtee-kandoi** [MouseLand/cellpose#950]
Hi,

I initialized a model using the following code:

from cellpose import models
model = models.Cellpose(gpu=False, model_type='cyto3')

But I am getting an `HTTP Error 500: INTERNAL SERVER ERROR` message when attempting to download the model files.

I'm running this in a conda environment. Any suggestions on how to resolve this would be greatly appreciated!

Thank you.

**Comment by carsen-stringer** [comment]
you need to make sure you have an internet connection, also sorry the website may have been down for a short time
