### ISSUE TITLE
running in a non internet environment

### ISSUE THREAD

**Issue by EricDeveaud** [MouseLand/cellpose#952]
Hello, 

I'm trying to install cellpose-3.0.8 to be run on a cluster whose compute nodes does not have internet access.
Installation is done on a ReadOnly shared drive mounted on the nodes. 

this mean that users won't be abble to download some required files.
https://www.cellpose.org/static/images/cellpose_transparent.png
https://www.cellpose.org/static/images/cellpose_gui.png

NB I can download thoose files and patch `cellpose/gui/gui.py` and `cellpose/gui/gui3d.py` to point to it. 

models won't be abble to be downloaded by users. 

after looking at `docs/models.rst` and  `models.py code` I noticed some models described but not available 
eg
`docs/models.rst` describe 3 cytoplasm models `cyto3`, `cyto2`and `cyto`. 
unfortunatly 
```
https://www.cellpose.org/models/cyto2
https://www.cellpose.org/models/cyto
```
returns a 500 error 

same happens for `nuclei`

while `models.py` describe more models than `docs/models.rst`. eg `neurips_*` ones.

can you please provide a comprehensive list of all defaults models that cellpose3 can use ? `deblur_*`, `denoise_*`, `size_*`
and // or an archive whith the complete set. 

I will download the models and store on a local storage pointing it using `CELLPOSE_LOCAL_MODELS_PATH`

regards

Eric

**Comment by carsen-stringer** [comment]
this zip file is out of date but we will update it soon and list the models available in the readthedocs: https://github.com/MouseLand/cellpose?tab=readme-ov-file#download-of-pretrained-models

**Comment by EricDeveaud** [comment]
so far what I was abble to determine is that cellpose-3.0.8 
requires at list 
```
bact_fluor_cp3
bact_phase_cp3
cyto2_cp3
cyto3
cytotorch_0
deblur_cyto3
deblur_nuclei
deepbacs_cp3
denoise_cyto3
denoise_nuclei
livecell_cp3
neurips_cellpose_default
neurips_cellpose_transformer
neurips_grayscale_cyto2
nucleitorch_0
size_cyto3.npy
size_nucleitorch_0.npy
tissuenet_cp3
transformer_cp3
upsample_cyto3
upsample_nuclei
yeast_BF_cp3
yeast_PhC_cp3
```

can you confirm this is correct and thta I'm not missing any further file//model 

regards

Eric

**Comment by carsen-stringer** [comment]
I've updated the google drive zip file with all the models available from the website, and added more information about the models in the restore and models readthedocs
