### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Voidext** [MouseLand/cellpose#962]
Error after changing the cellprob threshold after segmentation

Grayscale image

![image](https://github.com/MouseLand/cellpose/assets/41903646/1a4d03e4-4fe9-41e5-abfb-aadc13eb3bd8)

![image](https://github.com/MouseLand/cellpose/assets/41903646/6167ad84-5192-47b7-8eff-cd198caa6166)

CellPose 3.0.9

**Comment by carsen-stringer** [comment]
I think this should be fixed now, `pip install cellpose --upgrade`, if not I will re-open the issue
