### ISSUE TITLE
napari-cellpose

### ISSUE THREAD

**Issue by melonora** [MouseLand/cellpose#965]
Hi there cellpose team!

I saw that the last update to the napari cellpose plugin was a while ago and cellpose has had many awesome updates since then. I know one can use the cellpose gui but I was wondering whether there were particular reasons for not yet updating the plugin (just too swamped is also just a valid reason:)). I am a bit time constrained myself, but in some free time can create a fork and try to add the new updates.

**Comment by carsen-stringer** [comment]
we have updated to support cellpose3! we are aiming to add training in napari soon and also the restoration models, please let us know if you have any issues using it over in that repo

**Comment by melonora** [comment]
@carsen-stringer great! will try it out. Is there some branch already for the added training in case you want some beta testers?

**Comment by carsen-stringer** [comment]
Not yet but soon!
