### ISSUE TITLE
y.segmented = y_data unboundlocalerror: local variable 'y_data' referenced before assignment

### ISSUE THREAD

**Issue by Pvannd** [MouseLand/cellpose#966]
Cellpose version 3.0.10 and cellprofiler 4.2.6.  I can't get cellpose to run as a plug-in. It runs in the same environment fine. But I can't edit the runcellpose file to much with out cellprofiler not recognizing the file. Please help me im losing sleep trying to figure it out. Ive changed the workers and GPU memory share workers but nothing has fix the issue for it to run.
![452a56dcf75121f31a5c74ffb064563219ba00dc_2_1332x1000](https://github.com/MouseLand/cellpose/assets/174470313/207b69bc-0539-4bcc-a5a0-523a5ad0a98b)
![3b0b8d3bf8fd5581ad09d4b17784f85546780f1d_2_750x1000](https://github.com/MouseLand/cellpose/assets/174470313/a384d96a-e8ec-40bd-b278-6eac90b9ad12)
![31645f6b34adc9ced4abf115012c16e8a0d450bb_2_750x1000](https://github.com/MouseLand/cellpose/assets/174470313/8c0fc76a-1fd1-4bd3-a580-3bdad26f0d34)

![31f21affe6bca626ae6720de44a7ccc61842e668_2_750x1000](https://github.com/MouseLand/cellpose/assets/174470313/accfe0db-3952-43a6-aea6-7d8293c6617d)

**Comment by ian-coccimiglio** [comment]
My gut reaction is that Cellprofiler was built cooperate with Cellpose 2 and not on Cellpose 3. The relevant error seems to be that net_avg was provided as a parameter to eval(), but this is no longer a parameter in Cellpose 3. Therefore, masks/segmentations can't be generated.

I would suggest downgrading to Cellpose 2 or else going into the underlying script to remove that parameter as an input.

**Comment by Pvannd** [comment]
> My gut reaction is that Cellprofiler was built cooperate with Cellpose 2 and not on Cellpose 3. The relevant error seems to be that net_avg was provided as a parameter to eval(), but this is no longer a parameter in Cellpose 3. Therefore, masks/segmentations can't be generated.
> 
> I would suggest downgrading to Cellpose 2 or else going into the underlying script to remove that parameter as an input.

Omg! Thank you sweet soul for helping me and for replying downgrading worked.

**Comment by Pvannd** [comment]
> My gut reaction is that Cellprofiler was built cooperate with Cellpose 2 and not on Cellpose 3. The relevant error seems to be that net_avg was provided as a parameter to eval(), but this is no longer a parameter in Cellpose 3. Therefore, masks/segmentations can't be generated.
> 
> I would suggest downgrading to Cellpose 2 or else going into the underlying script to remove that parameter as an input.

I tried changing the input but then Cellprofiler wouldn't recognize the file. But downgrading worked.

**Comment by carsen-stringer** [comment]
great! I think you may want to raise an issue on cellprofiler to see if they'll support cellpose3 in the future since we have more models available in that version

**Comment by andysaiz** [comment]
I also encountered this issue "local variable 'y_data' referenced before assignment, and I can confirm it was solved by uninstalling cellpose3 and downgrading to cellpose2. I am running CellProfiler inside a Python venv with cellpose within it, so I used:

pip uninstall cellpose

followed by: 

pip install cellpose==2.3.2

And that worked!
