### ISSUE TITLE
[FEATURE] Saving out masks of different channels?

### ISSUE THREAD

**Issue by santiaci325** [MouseLand/cellpose#975]
I would like to create masks for separate color channels and save them out separately. I am seeing that there is no way to do that in the GUI. Could someone walk me through this? Or is this a feature that would be added in the future?

**Comment by carsen-stringer** [comment]
correct, for now you need to separate your images by channel and then you can run them in an automated way, or you can duplicate your folder of images and run cellpose on one channel on one folder and on the other channel in the other folder. support beyond this is not something we are going to support in the near term
