### ISSUE TITLE
[FEATURE] Hosting a custom Cellpose model under GCP Vertex AI

### ISSUE THREAD

**Issue by keesh0** [MouseLand/cellpose#976]
Hello,
I have a nice CellPose model based on cyto2.
It has been enhanced via Human-In-The-Loop training from the Cellpose GUI.
It runs inference fast in a GPU-enabled Python script running under Windows 11.

I have not uncovered any information on hosting a custom Cellpose model under GCP Vertex AI.
Not sure how to convert to a MAR file?
I am concerned about retaining customer Cellpose parameters like diam_mean.
Does anybody have any experience with this?
thx in adv
e.-

**Comment by carsen-stringer** [comment]
sorry @keesh0 I don't think this is something we will support in the near future. I have added the train and test losses as outputs of the training function `train.train_seg` to be used for automated monitoring. generally speaking though I think it's also a good idea to check the full output (the segmentations) to see how the model is doing which requires an additional step these platforms don't necessarily support out-of-the-box
