### ISSUE TITLE
What is meant by tiling?

### ISSUE THREAD

**Issue by chrisroat** [MouseLand/cellpose#98]
The comment on transforms.make_tiles indicates "there are 4 versions of each tile".  I interpreted one of two ways, and in each case I'm not exactly following.  Can you clarify?

1. Thought 1: the simplest explanation is that each tile is replicated 4 times in 4 orientations.  I do not see this proliferation of tiles in the output of the function -- each tile is only present once.

2. Thought 2: each region of data is in a different orientation in each tile it is included in.  This seems to be what the code is trying to do, BUT it does not guarantee each region will be in 4 different orientations.  The [augment loop](https://github.com/MouseLand/cellpose/blob/2b5dca97de9ac09cbbb9a3b46392bae2e890883f/cellpose/transforms.py#L154) rotates tiles, but the mod%4 on tile number means orientations are dependent on how many tiles are in each row.  It's possible for data to only appear in 2 or 3 orientations.

Below is some code which demonstrates the issue, and shows a potential path to a solution by using the row number when doing the flipping.  See the various orientations of the [[18, 19], [26, 27]] region in the output.  The original code duplicates an orientation -- see the bold.

[Incidentally - is it expected for data to be transformed to float64 by this function?  If downstream code does need float64, I would expect the downstream to do be responsible for the conversion.]

```
import numpy as np
from skimage import util
from cellpose import transforms

data = np.arange(8*8).reshape(1,8,8)

original, _, _, _, _ = transforms.make_tiles(data, bsize=4)
print('Original')
print(original[np.array((0,1,3,4))])


def updated_tile(arr, bsize=4):
    tile_size = (arr.shape[0], bsize, bsize)
    # skimage requires a non-zero z-step, even though our window is the full shape of arr.
    tile_step = (1, bsize//2, bsize//2)

    # Use np.array to create view to a real array (with ~4x the memory footprint)
    result = np.array(util.view_as_windows(arr, tile_size, step=tile_step))

    # Need to add final tiles along x/y edge, which windows does not create if not evenly divided.

    # Even rows are flipped according to x-position mod 4
    # result[:, 1::2, 0::4] # Not flipped
    result[:, ::2, 1::4] = np.flip(result[:, ::2, 1::4], 4)
    result[:, ::2, 2::4] = np.flip(result[:, ::2, 2::4], 5)
    result[:, ::2, 3::4] = np.flip(result[:, ::2, 3::4], (4,5))

    # Odd rows are flipped similarly, but shifted by two relative to even rows.
    result[:, 1::2, 0::4] = np.flip(result[:, 1::2, 0::4], 5)
    result[:, 1::2, 1::4] = np.flip(result[:, 1::2, 1::4], (4,5))
    result[:, 1::2, 2::4] = np.flip(result[:, 1::2, 2::4], 4)
    # result[:, 1::2, 3::4] = # Not flipped
    
    tiles = result.shape[0] * result.shape[1] * result.shape[2]
    
    return result.reshape((tiles, bsize, bsize))


updated = updated_tile(data)
print('\nUpdated:')
print(updated[np.array((0,1,3,4))])
```

<pre>
Original
[[[[ 0.  1.  2.  3.]
   [ 8.  9. 10. 11.]
   [16. 17. <b>18. 19.</b>]
   [24. 25. <b>26. 27.</b>]]]

 [[[26. 27. 28. 29.]
   [18. 19. 20. 21.]
   [10. 11. 12. 13.]
   [ 2.  3.  4.  5.]]]

 [[[43. 42. 41. 40.]
   [35. 34. 33. 32.]
   [27. 26. 25. 24.]
   [19. 18. 17. 16.]]]

 [[[<b>18. 19.</b> 20. 21.]
   [<b>26. 27.</b> 28. 29.]
   [34. 35. 36. 37.]
   [42. 43. 44. 45.]]]]

Updated:
[[[ 0  1  2  3]
  [ 8  9 10 11]
  [16 17 18 19]
  [24 25 26 27]]

 [[26 27 28 29]
  [18 19 20 21]
  [10 11 12 13]
  [ 2  3  4  5]]

 [[19 18 17 16]
  [27 26 25 24]
  [35 34 33 32]
  [43 42 41 40]]

 [[45 44 43 42]
  [37 36 35 34]
  [29 28 27 26]
  [21 20 19 18]]]
</pre>

**Comment by marius10p** [comment]
I think you're right, nice catch! Indeed option #2 was intended, and the wording is incorrect. 

The goal was to do a different rotation depending on the 4 combinations of row%2 and column%2. Each of these corresponds  to a near complete tiling of the image (with some parts of the border only covered once or twice). We will fix the code so that this is achieved.

**Comment by carsen-stringer** [comment]
this has been fixed, please `pip install cellpose --upgrade`
