### ISSUE TITLE
[BUG] Invert after intensity normalisation

### ISSUE THREAD

**Issue by qin-yu** [MouseLand/cellpose#982]
**Describe the Bug (might not be a bug tho)**

Hi @carsen-stringer! 

I found three suspicious implementations in intensity normalization but could only identify two as potential bugs. I attempted to fix these two in #981, but I still wonder if the third issue should be addressed:

To invert the image so that dark cells become bright cells while the bright background becomes darker, the current implementation is:
https://github.com/MouseLand/cellpose/blob/84344b0ceb6eb91e759301fbdad5c9b77a1c881b/cellpose/transforms.py#L666-L667

essentially:

```python
image = -1 * image + 1
```

However, `image` here is usually the output of a percentile-based normalization like `normalize99()` and is not strictly within the [0, 1] range. I guess most pixels are in [0, 1] so this inversion makes sense, but still some are outside [0, 1]. I haven't thoroughly thought this through. Is this a problem, or is it working as intended?

Many thanks!

**Comment by carsen-stringer** [comment]
thanks for looking into this, yes this is how it should work, like when not inverted, some pixels will lie outside the [0,1] range
