### ISSUE TITLE
Training denoise model

### ISSUE THREAD

**Issue by walkeraw2002** [MouseLand/cellpose#984]
Hello,

I was wondering if it is possible to train the denoise, deblur, and upsample models on our own images for fine-tuning. I see there is documentation for training the segmentation model, but I haven't been able to find information on training the image enhancement models.

Thank you very much!

**Comment by carsen-stringer** [comment]
we have added the information here: https://cellpose.readthedocs.io/en/latest/restore.html#training-your-own-models

you can use --pretrained_model as an input in the CLI to start from one of our models (or in the API by specifying the model type when creating the DenoiseModel). we have not tested fine-tuning though, so I'm not sure how well it will work, it would be great if you could let us know how it goes
