### ISSUE TITLE
[BUG] Regarding the training function under `cellpose.train.train_seg`

### ISSUE THREAD

**Issue by anwai98** [MouseLand/cellpose#992]
**Describe the bug**
The function `cellpose.train.train_seg` is really cool to perform code-level training / finetuning. I spotted that the parameters `train_labels_files` and `test_labels_files` are [arguments](https://github.com/MouseLand/cellpose/blob/main/cellpose/train.py#L325-L333) possible to pass in the `cellpose.train.train_seg` function, however, they are not utilized later by [`_process_train_test`](https://github.com/MouseLand/cellpose/blob/main/cellpose/train.py#L384-L391). Would it be possible to pass the aforementioned arguments to the `_process_train_test` function?

**To Reproduce**
```python
model_path = train.train_seg(
    net=model.net,
    train_files=train_image_files,  # list of .tif image filepaths for training
    train_labels_files=train_label_files,  # list of .tif label filepaths for training
    test_files=val_image_files,  # list of .tif image filepaths for testing
    test_labels_files=val_label_files,  # list of .tif label filepaths for testing
    channels=[chan, chan2],
)
```

Let me know if you want any further information on this.

Thanks in advance! :)

**Comment by anwai98** [comment]
Oops, I just spotted that someone already reported about this https://github.com/MouseLand/cellpose/issues/989. I'll leave this open here still in case the context helps!

**Comment by carsen-stringer** [comment]
sorry this bug should be fixed now!
