### ISSUE TITLE
How to run a batch with the new features of Cellpose 3 ?

### ISSUE THREAD

**Issue by gabriel5222** [MouseLand/cellpose#996]
Hello,

I need to use the new features of Cellpose 3 (Denoising, Deblur and Upsample) for one of my analyse and I would like to know if it's possible to do it in batch, the old command line for it don't includ those new features.

Best

**Comment by carsen-stringer** [comment]
this is documented here: https://cellpose.readthedocs.io/en/latest/restore.html#command-line-usage please let us know if it's not working and I'll reopen the issue
