### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by drosi24** [MouseLand/cellpose#997]
Dear Cellpose team, We are having some issues in the Cellpose in jupiterhub. When manually segmenting, starts giving a trail of strokes without stop and does not allow manual segmentation. Does anyone have a suggestion for how to solve this issue?

**Comment by carsen-stringer** [comment]
please upgrade to the latest python (=3.10 or 3.11) and try using an Anaconda prompt, I will merge this with the other issue
